### ISSUE TITLE
[Suggestion][theme support] remove  class="h-100" from body for better theme support

### ISSUE THREAD

**Issue by philippd1** [bludit/bludit#1000]
I suggest removing  `class="h-100"` from the `<body>` tag for better theme support.
When `class="h-100"` is set, the page will be white colored background, once you scroll down (over the device height)
To fix this, simple remove the class.
#987

**Comment by dignajar** [comment]
If you remove that the Editor area is not taking the max height, which I want to keep.

**Comment by philippd1** [comment]
oh well...
i think i just found a better solution than I suggested yesterday.
in css, just add 'height: 100%; to the body tag'.
This will prevent half of the page having a white background even tho a black admin theme is set

**Comment by dignajar** [comment]
have you check the editor if has the max height ?

**Comment by clickwork-git** [comment]
> in css, we should be able to just add 'height: 100%; to the body tag'

As far as I know, height works only if also width is set.
