### ISSUE TITLE
Request: Filter Helper

### ISSUE THREAD

**Issue by SamBrishes** [bludit/bludit#1004]
Hellow,

sometimes it would be really cool and helpful to edit, change or manipulate some functions, variables and behaviours of the bludit core system, or one of the core plugins. A small filter system would already help in many ways. Something like:

```php
<?php

    class Filter{
        /*
         |  FILTER STORAGE
         */
        static protected $filters = array();

        /*
         |  HOOK FILTER
         |
         |  @param  string  The unique filter id.
         |  @param  callb.  The function, which should called for this filter.
         |
         |  @return bool    TRUE if everything is fluffy, FALSE if not.
         */
        static public function hook($filter, $callback){
            if(!(is_string($filter) && is_callable($callback))){
                return false;
            }

            if(!isset(self::$filters[$filter])){
                self::$filters[$filter] = array();
            }

            self::$filters[$filter][] = $callback;
            return true;
        }

        /*
         |  APPLY FILTER
         |
         |  @param  string  The unique filter id.
         |  @param  multi   The variable, which should get filtered
         |
         |  @return multi   The filtered variable or the source variable.
         */
        static public function apply($filter, $variable){
            if(!isset(self::$filters[$filter])){
                return $variable;
            }

            foreach(self::$filters[$filter] AS $callback){
                $variable = call_user_func($callback, $variable);
            }

            return $variable;
        }
    }
```
(Just a small example, you can also overdo it, like [I did a long time ago](https://gist.github.com/SamBrishes/15f102b9bd5a3c9f3fa5ae692106a3c1))... But this few lines of code are already enough to control many thinks. Just a few small examples:

- A filter system would allow developers to "edit" or "manipulate" the content of a page (when used in the `Page->content()` method). This would open a complete new world of custom variables and content parts (at least it would simplify this).
- It can be used within the **Canonical Plugin** to change the canonical link or add more of them ([like this way](https://gist.github.com/SamBrishes/32c4c07ed094fb874073dcaeffd7742f), for example). That would be really helpful for something like... a [Pagination](https://github.com/SamBrishes/pagination) Plugin ;3
- The **RSS** and **SiteMap** plugins would benefit from it as well, to change the structure, add custom items or elements.

Something like this makes Bludit way more adaptable, even if I really enjoy it to achieve such functions completely without any filter at the moment (Still a filter would be way easier ;D).

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi,
I don't get the idea, from the example to change the `Page->content()`, how the filter works ?

**Comment by SamBrishes** [comment]
Hellow,

If the filter is used within the `Page->content()` method, each hooked filter function would be able to edit the respective page content before it gets shown / printed on the frontend. So it would be possible to "add" custom Shortcodes, apply a custom Markup parsers or to do other cool stuff like changing parts of the page content dynamically.

## A small example
Just for the example, let us say the `Page->content()` method would look like this:

```php
<?php

class Page{
    
    // [...]
    
    public function content($sanitize=false) {
        $content = $this->getValue('content');
        if (!empty($content)) {
            return $content;
        }
        
        // Get the raw content
        $content = $this->contentRaw();     

        // Apply Markdown Parser
        if(MARKDOWN_PARSER){
            $parsedown = new Parsedown();
            $content = $parsedown->text($content);
        }

        // Append Images
        if(IMAGE_RELATIVE_TO_ABSOLUTE){
            $domain = IMAGE_RESTRICT?DOMAIN_UPLOADS_PAGES.$this->uuid().'/':DOMAIN_UPLOADS;
            $content = Text::imgRel2Abs($content, $domain);
        }

        // Apply Filter
        $content = Filter::apply("content", $content);

        // Sanitize and Return
        if($sanitize){
            return Sanitize::html($content);
        }
        return $content;
    }

    // [...]
    
}
```
<br>
<br>

The only change is the `$content = Filter::apply("content", $content);` line, which pass the content to all available "content" - named filters (if there is any). This would Plugin developers allow to write functions like
<br>

```php
<?php
    
    class MyPlugin extends Plugin{

        public function init(){

            /*
             |  Replace the custom shortcode `<!-- ShortCode -->`
             |  with cool new content.
             */
            Filter::hook("content", function($content){
                return str_replace("<!-- ShortCode -->", " Cool Dynamic Content ", $content);
            });
    
            /*
             |  Apply an textile Parser to the page content.
             */
            Filter::hook("content", function($content){
                return textileParser($content);
            });

            /*
             |  Modify all available header tags within the content.
             |  Can be useful to create anchor-linked table-of-contents widgets.
             */
            Filter::hook("content", function($content){
                return preg_replace_callback("/\<h([1-6]{1})\>(.*)?\<\/h\g1\>/m", function($string){
                    
                    // Loops each available Header Tag <h1> - <h6>
                    
                }, $content);
            });
            
        }
        
    }
```

So the content string gets passed through all hooked filter functions before it gets printed on the template. And this are just a few small examples.

Sincerely,
Sam.

**Comment by dignajar** [comment]
Ok now I got it, looks good but you can do the same with a plugin.

```
class ModContent extends Plugins {

	private function cool($content) {
		return str_replace("<!-- ShortCode -->", " Cool Dynamic Content ", $content);
	});

	// This hooks is load when the pages are already setted
	function beforeSiteLoad() {
		global $content;

		// Foreach loaded page modified the page's content
		foreach ($content as $key=>$page) {
			$pageContent = $page->contentRaw();
			$pageContent = $this->cool($pageContent);
			$page->setField('content', $pageContent);
		}
	}
}
```

The method content has a little "hack" for return the content if already setted, to avoid to read the file `index.txt` with the content.
Take a look to these lines, https://github.com/bludit/bludit/blob/master/bl-kernel/pagex.class.php#L69-L73

You can do the same with any field `title` `description` etc..
