### ISSUE TITLE
[Theme] Blog X sidebar moves down

### ISSUE THREAD

**Issue by datenbrei** [bludit/bludit#1006]
### Describe your problem
When I visit the home page of my site the sidebar of the Blog X theme is moved under beneath the article list.

### Expected behavior
The sidebar should always be visible on the right - both in the article list and in the single article view.

### Actual behavior
When I switch to the single article view the sidebar re-appears to the right of the article list. Going back to home it is gone again to the bottom of the page. 

### Steps to reproduce the problem
You can see the behaviour on my site https://herrdoering.de/en/ . I have the feeling, that it could have to do with article header images, because I had a situation where specific articles did force this error and others did not. Actually I have no idea about this.

### Bludit version
3.8.1 - pro

**Comment by datenbrei** [comment]
In the list of posts after the Breaked content (after "blabla") there is an opened paragraph, which does not get closed. This may be the problem. 
~~~
		<!-- Breaked content -->
		<div class="content hc-editor-content">
<p>blabla.</p>
<p>
~~~

There is also a `<div class="container">` which does not get closed in the end:
~~~
	<!-- Content -->
	<div class="container">
~~~

This may be easy to fix. I attached a html file (as txt) which is well formatted. Here you can see, what is missing.

[en.txt](https://github.com/bludit/bludit/files/3013134/en.txt)

**Comment by dignajar** [comment]
Hi,
I don't see any problem in the demo, can you try there ?
https://demo.bludit.com/

And the code you mention the tags are closed.
https://github.com/bludit/bludit/blob/master/bl-themes/blogx/index.php#L14-L42

Have you added some extra plugin or maybe some HTML code in your posts ?
