### ISSUE TITLE
Email field denied @ charachter

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#1007]
### Describe your problem
The email field in the profile and add the new user do not accept @ character.

### Expected behavior
It should behave as an email field and validate the form before saving.

### Actual behavior
It acts like the text filed and it's not a required filed.

### Steps to reproduce the problem
Add the new user or edit the user profile

### Bludit version
v3.8.1

**Comment by dignajar** [comment]
Hi,
I improved the profiles and users in Bludit v3.9.0 beta 1. Please take a look.
