### ISSUE TITLE
a file upload vulnerability in bl-kereln/ajax/upload-logo.php

### ISSUE THREAD

**Issue by liao10086** [bludit/bludit#1011]
### Describe your problem
a file upload vulnerability in bl-kereln/ajax/upload-logo.php
can upload php file
![image](https://user-images.githubusercontent.com/37523122/55223929-462e2e80-524a-11e9-8b65-d87e1ad2daac.png)

### Expected behavior
Limit upload file type
### Actual behavior
can upload php file
### Steps to reproduce the problem
so I upload a php file
![image](https://user-images.githubusercontent.com/37523122/55224013-7970bd80-524a-11e9-931a-1940443d6bbe.png)

Visit http://192.168.10.12/bl-content/uploads/BLUDIT.php
![image](https://user-images.githubusercontent.com/37523122/55224064-97d6b900-524a-11e9-924c-4f92011c93d7.png)

### Bludit version
3.8.0

author by:xijun.liao@dbappsecurity.com.cn

**Comment by dignajar** [comment]
Hi,
I will fix it. The same bug as here.
https://github.com/bludit/bludit/issues/978

Just to inform to the users, you need to have administrator permissions for execute this vulnerability.

**Comment by liao10086** [comment]
The version is 3.8.1
It's not the same problem as #978  is, they have different triggers.
![image](https://user-images.githubusercontent.com/37523122/55271608-98269100-52ea-11e9-86dc-c903921da96e.png)

You can fix it in bl-kereln/ajax/upload-logo.php   and  check  suffix like jpg,png or gif and so on
