### ISSUE TITLE
Blank screen after fresh install via docker

### ISSUE THREAD

**Issue by p4block** [bludit/bludit#1013]
### Describe your problem
When accessing Bludit after finishing the installation (clicking the Install button below the admin password), the page will go blank. No errors with be logged in docker. 

I get the same results on a server that has been running bludit 3.4 (unable to update) and on fresh laptop / desktop

### Expected behavior
Something shows up

### Actual behavior
Completely empty response from server

### Steps to reproduce the problem
```
docker run --name bludit \
    -p 8000:80 \
    -v bludit:/usr/share/nginx/html/bl-content \ 
    -d bludit/docker:latest
```

### Bludit version
3.8.1

**Comment by dignajar** [comment]
Hi,
do you have the directory `bludit` ?
Before the command you paste, have you create the directory ?

Can you create a new directory and check the logs menwhile you are installing, the following steps.

```
mkdir ~/bluditx

docker run --name bluditx -p 8000:80 -v ~/bluditx:/usr/share/nginx/html/bl-content -d bludit/docker:latest

docker logs -f bluditx
```

Then go to the browser `localhost:8000` and do the installation and check the logs.

**Comment by p4block** [comment]
If I pass the folder to it, it will complain that it has no write permissions (which makes sense, as it runs under a certain non-root user) 

Chmod 777'ng the folder will make the install able to continue, but will fail 

The issue also exists when I don't pass the folder from the host, just running the container alone.

**Comment by dignajar** [comment]
Strange behavior because if you run the docker without the volume, Docker create a filesystem directory for that docker.

```
docker run --name bluditx -p 8000:80 -d bludit/docker:latest
```

Can you paste the logs ? and what version of Docker are you using ?

**Comment by p4block** [comment]
Have everything logged here:
https://hastebin.com/xuzojuyifo.sql

**Comment by dignajar** [comment]
There was a few problem in the image tag `latest` because was downloading a wrong version.
I create a new Dockerfile with PHP 7.2 and Bludit v3.8.1, also I enabled the debug mode TRACE by default.

Can you try with the `latest` tag ? just in case delete the image from your system.

```
docker rmi bludit/docker:latest
docker run --name bludit -p 8000:80 -d bludit/docker:latest
```

**Comment by p4block** [comment]
The `latest` tag worked now! Both new install and our previous blog are back up and running.

I also confirm I had to remove existing containers and docker system prune -a... that whole deal. 

Now getting a lot of php debug spam on log as expected, but the web is working perfectly.

Thanks a lot!

**Comment by dignajar** [comment]
Good, I will improve the logs.

You can also delete this line https://github.com/bludit/docker/blob/master/Dockerfile#L60 and build the docker for you self.
