### ISSUE TITLE
After creating the site, the default news disappears in a few days.

### ISSUE THREAD

**Issue by TheTrendingNet** [bludit/bludit#1025]
Hello! After creating the site, the default news disappears in a few days. Only their names remain without description. New news added manually do not disappear. How to fix it (the disappearance of the descriptions of the news by default)? Thank! https://i.gyazo.com/83d3d8071370eb22dd0d125f49e59669.png

**Comment by dignajar** [comment]
Hi,
please do not skip the obligatorily fields when you create an issue in GitHub, we can know which version of Bludit are you using, how we can reproduce it.
Do you have access to the logs such as `php_error.log` ?

**Comment by TheTrendingNet** [comment]
Hello! I am using v.3.8.1.
Warning: file_get_contents(/var/www/user/data/www/site.com/bl-content/pages/настройте-свой-новый-сайт/index.txt): failed to open stream: There is no such file or directory in /var/www/user/data/www/site.com/bl-kernel/pagex.class.php on line 56

**Comment by dignajar** [comment]
Looks like the file were deleted.
The file `/var/www/user/data/www/site.com/bl-content/pages/настройте-свой-новый-сайт/index.txt` exists ?

**Comment by dignajar** [comment]
are you using some external plugin ?

**Comment by TheTrendingNet** [comment]
Yes, the files were deleted on their own. I use the theme Medium.
News added manually is not deleted.

**Comment by Joduai** [comment]
@TheTrendingNet  Try on a fresh test instance with disabled unicode in URLs (options -> SEO tab)

**Comment by TheTrendingNet** [comment]
@Joduai, where can I download test instance?

**Comment by Joduai** [comment]
Just install another bludit website under a subdomain, disable unicode, and then try to add couple demo articles in cyrilic.
Then you might compare the database files between your two websites, as I suppose there's a problem with processing strings in urls containing cyrilic or asian letters. I'm short in time currently, so I cannot try and test this on my own.

**Comment by dignajar** [comment]
Hi @TheTrendingNet, have you the opportunity to test it or found the issue ?
Have you used some plugin like `backup` or `timemachine-x` before this happen ?

**Comment by TheTrendingNet** [comment]
No, I did not use plugins. Everything worked for me and suddenly ceased, for no apparent reason.
