### ISSUE TITLE
Don't force "admin" as default username

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#1026]
Hellow,

### Describe your problem
I guess it isn't really recommended and secure to force "admin" as default username. (I also changed it on all my productive websites on the database file) It would be really cool, if the username field on the installation wouldn't be "disabled" and if the user can choose the username. I mean "admin" can still be the default value, of course, so nobody has to change it, but it would be friendly if I'm able to do so.

### Expected behavior
Selectable username on the installation form.

### Actual behavior
"admin" is forced as username

### Steps to reproduce the problem
Just try to install Bludit :D 

### Bludit version
3.x.x

Thanks.

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi,
for the moment is need it in the system, to recover password and if you delete an user and you want to keep the content of this user the pages are assigned to the `admin`.

What I recommended is disabled this user and create one with Administrator role.
https://docs.bludit.com/en/security/disable-admin-user

**Comment by ltGuillaume** [comment]
Can't you ask for the default admin's name upon installation?

**Comment by dignajar** [comment]
Yes is possible, but we need to keep the username of the user in some place
to know who is the "FIRST" Administrator.

**Comment by Torsten-K** [comment]
I don’t get it. Why can’t on first installation be asked for the preferred admin’s user name? The userfile would contain the same data as it does presently, only the admin’s name would not be admin, but someting else.

**Comment by ltGuillaume** [comment]
Yeah, that makes no sense. If for any reason it's important which user is first admin, you could also make a new field for this.

**Comment by dignajar** [comment]
As I said before, it's possible to set a new field with the new Administrator username, but I need to add that field, add more code to check if the user exists, prevent the users delete that administrator, etc..

I prefer to keep it as simple as possible and secure, for 5/6 years has the project we never had a bug/vulnerability in the login system.

**Comment by Torsten-K** [comment]
> […] to know who is the "FIRST" Administrator.

Well, I’d say, the first administrator is the one who installed the CMS and who is the first user in users.php with role _admin_, like in WordPress or wherever.. Because Bludit works and doesn’t get confused if I change the name _admin_ to something else in the users file, or if I create a second admin unser and delete the first one. So I can’t see why it should be so complicated to ask for the admin’s login name on first install.

**Comment by Deepnerd** [comment]
For the possible brute force attack (I know there is a security to block the brute force to the login page) on admin page, or even username guessing, so I had to change my username to an completely hard to guess. as I'm the only admin in the website there are no other users. so I changed my "admin" username to my own one without even making an new admin account. I entered to the bl-content page, then databases > users.php and you can see in the beginning of the saved user line "admin" so I changed it to my own username and it worked. It's not a must, but I had to change it for security problems. Didn't had any problem at all. all is well.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
