### ISSUE TITLE
Missing some strings in translation file

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#1029]
### Describe your problem
There is some string miss in the languages file such as "logo": "SITE LOGO", to translate this string translators should add "logo": "string" to end of the JSON translation file, and for some of them should hard code strings.

### Bludit version
3.x.x

**Comment by dignajar** [comment]
I pushed some changes to github and included this missing translations.

**Comment by dignajar** [comment]
Hi,
I close the issue, please take a look to the version 3.9 from Github with the new features, if you still have a problem feel free to open the issue.
Regards

**Comment by abdulhalim** [comment]
Hello,
OK, I will do that.
Best regards...
