### ISSUE TITLE
autosave is messy, created new tab under content for all autosave versions

### ISSUE THREAD

**Issue by gidzbeta** [bludit/bludit#1031]
When bludit autosaves, it put it with the drafts and gets really messy and confusing. Sometimes don't know which version to use, and becomes a massive distraction in keeping things clean and clear.

Have a different tab with autosaves, as I only the auto-recover IF an issue occurs with the main save. It's just a backup for exceptional circumstances. 

Create a separate tab for autosave, and provide a notification when autosave is the more recent version (or a comparison to show if the autosave is different to the main), so I can be sure which is the 'true' version I should go to.

Bludit Edition | Standard - Upgrade to Bludit PRO
-- | --
Bludit Version | 3.8.1
Bludit Codename | APA
Bludit Build Number | 20190228

**Comment by dignajar** [comment]
Hi,
I created a new type `autosave` and create a new tab `Autosave` which only appear if there are autosave pages.

Also I have in mind to remove automatically this autosave after 30 days, like expiration date.

**Comment by dignajar** [comment]
Hi,
I close the issue, please take a look to the version 3.9 from Github with the new features, if you still have a problem feel free to open the issue.
Regards
