### ISSUE TITLE
Behavior of <code>

### ISSUE THREAD

**Issue by TimoZacherl** [bludit/bludit#1032]
### Describe your problem
When I am using html tags inside the `<code>..</code>` tag the code doesn't display as it should after saving.

### Expected behavior
It should be displayed like this:
![p1](https://user-images.githubusercontent.com/38291523/58276024-b662b780-7d96-11e9-8f65-8994aa9bce7d.PNG)

### Actual behavior
But after saving once it looks like this:
![p2](https://user-images.githubusercontent.com/38291523/58276118-ed38cd80-7d96-11e9-9671-25ce359f9054.PNG)

Whilest in the real blogpost it is still as it should:
![p3](https://user-images.githubusercontent.com/38291523/58276195-1b1e1200-7d97-11e9-8203-ee3658600011.PNG)

After saving a second time, everything is messed up:
![p2](https://user-images.githubusercontent.com/38291523/58276118-ed38cd80-7d96-11e9-9671-25ce359f9054.PNG)
![p4](https://user-images.githubusercontent.com/38291523/58276283-502a6480-7d97-11e9-9bf3-5c9306ab7c6a.PNG)

I did also get the issue with SimpleMDE.

### Steps to reproduce the problem
Create a new post, create a code example and save twice.

### Bludit version
3.9.0-beta, also tried 3.8.1 before

**Comment by anaggh** [comment]
Try changing this line https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/edit-content.php#L338
```
<?php echo $page->contentRaw(false) ?>
```
to
```
<?php echo $page->contentRaw(true) ?>
```

Not sure if this is the fix.

**Comment by TimoZacherl** [comment]
Works now! Thx
