### ISSUE TITLE
JavaScript errors after upgrade from 3.8.1 to 3.9.0

### ISSUE THREAD

**Issue by prbt2016** [bludit/bludit#1036]
### Describe your problem
Hello,

I was in the process of upgrading Bludit from version 3.8.1 to 3.9.0. I followed this guide 
https://docs.bludit.com/en/getting-started/upgrade-guide

However I face an issue after upgrade. i.e When I click on 'New content' i get the following errors thrown i.e : 
Failed to initialize plugin: textcolor
Failed to initialize plugin: lists
Failed to initialize plugin: advlist 
Failed to initialize plugin: pagebreak
Failed to initialize plugin: link
Failed to initialize plugin: image
Failed to initialize plugin: code

### Steps to reproduce the problem

->Install Bludit version 3.8.1 and upgrade it to 3.9.0 (i.e by keeping only the bl-content folder and replacing all the other files with newer version files.
->Visit the Admin panel and Click on 'New Content'. The above errors will be thrown. 

### Bludit version
Upgrade from 3.8.1 to 3.9.0.

Could you please test this at your end? and post a fix for this?

**Comment by dignajar** [comment]
Hi,
I had this problem because of the cache of Cloudflare.
If you have some cache system you need to purge your files and in your browser do a HARD Refresh in Chrome is (CTRL + SHIFT + R) or clean up your browser cache.
Regards

**Comment by dignajar** [comment]
I fixed this problem with this.
https://github.com/bludit/bludit/commit/ce3d52736f84fb4ff38c24500c71734949eca67a
