### ISSUE TITLE
Profile image preview

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#1043]
### Describe your problem
After uploading the avatar it doesn't show the image but only alt text
### Steps to reproduce the problem
Simply upload an image for the avatar
### PHP version
7.2.11

### PHP logs
If you have access to the logs could be really helpful for troubleshoot, if you don't have access delete this line.

### Bludit version
3.9.1

**Comment by dignajar** [comment]
Hi, are your trying to upload an svg format ? or what is the extension ?

**Comment by abdulhalim** [comment]
Hello,
I checked for all extensions, no one works.
svg,gif,png,jpeg all image in 250x250 px

**Comment by dignajar** [comment]
Can you check the php logs after trying to upload the image ?

**Comment by abdulhalim** [comment]
I checked the **php_errors.log** there is no error related to this problem, so I deleted the content of file, after that I didn't get any error.

but, I have two messages in the FF console.

### During the upload file.
```
absolutePath: "C:\\laragon\\www\\nasim\\bl-content\\uploads\\profiles\\admin.png"
​
absoluteURL: "http://nasim.test/bl-content/uploads/profiles/admin.png"
​
filename: "admin.png"
​
message: "Image uploaded."
​
status: 0
```
### During the save the profile.

`Form contains a file input, but is missing method=POST and enctype=multipart/form-data on the form.  The file will not be sent.`

p.s: I checked with PNG,JPG,GIF / Firefox and Chrome

**Comment by netbuk** [comment]
Same problem here.
[Bludit Forum](https://forum.bludit.org/viewtopic.php?f=19&p=6849#p6849)
After upload there is no file in the folder.

**Chrome Console**
<img width="991" alt="Screenshot_Bludit_Upoad-Pic" src="https://user-images.githubusercontent.com/8388140/59031933-57587480-8865-11e9-8bfb-3011aeb3635b.png">

**PHP version**
7.1.30

**Bludit version**
3.9.1 Pro

CHMOD @ bl-content = 775
CHMOD @ bl-content/uploads = 775
CHMOD @ bl-content/uploads/profiles = 775
same result with CHMOD 755 for all listed above folders

**Comment by dignajar** [comment]
I found the problem.
Can you update the file https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/profile-picture-upload.php
thanks

**Comment by abdulhalim** [comment]
Yes, It's working now... 
Thank you, Diego

**Comment by dignajar** [comment]
Thanks to you for the troubleshooting
