### ISSUE TITLE
Post preview issue

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#1044]
### Describe your problem
the Post preview button in the editor does not work at all (new post/ edit post)
### PHP version
If you don't know delete this line.
7.2.11
### Bludit version
3.9.1

**Comment by dignajar** [comment]
I need more information about the problem, not just is not working.
Which browser are you using ? can you check the console from the browser (chrome > right click on the page > inspect > console)

**Comment by abdulhalim** [comment]
First of all I checked with Firefox, it has problem, I checked with google chrome and opera, they were fine, also IE(edge) has problem with this.

#### error log on console ( chrome and the firefox was the same)
```
/bl-plugins/tinymce/tinymce/plugins/autoheight/plugin.min.js?version=5.0.6:1 Failed to load resource: the server responded with a status of 404 (Not Found)
tinymce.min.js?version=5.0.6:9 Failed to load plugin: autoheight from url plugins/autoheight/plugin.min.js
fd @ tinymce.min.js?version=5.0.6:9
plugin.min.js?version=5.0.6:9 Text color plugin is now built in to the core editor, please remove it from your editor configuration
(anonymous) @ plugin.min.js?version=5.0.6:9
plugin.min.js?version=5.0.6:9 Color picker plugin is now built in to the core editor, please remove it from your editor configuration
(anonymous) @ plugin.min.js?version=5.0.6:9
```

**Comment by dignajar** [comment]
For the errors you have in the console can you disable and enable `TinyMCE` ?

**Comment by abdulhalim** [comment]
I did what you say and right now everything is OK, and post preview is OK too.
Thank you again
