### ISSUE TITLE
Request: Protect variables.php from changes after update

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#1047]
Hey guys,
I have a question: Is it possible to lock /bl-kernel/boot/variables.php or overwrite this settings with an custom file? E.g. local-variables.php

Because after an update the custom ADMIN_URI_FILTER definition will be overwrite with default parameters.

**Comment by dignajar** [comment]
Hi,
I splinted the file `init.php` to `variables.php` to provide this kind of changes, you can have a backup of `variables.php` and replace when Bludit is updated.

The main issue is you can not overwrite constants.
