### ISSUE TITLE
Please show image/relative settings in Admin

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1048]
### Describe your problem
Please show image location setting in Admin, along with `relative to` setting for easy update instead of being hidden.

### Bludit version
v3.x

**Comment by DivineDominion** [comment]
Found this in `admin/controllers/dashboard.php`:

```php
		// Updates only for version less than Bludit v3.1
		if ($site->currentBuild()<='20180921') {
			@mkdir(PATH_UPLOADS_PAGES, DIR_PERMISSIONS, true);
			$site->set(array('imageRelativeToAbsolute'=>true, 'imageRestrict'=>false));
		}
```

It seems the relative path stuff is deprecated and not supposed to be used anymore :( 

I find per-page image upload nice in most cases, but would also like to have a shared media library to not upload the same file time and time again for a series. Looks like this isn't about to happen very soon, though.

**Comment by BlakesHeaven** [comment]
Thanks DD

 @dignajar , could you clarify please? I have this enabled so that all photos are in upload dir in v3.9.1 
what will happen in I upgrade to v3.9.2?
Will you provide an upgrade path to move used images to upload/page for?

**Comment by dignajar** [comment]
By default from the version 3.1 the images are per page but Bludit support both system, image per page and all image in one place.

You can upgrade from 3.9.1 to 3.9.2 and nothing happen.

**Comment by BlakesHeaven** [comment]
Hi @dignajar , thanks for the response, much appreciated. 
So... the original question was, will you please add an option to Admin to display and set the option:
```php 
$site->set(array('imageRelativeToAbsolute'=>true, 'imageRestrict'=>false));
```
Thanks

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
