### ISSUE TITLE
[Bug] pages numbers in images windows

### ISSUE THREAD

**Issue by RenaudILTIS** [bludit/bludit#1051]

**Comment by RenaudILTIS** [comment]
To have this issue : I had 4 images in the article, and then I tried to upload 4 more images in one time (with the Ctrl multi-selection).
Now the upload window is not working properly : the upload is working, but the progress bar stay red at the end of the upload and the image list is not updated (but the file is uploaded).

**Comment by clickwork-git** [comment]
Yes, it's a bug. As a sort of workaround till it will be fixed you can close the editor and reopen it.

**Comment by RenaudILTIS** [comment]
Yes, it's what I made. I listed the names of the files and insert them in the html. Thank you.

**Comment by dignajar** [comment]
I feel the issue is the paginator is not updated after upload the images ?

**Comment by RenaudILTIS** [comment]
Something like that.
