### ISSUE TITLE
Pagination by pages does not work correctly

### ISSUE THREAD

**Issue by TheTrendingNet** [bludit/bludit#1052]
Hello. 
In version 3.9.1. Pagination by pages does not work correctly, how to fix it?
For example, we have 3 pages, on page 3 there is a link to 4 pages. 
4 pages not found /?page=4

**Comment by clickwork-git** [comment]
Which theme do you use?

**Comment by TheTrendingNet** [comment]
Blog X
https://i.gyazo.com/c313e9615e27505f0dc9f8506828ccfc.png
https://i.gyazo.com/11e0c715567a2fef89ccbb30cacbfeff.png

**Comment by dignajar** [comment]
Hi, but the button is disabled for the page 4 or not ?

**Comment by TheTrendingNet** [comment]
Yes, the button is disabled. 
But there is a link. 
Links should not be at all on page 4. After all, there are no 4 pages. 
I am doing ajax loading pages, I am hampered by a link to 4 pages ...

**Comment by dignajar** [comment]
ok, I removed the link

**Comment by TheTrendingNet** [comment]
Thank you very much!
