### ISSUE TITLE
Image upload feature in 'new contents' allows to upload malicious svg file.

### ISSUE THREAD

**Issue by Hexife** [bludit/bludit#1056]
### Describe your problem
I read the #220 and #686 issues but upload of malicious SVG file lead to stored XSS threat.

It seems to need sanitizing logic for SVG files if Bludit needs to upload SVG image.

### Steps to reproduce the problem
1. Make a malicious SVG Files.
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">

<html><head><title>malicious</title></head><body><script>alert('XSS');</script></body></html>

  <g fill="#97C024" stroke="#97C024" stroke-linejoin="round" stroke-linecap="round">
    <path d="M14,40v24M81,40v24M38,68v24M57,68v24M28,42v31h39v-31z" stroke-width="12"/>
    <path d="M32,5l5,10M64,5l-6,10 " stroke-width="2"/>
  </g>
  <path d="M22,35h51v10h-51zM22,33c0-31,51-31,51,0" fill="#97C024"/>
  <g fill="#FFF">
    <circle cx="36" cy="22" r="2"/>
    <circle cx="59" cy="22" r="2"/>
  </g>
</svg>
```

2. Upload "SVG" files using Image upload feature
    ( admin panel -> new contents -> Image upload button)
![upload](https://user-images.githubusercontent.com/10476944/60152782-f2b58780-981c-11e9-85a9-156b04432e92.png)

3. Access the URL of thumbnail image. Browser execute its JavaScript.
![urlofimage](https://user-images.githubusercontent.com/10476944/60152783-f2b58780-981c-11e9-9ea1-67a7f6798c89.png)

![execute](https://user-images.githubusercontent.com/10476944/60152781-f2b58780-981c-11e9-87b0-505dbca50edd.png)

### PHP version
PHP 5.6.40

### Bludit version
bludit 3.9.2

**Comment by dignajar** [comment]
This issue is really hard to fix, also Bludit allows to the user to insert any kind of content in the page (javascript, svg, etc), we need to trust in the users we gave access to the system.
