### ISSUE TITLE
Create Backup does not complete (stops on white screen)

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1058]
### Describe your problem
When Using the Backup plugin to create a backup the screen does not refresh back to the Backup plugin screen - it sits there on a plain white screen on `/admin/configure-plugin/pluginBackup`

Looking in `/bl-content/workspaces/backup` on the server files I can see a recent zip, `2019-07-02-21-26-58.zip` and also a matching folder, `2019-07-02-21-26-58`

I do not know if the folder should be deleted once the zip is created, but it is still there.

> I tried inserting an image but following upload, GitHub said "something went really wrong"

Also, deleting a backup does not remove the folder... zip yes, but not that folder - but I suspect the folder should not be there anyway.

### Steps to reproduce the problem
1. Log into Admin
2. Click on `Backups` or goto plugins and `Backups`
3. Click `Create Backup`
4. Wait for backup to finish
5. Check folder mentioned above.
6. If white screen, edit the url address going back one folder.

1. Click `delete Backup`
2. Check  server folders and folder as per above.

### PHP version
v5.6

### Bludit version
v3.9.2

**Comment by clickwork-git** [comment]
1) Have you tried with PHP 7.x (5.6 is outdated)?

2) Which values are set for max_execution_time and max_input_time?

**Comment by BlakesHeaven** [comment]
You may well be right... the site with PHP 5.6 where the issue is, is as high as it can go with the host.
On another hosted site on PHP v7.x the backup works fine.
I forget what PHP version Bludit supports, and if v5.6 is below that, I'm happy for the issue to be closed.

**Comment by BlakesHeaven** [comment]
Actually - I have just tested again on the site that definitely wasn't working and although it took about 10 seconds it worked - so let's close this.
