### ISSUE TITLE
The possibility of moving to the next post is?

### ISSUE THREAD

**Issue by TheTrendingNet** [bludit/bludit#1065]
Hello.

It is possible to go to the next page. 
The possibility of moving to the next post is?

https://i.gyazo.com/0d6959ee74b49ff3224c48387be8b77d.png

**Comment by DivineDominion** [comment]
I think there doesn't exist a plugin for this, yet.

You could add this directly to your theme, if you want. It should go something like this.

To approach this problem, you can get all pages and pick the ones next to the current page. Description see: https://docs.bludit.com/en/dev-snippets/content-pages

```php
<?php
    // Page number of the paginator, the first page is 1
    $pageNumber = 1;

    // The value -1 tell to Bludit to returns all the pages on the system
    $numberOfItems = -1;

    // Only get the pages with the satus published
    $onlyPublished = true;

    // Get the list of keys of pages
    $items = $pages->getList($pageNumber, $numberOfItems, $onlyPublished);
```

Then get the index for the current page.

```php
    $currentPageKey = $url->slug();

    $index = -1; // -1 means "not found (yet)"
    $i = 0; // Counts the current page in the list
    foreach ($items as $key) {
        if ($key == $currentPageKey) {
            // Set $index to the current index, signifying the page was found, and end the search loop
            $index = $i;
            break;
        }

        // Increment index enumeration
        $i = $i + 1;
    }
```

With the `$index` now being either `-1` (not found) or set to the index of the item in the `$items` array, you can get the neighboring items in the sorted list of pages.

```php
    $prevPage = false;
    $nextPage = false;

    if ($index != -1) {
        // Fetch next and previous page if their index is inside the bounds of $items
        $prevIndex = $index - 1;
        $nextIndex = $index + 1;
        if ($prevIndex != -1) {
            $prevPage = buildPage($items[$prevIndex]);
        }
        if ($nextIndex < count($items)) {
            $nextPage = buildPage($items[$nextIndex]);
        }
    }
    
    if ($prevPage) {
        echo '<a href="' . $prevPage->permalink() . '">Previous Post</a>';
    }

    if ($nextPage) {
        echo '<a href="' . $nextPage->permalink() . '">Next Post</a>';
    }
```

**Comment by dignajar** [comment]
This feature is implemented in Bludit Core.

```
<?php
if ($WHERE_AM_I=='page') {
	if ($page->nextKey()) {
		$nextPage = buildPage($page->nextKey());
		echo "The title of the next page: ".$nextPage->title().'<br>';
	} else {
		echo "There is not next page.".'<br>';
	}
	
	if ($page->previousKey()) {
		$prevPage = buildPage($page->previousKey());
		echo "The title of the previous page: ".$prevPage->title().'<br>';
	} else {
		echo "There is not previous page.".'<br>';
	}
}
?>
```

**Comment by haywardgb** [comment]
I'm using that code and it doesn't work reliably. If I edit a page, change a date or sometimes it just does it randomly for no reason. It will show the previous post link, but not the next post, or vise versa, even though there's very clearly several posts "next" and "previous" in the cue.  https://gist.github.com/haywardgb/47118bcbe4eb7c9d3cabbdbec31fe5a5

This is somewhat game breaking for me, as I'm running a blog and without a reliable "Next Post" and "Previous Post" method, it's back to WordPress unfortunately. Otherwise I absolutely love Bludit, but needs must and all that.

**Comment by DivineDominion** [comment]
@haywardgb Does my code further above work for you? We're still using that to paginate blog posts and it's fine

**Comment by haywardgb** [comment]
> @haywardgb Does my code further above work for you? We're still using that to paginate blog posts and it's fine

It does. I didn't use it initially because the dev gave the official core functions for doing it. Weird how the official work is broken but yours isn't. But you have my gratitude all the same, thank you :)
