### ISSUE TITLE
1 on top of every Page page, not on the home since v3.9.2 (also in other default themes)

### ISSUE THREAD

**Issue by rduinmaijer** [bludit/bludit#1068]
### Describe your problem
You see 1 in the left top of every Page page, not on the home since v3.9.2 (also in other default themes)

### Steps to reproduce the problem
Go to https://testing.richardd.nl/why-host-your-own-blog-in-2019
Look topleft (you see 1)

### PHP version
PHP version: 7.1.30

### Bludit version
Version 3.9.2
![chrome_2019-07-22_21-12-59](https://user-images.githubusercontent.com/31839655/61658390-89af1b80-acc5-11e9-9bab-5debbdbbb4a6.png)

**Comment by dignajar** [comment]
Hi,
are you sure in the default themes happens? because looks like the theme is printing the number 1.

**Comment by rduinmaijer** [comment]
Hi Diego,

I switched to another themes (default), I tried multiple.
I am quite positive that the one didn't come from my theme...

Cheers,
Richard

**Comment by rduinmaijer** [comment]
This screenshot is from the Alternative theme
![chrome_2019-07-23_09-38-58](https://user-images.githubusercontent.com/31839655/61692395-d7f80500-ad2d-11e9-91d3-234c321af223.png)

**Comment by Joduai** [comment]
This 1 digit is printed out by one of the plugin you have installed.
I don't remember which one, but somebody probably on bludit's forums mentioned about this.

**Comment by SkyDiverCool** [comment]
Have the same exact issue

**Comment by rduinmaijer** [comment]
The issue is closed but I found the plugin causing this, for others.
Reactions https://plugins.bludit.com/plugin/reactions upgraded to 1.0.1 and it's oke again.
