### ISSUE TITLE
Cannot delete admin user

### ISSUE THREAD

**Issue by tomexx** [bludit/bludit#1070]
### Describe your problem
Cannot delete admin user, even if there is another administrator account available

### Steps to reproduce the problem
Go to /admin/edit-user/admin -> Security -> Delete user and delete content -> (Nothing happens)

### Bludit version
3.9.2

**Comment by dignajar** [comment]
Hi,
you can not delete the `admin` user but you can disable it.

https://docs.bludit.com/en/security/disable-admin-user

**Comment by tomexx** [comment]
Maybe then it would be good to update the docs and disable buttons in administration when editing admin user

**Comment by Torsten-K** [comment]
You can rename the admin user in _/bl-content/databases/users.php_. But it would be better if it was possible to choose a name during the installation process.
