### ISSUE TITLE
Draft status cannot be set on child pages

### ISSUE THREAD

**Issue by formsandlines** [bludit/bludit#1071]
When I set a parent page for a post in "Advanced -> Parent" I am no longer able to set the status on a page to "draft". I can set the switch to draft but when I hit "save" it always resets back to published.

Is there a reason for this behavior or is it a bug?

Using Bludit Pro 3.9.2 on PHP 7.2.8 (local server).

**Comment by Joduai** [comment]
I confirm that this problem exist.
Just wondered why my new post is getting published after setting a parent.

**Comment by dignajar** [comment]
This bug was fixed for the next version. thank you
