### ISSUE TITLE
Subpage cannot be saved if the parent page has a title with "&" in it.

### ISSUE THREAD

**Issue by medworker** [bludit/bludit#1072]
### Describe your problem
Subpage cannot be saved if the parent page has a title with "&" in it. Exactly the "parent" page in the subpage settings is not saved. 

### Steps to reproduce the problem
1. make a page called "Sommer & Winter"
2. make another page called "Sommer Fun" 
3. in the page "Sommer Fun" select the parent page "Sommer & Winter" and press Save

### PHP version
If you don't know delete this line.

### PHP logs
If you have access to the logs could be really helpful for troubleshoot, if you don't have access delete this line.

### Bludit version
latest

**Comment by dignajar** [comment]
Fixed, thanks for report it.
