### ISSUE TITLE
Markdown content is not saved

### ISSUE THREAD

**Issue by dgleba** [bludit/bludit#1073]
### Describe your problem
markdown is not saved

### Steps to reproduce the problem
go to bludit demo

https://demo.bludit.com/admin/content

Add easymde plugin

create content

it will not save. Only title saves.

**Comment by dgleba** [comment]
Maybe I needed to disable tinyMCE first?

**Comment by Joduai** [comment]
You can't have more than 1 content editor enabled. 
Editor plugin loaded as second one will overwrite content because its textarea is empty.

**Comment by dgleba** [comment]
thanks
