### ISSUE TITLE
Proposal: YAML frontmatter implementation for custom fields and arbitrary data structures

### ISSUE THREAD

**Issue by DivineDominion** [bludit/bludit#1075]
## Proposal 

With regard to #906 and #895 I was thinking about implementing custom field without having to change the editor options UI: add [YAML Frontmatter](http://assemble.io/docs/YAML-front-matter.html) support.

Example of YAML Frontmatter and content in a single file:

```markdown
---
key: "Value here"
---

Text content of the post.
```

This adds the flexibility to **specify arbitrary data structures** within pages. The example of #906 is about ingredients and preparation steps for recipes.

Themes could render different templates or partials for metadata like this in a cookbook website.

## Proposed changes to Bludit

1. A YAML parser would extract the frontmatter, if there is any, during `buildPage` / `Page::__construct`. 
    - The YAML is then made available via e.g. `Page::getYAML()`, similar to how `Page::getDB()` works. 
    - The remainder of the text after the frontmatter is processed exactly like it is now.
2. Themes and plugins can access the YAML content and work with it from a `Page` object.
3. Optional: A YAML-metadata plugin can add a hook for  `afterPageModify` and `afterPageModify` to read the page's YAML and duplicate its contents in the DB. Preprocessing the YAML after editing a page speeds up the rendering, compared to parsing YAML directly during `buildPage`/`Page::__construct`.
    - An example of a plugin updating the DB upon page changes: https://github.com/ange007/bludit-posters/blob/master/plugin.php#L287

### Implementation

PHP Comes with a YAML parser: https://www.php.net/manual/en/book.yaml.php

The PHP [FrontYAML library](https://github.com/mnapoli/FrontYAML) supports YAML Frontmatter parsing _and_ uses Parsedown for Markdown contents by default. With this library, changes to `Page::content` and `Page::__construct` are minimal.

### Known Use of  YAML Frontmatter

This is a pretty popular approach, and YAML is well-supported!

- [Jekyll](https://jekyll.github.io/) static site generator
- [nanoc](https://nanoc.ws) static site generator
- [Gatsby](https://www.gatsbyjs.org/) static site generator
- probably even more on these lists: https://github.com/myles/awesome-static-generators and https://staticsitegenerators.net/
- [VSNotes note-taking plugin](https://marketplace.visualstudio.com/items?itemName=patricklee.vsnotes)
- [notable](https://github.com/notable/notable) open source note-taking app

### Upsides

+ Supporting optional YAML frontmatter is a very simple addition to the parser
+ It does not require any extra user interface in the backend
+ It's fully backwards-compatible

### Downsides

Failing to parse YAML would need to show an error to the user, and/or display the malformed frontmatter as regular page content.

The extra parsing step can slow down `buildPage`. 

Caching the YAML parsing result as mentioned above in the DB and just skipping the frontmatter during rendering will keep the performance impact upon display negligible.

### Custom fields as database additions

Instead of storing data structures in the content, they could be added directly to the database.

The database supports addition of arbitrary key--value-pairs already. Instead of adding data structures to the content, they can also be added as custom fields to the DB. You can edit the PHP files and add data manually without Bludit complaining, so backward compatibility would be ensured. See #895 for discussion.

It would be easy to add an "advanced" interface of the page options editor that displays all metadata as a tree structure/outline view. Then users can add and edit anything, from page title and creation date to custom fields.

Examples:

- Powerful visual JSON editor supporting multiple value types natively: https://jsoneditoronline.org/
- Simpler jqTree editor of nested data: https://mbraak.github.io/jqTree/
- [Fancytree](http://wwwendt.de/tech/fancytree/demo/#sample-playground.html) JS framework, like this CodePen demonstrates: https://codepen.io/mar10/pen/mXgmXV

## Conclusion

YAML Frontmatter parsing would be a non-invasive addition to the Bludit page parser. It's highly extensible and enables users to create any data structure for their content, being displayed in a structured way instead of a simple Markdown-to-HTML rendering.

Using YAML Frontmatter keeps the data in the page content. This makes the data highly portable.

If Bludit instead adds custom fields directly to the database files, the user-entered data is "hidden" and not as easy to backup and copy. In addition to the page's `index.txt`, you will also need access to and understanding of the potentially huge database file. To edit the database directly also requires a specialized user interface.

In the future, using YAML Frontmatter could even help make the content more portable. Metadata like categories, tags, creation date, cover image file name etc. could be moved to the file's YAML frontmatter by default. Then every file would be atomic and self-contained. The database could copy the metadata for caching and quick filtering/searching. The file itself would be the single source of truth, though, and the database just easily replaceable derived data. This potentially opens up Bludit's audience: the lock-in effect and the need for import/export plugins is reduced when the files themselves contain all the data already. People can copy their existing static site generator's content into Bludit and vice versa.

---

I would be willing to implement this feature and help support this for Bludit 4 if this is accepted by the maintainers and the community.

**Comment by dignajar** [comment]
Hi,
custom fields are implemented via JSON on the new version of Bludit v3.10.
