### ISSUE TITLE
Draft mode interfears with the publish date

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1088]
### Describe your problem
Draft mode interfears with the publish date by resetting it back to current date.

### Steps to reproduce the problem
Create new content
Switch to Draft mode 
Type title and content
Enter publish date
Save. It seems to jump back to content, which it shouldn't. 
Go back in to edit page. Check date.
Date is still ok
Click save
Check date 
It has reverted back to current date - it should not!

### Bludit version
V3.9.2.

### Expecting 
Being in draft mode must not effect the publish date. 
I also think the status should default to Draft in the first place.

**Comment by dignajar** [comment]
Hi,
to be honest I don't remember why I set up this behavior.

Here is the code.
https://github.com/bludit/bludit/blob/master/bl-kernel/pages.class.php#L235-L241

I will change it.

**Comment by BlakesHeaven** [comment]
Great, many thanks.

**Comment by dignajar** [comment]
I uploaded the fix, thanks
