### ISSUE TITLE
Bludit 3.10.0-20190925 $(...).autoComplete is not a function

### ISSUE THREAD

**Issue by hxii** [bludit/bludit#1089]
### Describe your problem
Parent page autofill does not work and results in a JS error:
```
jquery.min.js?version=3.10.0-beta:2 Uncaught TypeError: $(...).autoComplete is not a function
    at HTMLDocument.<anonymous> (*:438)
    at e (jquery.min.js?version=3.10.0-beta:2)
    at t (jquery.min.js?version=3.10.0-beta:2)
```
The offending line is `$("#jsparentTMP").autoComplete({`
### Steps to reproduce the problem
Create two pages and try to set the parent of one of them.

### Bludit version
Bludit 3.10.0-20190925

### PHP version
PHP 7.3.9-1

**Comment by dignajar** [comment]
Fixed, please check. thanks for report it.

**Comment by hxii** [comment]
Sweet, looks like it works now, thanks Diego!
