### ISSUE TITLE
TinyMCE inline editing

### ISSUE THREAD

**Issue by pixcase** [bludit/bludit#1092]
Hey I hope someone can hgelp me...

The Plugin TinyMCE has an inline Editing option which you can edit the page fron the frontend.

I have try it to implement it, but I don't know how. 

When I insert 
`<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#myeditablediv',
    inline: true
  });
  </script>`

to the <head> of Bludit, everyone can edit the Site from the frontend.

How can I do this, that only Administrators or Useres can edit them?

**Comment by stokesman** [comment]
It may help to take a look at how [this plugin](https://github.com/Bayerberg/bludit-admin-bar/blob/master/plugin.php) works. It includes an admin bar on the frontend only for visitors that are logged in.

Besides that I don't think it's appropriate to have made an issue for this. I would suggest the [Bludit forums](https://forum.bludit.org) is a better place for such.

**Comment by dignajar** [comment]
Hi, yes please post in the forum this kind of topics.
Regards
