### ISSUE TITLE
404 - Not found

### ISSUE THREAD

**Issue by en1cc** [bludit/bludit#1095]
### Describe your problem
Every time i install Bludit on a Virtual Machine with Debian 10 and PHP 7.3, i can run the Installation script and set a admin password. But after this, when i want to enter admin area or use any other hyperlink that points on the server i get a 404 not found.

### Bludit version
Bludit 3.9.2

### PHP version
7.3

![2019-10-15 11_16_29-Window](https://user-images.githubusercontent.com/55091336/66818325-74046780-ef3d-11e9-85f9-30f88cd67fcd.png)

**Comment by turbopixel** [comment]
Hello,
is there a `.htaccess` file in the directory? What does the link to the admin area look like?

**Comment by eddi888** [comment]
Your .htaccess are not processed from the Apache HTTPD. 

You need to allow a override configuration like:
/etc/apache2/sites-enabled/000-default.conf
...
  <Directory /var/www/html/>
    AllowOverride All
  </Directory>
...
