### ISSUE TITLE
5000 post automatic delete without notice

### ISSUE THREAD

**Issue by lk21indoxx1** [bludit/bludit#1098]
### Describe your problem
Using API plugin for grabbing, When i create 5000+ post in one category in 3 hour, data post is auto delete. And now i'm just have 100+ post. I don't know what the problem. In bl-content\databases\categories.php, pages.php and tags.php the data is auto delete so i'm just have 100+ list post, but in bl-content\pages\ and bl-content\uploads\pages it's normally.

I'm try in localhost not in live host.

Hope this can fix, imagin if you live website, and have 10.000 posts and that data auto delete without notice. Thanks.

Sorry for bad english languange.

### PHP version
7.1

### PHP logs
No error log

**Comment by dignajar** [comment]
Hi,
what version of Bludit ?
Can you describe how to reproduce the error ?

**Comment by lk21indoxx1** [comment]
I'm trying in new bludit version 3.10.0.

Can you describe how to reproduce the error ?
I can not reproduce the error, that is fast post 5000 post in 2-3 hour. 

This is the screenshot:
![bludit-categories](https://user-images.githubusercontent.com/56870690/67277629-6dec2900-f4f1-11e9-9a01-808ac1ae9b64.jpg)

and in my other folder:
![bludit-pages](https://user-images.githubusercontent.com/56870690/67277777-ca4f4880-f4f1-11e9-87d7-c82098bcbf8a.jpg)

This is in content in my admin:
![bludit-admin](https://user-images.githubusercontent.com/56870690/67277896-07b3d600-f4f2-11e9-970b-9e92200b1b6c.jpg)

And all delete post is 404 error page, and i can not edit delete page too.

Thanks for your answer.

**Comment by anaggh** [comment]
@lk21indoxx1 Are you adding posts sequentially one by one or multiple scripts are adding posts at the same time concurrently. Maybe it is related to `LOCK_EX` https://github.com/bludit/bludit/blob/master/bl-kernel/abstract/dbjson.class.php#L79

There is no database in Bludit since it is a flat file cms. In databases there is usually row level locking in table.

**Comment by anaggh** [comment]
I can reproduce this with https://github.com/anaggh/bludit-scripts/tree/master/scalability-test

Run `php scalabilityTest.php 5000`

While the posts are getting added, Create a new post from the admin dashboard. It will add to `/bl-content/pages/xxx/index.txt` but wont save to `pages.php`

**Comment by dignajar** [comment]
but this is like you said about the LOCK_EX, I don't understand who needs to create many pages in a really short time.. put a slepp between?

**Comment by anaggh** [comment]
Ya I think lk21indoxx1 is trying to scrape and aggregate content :P They are better off using a different CMS (with InnoDB). Even after using sleep they will have other big headaches storing so much content in any flat file cms.

**Comment by lk21indoxx1** [comment]
Yes, anaggh, i need json for my content, because can speed load from json,
but i try create my own needed, i'm just add only title and category using
mysql but for content stay using json, now i'm can scrape many pages one
time without worry, and i'm test this idea maybe more speed if you have
thousand or even ten thousand post.
http://prntscr.com/pukkb0

But thanks for your great CMS. :)

Pada tanggal Jum, 8 Nov 2019 pukul 23.29 anaggh <notifications@github.com>
menulis:
