### ISSUE TITLE
favicon link rel="shortcut icon" is invalid html

### ISSUE THREAD

**Issue by vampaz** [bludit/bludit#1099]
### Describe your problem
The Theme favicon returns rel="shortcut icon" in the link tag.
[This is invalid Html](https://html.spec.whatwg.org/multipage/links.html#rel-icon) and "icon" is the valid rel value in this case

### Steps to reproduce the problem
On iOS add a Bludit url to the home screen, instead of seeing the favicon the OS displays a preview.

### Bludit version
3.10.0

### PHP version
N/A

### PHP logs
N/A

**Comment by dignajar** [comment]
Fixed, thanks
