### ISSUE TITLE
Option to change the admin name in installation.

### ISSUE THREAD

**Issue by crydotsnake** [bludit/bludit#1100]
Hello folks!,

i dont reallys understand why i cant change the admin username on the installation. I think, it would save some time if i could change the username for the backend directly in the installation.

**Comment by dignajar** [comment]
Hi,
the system needs an Administrator user for example if you delete a user and you want to keep the pages of the user, the pages are transferred to the Administrator, or for recovery the password.
You can disable the user if you want. https://docs.bludit.com/en/security/disable-admin-user

**Comment by crydotsnake** [comment]
Ahh okay, sounds like a pretty cool feature! :). Thank you!.

**Comment by dignajar** [comment]
Related topic. https://github.com/bludit/bludit/issues/1070
