### ISSUE TITLE
Bludit 3.10.0 new search input issue

### ISSUE THREAD

**Issue by mhancoc7** [bludit/bludit#1102]
### Describe your problem
When viewing Bludit 3.10.0 in a mobile view the new search input in the admin shows as a tiny input to the top right

### Steps to reproduce the problem
Login to admin and use the browser dev tools to view the site in a mobile view

### Bludit version
3.10.0

![image](https://user-images.githubusercontent.com/1692414/67642690-7a4ef800-f8dc-11e9-884f-8a204ff89bf7.png)

**Comment by anaggh** [comment]
It happens because of this https://github.com/bludit/bludit/blob/3e151632402bf53413b2026c40c25a6e13edcc39/bl-kernel/admin/views/dashboard.php#L3

Maybe we should get rid of `d-none d-sm-block`

**Comment by dignajar** [comment]
Fixed, I did what @anaggh mention.
