### ISSUE TITLE
Custom Fields squash out the content editor - about 8 max

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1106]
### Describe your problem
The more Custom field you add the smaller the editing area gets, to the point where it does not exist in a usable size.
![image](https://user-images.githubusercontent.com/37149377/68945116-8e816900-07a7-11ea-87a3-b60501a9f7a9.png)

### Steps to reproduce the problem
Add 9 or more custom fields and try to edit content

### Bludit version
3.10.0

### Suggestion
Format custom fields to be spread across a minimum of 2 columns to be more efficient of space used and fix the content editor size to a fixed or minimum height.

**Comment by BlakesHeaven** [comment]
Hi @dignajar , is there a quick fix for this? My person, who needs put up new pages urgently, has a laptop and their screen is a lot smaller than my desktop monitor, which makes the issue much worse for them.

I noticed before that there is an options tab called `Custom`. Maybe you intended to originally put the custom fields there; perhaps that is the best place for them. Maybe give people the choice in general settings... maybe an option in the JSON for each; to specify, `top`, `bottom`, `tab`.... 

What do you think?

![image](https://user-images.githubusercontent.com/37149377/68995044-61a18480-0881-11ea-8dae-6f0920c8276b.png)

**Comment by dignajar** [comment]
Hi,
I need to check the CSS to fix that problem.

To show the custom fields in the tab `options > customs` remove the field `position` from the JSON.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
