### ISSUE TITLE
[REQUEST] Automatically resize images

### ISSUE THREAD

**Issue by burlakko** [bludit/bludit#1108]
### Describe your problem
It's more a feature request, not a bug issue. Sorry if i put it in the wrong place.
Is there a way to automatically resize uploaded images?

### Steps to reproduce the problem
Yes, it's easy to convert images on your computer before uploading it to the web site. But if you use a phone to write content it would be super handy to set the desired width and quality beforehand, so Bludit would automatically resize images.

### Bludit version
3-10-0

**Comment by BlakesHeaven** [comment]
Good call. It would be fantastic to see something like this added:
![image](https://user-images.githubusercontent.com/37149377/68993928-f782e280-0874-11ea-9fba-327d533777f1.png)

**Comment by burlakko** [comment]
That would be great!
But setting at least one standard size and quality apart from thumbnails would already be a nice step.

**Comment by burlakko** [comment]
I'd like to write a plugin for that matter. Can you at least add the `afterImagesUpload` hook? Or any other way to get and modify the uploaded images?

**Comment by TheNomad11** [comment]
Any news on this? Would be great!

**Comment by dignajar** [comment]
Is not implemented yet, but I added a new library for manage Images for Bludit v4 and will we possible to do it.

**Comment by TheNomad11** [comment]
> Is not implemented yet, but I added a new library for manage Images for Bludit v4 and will we possible to do it.

Cool, thanks, would be perfect for photo blogging!

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
