### ISSUE TITLE
[CORE] Update vendors 2019-11-17

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#1109]
tinymce 5.0.16 -> 5.1.1 https://www.tiny.cloud/get-tiny/self-hosted/
select2 4.0.10 -> 4.0.12 https://github.com/select2/select2/releases
select2 bootstrap4 theme 1.4.2 https://github.com/ttskch/select2-bootstrap4-theme/tree/master/dist
jstz build 2015-11-04 -> 2019-09-09 https://github.com/pellepim/jstimezonedetect
lineawesome 1.1.0 -> 1.2.1 https://github.com/icons8/line-awesome (Too many breaking changes)

**Comment by anaggh** [comment]
+ bootstrap 4.3.1 -> 4.4.0 https://github.com/twbs/bootstrap/releases

**Comment by dignajar** [comment]
Updated
- TinyMCE v5.1.3
- select2 v4.0.12

I need to check Bootstrap 4.4 and the icon themes, maybe for Bludit v4.

**Comment by dignajar** [comment]
Updated:
- jstz build 2015-11-04 -> 2019-09-09 https://github.com/pellepim/jstimezonedetect

**Comment by dignajar** [comment]
The only missing is line-awesome and I feel is not a priority, are just icons. I going to close the issue to clean up a little, but feel free to create a new one with new updates of vendors.
