### ISSUE TITLE
Bootstrap and jQuery are requested over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by lauraled** [bludit/bludit#1119]
### Bootstrap and jQuery are requested over HTTP instead of HTTPS
On every page in my fresh Bludit installation, the Bootstrap and jQuery resources are requested over HTTP instead of HTTPS. This results in a warning by Firefox and Chrome and the resources are not loaded. As a result, the site loads without CSS. All the other resources except jQuery and Bootstrap load just fine over HTTPS. Also, the resources load over HTTPS before and during the installation, just not after it finished.
I have Bludit running behind a reverse proxy (NGINX), if that matters. 

### Steps to reproduce the problem
- Create a fresh install of Bludit
- Install it
- Set it up to be accessed through a reverse proxy

### Bludit version
3.10.0

### PHP version
v7.2.24-0ubuntu0.18.04.1

### PHP logs
There are no error logs.

Thanks in advance.

**Comment by dignajar** [comment]
Hi,
have you checked in the settings the procotol in `settings > advanced > SITE URL` ?

**Comment by mirivlad** [comment]
Change your Site url from http://example.com to https://examle.com

**Comment by mirivlad** [comment]
> 
> 
> Hi,
> have you checked in the settings the procotol in `settings > advanced > SITE URL` ?

May be remove protocol type from JS | CSS urls? Browser allow use //example.com/jquery.js for use current page protocol.

**Comment by lauraled** [comment]
Hey guys,

sorry for the late reply. It was indeed an issue with the site URL. I thought I had looked through all the settings, but I apparently overlooked this one. 

Thanks!
