### ISSUE TITLE
Disable mandatory JPG-->PNG avatar conversion

### ISSUE THREAD

**Issue by xcme** [bludit/bludit#1120]
### Describe your problem
I prepared an avatar to use it on my site. I resized it and saved in **jpg** to reduce the file size. When I applied it to the user it was converter to **png** and the size became increased in 20 times. Is there a way to keep pictures 'as is'?

### Bludit version
3.10.0

**Comment by xcme** [comment]
As a workaround I replaced the PNG on the my initial JPG manually and it works.

**Comment by hxii** [comment]
https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/profile-picture-upload.php#L46
It's basically replacing the above with
`$image->saveImage(PATH_UPLOADS_PROFILES.$filename, PROFILE_IMG_QUALITY, false, false);`

**Comment by xcme** [comment]
Note, [this code](https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/image.class.php#L31#L35) doesn't imply the situation with two **false** because it wants at least one **true**. Thereby, it does nothing in that case. And because the [line 38](https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/profile-picture-upload.php#L38) hardcodes the extension as **png** it will be saved as **png**. So, we need **true**, **false** there.

But it increases the file size twice in my case anyway, so I just disabled converting and changed the [line 41](https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/profile-picture-upload.php#L41) to:
`rename($_FILES['profilePictureInputFile']['tmp_name'], PATH_UPLOADS_PROFILES.$filename);`

Now I got what I wanted. I think it's OK to keep original file because only authorized admin could update user pictures.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
