### ISSUE TITLE
Cron job for plugin

### ISSUE THREAD

**Issue by satorc** [bludit/bludit#1122]
### Describe your problem
Hi guys.
Can i set cronjob for auto import in wordpress import plugin ?
For example use command like this " /usr/bin/php /srv/sitename/artisan update-sources"

### Bludit version
3.8.1

### PHP version
7.0, 7,2

### PHP logs

The default settings of the PHP Error Log file varies from OS to OS. The location of the error log file itself can be set manually in the php.ini file. On a Windows server, in IIS, it may be something like `error_log = C:\log_files\php_errors.log` in Linux it may be a value of `/var/log/php_errors.log`.

**Comment by dignajar** [comment]
You can set a cronjob in the system, Bludit does not provide a cronjob utility.
