### ISSUE TITLE
no scroll the list of pictures

### ISSUE THREAD

**Issue by moddc** [bludit/bludit#1123]
when uploading more than 5 images in the list scroll through the images. images are not available (they are not visible).
uploading 10 images in the list to insert in the post, visible only the last 5 uploaded

and also, very short batch (checkbox) add images to post

//translate google, sorry :-))
### Bludit version
3,10,0

**Comment by kostaslgr** [comment]
Same here!

### Describe your problem
When creating a post, i browse pictures and upload them to use them. In previous versions when the number of picture were more than a few, there would be a second page with a link at the bottom of the modal window that would lead to the second page of the loaded pictures. Now at the version 3.10.0-beta.

### Steps to reproduce the problem
Create a post and start loading pictures. the new pictures will be added to the top and the bottom pictures will not show.

### Bludit version
3.10.0-beta, using greek translation and Mediumish theme

![εικόνα](https://user-images.githubusercontent.com/46957480/73437339-d5b5d980-4354-11ea-9bd6-91658b72d2f4.png)

**Comment by dignajar** [comment]
Hi,
this issue was fixed https://github.com/bludit/bludit/commit/8d2056dfac8d3ffc8a34cb55213062fe7ba6bdee

thanks to @anaggh

**Comment by dignajar** [comment]
Hi, I just released the new version 3.11.0 and this issue is solved, please let me know if you have some problem.
