### ISSUE TITLE
Child themes possible?

### ISSUE THREAD

**Issue by misterunknown** [bludit/bludit#1127]
### Describe your problem
Is it possible to create child themes? I like the default theme "alternative", but would like to change some CSS values, while being able to update the original theme. Or is there another way of making changes while keeping updatability?

### Bludit version
3.10.0

**Comment by dignajar** [comment]
Hi, is not possible to do what you want.

**Comment by anaggh** [comment]
You can use the `HTML Code` Plugin to inject.

Example:

Add to Website > Head

```
<style>
.navbar-dark, .footer {
  background-color: black !important;
}
h1,h2 {
  color: #1a237e;
}
body {
  background-color: #c5cae9;
}
</style>
```

**Comment by misterunknown** [comment]
Ok, thank you both for your answers. I just tried the HTML-Code plugin and it works for my needs.
