### ISSUE TITLE
Security - Arbitrary Change Profile Picture

### ISSUE THREAD

**Issue by thatsa9** [bludit/bludit#1131]
### Describe
This vulnerability allows authenticated users to change other user's profile pictures.

### Steps to reproduce the vulnerability
1. Tried to login via Administrator privilege. We found 3 accounts.
﻿
![image](https://user-images.githubusercontent.com/60623594/73809507-076fea00-4806-11ea-979d-980be16df3af.png)

Moreover, we can access directly to Profile Pictures like this
_http://site-name/bludit/bl-content/uploads/profiles/[username].png_

![image](https://user-images.githubusercontent.com/60623594/73809546-2b333000-4806-11ea-90f8-e0d91f2db4da.png)

![image](https://user-images.githubusercontent.com/60623594/73809557-35edc500-4806-11ea-9063-60ef381455d6.png)

![image](https://user-images.githubusercontent.com/60623594/73809584-40a85a00-4806-11ea-9c9e-28e55d049d4a.png)

2. Tried to login via limit privilege (username: admon2, role: Editor). 
![image](https://user-images.githubusercontent.com/60623594/73809622-633a7300-4806-11ea-9ae0-985e7d10f4cd.png)

From a HTTP Request to perform to change a user picture. 
![image](https://user-images.githubusercontent.com/60623594/73809643-72b9bc00-4806-11ea-8265-8225e6e6c872.png)

We could change the username to another username.
![image](https://user-images.githubusercontent.com/60623594/73809679-8c5b0380-4806-11ea-8e52-9ea87ff6607f.png)

As a result, we could change to the profile picture of another user.
![image](https://user-images.githubusercontent.com/60623594/73809693-9bda4c80-4806-11ea-95ed-efe6a3ef72ce.png)

![image](https://user-images.githubusercontent.com/60623594/73809708-a563b480-4806-11ea-991d-82e0895119c9.png)

Login with Administrator to verify the change via username “admin” and found a profile picture has changed.
![image](https://user-images.githubusercontent.com/60623594/73809728-b3b1d080-4806-11ea-81b4-85fee67e226f.png)

In addition, we could arbitrarily create a picture (png) to other directories.
![image](https://user-images.githubusercontent.com/60623594/73809742-bd3b3880-4806-11ea-914f-e7097dade344.png)
![image](https://user-images.githubusercontent.com/60623594/73809753-c5937380-4806-11ea-9b7d-e44756790e04.png)

**Comments**
The vulnerability doesn't validate an authorization before the upload process. Moreover, it could be pulled username from trusted source

### Bludit version
Affected in Bludit v3.10.0

### PHP version
PHP Version 7.1.33

**Comment by dignajar** [comment]
I will check, thank you!

**Comment by dignajar** [comment]
Fixed, thank you
