### ISSUE TITLE
[REQUEST] Install new themes from bludit admin panel

### ISSUE THREAD

**Issue by theuser17** [bludit/bludit#1139]
The site administrator can now install the theme by uploading it and activating it from the admin panel.
But perhaps the best way is for the webmaster to install the templates directly through his own admin panel. (Something like installing templates in WordPress)

**Comment by philippd1** [comment]
there's already a plugin for that: https://github.com/philippd1/bludit-theme-download
and it's on the roadmap for Bludit v4 😉

**Comment by philippd1** [comment]
@theuser17 let's close this issue in favor of the dedicated #1140 thread heh? 🙂
