### ISSUE TITLE
Save button in content editor downloads php files instead of saving

### ISSUE THREAD

**Issue by DigitalAssasin** [bludit/bludit#1141]
Hi Diego,

I've updated my bludit installation to the 3.11.0 Pro version lately.

Today I wanted to change published content. After I did the change and clicked on "Save" the site was starting the download of a PHP file instead of saving the content.

More irritating: This is only true for one specific article. All other contents can be changed without problems.

Any idea what could cause such a behavior?

Regards,

Christian

**Comment by dignajar** [comment]
Hi,
it's really strange behavior.

Maybe there is some code inside the page? or some configuration in your webserver, some regex ?

Which web server are you using and PHP version ?

I can recommend following these threads.
- https://stackoverflow.com/questions/5121495/php-code-is-not-being-executed-instead-code-shows-on-the-page
- https://stackoverflow.com/questions/12142172/apache-shows-php-code-instead-of-executing

**Comment by DigitalAssasin** [comment]
Hi Diego,

thanks a lot for the quick reply!

Yes, it is a strange behaviour indeed. There is no special stuff with this specific content. Just an article with some images like other ones in my bludit installation.

I'm using a webspace package provided by the german hoster Strato and I played a little bit around with the PHP versions. The behavior persists from version 7.2 to 7.4.

I will have a look to the links you provided later. Thank you for these hints.

I could also provide you the content file if this helps you investigating.

Regards,

Christian

**Comment by dignajar** [comment]
Can you try to reproduce it on the demo (https://demo.bludit.com), I mean with the same content and URL name, but I'm pretty sure is from the webserver the issue.

**Comment by DigitalAssasin** [comment]
Hi Diego,

today I wanted to dig a little bit deeper into this issue.

What should I say... It isn't reproduceable anymore. I can change and the article without any problems. I didn't change anything. No update of Bludit or the plugins since I reported this issue.

We are living in a strange world sometimes ;o)

I will close this issue.

Thanks for your tips and time.

Stay safe and healthy with your family!
