### ISSUE TITLE
Error when retrieveing filesize from $file object via getSize()

### ISSUE THREAD

**Issue by cblte** [bludit/bludit#1143]
Issues with displaying "Disk Usage" on the admin/about page. The code piece `$file->getSize();` does not work on my host. But works on local windows php server. 

Solved the issue with replacing the [line 282][282] (`filesystem.class.php`) with the code `$size += filesize($file);`. *Disk usage* is now displayed on the `admin/about` page and on the dashboard when the *Show Content Stats* of the *Simple Stats* are enabled.

[282]: https://github.com/bludit/bludit/blob/006e87daf1cb22075479571144be0c293325439f/bl-kernel/helpers/filesystem.class.php#L282

**Comment by anaggh** [comment]
Trying to debug the svg issue on Windows 10 version 1909 with xampp. Seems like the symlink() function does not even work on Windows as it needs admin privileges 
```PHP Warning:  symlink(): Permission denied ```
