### ISSUE TITLE
Inserting malicious JavaScript on the WYSIWYG editor could lead to admin account takeover.

### ISSUE THREAD

**Issue by MohitDabas** [bludit/bludit#1171]
### Describe your problem
Inserting Javascript could lead to an admin account take over.Moreover while changing  the admin password, you don't require current password which makes it more lethal

### Steps to reproduce the problem
Insert the following code in WYSIWYG editor
<img width="1007" alt="Screenshot 2020-04-01 at 10 43 48 AM" src="https://user-images.githubusercontent.com/8898184/78101652-ceb75000-7405-11ea-8fe8-88d27d798c3f.png">
The token were shown in the response recived 
<img width="1351" alt="Screenshot 2020-04-01 at 10 33 42 AM" src="https://user-images.githubusercontent.com/8898184/78101682-e68ed400-7405-11ea-99d0-bb906a7f1e8b.png">
The password could easily be changed via javascript
<img width="1330" alt="Screenshot 2020-04-01 at 10 32 21 AM" src="https://user-images.githubusercontent.com/8898184/78101701-00301b80-7406-11ea-8080-2eb3eb3f59fc.png">

Nearly anything can be done on Admin account and I don't think it is a feature when you can take the admin account by just posting some content

### Bludit version
3.12.0

### PHP version
PHP 7.1.32

**Comment by dignajar** [comment]
Thank you for post the issue. This was already posted before.
Bludit allows Javascript code in the pages; Bludit does not support user registration is only invited by the administrator of the website, so it's up to the administrator to decide who can post in his system.
Regards
