### ISSUE TITLE
Bludit for Google App Engine

### ISSUE THREAD

**Issue by syaifurrizal** [bludit/bludit#1173]
Hi guys,

I successfully run Bludit in Google App Engine Standard with some work around. Please check at: 

[https://syaifurrizal-grav.appspot.com](https://syaifurrizal-grav.appspot.com) 

May be someone already done this. But I'm still happy and want to share here.

By the way, the step I did:
1. It's assume that you are already familiar with Google Cloud SDK, creating project in Google Cloud with App Engine, and understand that this App Engine after we deploying the app, the app are read only (like a sandbox?).
2. Install Bludit at local computer and do all the things for the first installation.
3. After successfully running Bludit at local computer, browse file folder then go and find file `/bl-content/database/site.php`.
4. Open file `site.php` with text editor and find line code for `"url":"\/\/your-localhost-installation-directory"` and change it to `"url":"https:\/\/your-project-name.appspot.com"` then save it. Noted that we writing with `https` instead of `http`. Because by default this subdomain generated by App Engine serve both `http` and `https`. If we only write `http` in this setting, later when we open the sub domain with `https` the page sometime will load incorrectly.
5. Create new file `php.ini` at the same directory with `index.php` and `install.php`. Open and write: 
```php
allow_url_include = "1"
```
6. Create new file `app.yaml` at the same directory with `index.php` and `install.php` (again). Open and write:
```yaml
runtime: php72

handlers:
- url: /(.*\.(htm|html|css|js|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: \1
  upload: .*\.(htm|html|css|js|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
```
7. Deploy it from your localhost installation folder `gcloud app deploy`.

As I said before, this App Engine from my understanding are read only for each app we deployed. That's why after we deploy the app, this serve like a static site but with capability of php or any runtime used for deploying (Actually I don't know what I'm talking about. I just said what internet said. Don't judge me).

There're an official step by step to install WordPress in App Engine and if I'm not wrong, it's also some trick to make WordPress to be able upload and update by using default Bucket Storage. But I'm not a developer, I only someone who write some blog post in Blogger.com and want to try some new platform for Blogging.

Btw, I also tried with Grav, that's why the subdomain generated by the App Engine have Grav name at there. But Grav are too complicated. It's almost blowing my brain.

Hopefully you guys have a plan to make official Bludit to be able running in Google Cloud Platform especially with App Engine.

Sorry for my broken English.

Regards.

**Comment by dignajar** [comment]
Hi,
thank you for your tutorial.
I will check Google App Engine Standard, I never use it before.
Regards

**Comment by syaifurrizal** [comment]
@dignajar Thank you for your reply

Want to inform you that I'm successfully installing Blundit directly in App Engine with moving all bl-content path to default storage bucket by using stream wrapper (just copy paste and edit from documentation) also with removing all lock_ex in the put function because it's prevent Bludit to write files in bucket. 

I put all Bludit edited files in [here](https://github.com/syaifurrizal/gae-bludit-mod).

The web on `syaifurrizal-grav.appspot.com` above I'll shut it down and move it to [https://bludit.appspot.com](https://bludit.appspot.com/) incase someone interested.

Regards.
