### ISSUE TITLE
(Re-) Load Preview on a single Window / Tab

### ISSUE THREAD

**Issue by SamBrishes** [bludit/bludit#1178]
### Describe your problem
In my opinion it is really annoying when every time I click on the "Preview" button a new window / tab opens. This behaviour can be prevented by using an own name within the `window.open()` method, instead of just `_blank`. That would reload the existing window, or just create it if it doesn't exist. Using the additional `.focus()` method on the window element allows also to "switch" to the Preview tab:

[This is how it would look](https://github.com/pytesNET/bludit/blob/master/bl-kernel/admin/views/new-content.php#L455)

```javascript
var preview = window.open("<?php echo DOMAIN_PAGES.'autosave-'.$page->uuid().'?preview='.md5('autosave-'.$page->uuid()) ?>", "bludit-preview");
preview.focus();
```

### Steps to reproduce the problem
Press the Preview button a few times ;D

### Bludit version
3.12.0

### PHP version
7.2.9

**Comment by dignajar** [comment]
Thank you really nice hack.
I implemented.

https://github.com/bludit/bludit/commit/134ac64e07ef9e3d49d0115d25e5502be234caf1

**Comment by SamBrishes** [comment]
Thanks :D
