### ISSUE TITLE
Syntax highlighting and indentation for TinyMCE's code plugin

### ISSUE THREAD

**Issue by DigitalAssasin** [bludit/bludit#1180]
Hi,

this is not mentioned as a bug report. This is more a question or a low-priority feature request.

I started using the Lightbox plugin on my pages. To enable the lightbox functionality, it is required to add an anchor element for each image element I want to show in the lightbox. This is currently only possible by manipulating the source code of the page directly.

I'm using the TinyMCE editor since this editor provides a source code view of the generated page and allows me to edit the code directly from my browser without the need to download the page's files and manipulate them in a local editor.

But since this code editor is quite low-level, it doesn't support syntax highlighting and indentation which makes it quite hard to find the correct positions in the code for the manipulation.

Do you know if it is possible to enhance TinyMCE's code functionality? Is there a TinyMCE code plugin which provides a code view with syntax highlighting and / or indentation? If there is one, it would be great to use this plugin as a standard for Bludit's TinyMCE package.

I know the TinyMCE editor and it's code plugin are third party components. So maybe this could be even the wrong point to ask.

Regards,

Christian

**Comment by nuke86** [comment]
Hi,
if you are using TinyMCE editor, in Admin dashboard -> Plugins you can find TinyMCE plugin as actived. Click on Settings of this plugin and add an entry on Toolbar top and Plugin textareas: 
- you can add just a space and the string **codesample** in both text areas.

In this way you can publish code lines and code sample in your contents.

**Comment by dignajar** [comment]
Thanks @nuke86
