### ISSUE TITLE
Feature request: multiple domain support.

### ISSUE THREAD

**Issue by MrCyjaneK** [bludit/bludit#1197]
### Describe your problem
When a blog is accessible on 2 or more domains, it will load resources from domain given in settings. 

### Steps to reproduce the problem
Make clean installation, and try to access it from a different domain

### Bludit version
3.12.0

I've managed to fix this issue by changing the definition of `DOMAIN` in `bl-kernel/boot/init.php` to:
```PHP
define('DOMAIN',"");
```
And changing domain to absolute path of installation (/blog/ in my case. Below are some screenshots of how it works.
![bludit-multidomain-1](https://user-images.githubusercontent.com/20381330/82051407-121a0500-96ba-11ea-8d1d-a2c02bd51961.png)
![bludit-multidomain-2](https://user-images.githubusercontent.com/20381330/82051408-12b29b80-96ba-11ea-8348-522fd362a609.png)
![bludit-multidomain-3](https://user-images.githubusercontent.com/20381330/82051410-134b3200-96ba-11ea-8f03-510b2eb9261d.png)

**Comment by cheesington** [comment]
This would be great!  I've been rewriting links in served pages with apache to work around this problem up to now.  Happy to hear it's a simple fix.

**Comment by MrCyjaneK** [comment]
Well, I know that this issue is old, but now to support multiple domains I need to:
```define('DOMAIN',"");```

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
