### ISSUE TITLE
Already wrote about the problem here

### ISSUE THREAD

**Issue by kalimba666** [bludit/bludit#1200]
https://github.com/bludit-themes/mediumish/issues/5

Please have a look.

I like bludit, it's faster than WP. But there should be more flexibility and the search doesn't work at all (white screen is the "result").

No submenus possible. I would like a "burger menu" in the topbar, like in the twenty twenty Wordpress theme with plugin Twentig installed.

P.S. GDPR is also relevant and plugins should be open, means: a description would be needed for what is saved by which plugin.

**Comment by dignajar** [comment]
Hi,
please use this section for report issues on Bludit core.
You can ask in the forum or in the chat.
Regards

**Comment by kalimba666** [comment]
Hi,

the forum is no use, if you are looking for serious support, you will be banned. As it happened for me.
