### ISSUE TITLE
Possible XSS and HTML injection on admin page.

### ISSUE THREAD

**Issue by gh0st56** [bludit/bludit#1205]
Hello I think I found a vulnerability.

This vulnerability consists in a function called showAlert() in the administration panel of bludit,that when accessed in DOM, allows users define the text to be popped up in the message box. But this function dont have any sanatization and the user can inject any javascript and html code in the page

the payload used was: showAlert("<script>alert(1)</script>");

![XSS Picture](https://github.com/gh0st56/bludit-DOM-xss/blob/master/xss-bludit.jpg)

The versions that i tested was the Bludit 3.x. I'll check the old ones for a more in deep report

Thank you.

https://github.com/gh0st56/bludit-DOM-xss

**Comment by dignajar** [comment]
Hi, please search in the issue about this XSS, Bludit allows to the user to insert javascript code. regards
