### ISSUE TITLE
Bug: Search Plugin will not work if itemsPerPage is set to "All Content"

### ISSUE THREAD

**Issue by anaggh** [bludit/bludit#1208]
### Steps to reproduce the problem
Settings > Advanced > Items Per Page -> All Content

`itemsPerPage` is now set to `-1`

Searching now will not show any results.
```
[Thu Jun 11 21:21:16 2020] PHP Warning:  array_chunk(): Size parameter expected to be greater than 0 in /bl-plugins/search/plugin.php on line 134
```

### Bludit version
3.12.0

**Comment by dignajar** [comment]
Fixed by @SamBrishes in https://github.com/SamBrishes/bludit/commit/1ffc196e30b5304dab3a6a7da8300b32cb2d81ac
