### ISSUE TITLE
searching for partial article title returns no results

### ISSUE THREAD

**Issue by working-name** [bludit/bludit#1217]
### Describe your problem
First time looking at bludit; interesting idea. Playing with the demo site however I noticed that the search functionality is rather limited. Unless you search for the full post title it won't be found. Searching for content within articles seems to work as far as I've tested.

### Steps to reproduce the problem
- Search for 'fox' - doesn't bring up the page 'My Fox': [search for fox on demo site](https://demo.bludit.com/search/fox)
- Search for 'my fox' - brings up the page 'My Fox': [search for my fox on demo site](https://demo.bludit.com/search/my%20fox)

### Bludit version
3.12.0 (demo site)

**Comment by dignajar** [comment]
Hi, there is a limitation with the characters, 5 is the min.
I will improve it.

**Comment by Zorrototo** [comment]
I also noticed I couldn't have also any result searching my pages, then by exploring the code I just changed 5 to 4 in /bl-plugins/search/plugin.php

```
		// Inlcude Fuzz algorithm
		require_once($this->phpPath().'vendors/fuzz.php');
		$fuzz = new Fuzz($cache, 10, 1, true);
		$results = $fuzz->search($text, 4);
```

It now gives lot more expected results. I tried with 3 but then it seems to have too much results, but expected results seem to still be on top on page so it works I guess. It is just my workaround in case it helps.

**Comment by dignajar** [comment]
I made some change in the search plugin, now is possible to set up the min chars from the admin panel.
https://github.com/bludit/bludit/commit/2517f0d1818fd350a916bcf343b5ccbd622a776b#diff-6b8d16cfa24497431c021e860d5ee7e5

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
