### ISSUE TITLE
Bludit V3.12.0 -- Admin File Upload  vulnerability

### ISSUE THREAD

**Issue by whiskey-jj** [bludit/bludit#1218]
### Describe your problem
A file upload vulnerability was discovered in Bludit V3.12.0
Hackers need administrator rights.
Hacker can use a backup file to control the server.

### Steps to reproduce the problem

1. Download the latest version of bludit from GitHub.

2. Using burpsuite when uploading logo in the background.
Change picture content to PHP code
`<?php eval($_POST[cmd]); ?>`

![QQ截图20200628011558](https://user-images.githubusercontent.com/40733224/85928228-fa02eb80-b8dd-11ea-8e5f-954ca7a576a5.png)

3. Enable backup plugin.Generate and download a backup file, modify the extension of logo file directly in the zip file.
If you unzip the backup to modify it, the upload will be blocked by WAF.
![image2](https://user-images.githubusercontent.com/40733224/85928608-ca091780-b8e0-11ea-8236-000d9767b429.png)

![image3](https://user-images.githubusercontent.com/40733224/85928265-451cfe80-b8de-11ea-9fcc-8e98f0c0f9d1.png)
![20200628012606](https://user-images.githubusercontent.com/40733224/85928277-5c5bec00-b8de-11ea-8afe-c48cfc2d4098.png)

4. Access _http://127.0.0.1/bl-content/uploads/BLUDIT.php_ to get the getshell
![image4](https://user-images.githubusercontent.com/40733224/85928302-a0e78780-b8de-11ea-80be-761c50b4aa81.png)

Vulnerability in /bl-plugins/backup/plugin.php
```
	public function uploadBackup($backup)
	{
		global $L;

		// Check File Type
		if ($backup["type"] !== "application/zip" && $backup["type"] !== "application/x-zip-compressed") {
			return $this->response(415, $L->get("The passed file is not a valid ZIP Archive."));
		}

		// Check File Extension
		if (stripos($backup["name"], ".zip") !== (strlen($backup["name"]) - 4)) {
			return $this->response(415, $L->get("The passed file does not end with .zip."));
		}

		// Check ZIP extension
		if(!$this->zip) {
			return $this->response(400, $L->get("The passed file could not be validated."));
		}

		// Validate ZIP File
		$zip = new ZipArchive();
		$zip->open($backup["tmp_name"]);
		if($zip->addEmptyDir("databases") || $zip->addEmptyDir("pages") || $zip->addEmptyDir("uploads")) {
			$zip->close();
			return $this->response(415, $L->get("The passed file is not a valid backup archive."));
		}
		$zip->close();

		// File Name
		$name = $backup["name"];
		$count = 0;
		while (file_exists($this->workspace() . $name)) {
			$name = substr($backup["name"], 0, -4) . "." . ++$count . ".zip";
		}

		// Move File to Backup Directory
		Filesystem::mv($backup["tmp_name"], $this->workspace() . $name);
		return $this->response(200, $L->get("The backup file could be uploaded successfully."));
	}
}
```
We can check the image content uploaded by users.
Or just delete the backup module

### Bludit version
V3.12.0

### PHP version
PHP7.3.9nts

**Comment by SamBrishes** [comment]
Hellow,

my solution, as submitted as 2 pull requests, is

- validating the MIME Type, next to the file extension
- adding a MD5 checksum file to the backup archive

This should fix this vulnerability. 

~ Sam.

PS.: Thanks for mention Burp Suite, didn't know about this program. It's really cool. :D

**Comment by whiskey-jj** [comment]
Hello,
  I found a way to bypass the new version of the restrictions to execute files.
  For MD5 detection, attackers only need to set up a local environment, add PHP files in the folder (for example,\bludit-master\bl-content\uploads\profiles), and then use the zip file generated by backup function to attack other servers.

![image](https://user-images.githubusercontent.com/40733224/87173963-143ebf80-c309-11ea-9e93-1cd3800b33e8.png)

**Comment by whiskey-jj** [comment]
> Hellow,
> my solution, as submitted as 2 pull requests, is
> 
> validating the MIME Type, next to the file extension
> adding a MD5 checksum file to the backup archive
> 
> This should fix this vulnerability.
> ~ Sam.
> PS.: Thanks for mention Burp Suite, didn't know about this program. It's really cool. :D

Hello,
    I found a way to bypass the new version of the restrictions to execute files.
    For MD5 detection, attackers only need to set up a local environment, add PHP files in the folder (for example,\bludit-master\bl-content\uploads\profiles), and then use the zip file generated by backup function to attack other servers.
![image](https://user-images.githubusercontent.com/40733224/87174879-6b915f80-c30a-11ea-8353-36e651a511c5.png)
