### ISSUE TITLE
Parent / Child URL issue

### ISSUE THREAD

**Issue by JTWebTools** [bludit/bludit#1231]
### Describe your problem
I found an error on the admin content page.
When I create a child page, the desktop icon link at the Actions column returns the parent permalink.
I'll show you what I mean.

**The next picture shows the parent, of course everything is fine here.**
![parent-page](https://user-images.githubusercontent.com/62479795/87324278-2babc180-c530-11ea-9f8b-20046867edb7.png)

**In the following picture the child is shown with an incorrect URL.**
![child-page-url-nok](https://user-images.githubusercontent.com/62479795/87324306-3403fc80-c530-11ea-8c28-c63505636744.png)

**In this picture the child is shown with a corrected link.**
![child-page-url-ok](https://user-images.githubusercontent.com/62479795/87324341-3d8d6480-c530-11ea-8ab8-45cbc5fd880d.png)

### Steps to reproduce the problem
**The issue found in the _bl-kernel / admin / views / content.php_ file.**
![code-permalink-nok](https://user-images.githubusercontent.com/62479795/87324381-4e3dda80-c530-11ea-811b-82e962dc1527.png)

**And the solution:**
![code-permalink-ok](https://user-images.githubusercontent.com/62479795/87324406-5564e880-c530-11ea-976d-20d204947325.png)

### Bludit version
3.12.0

### PHP version
7.4.5

Please fix it in the next release.
Thank you!
Tomy

**Comment by dignajar** [comment]
Thank you for the detailed issues.
Here is the fix, https://github.com/bludit/bludit/commit/cbf1b5ec1d4a8ddbdaa8b544023a5751ce90bc88
