### ISSUE TITLE
Show categories in dashboard

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1244]
I think it makes sense to show also the categories in the overview of the content in the admin dashboard.

At the moment a template with this addition can be downloaded from

https://github.com/clickwork-git/bludit-modifications-and-snippets/blob/master/admin/views/content.php

**Comment by SamBrishes** [comment]
Good Idea.

A small issue: You're using the wrong variable  [on line 100](https://github.com/clickwork-git/bludit-modifications-and-snippets/blob/master/admin/views/content.php#L100):

```
echo '<td class="pt-3">'.$child->category().'</td>';
```

should be 

```
echo '<td class="pt-3">'.$page->category().'</td>';
```

![wrong](https://user-images.githubusercontent.com/31392477/88758327-79e3d600-d168-11ea-9490-d4f2812211e0.JPG)

**Comment by clickwork-git** [comment]
Thank you! I made a mistake when copying from my local installation to Github.

The issue is now fixed

**Comment by clickwork-git** [comment]
Perhaps it's not a good idea. It's okay if somebody needs it. But there is not always space for it.

![grafik](https://user-images.githubusercontent.com/14312561/89100686-55eaf380-d3f9-11ea-8059-2aa249241f88.png)

**Comment by dignajar** [comment]
It's done for Bludit v4.

![Uploading Screenshot 2021-03-10 at 14.09.21.png…]()

**Comment by dignajar** [comment]
<img width="1112" alt="Screenshot 2021-03-10 at 14 09 21" src="https://user-images.githubusercontent.com/507352/110669088-bec5f580-81aa-11eb-9329-ceb96fbab592.png">

**Comment by clickwork-git** [comment]
Thank you Diego!

Today was a similar wish in the forum: The addition of the author.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
