### ISSUE TITLE
Custom fields via plugin?

### ISSUE THREAD

**Issue by Evergardener** [bludit/bludit#1245]
Is there any way to edit custom fieds via plugin, is there any function for this?
I'm not talking about custom hooks.
I'm talking about this:
![2020-07-30_145210](https://user-images.githubusercontent.com/67442100/88914749-22329100-d274-11ea-8075-9e08374b9243.png)

**Comment by dignajar** [comment]
Plugins has full access to the databases, you can modify settings from a plugin.

Check this example. `Example: Change settings via form`
https://docs.bludit.com/en/plugins/admin-panel-controller-and-view

**Comment by Evergardener** [comment]
Alright, that's cool, so which function does it? :D 👍🏻
I mean, when I look at the code, I see that $pages object has setCustomFields() method, which changes custom fields for all pages, but it doesn't wanna work.
However core editSettings() function works perfectly, but it erases all previous custom fields, to my confusion it uses $pages->setCustomFields() too.
I don't know what's happening, setCustomFields() function returns bool(true), but there's no changes in database.

What I did, which didn't work:
```
global $pages;
$json = '{"inStock":{"type":"bool","label":"In Stock","tip":"Select this field if you have stock."}}';
$pages->setCustomFields($json);
```
But this one did it perfectly erasing all other custom fields and putting given one:

```
$json = array('customFields'=>'{"inStock":{"type":"bool","label":"In Stock","tip":"Select this field if you have stock."}}');
editSettings($json);

```

Bludit's core function:
```
if (isset($args['customFields'])) {
		// Custom fields need to be JSON format valid, also the empty JSON need to be "{}"
		json_decode($args['customFields']);
		if (json_last_error() != JSON_ERROR_NONE) {
			return false;
		}
		$pages->setCustomFields($args['customFields']);
	}
```

$pages method:
```
public function setCustomFields($fields)
	{
		$customFields = json_decode($fields, true);
		if (json_last_error() != JSON_ERROR_NONE) {
			return false;
		}
		foreach ($this->db as $pageKey=>$pageFields) {
			foreach ($customFields as $customField=>$customValues) {
				if (!isset($pageFields['custom'][$customField])) {
					$defaultValue = '';
					if (isset($customValues['default'])) {
						$defaultValue = $customValues['default'];
					}
					$this->db[$pageKey]['custom'][$customField]['value'] = $defaultValue;
				}
			}
		}

		return $this->save();
	}

```

**Comment by dignajar** [comment]
The custom fields are in the `$site` object.

https://github.com/bludit/bludit/blob/master/bl-kernel/site.class.php#L50

Follow the example that I sent to you, try to modify the site title, then try to modify the custom fields.

**Comment by Evergardener** [comment]
So I'm guessing expanding database feature didn't implemented in method itself, old entries still were erased. 
I managed to do it that way:
```
...init{
global $site;
$json = json_decode('{"inStocky":{"type":"bool","label":"In Stocky","tip":"Select this field if you have stock."}}', true);
$myFields = $site->customFields();
$final = json_encode(array_merge($json, $myFields));
$site->set(array('customFields'=>$final));
}
```

**Comment by Evergardener** [comment]
Will you add database expansion feature in the future?
Should I delay before adding new lines to plugin?

**Comment by Evergardener** [comment]
Dowg?

**Comment by dignajar** [comment]
No, I don't have a plan in near feature to do database expansion.
