### ISSUE TITLE
[SECURITY] Missing configurations inside Nginx - Docker image

### ISSUE THREAD

**Issue by ShyanJMC** [bludit/bludit#1247]
### Describe your problem
There are missing configurations inside nginx's server which degrade the blog's security. <br />
I open this issue because Bludit project don't have "Security policy" and docker's image is official.

### Steps to reproduce the problem
With many security tools is easy to find that type of issues, for example; OWASP ZAP which is the most popular tool.

### Bludit version
3.13.1

### Missing security configurations

1. Missing; `add_header X-Frame-Options "SAMEORIGIN";` in `conf.d/default.conf` server block.
2. Missing; `add_header Content-Security-Policy-Report-Only: "default-src 'none'; script-src http://yoursite.com";` in `conf.d/default.conf` server block.
3. Missing; `add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;` in `conf.d/default.conf` server block.
4. Missing; `add_header X-Content-Type-Options "nosniff" always;` in `conf.d/default.conf` server block
5. Missing; `add_header Cache-Control "public, no-transform";` in `conf.d/default.conf` server block. 
5. Missing; `fastcgi_hide_header X-Powered-By;` in in `conf.d/default.conf` "location php" block. 
6. Missing; `add_header X-XSS-Protection "1; mode=block";` in `conf.d/default.conf` server block. 
7. Missing;` add_header X-Permitted-Cross-Domain-Policies master-only;` in `conf.d/default.conf` server block. 
8. Missing; `add_header Referrer-Policy same-origin;`  in `conf.d/default.conf` server block. 
9. Missing; `add_header Feature-Policy "geolocation 'none'; camera 'none'; speaker 'none';";` in `conf.d/default.conf` server block.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
