### ISSUE TITLE
FEATURE REQUEST : add subcategories to categories menu and/or submenu of pages or categories to static pages menu items

### ISSUE THREAD

**Issue by jimmurple** [bludit/bludit#1248]
### Describe your problem
I understand that static pages are... well, static, and categories (as well as tags) are dynamically generated. At some point, I was wondering if I could gather a bunch of static pages in a menu that would show up in the sidebar, or in the navbar. Even better, would be the ability to have subcategories within categories, which would be a great way to organize data.

### Steps to reproduce the problem
Withknown categories are a great example of what I am trying to describe

### Bludit version
3.12.0

### PHP version
7.4.

**Comment by lightmat** [comment]
>  I was wondering if I could gather a bunch of static pages in a menu that would show up in the sidebar

There you can use the core plugin 'Static Pages'

**Comment by jimmurple** [comment]
Hi Lightmat,
thanks for the reply, but I guess my description was a bit too allusive. What I am trying to describe is a categorization that would be intended only to static pages, and be visible from the static page menu instead of being a part of categories. It would be just a way to assemble a bunch of static pages under a header name that would be set as a categorization for these particular pages. As mentioned, the Withknown categorization is an enlightening example of what I am trying to describe.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
