### ISSUE TITLE
XSS vulnerability in 'about' plugin , need 'Blog X' theme to be active

### ISSUE THREAD

**Issue by zongdeiqianxing** [bludit/bludit#1250]
1  http://10.150.10.170/admin/configure-plugin/pluginAbout
About</h2><script>alert('about label')</script>
![image](https://user-images.githubusercontent.com/34082644/89150659-a5fcbe00-d591-11ea-86ed-a1d862b73dcf.png)

2 http://10.150.10.170/create-your-own-content
![image](https://user-images.githubusercontent.com/34082644/89150591-7fd71e00-d591-11ea-9396-1dfa1dcc6552.png)
![image](https://user-images.githubusercontent.com/34082644/89150612-86659580-d591-11ea-85a1-5732d5307b62.png)

**Comment by clickwork-git** [comment]
No vulnerability. You must have admin access. And yes, the admin has to be able to add scripts to the editor field.

**Comment by zongdeiqianxing** [comment]
1.
