### ISSUE TITLE
XSS vulnerability in 'tags list' plugin , need 'Blog X' theme to be active

### ISSUE THREAD

**Issue by zongdeiqianxing** [bludit/bludit#1251]
1 open http://10.150.10.170/admin/edit-content/follow-bludit
Visits<script>alert('xx Tags')</script>
![image](https://user-images.githubusercontent.com/34082644/89150785-eceab380-d591-11ea-8a0b-81e04fee69da.png)

2  open http://10.150.10.170/follow-bludit
![image](https://user-images.githubusercontent.com/34082644/89150817-02f87400-d592-11ea-94ab-0b7e7d5bc383.png)

**Comment by clickwork-git** [comment]
No vulnerability. You must have admin access.

**Comment by SamBrishes** [comment]
You don't need to "hide" your XSS Script on the tags... You can also paste it on the content editor itself (Just use Source Code Action Button on TinyMCE).

![xss1](https://user-images.githubusercontent.com/31392477/89213153-f2152600-d5c4-11ea-9d7c-87af7bcce332.JPG)

![xss2](https://user-images.githubusercontent.com/31392477/89213155-f5101680-d5c4-11ea-8870-f200275ba8cc.JPG)


PS. To be serious, next to my [post on your first XSS Issue](https://github.com/bludit/bludit/issues/1249#issuecomment-668162582), you may can easily fixs this by using `strip_tags()` or an regexp, which removes all non-alphanumeric characters... And my "hacky" XSS may can only be fixed using a big library, such as [Kses](https://github.com/pytesNET/php-helpers/tree/master/PIT/Kses).

**Comment by dignajar** [comment]
Hi guys,
there are someplace where we need to filter Javascript code or any kind of code, for example in tags, or category names, etc..

But there are places such as the page content where I like to keep the user publish Javascript, for example, to embed Tweets, Google maps, or any kind of embed code.

Regards

**Comment by zongdeiqianxing** [comment]
if you think there is not a risk , you can ignore it
