### ISSUE TITLE
XSS vulnerability in 'HTML Code' plugin , need 'Blog X' theme to be active

### ISSUE THREAD

**Issue by zongdeiqianxing** [bludit/bludit#1252]
1 http://10.150.10.170/admin/configure-plugin/pluginHTMLCode
<script>alert("THML CODE's Head")</script>
![image](https://user-images.githubusercontent.com/34082644/89151071-a5185c00-d592-11ea-85ba-4d085d4ab89e.png)

2 http://10.150.10.170/create-your-own-content
![image](https://user-images.githubusercontent.com/34082644/89151116-c416ee00-d592-11ea-9a06-a121e0e0b393.png)
![image](https://user-images.githubusercontent.com/34082644/89151194-f6c0e680-d592-11ea-9397-2d22cbf3e667.png)

**Comment by dignajar** [comment]
This is fine, Bludit allow javascript code.
