### ISSUE TITLE
Reflected XSS on admin login page, username input

### ISSUE THREAD

**Issue by 404-OS** [bludit/bludit#1254]
**### Describe your problem**
The verifyUser () function inside the login.class.php class, applies htmlspecialchars () and trim () on the username.
These functions do not prevent the use of the character "

![verifyUser](https://user-images.githubusercontent.com/69433799/90028038-7d737300-dcb9-11ea-8190-b7635fc77964.PNG)
##
![html](https://user-images.githubusercontent.com/69433799/90028261-be6b8780-dcb9-11ea-98f1-163f20753ef2.PNG)

The login.php view for admin directly loads the $ _POST value in the username input value.

![username-input](https://user-images.githubusercontent.com/69433799/90035510-2c1bb180-dcc2-11ea-9fce-95861fc70e88.PNG)

### Steps to reproduce the problem
With this in mind, you can break the html code using the "character followed by a js event like onclick. 
Go to admin login username field and put this payload: "onclick('XSS');  Or try with your username. Ex: 404-OS"onclick('XSS');

![xss-added](https://user-images.githubusercontent.com/69433799/90036861-c7f9ed00-dcc3-11ea-9793-5e4c356c696d.PNG)
##
![xss-launched](https://user-images.githubusercontent.com/69433799/90036912-db0cbd00-dcc3-11ea-87e4-1b95c9da83f1.PNG)

### Bludit version
Tested on bludit 3.9.2 and latest version

### PHP version
Tested on php 5.6 version

### Proposal solution
Create a function that apply a black list with special chars and js events to filter in a string on sanitize.class.php

**Comment by Tibinsunny** [comment]
Hmm,
This seems to be a valid issue @404-OS  . I was able to reproduce it. 
I'm going to take a stab at the issue. Let me check if I can implement a fix.


Cheers,
Tibin

**Comment by dignajar** [comment]
Fixed by @Tibinsunny
