### ISSUE TITLE
Published or not published?

### ISSUE THREAD

**Issue by a6147z** [bludit/bludit#1269]
1) A page should denote whether it is published(green color) or not published (red Color).
2) A page should denote whether it is saved (green color) or not saved (red Color).
3) A tick mark and and cross mark will also help

**Comment by clickwork-git** [comment]
>     1. A page should denote whether it is published(green color) or not published (red Color).

Where should this color mark be?

Content that is not published is marked as "Draft" (and yes, "Published" is marked green) and can be found at "Content" > "Draft".

>     2. A page should denote whether it is saved (green color) or not saved (red Color).

Yes, a hint, if a content is not yet saved would help. Perhaps a popup.
 
>     3. A tick mark and and cross mark will also help

Help for what? Where?

**Comment by BlakesHeaven** [comment]
Sorry if you think this is not relevant,  however, I believe the status should be the only thing that denotes it a page is published or not. The scheduled date should not be touched or interfered with when changing the status. 
Equally, children should be allowed to be added to pages that are Draft or scheduled in the future.
Thanks.

**Comment by a6147z** [comment]
@clickwork-git Posting a new page/post and whether it is published or not, needs to be tested.
the testing should be about: how a newbie  will come to know whether the new post is published or not? 
I come know that just today  that saving will publish the new post.
Should it be done?

**Comment by BlakesHeaven** [comment]
IMO, there are two things that cause confusion here:
1. New content should start as Draft, not Published
![20201019_195738](https://user-images.githubusercontent.com/37149377/96501096-c874ae00-1247-11eb-8e1e-df5a510c05b2.jpg)
Then, when it is saved it will **not** be immediately published. It should be up to the content creator to change the state from Draft to Publish**ed**
If a colour indicator helps, how does the red look by the button?
2. The text of the status, "Publish" is simply wrong and very misleading to a newbie, as @a6147z puts it! It should be "Publish**ed**", with an "ed" at the end. To "Publish" is what you do to make it published. 
![20201019_200323](https://user-images.githubusercontent.com/37149377/96506340-5d2eda00-124f-11eb-90c5-0ce04ea0caa3.jpg)
You could argue that the button text should be separated from the status text:
- Btn text, "Make Published". Current Status: "Draft"
- Btn text: "Make Draft". Current Status: "Publish**ed**"

Sorry,  but I've made these exact comments before, along with the statement above about the date needing to be separated from the status so Parent Child relationships can be established while scheduled. 

Anyway,  I hope this helps.

**Comment by dignajar** [comment]
Hi guys, I'm working on the new UI for Bludit v4.
I will let you know when I have something working properly and you can check it and we can review this issue with the confusion with the buttons and the publish status.

**Comment by a6147z** [comment]
There should be four button :
- 1. Save button> no matter the post is published or draft (blue colour is ok)
but saving it first time, it should change to draft. tick/cross mark and grey colour is good  sign after saving a draft.
- 2. Preview button > ok - (Black colour is ok)
- 3. Publish button (which can be changed to published after publishing) - tick and cross mark, when not 'published' white colour is ok, after publishing green is better. Bigger id better.
- 4. Draft button  > a button to unpublish and make the published post back to draft. Ted colour may be okay.
All on first button.at least on first page while posting.

**Comment by dignajar** [comment]
I'm working in the admin area and everything will be AJAX, so you don't need to leave the page to apply the changes.
For the Editor you can edit the features, click on Save button, and will apply instantly.

For example, if the user clicks on the status, then choose the status, and click "Save" will apply the changes.

<img width="1351" alt="Screenshot 2020-10-22 at 16 58 16" src="https://user-images.githubusercontent.com/507352/96890472-f5af9f00-1487-11eb-872c-1d5e3b60afa7.png">
<img width="1357" alt="Screenshot 2020-10-22 at 16 58 05" src="https://user-images.githubusercontent.com/507352/96890487-f9432600-1487-11eb-8016-6efd618cd2ac.png">
<img width="1345" alt="Screenshot 2020-10-22 at 16 57 49" src="https://user-images.githubusercontent.com/507352/96890490-f9dbbc80-1487-11eb-9aab-249ec2842cd3.png">

**Comment by dignajar** [comment]
also for the case the user click in the button "Save" will be disabled and the word will change to "Saved".

<img width="1354" alt="Screenshot 2020-10-22 at 17 04 15" src="https://user-images.githubusercontent.com/507352/96891183-af0e7480-1488-11eb-83fc-1158c700dd54.png">

**Comment by lightmat** [comment]
@dignajar -  Looks great but isn't Draft and Private same same? Or is Private like an private page for selected members?

**Comment by dignajar** [comment]
@lightmat it's not implemented yet, but the idea is a published page but only accessible if you have the link, I mean is not display in the main page. Maybe the name is not correct, suggestions?

**Comment by lightmat** [comment]
@dignajar - No i'am aware of that. Well i think the word "Private" is fine, but the text could be a bit more precise if it is something like "Publish the page, visible only by linked url"

**Comment by BlakesHeaven** [comment]
Hi @dignajar , looking great and I like your Private option, or Unlisted as YouTube calls it.

Will you be addressing the date thing, where if scheduled in the future it won't let you create parent/child relationships? Very important to pre schedule a set of pages.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Comment by kragil** [comment]
I think this should be reopened. This Publish as default and as a Toggle Button is pretty bad and not something people expect. I support all the changes that are proposed here.
