### ISSUE TITLE
File name of uploaded logo

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1272]
The file name of the uploaded logo uses the title of the website:

`<img src="/bl-content/uploads/<?php echo $site->title(); ?>.png" alt="logo">?`

It would be better to use something like `logo.png`, because the title of the website could consist of several words (with spacing) and special characters. This could cause problems with some servers or browsers.

**Comment by lightmat** [comment]
I agree. It can also be that you change the title of the page, so it is easier if it is a fixed name as a logo, so you do not have to remember to change the name of the logo.

**Comment by dignajar** [comment]
The idea with the name of the file was for SEO purposes, so the search engines can link your image with your website name. I don't know if it's valid.

What is possible is trim spaces and special-chars from the filename.

**Comment by dignajar** [comment]
@lightmat you don't need to change the code for get the logo-name, you can use
```
<?php
echo 'Logo URL' . $site->logo();
echo 'Logo filename' . $site->logo(false);
?>
```

**Comment by lightmat** [comment]
@dignajar - well yes, that's how it could be done. I had not just thought about that. 😄

**Comment by SavaAlexandruStefan** [comment]
the idea is good. The file name can contain spaces and it messes up with your html validation

**Comment by dignajar** [comment]
For Bludit v4, I did the following to keep the SEO feature in the logo.

If the Site title is empty, the filename is `logo.<extension>`.
If the Site title is `Happy Blög`, the filename will be `happy-blog.<extension>`.

The extension is the same as the file you uploaded.

The PHP functions to get the filename logo.
```
echo $site->logo(false); // Print the filename
echo $site->logo(); // Print the absolute path of the logo with the domain
```

Image example
```
<img src="<?php echo $site->logo() ?>" alt="Site logo" />
```

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
