### ISSUE TITLE
How do I pass a function argument via plugin hooks?

### ISSUE THREAD

**Issue by kovalensky** [bludit/bludit#1279]
Given what is written on the page https://docs.bludit.com/en/plugins/custom-hooks-for-plugins, the hook can be called using the Theme::plugins('HOOK') method, but what if I want to pass arguments to the function like Theme::plugins('HOOK($data)')?
Maybe it is a bizarre question.

**Comment by dignajar** [comment]
Hi, yes you can do it like this.

```
Theme::plugins('HOOK', $args = array());
```

https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/theme.class.php#L229

**Comment by smell-of-rain** [comment]
> 
> 
> Hi, yes you can do it like this.
> 
> ```
> Theme::plugins('HOOK', $args = array());
> ```
> 
> https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/theme.class.php#L229

Hmm, so it always echoes output, I was hoping that it will return it :(
https://github.com/bludit/bludit/blob/8c4a6d8f9e34c75cdbdecfc326b1f8802e7feabe/bl-kernel/helpers/theme.class.php#L233

**Comment by dignajar** [comment]
can you tell me what are you trying to do ? maybe we can figure it out some workaround or improve the functions.

**Comment by smell-of-rain** [comment]
I wanted to create something like a Custom Fields database for pages, with the hope of adding a counter for article visits, but I didn't want to connect widgets.
I already did this by embedding it in the theme code, but I wanted to write a separate plugin for the sake of interest, but the echo problem caught up with me, and plus passing something like Theme::plugins('customPages', array(array("key"=>$value), false, true)) or Theme::plugins('customPages')["key"] is wildly uncluttered.
I would like to get something more convenient and close to the end user in the next releases. Thank you.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
