### ISSUE TITLE
Bludit with UIkit newer than 3.1.6

### ISSUE THREAD

**Issue by dizajnadva** [bludit/bludit#1280]
### Describe your problem
So, during testing, when including UIkit version newer than 3.1.6 as described on :

https://docs.bludit.com/en/themes/include-frameworks

sample autoplay slideshow html code insetrted to the Bludit page does not start like it should, but has a noticeable delay. Delay is so long that it misses all (three in the test) slides and starts sliding only afterwards. Even w or w/o autoplay clicking on the next slideshow item icon does nothing for nuber of seconds..

### Steps to reproduce the problem
Install Bludit 3.13.1and follow https://docs.bludit.com/en/themes/include-frameworks but w links to newer versions of UIkit

### Bludit version
3.13.1

**Comment by dignajar** [comment]
Hi, looks like is not an issue with Bludit.
Check the logs in the browser console.
