### ISSUE TITLE
Bludit Pro Php Errors Log Files

### ISSUE THREAD

**Issue by neilsweb** [bludit/bludit#1286]
### Describe your problem
Hi Guys I seem to have a problem in my error log files, but dont know what is actually causing the issue. the errors only put these in my logs. I've wriiten the url's below and what error actually comes.

### Steps to reproduce the problem
When i visit these Url's I get the following errors in error log files, I did post this on the forum but someone suggested that it is a bug. Please understand I'm not a professional but willing to learn.

### Bludit version
Bludit Pro 3.13.1

### PHP version
7.4.9 Mamp Pro version 6.1 on Mac 

### PHP logs
URL Visited: /admin/dashboard gets these errors:   /bl-content/workspaces/backup/*.zip, /bl-content/workspaces/simple-stats/*.log

URL Visited: /admin/settings /bl-languages/*.json, /bl-content/workspaces/backup/*.zip
URL Visited: /admin/new-content /uploads/pages/11285b4a1a27aacaf4f9edbe706d7880/thumbnails/*.*

On nearly every url i visit in Admin i get this error /bl-content/workspaces/backup/*.zip

When i disable backup i get this error on some admin url's /bl-languages/*.json

The front cms is perfectly fine.

**Comment by dignajar** [comment]
Hi,
thanks for report the issue.

Have you install some plugin / theme ?

Can you enable the full logs, you need to change this file on line 12, and put the loglevel to `INFO`.
https://github.com/bludit/bludit/blob/master/bl-kernel/boot/init.php#L12

Regards

**Comment by neilsweb** [comment]
Hi,
I went to: /bl-kernel/boot/init.php and this is already set to INFO by default.

// Debug mode
// Change to FALSE, for prevent warning or errors on browser
define('DEBUG_MODE', FALSE);
define('DEBUG_TYPE', 'INFO'); // INFO, TRACE
error_reporting(0); // Turn off all error reporting
if (DEBUG_MODE) {
	// Turn on all error reporting
	ini_set("display_errors", 0);
	ini_set('display_startup_errors',0);
	ini_set("html_errors", 1);
	ini_set('log_errors', 1);
	error_reporting(E_ALL | E_STRICT | E_NOTICE);
}

On default installation with Bludit Pro in my server log php errors in Mamp Pro all i get when visiting or refreshing the page in /admin/settings is: 
[18-Nov-2020 15:30:29 Europe/London] /Users/myname/Sites/myfolder/bl-languages/*.json

I had to change myname/myfolder/ in example to hide my information.

Thanks

**Comment by neilsweb** [comment]
Hi Guys,
I know what part of the code is causing this error: [18-Nov-2020 15:30:29 Europe/London] /Users/myname/Sites/myfolder/bl-languages/*.json

In /bl-kernel/admin/views/settings.php on line 476 is:
'options'=>$L->getLanguageList(),

if i edit this out and refresh the /admin/settings page i get no error, So I'm assuming it must be something to do with the languages it fetches, but I'm not a coder and i may be wrong! but just trying to help.

**Comment by dignajar** [comment]
What is your default language in the settings ?

I'm start to thing you have some broken `.json` file, can you do the following:
- Delete all files from `/Users/myname/Sites/myfolder/bl-languages/`
- Copy from the original zip file, the file `en.json` to `/Users/myname/Sites/myfolder/bl-languages/en.json`

**Comment by neilsweb** [comment]
Hi,
Thanks for getting back to me.

Default language is English

Locale is en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ

Hi done what you have said I have only en.json file in the directory and exactly same issue in php error log file
[19-Nov-2020 10:05:32 Europe/London] /Users/myname/Sites/myfolder/bl-languages/*.json

**Comment by dignajar** [comment]
The thing is that error doesn't said anything, I would like to have the full error log.
Let do the following, increase the loglevel to `TRACE`, the same file I mention before change `INFO` for `TRACE`.

```
define('DEBUG_TYPE', 'TRACE'); // INFO, TRACE
```

Also please paste the full log.
Thanks!

**Comment by neilsweb** [comment]
Hi,
I have made fresh install of Bludit Pro left everything default my language is English, deleted the .json languages and only have fresh copy of en.json in their also changed the file to TRACE and cleared my php_error.log. The logs don't say anything different with enabling TRACE.

I visited a few links in the Admin, here is the copy of the full log file with nothing changed:

[19-Nov-2020 16:58:55 Europe/London] /Users/neiltaylor/Sites/bludit-pro/bl-content/workspaces/simple-stats/*.log
[19-Nov-2020 16:59:11 Europe/London] /Users/neiltaylor/Sites/bludit-pro/bl-languages/*.json
[19-Nov-2020 16:59:27 Europe/London] /Users/neiltaylor/Sites/bludit-pro/bl-content/uploads/pages/bf07c1f3a9a57dfd9d3e8b74435f1e33/thumbnails/*.*

Thanks again for help.

**Comment by neilsweb** [comment]
Hi,
Been up all night trying to find the actual problem, I think I've narrowed it down to select2 because everypage that is causing a problem has some script that involves select2. I think it may be a path issue?

I started the website this time with php -S localhost:8000 abd here i can see that the url's are going to the actual path rather than the domain, but i'm not a programmer and maybe wrong so i copied the output from the terminal.

It actually shows the full path /Users/neiltaylor/Sites/countyskills while the rest of the pages start with /bl-kernel/admin/

[Fri Nov 20 04:07:42 2020] /Users/neiltaylor/Sites/countyskills/bl-content/workspaces/simple-stats/*.log
[Fri Nov 20 04:07:42 2020] [::1]:63719 [200]: /admin/dashboard
[Fri Nov 20 04:07:42 2020] [::1]:63720 [200]: /bl-kernel/css/bootstrap.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63721 [200]: /bl-kernel/css/line-awesome/css/line-awesome-font-awesome.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63723 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63722 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/booty-dark.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63724 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.bootstrap.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63725 [200]: /bl-kernel/css/jquery.datetimepicker.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63726 [200]: /bl-kernel/css/select2.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63727 [200]: /bl-kernel/css/select2-bootstrap4.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63728 [200]: /bl-kernel/js/jquery.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63729 [200]: /bl-kernel/js/bootstrap.bundle.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63730 [200]: /bl-kernel/js/jquery.sortable.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63731 [200]: /bl-kernel/js/jquery.datetimepicker.full.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63732 [200]: /bl-kernel/js/select2.full.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63733 [200]: /bl-kernel/js/functions.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63734 [200]: /bl-plugins/simple-stats/css/chartist.min.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63735 [200]: /bl-plugins/simple-stats/css/style.css?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63736 [200]: /bl-plugins/simple-stats/js/chartist.min.js?version=3.13.1
[Fri Nov 20 04:07:42 2020] [::1]:63737 [200]: /bl-kernel/img/logo.svg
[Fri Nov 20 04:09:36 2020] /Users/neiltaylor/Sites/countyskills/bl-content/workspaces/simple-stats/*.log
[Fri Nov 20 04:09:36 2020] [::1]:63742 [200]: /admin/dashboard
[Fri Nov 20 04:09:36 2020] [::1]:63744 [200]: /bl-kernel/js/jquery.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63743 [200]: /bl-kernel/js/bootstrap.bundle.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63745 [200]: /bl-kernel/js/jquery.sortable.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63746 [200]: /bl-kernel/js/jquery.datetimepicker.full.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63747 [200]: /bl-kernel/js/functions.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63748 [200]: /bl-kernel/js/select2.full.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63749 [200]: /bl-plugins/simple-stats/js/chartist.min.js?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63750 [200]: /bl-kernel/css/bootstrap.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63751 [200]: /bl-kernel/css/line-awesome/css/line-awesome-font-awesome.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63752 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63753 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/booty-dark.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63754 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.bootstrap.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63755 [200]: /bl-kernel/css/jquery.datetimepicker.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63756 [200]: /bl-kernel/css/select2.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63757 [200]: /bl-kernel/css/select2-bootstrap4.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63758 [200]: /bl-plugins/simple-stats/css/chartist.min.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63759 [200]: /bl-plugins/simple-stats/css/style.css?version=3.13.1
[Fri Nov 20 04:09:36 2020] [::1]:63760 [200]: /bl-kernel/img/logo.svg
[Fri Nov 20 04:09:36 2020] [::1]:63761 [200]: /bl-kernel/img/favicon.png?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63765 [200]: /admin/themes
[Fri Nov 20 04:10:25 2020] [::1]:63767 [200]: /bl-kernel/js/jquery.min.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63766 [200]: /bl-kernel/js/bootstrap.bundle.min.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63768 [200]: /bl-kernel/js/jquery.datetimepicker.full.min.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63769 [200]: /bl-kernel/js/jquery.sortable.min.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63770 [200]: /bl-kernel/js/functions.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63771 [200]: /bl-kernel/js/select2.full.min.js?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63772 [200]: /bl-kernel/css/bootstrap.min.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63775 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/booty-dark.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63773 [200]: /bl-kernel/css/line-awesome/css/line-awesome-font-awesome.min.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63774 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63776 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.bootstrap.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63777 [200]: /bl-kernel/css/jquery.datetimepicker.min.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63778 [200]: /bl-kernel/css/select2.min.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63779 [200]: /bl-kernel/css/select2-bootstrap4.min.css?version=3.13.1
[Fri Nov 20 04:10:25 2020] [::1]:63780 [200]: /bl-kernel/img/logo.svg
[Fri Nov 20 04:10:25 2020] [::1]:63782 [200]: /bl-kernel/img/favicon.png?version=3.13.1
[Fri Nov 20 04:10:41 2020] /Users/neiltaylor/Sites/countyskills/bl-content/workspaces/simple-stats/*.log
[Fri Nov 20 04:10:41 2020] [::1]:63784 [200]: /admin/dashboard
[Fri Nov 20 04:10:41 2020] [::1]:63786 [200]: /bl-kernel/js/jquery.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63785 [200]: /bl-kernel/js/bootstrap.bundle.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63787 [200]: /bl-kernel/js/jquery.datetimepicker.full.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63788 [200]: /bl-kernel/js/jquery.sortable.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63789 [200]: /bl-kernel/js/functions.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63790 [200]: /bl-kernel/js/select2.full.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63791 [200]: /bl-plugins/simple-stats/js/chartist.min.js?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63792 [200]: /bl-kernel/css/bootstrap.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63793 [200]: /bl-kernel/css/line-awesome/css/line-awesome-font-awesome.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63794 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63795 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/booty-dark.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63796 [200]: /bl-kernel/admin/themes/booty-dark-admin/css/bludit.bootstrap.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63797 [200]: /bl-kernel/css/jquery.datetimepicker.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63798 [200]: /bl-kernel/css/select2.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63799 [200]: /bl-kernel/css/select2-bootstrap4.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63800 [200]: /bl-plugins/simple-stats/css/chartist.min.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63801 [200]: /bl-plugins/simple-stats/css/style.css?version=3.13.1
[Fri Nov 20 04:10:41 2020] [::1]:63802 [200]: /bl-kernel/img/logo.svg
[Fri Nov 20 04:10:41 2020] [::1]:63804 [200]: /bl-kernel/img/favicon.png?version=3.13.1

**Comment by dignajar** [comment]
I was reading the forum, and you mention the problem is on the plugin simple stats ?

**Comment by neilsweb** [comment]
Yes I thought it was? but like i said I'm not a programmer and later realised there was more errors. I even installed it in different language to see if it was languge issue,  I then thought it may have something to do with Mamp on a Mac, so i uploaded it to live server in the night but still was getting the errors.

I then looked at the pages that I clicked and noticed a pattern that everyone of those pages contained select2.

**Comment by dignajar** [comment]
But I don't see errors in the logs, at least in the logs you are posting here

**Comment by neilsweb** [comment]
This is what i get in my server error logs:
/Users/neiltaylor/Sites/countyskills/bl-content/workspaces/simple-stats/*.log
If you look at the logs i posted above you can see it misses off "[::1]:63774 [200]:" So everytime it does this in my server logs it produces the error and it keeps repeating itself everytime I click on the links with selet2 involved. Probably im not explaining it properly.

Would it be better if i can video it to show you?

**Comment by lightmat** [comment]
I agree with @dignajar . This is not an error you see, but an info about an IPv6 http request, which has been completed with the HTTP status code 200 = OK.
In your hosts file, which you will find under "tools" in Mamp Pro, you can open "/etc/ hosts" and the last line will say ":: 1    localhost"
I think you get that message in Mamp because your network does not support IPv6, but I'm not sure and can not check it, because I also only have IPv4, so far.

**Comment by neilsweb** [comment]
I thought this was a error somewhere because even on my live server in error_logs file everytime I visited a link in admin with select2 it puts the lines: /Users/neiltaylor/Sites/countyskills/bl-content/workspaces/simple-stats/*.log and if i got backup plugin installed it did the same.

I will just login to my server once in a while to clear the lines in the error_logs file.

I do apologise if I have wasted your time looking into this, but thought it might have been a more serious issue.

thanks again for great support

**Comment by anaggh** [comment]
This should fix it - https://github.com/bludit/bludit/pull/1288/commits/a03c9f2558a9075d198a7b5a4f987f74f94faae3

**Comment by anaggh** [comment]
```
$ git blame -L 30,+1 bl-kernel/helpers/filesystem.class.php
a8b4b26c5 (Diego Najar 2020-03-14 12:03:43 +0100 30)            error_log($path.$regex.'.'.$extension);
```

**Comment by neilsweb** [comment]
@anaggh Thank you very much, also to everyone else who got involved! You Guys have a really good community here.
Also thanks for making the script open source.

**Comment by dignajar** [comment]
Yes @anaggh is right about the patch I did, I totally forgot about it.
