### ISSUE TITLE
Small bug found in welcome message ( admin dashboard )

### ISSUE THREAD

**Issue by SavaAlexandruStefan** [bludit/bludit#1289]
### Describe your problem
I've found a small bug in Bludit's admin panel. The welcome message shows good night when it's 12 o'clock (day time). Here's also the fix:

### Steps to reproduce the problem
Just enter admin panel -> dashboard

### Bludit version
3.13.1

Here's the fix also:  File: bl-kernel/admin/views/dashboard.php

```
<script>
$( document ).ready(function() {
$("#hello-message").fadeOut(1000, function() {
var date = new Date()
var hours = date.getHours()
if (hours > 6 && hours < 12) {
$(this).html('<span class="fa fa-sun-o"></span><?php echo $L->g('good-morning') ?>');
} else if (hours >= 12 && hours < 18) {
$(this).html('<span class="fa fa-sun-o"></span><?php echo $L->g('good-afternoon') ?>');
} else if (hours >= 18 && hours < 22) {
$(this).html('<span class="fa fa-moon-o"></span><?php echo $L->g('good-evening') ?>');
} else {
$(this).html('<span class="fa fa-moon-o"></span><span><?php echo $L->g('good-night') ?></span>');
}
}).fadeIn(1000);
});
</script>
```

 2 = were missing

**Comment by dignajar** [comment]
Hi, fixed for Bludit v4.
Also, I created a plugin for it to remove it from the Bludit Core.

**Comment by dignajar** [comment]
https://github.com/bludit/bludit/blob/v4.0/bl-plugins/welcome/plugin.php#L40-L42
