### ISSUE TITLE
How to get category key from a page

### ISSUE THREAD

**Issue by greinbold** [bludit/bludit#1293]
Hi

I have an issue to get category key from a page.

When I make a `var_dump($page)` it returns ` ["category"]=> string(5) "image"`. I think this is the category key.

When I try to get it with `$page->category()` it returns `Image`. I think this is the name of the category, not the key.

Then I try to find the category object:

```
$category = new Category($page->category());
```

This return

```
[Tue Dec 29 09:17:26 2020] 127.0.0.1:36416 [500]: GET / - Uncaught Exception: Category not found in database by key [Image] in /home/gregory/bludit-3-13-1/bl-kernel/category.class.php:20
Stack trace:
#0 /home/gregory/bludit-3-13-1/bl-themes/nosheep/php/home.php(37): Category->__construct()
#1 /home/gregory/bludit-3-13-1/bl-themes/nosheep/index.php(17): include('/home/gregory/b...')
#2 /home/gregory/bludit-3-13-1/bl-kernel/boot/site.php(26): include('/home/gregory/b...')
#3 /home/gregory/bludit-3-13-1/index.php(41): require('/home/gregory/b...')
#4 {main}
  thrown in /home/gregory/bludit-3-13-1/bl-kernel/category.class.php on line 20
```

How to get the category key from the page?

This issue seems similar to https://github.com/bludit/bludit/issues/1292

**Comment by dignajar** [comment]
Here the list of methods for categories.
https://github.com/bludit/bludit/blob/master/bl-kernel/pagex.class.php#L175-L220

This method returns the category name `$page->category()`

**Comment by greinbold** [comment]
Nice, it work, thanks you very much.

I'm so sorry for my newbie issues.
