### ISSUE TITLE
/rss.xml not found

### ISSUE THREAD

**Issue by greinbold** [bludit/bludit#1295]
### Describe your problem
Hi

I'm probably wrong somewhere but I don't see where.

I just activated the RSS plugin and when I try to access to the feed I get a 404:

```
[Wed Dec 30 09:19:59 2020] 127.0.0.1:42054 [404]: GET /rss.xml - No such file or directory
```

I have 5 published posts for the example.

### Steps to reproduce the problem

Write some posts, install the RSS feed plugin and try to access to the feed.

### Bludit version

3.13.1

### PHP version

```
$ php -v
PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

Regards

**Comment by greinbold** [comment]
I published my website on my server and the RSS feed plugin works now.

Maybe an issue only for the built-in web server which I use since the beginning.

**Comment by dignajar** [comment]
The built-in web server tries to find a file because of the extension so returns 404. The Apache has some rewrite rules that redirect the `rss.xml` to the file in `/bl-content/xxx`
