### ISSUE TITLE
API plugin GET /pages/<key> method does not return UUID

### ISSUE THREAD

**Issue by grz8** [bludit/bludit#1297]
### Describe your problem

Hi

To upload an image and attach it to a page via the API, I need the UUID of the page:

https://github.com/bludit/bludit/blob/master/bl-plugins/api/plugin.php#L476

But the GET `/api/pages/<key>` method does not return the UUID field:

```json
{
  "status": "0",
  "message": "Page filtered by key: titre-de-test",
  "data": {
    "key": "titre-de-test",
    "title": "Titre de test !!",
    "content": "",
    "contentRaw": "",
    "description": "",
    "type": "published",
    "slug": "titre-de-test",
    "date": "1 janvier 2021",
    "dateRaw": "2021-01-01 12:39:08",
    "tags": "",
    "username": "admin",
    "category": false,
    "dateUTC": "2021-01-01 11:39:08",
    "permalink": "http://localhost:8000/titre-de-test",
    "coverImage": false,
    "coverImageFilename": false
  }
}
```

In `databases/pages.php`

```json
{"titre-de-test":{"title":"Titre de test !!","description":"","username":"admin","tags":[],"type":"published","date":"2021-01-01 12:39:08","dateModified":"","position":0,"coverImage":"","category":"","md5file":"d41d8cd98f00b204e9800998ecf8427e","uuid":"7671c0ede6cd0dea3cb459653a9a882d","allowComments":true,"template":"","noindex":false,"nofollow":false,"noarchive":false,"custom":[false]}}
```

I checked:

-  https://github.com/bludit/bludit/blob/master/bl-kernel/pagex.class.php#L284
-  https://github.com/bludit/bludit/blob/master/bl-plugins/api/plugin.php#L399

I can see that the `$page->json` method should return the UUID, but it's not the case.

I don't understand why.

### Bludit version

3.13.1

### PHP version

```
$ php -v
PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
