### ISSUE TITLE
Bludit v3.13.1 Code Execution Vulnerability in "Backups"

### ISSUE THREAD

**Issue by Gingsguard** [bludit/bludit#1298]
Hi,I found a code execution vulnerability in Bludit v3.13.1 admin panel   

the path is bl-plugins/backup/plugin.php  

**1, Log in to the admin panel**  
![图片](https://user-images.githubusercontent.com/21252367/103636497-064ebc00-4f85-11eb-960c-f4d098576648.png)  

**2, Click the backups button**  
![图片](https://user-images.githubusercontent.com/21252367/103636585-2c745c00-4f85-11eb-96f4-d156c8d2047b.png)  

**3, Making evil backup zip**  

First download a backup
 
![图片](https://user-images.githubusercontent.com/21252367/103636622-37c78780-4f85-11eb-8d1a-e1ffb7ac3166.png)

then use this zip to modify  

Place phpinfo.php file in path 2021-01-05-16-20-03\uploads\pages 
 
![图片](https://user-images.githubusercontent.com/21252367/103636661-431ab300-4f85-11eb-9bff-360c02c499be.png)

![图片](https://user-images.githubusercontent.com/21252367/103636675-4746d080-4f85-11eb-8864-0df23fb850cc.png)

Package 2021-01-05-16-20-03 as evil.zip
 
![图片](https://user-images.githubusercontent.com/21252367/103636688-4a41c100-4f85-11eb-8695-df77451456b8.png)

Execute the script to generate the md5 for the .BLUDIT_BACKUP 
![图片](https://user-images.githubusercontent.com/21252367/103636698-4ca41b00-4f85-11eb-96d5-739eeedb9ac2.png)

**4, upload the evil backup zip**
 
![图片](https://user-images.githubusercontent.com/21252367/103636715-53329280-4f85-11eb-9a18-e4c6f90d7916.png)

**5, Click the restore backup button**
 
![图片](https://user-images.githubusercontent.com/21252367/103636722-562d8300-4f85-11eb-9aa2-d88ea9bcca93.png)

**6, Access the evil file bl-content/uploads/pages/phpinfo.php**
 
![图片](https://user-images.githubusercontent.com/21252367/103636727-59287380-4f85-11eb-8d1b-e8932cbe15c0.png)

**Comment by Gingsguard** [comment]
@dignajar

**Comment by dignajar** [comment]
Hi,
yes was already mentioned here.
https://github.com/bludit/bludit/issues/1242
