### ISSUE TITLE
Search plugin redirects output to .../search/...

### ISSUE THREAD

**Issue by polcud** [bludit/bludit#1302]
### Describe your problem
Hello,
while using the search box (search plugin), the results are displayed on a page with .../search/... added in its url:

`http://my-domain.com/search/...`

so also all the images lose their original path and are not displayed because of this 'search' string inserted, for example:

`http://my-domain.com/search/bl-content/uploads/pages/IMG_01.jpg`

instead of

`http://my-domain.com/bl-content/uploads/pages/IMG_01.jpg`

How to avoid this behaviour?
Thank you.

### Bludit version
3.13.1

### PHP version
7.2.30

**Comment by dignajar** [comment]
You need to use absolute URLs for your images.
