### ISSUE TITLE
[Suggestion] Frontend user core feature

### ISSUE THREAD

**Issue by grz8** [bludit/bludit#1304]
Hello

Today we can found **Comments** and **Reactions** plugins to allow frontend user to interact with our website.

Each plugin use his own user logic and it can be very difficult to connect them. I believe it's a good idea to purpose a frontend user management by the Bludit core and offer to the developers to attach their plugins to this core feature.

I see these important parts for the frontend user:
- Subscription of a new account
- Deletion
- Update password
- Email validation (optional)
- Edit profile (nickname, avatar, group, email)

And these things for the admin:
- Create a frontend user account (also via the API)
- Account validation (by user email validation, by admin, no validation)
- Deletion
- Enable/disable user (ban/unban)
- Edit password
- Edit profile (group, email)
- Manage groups

Then when we have this core feature, we can attach plugins (comments, reactions, bookmarks list, and new plugins).

Such a feature is complex and critical, but I believe it can help Bludit to gain audience near the web developers.

And, I really need such a feature.

I'm able to participate in this development if it can be approved.

What do you think about that?

**Comment by dignajar** [comment]
Hi,
I will have in mind for Bludit v4.
For the moment I'm refactoring the core and the admin panel, after that I will add new features / plugins.
Also, my idea is to keep it simple, I don't want to add more and more things.

Thank you for the feedback

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
