### ISSUE TITLE
[request] split page title from menu title for static pages

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#1306]
As title says, this feature is like a basic function of all SEO friendly CMSes and I still wonder it wasn't already implemented. Although it is achievable since bludit got custom fields, unfortunately isn't template friendly as it demands from website owner to define custom fields in bludit's options.

I wish this would be implemented in B.v4, as an additional field in page's general options window. 
If left empty it would get the value of page title.

**Comment by dignajar** [comment]
You mean to have 2 fields for titles?

**Comment by Joduai** [comment]
This is an example from getsimple cms.
There's a main field for page title which is automatically used as URI just like in bludit (page options are also hidden by default)
And an additional field for menu title, which is optional.

Now when I think about it, it would be also great to let the user decide if a static page appears in menu or not. An example need of this option is a custom 404 page that may be defined in bludit opions. Once user creates such static 404 page it is shown in page's menu by default. I needed to create an exception while generating menu in template to hide 404 page along with some other pages I didn't want to be shown.
I remember that some users asked how to hide such 404 from menu on B forums.
 
![Screenshot_2021-02-05 GetSimple CMS](https://user-images.githubusercontent.com/4009106/107043117-d59bb580-67c2-11eb-95c1-89aebefe22ed.png)

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
