### ISSUE TITLE
[request] Allow HTML entities in page titles

### ISSUE THREAD

**Issue by johannesh19** [bludit/bludit#1310]
I think it would be useful if one could use HTML entities or even HTML tags in the page title. This way, one could write technical terms, mathematical or chemical formulas, but also use control characters like non-breaking hyphens or non-breaking spaces. Also, effects like partially crossed-out headlines (in case of e. g. later corrections) would be possible.

I set up a website using technical terms in German (a language known for producing long words), and I was absolutely not satisfied with the word wrap used by my browser. Words like "Verbrennungsmo-tor" and "Einspritzpum-pe" were separated at non-optimal positions. Using soft hyphens (`&shy;`) would make it possible to declare possible breaking points.

_Using Bludit 3.13.1 Build 20200728 right now_

**Comment by dignajar** [comment]
You can do it from the theme.

- Create a page with the title `<b>Bold</b> is my title`
- Edit your theme and add the function `htmlDecode` where the title is printed.
```
echo Sanitize::htmlDecode($page->title());
```
