### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by stani63** [bludit/bludit#1312]
### When the Favicon image changes, it is new at the top of the browser but too new at the bottom of the page footer - which is a pity..

The original Bludit Favicon is nice and should stay in the footer.

### Steps to reproduce the problem
Complete here.

### Bludit version
Complete here.

### PHP version
If you do not know delete this line.

### PHP logs
If you do not know delete this line.

The default settings of the PHP Error Log file varies from OS to OS. The location of the error log file itself can be set manually in the php.ini file. On a Windows server, in IIS, it may be something like `error_log = C:\log_files\php_errors.log` in Linux it may be a value of `/var/log/php_errors.log`.

**Comment by dignajar** [comment]
Let me know which theme, because is more of an issue with the theme.
