### ISSUE TITLE
alt-Tag und title-Tag für Hauptbilder – alt tag and title tag for main images

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#1317]
Bludit 3.13.1 | Massively-2.1

Da es mich gestört hat, dass weder »alt-Tag« noch »title-Tag« bei den Hauptbildern zur Verfügung stehen, bin ich schließlich auf die Idee gekommen, mit Hilfe von benutzerdefinierten Feldern zu arbeiten. Wie das geht, kann man ja in der Bludit-Dokumentation –> Inhalt –> Benutzerdefinierte Felder nachlesen. Ich habe also zwei Felder für »alt-Tag« und »title-Tag« eingerichtet und die Zeile 12 der page.php des Themes entsprechend modifiziert. Sie sieht dann so aus:
`<div class="image main"><img src="<?php echo $page->coverImage() ?>" alt="<?php echo $page->custom('alt-Tag'); ?>" title="<?php echo $page->custom('title-Tag'); ?>" /></div>`
Damit ist die Seite unserer NachbarschaftStiftung: https://nachbarschaft-stiftung.de …

Since it bothered me that neither “alt tag” nor “title tag” were available for the main images, I finally came up with the idea of working with the help of user-defined fields. You can read how to do this in the Bludit documentation -> Content -> User-defined fields. So I set up two fields for “alt tag” and “title tag” and modified line 12 of the theme's page.php accordingly. It then looks like this: `<div class="image main"><img src="<?php echo $page->coverImage() ?>" alt="<?php echo $page->custom('alt-Tag'); ?>" title="<?php echo $page->custom('title-Tag'); ?>" /></div>`
This makes the page of our Neighbourhood Foundation: https://nachbarschaft-stiftung.de ...

Knut

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
