### ISSUE TITLE
$page->contentBreak() causing W3C validation error

### ISSUE THREAD

**Issue by geraldribisch** [bludit/bludit#1321]
### echo $page->contentBreak() causing W3C validation error
I want to set up a blog using Bludit and created a theme for it. In terms of review I did a check via [Nu Html Checker](https://validator.w3.org/) which promted following error: **No p element in scope but a p end tag seen.**

After checking the source it turned out that the error is caused by `<?php echo $page->contentBreak() ?>`

I use TinyMCE as HTML Editor and as you insert a page break it looks like the following: `<p><!-- pagebreak --></p>`. So as `$page->contentBreak()` is printed a `<p>` is opened but not closed again.

### Workarounds

To fix the issue I did a workaround on my theme. Instead of `<?php echo $page->contentBreak() ?>` I removed the redundant `<p>` by using `<?php echo substr($page->contentBreak(), 0, -3) ?>`.

Another workaround could be using `<?php echo $page->contentBreak()."</p>" ?>` to fix the validaiton error.

### Steps to reproduce the problem

- Create a post using TinyMCE
- Set a Page break to split content
- Look at the response of `$page->contentBreak()` or try to validate your home- or a category-page using [Nu Html Checker](https://validator.w3.org/)

### Bludit version
3.13.1 with TinyMCE as HTML Editor

**Comment by geraldribisch** [comment]
Hi there,

as it was pretty late yesterday I checked again looking for a proper solution.
Solution is pretty simple as there is a constant defined for the page break.

To fix the problem I adapted the constant in **bl-kernel/boot/variables.php** to

`define('PAGE_BREAK', '<p><!-- pagebreak --></p>');`

Sorry for the inconveniences.
Cheers, Gerald

**Comment by dignajar** [comment]
Hi, thanks for reporting the issue.
I would like to know if it possible to insert the `<!-- pagebreak -->` without the `<p>` from TinyMCE, because the PAGE_BREAK variable will change for each editor.

**Comment by geraldribisch** [comment]
Thank's for bringing it on the roadmap.  Otherwise you could do some kind of check in the function `contentBreak()` to remove the unnecessary `<p>`.

I didn't check the behaivour using other editors tho'.

**Comment by dignajar** [comment]
@geraldribisch there is a easy fix from TinyMCE, you can edit the plugin and add this line.
https://github.com/bludit/bludit/commit/ad0c024362c6b0e98f99a91ea617a30bf4e9f15f
