### ISSUE TITLE
Force cookie lifetime to stay logged in

### ISSUE THREAD

**Issue by Andrewsuares** [bludit/bludit#1324]
Hello,

I keep getting logged out after the browser is closed. I've set the cookie lifetime to 180 days. Is it possible to force the cookie lifetime so that I do not get logged out at all?

Using the latest version. PHP version is 7.3

Thanks!

**Comment by lightmat** [comment]
Have you checked your browser settings for incognito and cookies?
Have you looked in the "web developer tool" under the tab "storrage" and checked when your cookie expires in your browser?

**Comment by Andrewsuares** [comment]
Works great. My fault, I had cleared the cache.
