### ISSUE TITLE
Wordpress Importer Plugin Not Working

### ISSUE THREAD

**Issue by CodeCatCool** [bludit/bludit#1325]
### Describe your problem
The wordpress importer plugin doesn't work with PHP 8.0

### Steps to reproduce the problem
After updating to latest version, and then changing to PHP 8.0 the wordpress importer plugin stopped working.
When I change back to PHP 4.0 the wordpress importer plugin works again.

### Bludit version
3.13.1

### PHP version
8.0

### PHP logs

The default settings of the PHP Error Log file varies from OS to OS. The location of the error log file itself can be set manually in the php.ini file. On a Windows server, in IIS, it may be something like `error_log = C:\log_files\php_errors.log` in Linux it may be a value of `/var/log/php_errors.log`.

**Comment by dignajar** [comment]
Hi, you need to contact the developer of the plugin or ask in the Forum.
