### ISSUE TITLE
cross site script (xss) 

### ISSUE THREAD

**Issue by tamilanmkv** [bludit/bludit#1327]
### Describe your problem
I found a cross-site scripting attack on the login page http://localhost:800/admin/login
cross-site scripting is a vulnerability that allows an attacker to send malicious code(usually in javascript form)
to another user
Because a browser cannot know if the script should be trusted or not,
it will execute the script in user context allowing the attacker to access any cookies or sessions tokens retained
by the browser.

### Steps to reproduce the problem
1. open login page http://localhost:800/admin/login;
2. enter the username place ``admin"><img src=x onerror=alert(1)>`` and enter password 
3. trigger the malicious javascript code 

### Bludit version
bludit-3-13-1

### PHP version
PHP 7.4.15

**Comment by s22-tech** [comment]
I can confirm the security problem on my install.  Thanks for the heads up!

A quick and dirty fix is to add:
`$username = strip_tags($_POST['username']);` 
to
`/bl-kernel/admin/views/login.php`

and then use `$username` in place of `$_POST['username']`.

**Comment by tamilanmkv** [comment]
can you assign a new CVE for this report?

**Comment by dignajar** [comment]
Fixed for Bludit v4.

https://github.com/bludit/bludit/blob/v4.0/bl-kernel/admin/views/login.php#L42

**Comment by tamilanmkv** [comment]
can you assign a new CVE for this report?

**Comment by a6smile** [comment]
> I can confirm the security problem on my install. Thanks for the heads up!
> 
> A quick and dirty fix is to add:
> `$username = strip_tags($_POST['username']);`
> to
> `/bl-kernel/admin/views/login.php`
> 
> and then use `$username` in place of `$_POST['username']`.

It can be made simple by change $_POST['username'] to strip_tags($_POST['username'])

**Comment by tamilanmkv** [comment]
can you assign cve for this issue for my career
