### ISSUE TITLE
Bludit v4.0.0 Alpha 1: Creating new users not possible

### ISSUE THREAD

**Issue by Torsten-K** [bludit/bludit#1328]
### Describe your problem
Creating new users is not possible, there is an error message appearing: _Hello, I'm a Bludit alert!_

### Steps to reproduce the problem
As administrator, try to create a new user.

### Bludit version
v4.0.0 Alpha 1

### PHP version
7.4

**Comment by Torsten-K** [comment]
Same with categories, new content etc. File permissions are 644, folder permissions 755 on Apache HTTP server.

**Comment by dignajar** [comment]
What browser do you use ?

**Comment by Torsten-K** [comment]
> What browser do you use ?

Vivaldi 3.5.2115.81 (Stable channel) (64-Bit)
Firefox 89.0 (64-Bit)
Midori Webbrowser 7.0
Opera 68.0.3618.63
All under GNU/Linux (Xubuntu 20.10).

I will try a fresh installation, maybe something went wrong.

**Comment by dignajar** [comment]
can you open the browser inspector and check the console log ? because I use a lot of javascript and maybe there is some issue there.

Also in Network tab, should appear the request to the API

**Comment by Torsten-K** [comment]
Console:

Failed to load resource: the server responded with a status of 404 ()
/api/categories:1 Failed to load resource: the server responded with a status of 404 ()
api.js?version=4.0.0:166 SyntaxError: Unexpected token < in JSON at position 0
functions.js?version=4.0.0:44 An error occurred while trying to create the category.

Network:

Error: Promised response from onMessage listener went out of scope

**Comment by Torsten-K** [comment]
Same behaviour in Alpha 2. I can’ŧ change or create anything. Tried on another webhoster’s webspace, but it’s quite the same.

**Comment by Torsten-K** [comment]
No, still the same with Alpha 3. I tested on one paid webhosting and one free. I never had this issue with Bludit 3 or earlier.
![bludit-alert](https://user-images.githubusercontent.com/806012/121419996-e6288c00-c96c-11eb-95f8-070f5aa46fd2.png)

**Comment by dignajar** [comment]
What is the free hosting, I would like to test it there

**Comment by Torsten-K** [comment]
How can I send you a private message with the details?

**Comment by dignajar** [comment]
You can contact me through the Forum or the Chat, you share the free hosting URL I will create an account for myself.

https://gitter.im/bludit/support

**Comment by dignajar** [comment]
Bludit v4.0.0 alpha 5 released.
