### ISSUE TITLE
Bludit 4.0 and PHP 8

### ISSUE THREAD

**Issue by s22-tech** [bludit/bludit#1330]
### Describe your problem
There are a few errors running Bludit 4 under PHP 8

`PHP Deprecated:  Required parameter $filename follows optional parameter $path in /bl-kernel/helpers/filesystem.class.php on line 220`

`PHP Deprecated:  uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /bl-kernel/boot/rules/60.plugins.php on line 129`

`PHP Deprecated:  uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /bl-kernel/boot/rules/60.plugins.php on line 136`

**Comment by luonghieu184** [comment]
<?php //Theme::plugins('siteBodyEnd'); ?> not working on PHP 8

**Comment by luonghieu184** [comment]
//Theme::plugins('siteBodyEnd'); Not working PHP 8

**Comment by dignajar** [comment]
@luonghieu184 
That function was replaced by:
```
Theme::plugin('xxxxx') => execPluginsByHook('xxxxx')
```
