### ISSUE TITLE
https not default

### ISSUE THREAD

**Issue by modexkit** [bludit/bludit#1334]
### Describe your problem
https is disabled on the server by default
after installing the cms, there is a problem with displaying the template
I have to go to the settings and disable httpS
I think the best option is to make http initially

### Bludit version
Bludit Version | 4.0.0
Bludit Build Number | 20210523

**Comment by dignajar** [comment]
Bludit detects when the webserver is configured for HTTP or HTTPS. Here is the logic.
https://github.com/bludit/bludit/blob/v4.0/install.php#L82-L90

Maybe some conditional hit the configuration of your webserver ?

**Comment by dignajar** [comment]
I found the issue. Fixed!
