### ISSUE TITLE
Hide static pages from menu

### ISSUE THREAD

**Issue by bnetz** [bludit/bludit#1341]
Often you create static pages you don't want to be shown in the static menu. It would be nice if there was e.g. a checkbox in the settings of each static page where you could choose to hide them in the menu.

Right now you have to do it in the file that generates the menu, e.g. /themes/theme-name/php/navbar.php or …/header.php, where you can add something like
```
<?php foreach ($staticContent as $staticPage): ?>
  <?php if($staticPage->slug() != 'privacy' && $staticPage->slug() != '404'): ?>
    <li><a href="<?php echo $staticPage->permalink();  ?>"><?php echo $staticPage->title(); ?></a></li>
  <?php endif; ?>
<?php endforeach ?>
```

**Comment by BlakesHeaven** [comment]
The same can be true for any page type so I'd suggest this should apply to all pages. You particularly need to hide normal pages if doing parent/child configurations and need to schedule it for the future - you can't do both, so I do the parent/child stuff and hide the pages with an option for only Admin to see them
For now, as you say it's only achieved by a special menu  plugin or if build into the theme's menu. 
For now I use my 'auto archiving menu' plugin which uses a category to hide pages.

**Comment by dignajar** [comment]
For Bludit v4.0 there is a new page type called "unlisted" that does not show anywhere, only accessible if you have the link.
I hope fits your needs.

**Comment by fabianosantosnet** [comment]
Hi guys. I implement this feature in the plugin FS PAGE MENU.
