### ISSUE TITLE
How to set custom field values when creating new page via API ?

### ISSUE THREAD

**Issue by Zebraslive** [bludit/bludit#1342]
Is it possible to pass custom field values when creating a new page via api ?

**Comment by dignajar** [comment]
I answered in the forum https://forum.bludit.org/viewtopic.php?f=6&t=2152

**Comment by Zebraslive** [comment]
> I answered in the forum https://forum.bludit.org/viewtopic.php?f=6&t=2152

I replied, I'm unable to send the custom fields value when creating a new page. Please tell me, what is the correct format to use when sending custom field data along with the new page data?
Everything is being passed except the custom data and I've been stuck on this problem for a day now.
```
$fields = array(
            'token' => "ahblah",
            'authentication' => "blahblah",
            'title' => $szz['title'],
            'content' => $szz['description'],
            'slug' => $szz['slug'],
            'coverImage' => $mainimg,
            'tags' => $tagsz,
            'custom' => array (
      'boxart' => $szz['boxart'],
      'horizontalHeaderImage' => $szz['horizontalHeaderImage']
    )
        );
$fields_string = http_build_query($fields);
```
