### ISSUE TITLE
Bludit 4 Alpha 5: HTTP error 500

### ISSUE THREAD

**Issue by Torsten-K** [bludit/bludit#1345]
### Describe your problem
Installing Alpha 5 does not work, I receive a white page with error 500. Alpha 4 runs flawlessly. 

### Steps to reproduce the problem
I copied Bludit 4 Alpha 5 onto the Apache HTTP server. After the installation process, the white page with the error message appeared. I checked the .htaccess file, but I can’t find an error in it. Deactivating it does not help. 

### Bludit version
4.0.0. Alpha 5 
(Alpha 4 used to work)

### PHP version
7.4

### PHP logs
I can’t find any.

**Comment by dignajar** [comment]
Hi @Torsten-K  yes the issue is with PHP v7.x

I will release a new version with the fixes.

**Comment by Torsten-K** [comment]
I can confirm that Bludit 4.0.0. Alpha 5 works under PHP 8.0. Nevertheless, a fix for PHP 7.4 would me nice. Thank you in advance for your efforts.

**Comment by dignajar** [comment]
Please test Alpha 6.

**Comment by Torsten-K** [comment]
Alpha 6 works with PHP 7.4 and also 8.0. Thanks for your effort!
