### ISSUE TITLE
Bludit 4.0.0 Alpha 6: Content not saved

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1352]
If you create a new site, enter a title and some content, and choose then for example the option "Type" and select a type the button "Save" changes to "Saved", but the content is not saved (a page with "Empty title" and no content is created).

This is the case with all options.

**Comment by clickwork-git** [comment]
This also is the case with the other options.

**Comment by dignajar** [comment]
Fixed in beta 3.
