### ISSUE TITLE
Bludit 4.0.0: URL filter Blog works only with /blog/

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1370]
The URL filter Blog only works with /blog/.

**Comment by clickwork-git** [comment]
Sorry...

**Comment by dignajar** [comment]
Fixed

**Comment by dignajar** [comment]
Fixed, please check the new release v4.0.0 rc3.
Feel free to open the ticket if the issue is still there, if a new issue please open a new ticket.
