### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by NyamiDev** [bludit/bludit#1373]
On this page:
https://github.com/bludit/documentation-english/blob/master/pages/bludit-pro/domain-migrator/index.md

In this text blob:
"After the migration, the Backups and the checkpoints in TimemachineX won't work anymor. It is recommended that you deactivate and activate the plugins again to start from scratch."

Spelling of 'anymor' should be 'anymore'.

Thanks!

**Comment by dignajar** [comment]
Fixed. thanks
