### ISSUE TITLE
[4.0.0-rc-1] Cover image can not be deleted

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1377]
The cover image cannot be deleted only be replaced.

**Comment by dignajar** [comment]
I included if you do double-click over the cover image is deleted, I need to add some information about it or some tooltip.

**Comment by dignajar** [comment]
If you set a cover-image, and then put the mouse over the cover-image doesn't appear the tooltip?

![Screenshot 2022-02-22 at 18 30 43](https://user-images.githubusercontent.com/507352/155186318-7ee5af20-c78c-4ec0-8c03-06de4774c1c9.png)

**Comment by clickwork-git** [comment]
No. I try to find out why.

**Comment by clickwork-git** [comment]
Sorry, my bad! I tested the wrong version.
