### ISSUE TITLE
URL of the created page (v4 beta 2)

### ISSUE THREAD

**Issue by Torsten-K** [bludit/bludit#1381]
### Describe your problem
When you create a page, the URL of it should be generated by the page’s title. At the moment there is a default nonsense text like _no-content-1_ or similar. Every time you have to click onto the blue line reading _Aus dem Titel der Seite generieren_ (probably _Generate from the title of the page_ in English). In older Bludit version the URL was generated automatically from the title.

Additionally, it would be fine if German umlauts would be changed automatically, like ü to ue etc., but that is of course not so important for the time being.

### Steps to reproduce the problem
Create page, then click on _URL ändern_ (I presume it is _Change URL_ or so in English), and then you’ll see the URL is not generated from the title of the page.

### Bludit version
4.0.0 beta 2

### PHP version
7.4

### PHP logs
—

**Comment by dignajar** [comment]
Implemented in v4.0 rc2, the url is generated from title
