### ISSUE TITLE
[4.0.0-rc-1] Preview does not work

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1383]
The preview of the content does not work.

**Comment by kuzmandi** [comment]
**This problem still exists in 4.0.0-rc-2.**

When I create new pages, I can't preview them.

- If I click _View_ in the overview, Bludit opens the link as if it was already published (`/draft-page/` i.e.)
- If I press the _Preview_ button in the editor view, nothing happens. (The button also does not work if the page has already been published.)
