### ISSUE TITLE
[4.0.0-rc-1] Files cannot be deleted

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1384]
The filemanager does not allow to delete files.

**Comment by clickwork-git** [comment]
The problem affects images and other files.

**Comment by clickwork-git** [comment]
It seems that the function is missing.

**Comment by dignajar** [comment]
Implemented!.

**Comment by clickwork-git** [comment]
Does not work yet.

**Comment by clickwork-git** [comment]
Sorry, again my bad. Old version. Everything works.
