### ISSUE TITLE
Mobile menus don't work in included themes

### ISSUE THREAD

**Issue by susannemsv** [bludit/bludit#1386]
### Describe your problem
Mobile menus don't work in any included themes. Nothing happens when I click or tap the hamburger menu. I've tried both in the laptop (using MAMP) and on my phone with another install. 

### Steps to reproduce the problem
Complete here.

### Bludit version
4.0.0 beta 2

### PHP version
7.4

The default settings of the PHP Error Log file varies from OS to OS. The location of the error log file itself can be set manually in the php.ini file. On a Windows server, in IIS, it may be something like `error_log = C:\log_files\php_errors.log` in Linux it may be a value of `/var/log/php_errors.log`.

**Comment by dignajar** [comment]
Fixed for BlogX, also I did some improvements to the theme.
I will continue with the Alternative and check the Popeye theme.

**Comment by susannemsv** [comment]
Thanks! Where can I download the new version?

**Comment by dignajar** [comment]
I will prepare a new release this week.

Meanwhile, you can download it from Github https://github.com/bludit/bludit/archive/refs/heads/v4.0.zip
