### ISSUE TITLE
Bludit 4.0.0 Beta: Problem with value of the position

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1397]
The value of the position can be set to -1, -2 etc. This does not work.

**Comment by clickwork-git** [comment]
Fix: Add _min="0_" to _input_.

https://github.com/bludit/bludit/blob/320f9a2f0c26879d5b24f268c24fcfdfde8891b4/bl-kernel/admin/views/editor.php#L457

**Comment by dignajar** [comment]
Fixed, thanks
