### ISSUE TITLE
Unable to Deactivate Plugin - Getting Error "Missing API Token"

### ISSUE THREAD

**Issue by cinetube** [bludit/bludit#1404]
<img width="772" alt="Untitled" src="https://user-images.githubusercontent.com/23441775/148652550-0201ecf3-32c4-4fb6-8eda-27312e831d5f.png">

Unable to Deactivate Plugin - Getting Error "Missing API Token"

How to resolve this issue?

**Comment by clickwork-git** [comment]
Does this happen with all plugins? Which version of PHP do you use?

**Comment by cinetube** [comment]
> Does this happen with all plugins? Which version of PHP do you use?

It is happening to all my plugins. I am using PHP 8.

**Comment by dignajar** [comment]
Which version of Bludit ?

Can you try logout and login ?
