### ISSUE TITLE
Bludit 4.0.0 Beta3: Inserting Images with EasyMDE not working

### ISSUE THREAD

**Issue by LetOpDrempels** [bludit/bludit#1405]
### Describe your problem

Trying to insert images (files?) from the file manager is not working for me when using EasyMDE as the editor. I have only tried with jpg's, no other file types. With TinyMCE it works fine. Tried with Firefox and Chrome.

### Steps to reproduce the problem
Deactivate TinyMCE. activate EasyMDE, add content, try to insert image from file/image browser

### Bludit version
Bludit 4.0.0 Beta3

### PHP version
7.4

**Comment by dignajar** [comment]
Fixed, thanks.

You can replace the file for this new one, https://github.com/bludit/bludit/commit/5986c1d220592711e47e13534d6fd0627f62a5e2#diff-3ecc2eabbca6b0b90ccd2a166d49e0f82a1214064b0a2cf2acf2f217e5b66e31
