### ISSUE TITLE
[4.0.0-rc-1] Backup plugin

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1418]
The plugin Backup is missing.

**Comment by dignajar** [comment]
I was thinking to move the plugin outside the core package.

**Comment by clickwork-git** [comment]
It would be nice if it would be still part of the package. But you decide.

**Comment by BlakesHeaven** [comment]
I agree, ditto @clickwork-git

**Comment by dignajar** [comment]
Less plugins inside the core package, less vulnerabilities pointing to Bludit.

Also keeping plugins outside the core package allow us to release often new versions of the plugin with bug fixes or vulnerabilities fixes.
