### ISSUE TITLE
[4.0.0-rc-2] Can't create files. "Access denied or invalid endpoint"

### ISSUE THREAD

**Issue by EzequielBruni** [bludit/bludit#1419]
### Describe your problem
Every time I go to add content or change a global setting, I get the error message in the title. I am reasonably sure that permissions are not the issue, as the ownership of the directory is all set up properly, as is PHP-FPM, and I extracted the file using the web server user account.

Also, activating plugins seems to work just fine.

I mean... do the permissions look right?

![bludit-permissions](https://user-images.githubusercontent.com/1215780/161355842-d9788994-b497-475f-abe3-fe24f76d9274.png)

Oh, and here's my Nginx .conf file:

```
server {
    listen 80;
    listen [::]:80;

    # virtual server name i.e. domain name #
    server_name bludit.server.test;

    # document root #
    root        /home/www/html; # << This root directory works fine because SELinux isn't installed in the LXD containers.

    # log files
    access_log  /var/log/nginx/www_access.log;
    error_log   /var/log/nginx/www_error.log;

    index       index.php index.html;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        /etc/nginx/fastcgi_params;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }

    location ^~ /bl-content/databases/ { deny all; }
    location ^~ /bl-content/workspaces/ { deny all; }
    location ^~ /bl-content/pages/ { deny all; }
    location ^~ /bl-kernel/*.php { deny all; }
}
```

### Steps to reproduce the problem
1. Go to create new page or change global setting.
2. See error.
3. Sigh.

### Bludit version
4.0.0 Release Candidate 2

### Hosting or Webserver name
My own personal test server. Rocky Linux host, with Nginx, PHP-FPM and Bludit running in an Alpine Linux LXD container behind an Nginx reverse proxy.

### PHP version
PHP 8

Installed PHP modules include:

```
php8-cli
php8-common
php8-curl
php8-dom
php8-fpm
php8-gd
php8-gd
php8-intl
php8-json
php8-mbstring
php8-mbstring
php8-mysql
php8-opcache
php8-pgsql
php8-session
php8-sqlite3
php8-xml
php8-zip
```

### PHP logs

Basically only say this:
```
[01-Apr-2022 18:23:52] NOTICE: configuration file /etc/php8/php-fpm.conf test is successful

[01-Apr-2022 18:23:52] NOTICE: fpm is running, pid 4540
[01-Apr-2022 18:23:52] NOTICE: ready to handle connections
```

Setting the log level to `debug` honestly didn't help. 

### Nginx Error Logs (Sample)

```
2022/04/01 17:52:14 [error] 2633#2633: *332 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: bludit.server.test, request: "GET / HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "bludit.server.test"
2022/04/01 17:54:32 [error] 2633#2633: *359 FastCGI sent in stderr: "PHP message: [INFO] [4.0.0] [/api/plugins/pluginSearch] activatePlugin | Plugin installed" while reading response header from upstream, client: 127.0.0.1, server: bludit.server.test, request: "POST /api/plugins/pluginSearch HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "bludit.server.test", referrer: "http://bludit.server.test/admin/plugins"
2022/04/01 17:54:35 [error] 2633#2633: *363 FastCGI sent in stderr: "PHP message: [INFO] [4.0.0] [/api/plugins/pluginSearch] configurePlugin | Plugin configured: pluginSearch" while reading response header from upstream, client: 127.0.0.1, server: bludit.server.test, request: "PUT /api/plugins/pluginSearch HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "bludit.server.test", referrer: "http://bludit.server.test/admin/plugins-settings/pluginSearch"
2022/04/01 17:54:51 [error] 2633#2633: *371 FastCGI sent in stderr: "PHP message: [INFO] [4.0.0] [/api/plugins/pluginSearch] configurePlugin | Plugin configured: pluginSearch" while reading response header from upstream, client: 127.0.0.1, server: bludit.server.test, request: "PUT /api/plugins/pluginSearch HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "bludit.server.test", referrer: "http://bludit.server.test/admin/plugins-settings/pluginSearch"
```

### Nginx Access Logs (Sample)

```
127.0.0.1 - - [01/Apr/2022:18:12:36 -0600] "GET /admin/content HTTP/1.0" 200 15318 "http://bludit.server.test/admin/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36"
127.0.0.1 - - [01/Apr/2022:18:12:37 -0600] "GET /admin/editor HTTP/1.0" 200 51090 "http://bludit.server.test/admin/content" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36"
127.0.0.1 - - [01/Apr/2022:18:12:37 -0600] "GET /bl-kernel/img/default.svg HTTP/1.0" 304 0 "http://bludit.server.test/admin/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36"
127.0.0.1 - - [01/Apr/2022:18:12:37 -0600] "POST /api/pages HTTP/1.0" 401 48 "http://bludit.server.test/admin/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36"
```

**Comment by EzequielBruni** [comment]
Oh, and I can change themes and theme settings as well.

**Comment by kuzmandi** [comment]
I have the same problem.
I have also already checked the permissions and set them cleanly again.
Is there a debug mode in Bludit that could output usable error messages?

**Comment by kuzmandi** [comment]
I don't understand what the cause was, it seems to work now.

**What I did:**
I duplicated the folder with Cyberduck via FTP, deleted the original folder and duplicated the copy again to the original name. Now it works, although I can't tell any difference.

I want to suggest that Bludit can check the rights of its installation, so that anyone can solve such a problem without trying by chance.

@EzequielBruni Maybe you could try this and tell if it works?

**Comment by EzequielBruni** [comment]
@kuzmandi I can't speak to your experiences but... I'm closing out this issue as it appears to have been some weird, one-off crap. I woke up today, gave it another try... and it just worked. I hadn't updated any software, made any file or permissions changes since I tried it last. Nothing. It just decided to work.

I'm starting to wonder if my particular setup for Alpine Linux LXD containers, Nginx, and PHP-FPM might just be weird and messed up somehow... though I couldn't possibly tell you what's going on. I've updated my post on the forum as well.

**Comment by kuzmandi** [comment]
Okay, now this is a little bit frustrating, because I'm still having this problem.

**Comment by EzequielBruni** [comment]
@kuzmandi 

Oh, I updated the forum post, but not here. Ummm, I created an extra Alpine Linux container to test with, then I installed EVERY. SINGLE. PHP. MODULE. that happened to be in the repos. I downloaded the zip, extracted it, and it all worked flawlessly. Typemill too.

So I don't kow which PHP module is missing to make everyhting work right, but one of them is. This is uh... complicated, because downloading 4-500 MB of dependencies for every blog does seem like a bit much. Even so, give something like this a try just to see if your environment is having the same problem as mine.

**Comment by kuzmandi** [comment]
I have installed Bludit on the web space of an Internet service provider. It would be helpful if I could see in a log what exactly the problem is to report it to the support (or to open an issue here). All I can say is, that other PHP code (Wordpress, DokuWiki, Bludit 3.x) worked without problems.
