### ISSUE TITLE
[4.0.0-rc-2] Right sidebar/order of "More options"

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1423]
The right sidebar and especially the order of "More options" on the editing page are at the moment not very userfriendly.

I would prefer to set "Category" and "Tags" below "More Options".

Concerning "More options" I suggest the following order:

- Change URL
- Images & Files (not Files & Images)
- Type
- Parent page
- Position
- Description
- Publish date
- SEO features

**Comment by dignajar** [comment]
I change the order of the options for "More options", but the tags and category I feel are more important for the beginners.

**Comment by clickwork-git** [comment]
> [...] but the tags and category I feel are more important for the beginners.

You are right.
