### ISSUE TITLE
[4.0.0-rc-2] Quotes in page URL

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1428]
Quotes in the title of a content are converted to "quot" in the page URL.

_Richard Wagner and "Parsifal"_ for example becomes _richard-wagner-and-quot-parsifal-quot_.

**Comment by emanueleg** [comment]
I do not have (yet) a solution, but I've an explaination for this.

When you generate the title, [getFriendlyURL](https://github.com/bludit/bludit/blob/f6899abfeb983eefbda86c1587ba95df334cc87b/bl-plugins/api/plugin.php#L303) is called. At this point, the input text has already been [cleaned](https://github.com/bludit/bludit/blob/f6899abfeb983eefbda86c1587ba95df334cc87b/bl-plugins/api/plugin.php#L352) with the [sanitize function](https://github.com/bludit/bludit/blob/f6899abfeb983eefbda86c1587ba95df334cc87b/bl-kernel/helpers/sanitize.class.php#L17), which uses htmlspecialchars and encodes ``"`` as ``&quot;``. Then, the text is passed to [cleanUrl](https://github.com/bludit/bludit/blob/f6899abfeb983eefbda86c1587ba95df334cc87b/bl-kernel/helpers/text.class.php#L155), which calls [removeSpecialCharacters](https://github.com/bludit/bludit/blob/f6899abfeb983eefbda86c1587ba95df334cc87b/bl-kernel/helpers/text.class.php#L129). This latter function remove ``&`` and ``;``, leaving only ``quot``.

**Comment by dignajar** [comment]
I added a function to remove HTML entities.

Thanks for the path @emanueleg  sometimes is hard for me to check what I did 4 years ago :D

**Comment by dignajar** [comment]
Fixed, please check the new release v4.0.0 rc3.
Feel free to open the ticket if the issue is still there, if a new issue please open a new ticket.
