### ISSUE TITLE
[4.0.0-rc-2] Deactivaed user cannot be reactivated

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1429]
Deactivaed user cannot be reactivated.

See also https://github.com/bludit/bludit/issues/1407.

**Comment by emanueleg** [comment]
To re-activate a disabled user you need to change the password. 
In 4.0.0-rc-2 it works, although you have to force a refresh of the page after changing the password.

**Comment by clickwork-git** [comment]
Now it works... It was an installation who replaced an older one (which causes some bugs).

**Comment by clickwork-git** [comment]
It seems that I have overseen that the page has to be refreshed. Thank you!
