### ISSUE TITLE
[4.0.0-rc-2] Profile update requires password input

### ISSUE THREAD

**Issue by kuzmandi** [bludit/bludit#1430]
If I want to change my profile (nickname, bio, ...) I have to change (or enter the same again twice) my password too.

Error message: _"The password and the confirmation of the password do not match"_ - yes of course, I did not enter it at all, because the field was not visible... And when I enter it, I'm asked _if I'm sure I really want to change the password_...

**Comment by kuzmandi** [comment]
I have the impression that this phenomenon has to do with leftover data from previous Bludit installations or other user data stored in the used browser. The behavior only occurred until I deleted the stored data in the browser (Google Chrome) for the **automatic filling of forms** for this domain. (This apparently automatically filled in the first password field in the Security tab without me noticing.)

Perhaps renaming the form fields for password entry will help here?

In any case, I had a lot of nuts to crack in the last few days, which seems not to occur with a usual (one-time) installation of Bludit, but cause problems if you want to test it and therefore make multiple installations on the same server/folder/(sub)domain. All of these nuts seemingly lead to the same problem: Old (but "valid") session cookies and stored passwords for automated fill-in. Maybe it's enough to include that in the troubleshooting tips, but i recommend to take a closer look to this.

This may have something to do with these issues:
- https://github.com/bludit/bludit/issue/1427
- https://github.com/bludit/bludit/pull/1427

**Comment by dignajar** [comment]
Good catch about the automatically filled.
I will add this https://www.w3docs.com/snippets/html/how-to-disable-browser-autocomplete-and-autofill-on-html-form-and-input-fields.html

**Comment by dignajar** [comment]
Fixed for Bludit v4 rc3

**Comment by dignajar** [comment]
Fixed, please check the new release v4.0.0 rc3.
Feel free to open the ticket if the issue is still there, if a new issue please open a new ticket.
