### ISSUE TITLE
[4.0.0-rc-3] Parent page gets lost

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1440]
After an edit of the content the parent page gets lost.

**Comment by emanueleg** [comment]
Actually I think it is not lost but it is not shown in the modal window.
I've written a small fix (just a few lines): emanueleg/bludit@fb4b65a
Let me know if you can test it before I submit a PR.
Thanks!

**Comment by clickwork-git** [comment]
Thank you! No it works fine.

**Comment by dignajar** [comment]
Thanks for the PR @emanueleg it's merged
