### ISSUE TITLE
[3.13.1] Static pages loose their static setting (type) when changed to draft

### ISSUE THREAD

**Issue by apps4research** [bludit/bludit#1441]
As the headline states, when I set a static page to draft, and then republish it, the type setting is lost back to default (which is page).
Moreover, if I create child static pages and assign them to a static parent, I cannot even set them to draft more. As soon as you click the save button, its status turns back to being published. I've tested this not on 2 installations and the behaviour is the same.

**Comment by dignajar** [comment]
The type of page are `draft` `static` `published`, if you change from `static` to `draft` the type `static` type is lost.

**Comment by apps4research** [comment]
How is this fixed. You described the problem, but nothing more!

**Comment by dignajar** [comment]
There is not issue, is how that works by design. The database is quite
simple and keep only a key for the current type, what I can do for the next
version (v4) add another field in the database to know when is draft or not.

**Comment by joho1968** [comment]
Or possibly create "draftstatic", "draftpublished", etc. That would mean not breaking code that looks for "published" and "static". Though from a design POV, I would agree with having a second flag, "draft".
