### ISSUE TITLE
[4.0.0-rc-3]Error meta <Description>

### ISSUE THREAD

**Issue by cvetanet** [bludit/bludit#1443]
### Describe your problem
Error meta Description

### Steps to reproduce the problem
Complete here.

### Bludit version
4.0.0-rc-3

**Comment by clickwork-git** [comment]
Can you please describe the problem, and how it can be reproduced.

**Comment by cvetanet** [comment]
> Can you please describe the problem, and how it can be reproduced.

Sorry. Its work
