### ISSUE TITLE
directory creation permission issue 

### ISSUE THREAD

**Issue by typspan** [bludit/bludit#1448]
### Describe your problem
Complete here.

### Steps to reproduce the problem
Complete here.

### Bludit version
Complete here.

### Hosting or Webserver name
Complete here.

### PHP version
If you do not know delete this line.

### PHP logs
If you do not know delete this line.

The default settings for the PHP error log file vary from operating system to system. The location of the error log file itself can be set manually in the php.ini file. On a Windows server, in IIS, it may be something like `error_log = C:\log_files\php_errors.log` in Linux it may be a value of `/var/log/php_errors.log`.

**Comment by noraj** [comment]
Someone could rename this issue to _directory creation permission issue_ and add this in the body:

```
(4-00_rc-3) [01-Jul-2022 11:40:41 Europe/Madrid] PHP Warning: mkdir(): File exists in /home/ma221zw2/public_html/spainonthisday.com/bl-kernel/helpers/filesystem.class.php on line 56 [01-Jul-2022 11:40:41 Europe/Madrid] [ERROR] [4.0.0] [/api/pages] Pages::add | An error occurred while trying to create the directory: /home/ma221zw2/public_html/spainonthisday.com/bl-content/pages/empty-0 [01-Jul-2022 11:40:41 Europe/Madrid] [ERROR] [4.0.0] [/api/pages] createPage | Something happened when you tried to create the page.
```

Having 100% of the issue in the title is not helping 
![image](https://user-images.githubusercontent.com/16578570/179054588-5e1c57f9-2b7a-4289-b32c-a74d42848b83.png)

**Comment by dignajar** [comment]
Please create a new issue, this issue doesn't have any kind of information.
