### ISSUE TITLE
[3.13.1] + PHP8.1.9 Deprecated:  uasort(): Returning bool from comparison function is deprecated

### ISSUE THREAD

**Issue by BeJoNe** [bludit/bludit#1452]
### Describe your problem
[Tue Aug 30 12:31:04 2022] PHP Deprecated:  uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in C:\Rodeo\bludit-3.13.1\bl-kernel\boot\rules\60.plugins.php on line 125

### Steps to reproduce the problem
start the bludit web via php.exe -S

### Bludit version
3.13.1

### Hosting or Webserver name
Server 2019

### PHP version
php-8.1.9-Win32-vs16-x64

**Comment by dignajar** [comment]
Hi, Fixed on Bludit v3.14.1.
Thank you for the report!
