### ISSUE TITLE
Bludit Update from version 3.13.1 to 3.14.0: Deprecated and warnings

### ISSUE THREAD

**Issue by nullproblemo** [bludit/bludit#1453]
After updating from 3.13.1 to 3.14.0 I got these informations on the top of every page of my website:

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /var/www/virtual/user/html/bl-kernel/pages.class.php on line 419

Warning: Cannot modify header information - headers already sent by (output started at /var/www/virtual/user/html/bl-kernel/pages.class.php:419) in /var/www/virtual/user/html/bl-kernel/boot/rules/99.header.php on line 3

Warning: Cannot modify header information - headers already sent by (output started at /var/www/virtual/user/html/bl-kernel/pages.class.php:419) in /var/www/virtual/user/html/bl-kernel/boot/rules/99.header.php on line 4

So I returned to Bludit version 3.13.1.

**Comment by clickwork-git** [comment]
This happens with PHP 8.0.

There is also the following error:

Undefined variable $codesampleConfig in /var/www/vhosts/testinstallation.ch/juedische-lebensreform.ch/bl-plugins/tinymce/plugin.php on line 146

**Comment by nullproblemo** [comment]
I tried it again. The same problem with PHP 8.1.

**Comment by dignajar** [comment]
Hi, Fixed on Bludit v3.14.1.
Thank you for the report!
