### ISSUE TITLE
[3.14.1] After save content, the page goes blank with php 8.0

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1469]
### Describe your problem
One.com has marked php7.4 as end-of-life and is trying to upgrade everyone to 8.0 as a minimum, however, Bludit gave errors on v3.13.1 so php was put back to v7.4... everything was OK again...

... have now successfully upgraded bludit to v3.14.1 and all is fine while using php7.4, however, once PHP is changed to v8.0 the page goes blank after clicking save. The new content or edit has been saved, but it's a major fiddle having to go back to 'admin/content' listing.

I thought v3.14.1 was to make bludit compatible with PHP 8.x - was I wrong?

### Steps to reproduce the problem
With PHP v8.0, create new content or edit existing content and click save - the page goes blank

### Bludit version
3.14.1

### Hosting or Webserver name
One.com

### PHP version
v8.0

**Comment by BlakesHeaven** [comment]
Update: I'm trying to ascertain if a plugin is interfering with it, as I have now installed vanilla Bludit as a sub-site and it works Ok with php8.0. 
The only trouble is I can't have the live site on php7.4 and the test site on php8.0... if you have any suggestions of what functionality was dropped between php7.4 and php8.0 it might help me locate the code.

**Comment by Sellato** [comment]
I use Bludit as test site on PHP 8.1.* and have no problems, as I think :)

Add this lines at the top of your **.htaccess** file

php_flag display_errors on
php_flag display_startup_errors on
php_flag display_errors on
php_flag html_errors on

Now you can see what is a problem. Remove after fix a problem.

**Comment by BlakesHeaven** [comment]
Thanks @Sellato, I agree, Bludit is OK and I will give your suggestion a go.👍
I now have php running locally with a copy of the site 🙂 and was trying (unsuccessfully so far 🤨) to understand 'Composer' and hopping to add a plugin, Phan, to list incompatibilities. 

I'll  return with an update of what I find and changed.

**Comment by Sellato** [comment]
@BlakesHeaven As I remember you need PHP 7.3 for composer working. Check your PHP version. I use PHP 7.3.33-8 and works fine.

**Comment by BlakesHeaven** [comment]
A quick update.... I didn't get any errors to display, but I got WampServer installed, which sped up the debugging and I found a few places in my plugins that were broken where an array key hadn't been enclosed in 'speach_marks' - something php7.4 didn't mind but php8.0/8.1 did object to.... that fixed my critical errors...

OK - back to this reported issue, "when saving a page the page goes blank"...

I narrowed it down to the plugin call, "[Broken Link Checker](https://plugins.bludit.com/plugin/broken-link-checker#download)" listed on the Bludit Plugin page.  although the download link is broken...

Anyway, once the plugin is deactivated the issue goes away....  I was going to ask @anaggh if they have any thoughts on fixing it but they seem to have disappeared off the scene and all git repositories removed... a pity because this was a handy utility.

@dignajar, do you want to keep this issue open and possibly fix the plugin or close it as not your problem? I do think the plugin link should be removed though.

**Comment by dignajar** [comment]
not a bludit issue, thanks for the feedback
