### ISSUE TITLE
Please add "9" to the "Items per page" field.

### ISSUE THREAD

**Issue by GUSSAN-BEEDAN** [bludit/bludit#1474]
### Describe your problem
request

### Steps to reproduce the problem
none

### Bludit version
3.13.1

### Hosting or Webserver name
none

<img width="801" alt="スクリーンショット 2022-11-30 18 51 45" src="https://user-images.githubusercontent.com/96756270/204765761-a2780b20-4083-484a-a75b-c7c2810fa642.png">

**Comment by BlakesHeaven** [comment]
Better still,  remove the dropdown and let people add their own number with 0 or "All' meaning "All"

**Comment by dignajar** [comment]
Fixed for release 3.15
