### ISSUE TITLE
Markdown is not going to be parsed

### ISSUE THREAD

**Issue by BullyH** [bludit/bludit#1477]
### Describe your problem

Running in the same problem with 3.14.1 (build 20220807), as already described in #1339.

quote: "When I switched from TinyMCE to EasyMDE and started editing my pages in markdown the content was not parsed but rather came out as markdown code (plain text)."

Please could you provide a solution for that problem? - Thanks in advance!

### Steps to reproduce the problem

deactivate TinyMCE
activate EasyMDE
write content in markdown

The mentioned solution ([issue 1339](https://github.com/bludit/bludit/issues/1339)) by disabling line 70 … doesn't helped, unfortunately.

### Bludit version
Bludit Version: 3.14.1
Bludit Build Number: 20220807

### Hosting or Webserver name
Raspberry + Apache

### PHP version
PHP version: PHP 8.1.9 (cli) (built: Aug 15 2022 09:47:52) (NTS)

**Comment by dignajar** [comment]
I can not reproduce the error.
do you have enable in Settings > Advanced settings > PAGE CONTENT > Markdown ?
