### ISSUE TITLE
Snicker (native FlatFile comment system)

### ISSUE THREAD

**Issue by felhasznalonev** [bludit/bludit#1478]
Snicker https://github.com/bludit-plugins/snicker doesn't work anymore since Bludit v3.14.0 "Out Of Time" (not even v4.x RCs). Last properly work version is v3.13.1 "Edi". Can someone tell me something? It's annoying that very-very basic function (native FlatFile comment system) is lost when updating Bludit's core. Shouldn't such a basic function be made part of core so that Bludit can be used more boldly without loss?

**Comment by RickHays** [comment]
Found in plugin.php at line 801 - Session::start();

Looked at Buldit Session class and saw it required two values for it to work.  

So I changed Line 801 in plugin.php to Session::start('', true);  and that seemed to fix the issue.  Not sure if there are better values to put in place for what I selected.  But that did get me going.  Hope that helps you.

**Comment by felhasznalonev** [comment]
It seems to work for v3.14.1 but not for v4.0.0 (unfortunately).

**Comment by dignajar** [comment]
please post the issue in the github of the plugin. thanks
