### ISSUE TITLE
sanitize meta description

### ISSUE THREAD

**Issue by angerangel** [bludit/bludit#1489]
Hi,
meta description has to be sanitized because otherwise it becomes incorrect.
For example a post has this text:

**Tube size 1/4" is too small.**

creates this incorrect meta:

`<meta name="description" content="Tube size 1/4" is too small."  >`

I think that just a **htmlentities(  ,    ENT_QUOTES)**  function would resolve this matter.

**Comment by dignajar** [comment]
What version of Bludit ? for version 3.14.1 is encoded.

<img width="606" alt="Screenshot 2023-02-22 at 23 15 44" src="https://user-images.githubusercontent.com/507352/220772325-72490fac-0cfd-475f-aeb4-2d87f7ca23e9.png">
