### ISSUE TITLE
Image proble with 3.14.1

### ISSUE THREAD

**Issue by angerangel** [bludit/bludit#1490]
Hi,
I just upgraded to 3.14.1 pro and images uploading doesn't work well anymore.
The  uploaded image change name from **flower.jpg** to something like **ef0a3800b0b4f36a948ea9c1d085338c** without extension.
I need to retain at least extension, but I would prefer to retain name and extension.

**Comment by basteyy** [comment]
Do you have any plugin enabled?

**Comment by dignajar** [comment]
I need more context, and how to reproduce it.
