### ISSUE TITLE
Markdown Flavor

### ISSUE THREAD

**Issue by craigbass76** [bludit/bludit#1498]
### Which Markdown
Just wondering which markdown is being used, and if it's possible to change. 

There are tags I can use:
```
:::pb
blahdyblahblah
:::
```

Pandoc will convert that to:
```
<div class="pb">
blahdyblahblah
</div>
```
Which is what I'm hoping for. Then I can continue on with what I'm already doing (making PDFs from markdown with Pandoc and Weasyprint) and integrate it somehow.

**Comment by basteyy** [comment]
It's up to you. You can have an editor/parser of your choice. By default, bludit is shipped with [easymde](https://github.com/Ionaru/easy-markdown-editor#readme) and [TinyMCE](https://www.tiny.cloud/) for the editor, which will be processed into HTML. 

Php does not support Pandoc native. When you have it on your server, you can use a Php Pandoc Wrapper for parsing the content.

The easiest way to use Pandoc is, that you use a plugin. Checkout the docs for that.

**Comment by dignajar** [comment]
Bludit uses http://parsedown.org as Markdown parser.
