### ISSUE TITLE
Adding Pagination to Posts is broken.??

### ISSUE THREAD

**Issue by haywardgg** [bludit/bludit#1505]
### Describe your problem
When using the code to display the next and previous posts. It works okay some of the time, but you'll add a page or static content and the pagination breaks. You'll be going through the pages NEXT, NEXT and then it'll not work for the next Page even though there's clearly  several more pages to scroll through.. If I change the date or time of the next page it sometimes fixes it, but it's just weird. There's something going on under the hood that is causing this and for blogging, it's breaking the immersion! 

https://gist.github.com/haywardgb/47118bcbe4eb7c9d3cabbdbec31fe5a5

**Comment by haywardgb** [comment]
UPDATE: Just discovered it's the Autosave that's causing the issue.

**Comment by haywardgb** [comment]
Update: No drafts, no autosaves and the problem is back. This is driving me bonkers lol

**Comment by haywardgb** [comment]
So far the only way I can get around this bug is by changing the date on the offending Page to yesterdays date. Which defeats the object for my purposes. Anyone else having this issue ?

**Comment by dignajar** [comment]
please follow the instruction when you create an issue, I don't know what is the Bludit version, PHP version, etc
