### ISSUE TITLE
version 3.14.1 is vulnerable to stored xss

### ISSUE THREAD

**Issue by r4vanan** [bludit/bludit#1507]
### Describe your problem
I found a cross-site scripting attack on the new content creating page http://localhost:800/admin/new-content
it will execute the script in user context allowing the attacker to access any cookies or sessions tokens retained
by the browser.
Stored XSS, also known as persistent XSS, is the more damaging than non-persistent XSS. It occurs when a malicious script is injected directly into a vulnerable web application. 

### Steps to reproduce the problem

- login into the account
- click on the new content like in that image
![new_content](https://user-images.githubusercontent.com/35825039/231396673-c9bcb9c9-5912-481f-ba22-656587b71124.png)

- on that page click on the source code edit button
![source_code_edit](https://user-images.githubusercontent.com/35825039/231397062-ac06f572-9102-4e00-b59c-efa70ab5a361.png)

- in the source code inject the xss payload like `<script>alert("1")</script>`
![editing_ins_source](https://user-images.githubusercontent.com/35825039/231397573-9a5b1a7b-44dc-4ce6-884c-a76543bb927b.png)

- click save
- view that page in new tab 
![xss_popup](https://user-images.githubusercontent.com/35825039/231397866-6a44e591-14dc-4d9b-b9e4-eb3eb29c8318.png)

- xss alert message pop up
- view the page source how it executed
![page_source](https://user-images.githubusercontent.com/35825039/231398127-f8a34d83-e7fd-494e-8ebe-ae876f819eee.png)

### Bludit version
V3.14.1

### PHP version
PHP 8.2.4 (cli) (built: Mar 15 2023 15:27:52) (NTS)

**Comment by dignajar** [comment]
You need to have access to the admin panel to change configurations and store XSS. Feel free to provide a solution via PR. Thank you for reporting the issue.

**Comment by r4vanan** [comment]
Btw it is old cve
