### ISSUE TITLE
Version 3.14.1 about plugin is vulnerable to stored XSS

### ISSUE THREAD

**Issue by r4vanan** [bludit/bludit#1517]
### Describe your problem
I found a XSS vulnerability on about plugin which is inside the admin panel

### Steps to reproduce the problem

- login to the admin panel of the website.
- select theme tab
![6_select_theme](https://github.com/bludit/bludit/assets/35825039/3268eb76-5685-4d3b-9f21-390bf48b364c)
- activate theme **Alternative** to **Blog X**.
![5_blog_select](https://github.com/bludit/bludit/assets/35825039/4e2f2293-de93-4d7b-b940-784f15faf619)
- click back or navigate to the home page for the admin panel.
- click and open the plugins tab.
![1_choose](https://github.com/bludit/bludit/assets/35825039/317a1b86-5aee-451b-a783-85e245f54d8f)
- Select **About** setting tab.
![2_about_settings](https://github.com/bludit/bludit/assets/35825039/1b024a69-c135-4b82-bdae-4e1587555313)
- Insert the XSS payload on the input tab.
![3_insert_payload](https://github.com/bludit/bludit/assets/35825039/9bc1df13-42dd-45ed-811c-8d4a02c70478)
- save it and open the home page of the website.
![7_after_theme_changed](https://github.com/bludit/bludit/assets/35825039/5e6f31dc-f718-414f-9334-a5236038be2d)
- Here it is image which is proof for the xss.
![payload](https://github.com/bludit/bludit/assets/35825039/d7790e37-9653-468b-a76c-f28f37f68ccc)

(Note: it only execute in blog x theme )

### Bludit version
V3.14.1

### PHP version
PHP 8.2.6 (cli) (built: May  9 2023 16:47:59) (NTS)

**Comment by dignajar** [comment]
You need to have access to the admin panel to change plugin/theme configurations and add XSS. Thank you for reporting the issue.

**Comment by r4vanan** [comment]
It is old cve which is found in 2021
