### ISSUE TITLE
Plugin roles

### ISSUE THREAD

**Issue by Bencsi** [bludit/bludit#1520]
### Plugin roles
I wrote a plugin and I want to enable the access not just admin, but editor role also. Is it possible somehow?
I figured it out how to add to admin sidebar to be visible az editor role as well. Just added the checkrole() method call at the beginning of the adminSideBar() method in my plugin.php:

```
public function adminSidebar()
    {
        checkRole(array('admin', 'editor'),false);

        global $L;

        $pluginName = __CLASS__;
        $url = HTML_PATH_ADMIN_ROOT.'configure-plugin/'.$pluginName;

        $html = '<a id="current-version" class="nav-link" href="'.$url.'">'.$L->get('pluginname').' </a>';

        return $html;


    }
```

How can I do the same for accessing the plugin page as editor role?

**Comment by kraiosis** [comment]
Haven't test it yet with new version. Last time i used was something like this:

<?php $Login = new Login();
if ( in_array($Login->role(), array("editor","admin",true) )) 
{  
//your code to show
} 
?>

**Comment by dignajar** [comment]
Hi, please ask in the forum, GitHub issues are for bugs or request improvements. thanks
