### ISSUE TITLE
Is bludit 1.6.2 download legit?

### ISSUE THREAD

**Issue by clozanoruiz** [bludit/bludit#1546]
As of today 27/10/2023 (not excluding earlier days) the version 1.6.2 is available to download from the main site https://www.bludit.com/.
I haven't downloaded the zip file but he link points to this address: https://s3.amazonaws.com/bludit-s3/bludit-builds/...

Is it legit? Seems the versioning is quite different from the last version released here...

**Comment by dignajar** [comment]
Fixed, thanks for reported it
