### ISSUE TITLE
How to filter posts by category on the home page?

### ISSUE THREAD

**Issue by tonybgoode** [bludit/bludit#1548]
I want to be able to display all the posts on my home page, as it works normally, but filter out posts that are of specified categories. 

I haven't figured out exactly how to modify the code to accommodate this—any tips? 

I've seen there is an Unlisted feature coming in 4.0, but am hoping to come up with a solution in the meantime.

VERSION:
3.15.0

Thanks!
Tony

**Comment by ConvertedGrowth** [comment]
Hi Tony,

While the default API doesn't offer a built-in parameter for filtering by categories (like it does for example to only show published items), you can do this with if/else statements in PHP.

I currently run this usecase on my blog, where I only want to show blogs that match the current post's current category, for example at the bottom of https://convertedgrowth.com/cro/saas-pricing-page-test-examples.

For example, if you were using PHP to post a list of blogs with a link and title, you can use if/else statement to exclude particular categories.  

```
        <?php
             $pageNumber = 1;
             $numberOfItems = 5;
             $onlyPublished = true;
             $items = $pages->getList($pageNumber, $numberOfItems, $onlyPublished);
             foreach ($items as $key) {
               $page = buildPage($key);
               $relatedCategory = $page->category();
               if ($relatedCategory !== "General"){
                  echo "<a href='".$page->permalink()."'>".$page->title()."</a>";
               }
            }
            if ($relatedBlogCount == "0"){
        ?>
```

Cheers!
