### ISSUE TITLE
How to customize <title></title>

### ISSUE THREAD

**Issue by bluesky0341** [bludit/bludit#1552]
for example,
if my article title is ceramic cup,

then click view source code for this article

<title>ceramic cup</title>

above is not good for google seo

i need <title>ceramic cup, cermic mug</title>,this is good for google seo

how can i do?

**Comment by dignajar** [comment]
Please post this kind of questions on the forum.
https://forum.bludit.org

**Comment by bluesky0341** [comment]
i have sent post on forum，waiting for approve



---Original---
From: "Diego ***@***.***&gt;
Date: Thu, Jan 4, 2024 02:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bludit/bludit] How to customize <title&gt;</title&gt; (Issue #1552)




 
Please post this kind of questions on the forum.
 https://forum.bludit.org
