### ISSUE TITLE
Support for Bludit CMS Development

### ISSUE THREAD

**Issue by Mates-K1** [bludit/bludit#1561]
Dear @dignajar,

I am a great admirer of Bludit CMS and appreciate the work you have put into the project. I have noticed that there hasn’t been much activity on GitHub recently, and I would like to inquire if there is anything that could help increase the frequency of updates and development of the project.

I am reaching out here as I have been waiting for more than three days for my post to be approved on the official forum, and I am keen to find ways to support Bludit. If there is anything that could benefit the project - whether it be testing, documentation, or any other form of support - I would be eager to get involved and contribute to Bludit’s growth. Should you have any ideas or needs that I could assist with, please let me know.

Thank you for your hard work, and I look forward to the possibility of collaborating.

Best regards, Martin

**Comment by dignajar** [comment]
Hi @Mates-K1 ,
You can help creating Pull requests with changes, improvements, adding languages files, updating third party libraries, improving UI, whatever you want.

Everything is published in Github.

- https://github.com/bludit
- English doc > https://github.com/bludit/documentation-english
- Docker image > https://github.com/bludit/docker

Thanks for your support!
