### ISSUE TITLE
Use translated 'about' section title in sidebar

### ISSUE THREAD

**Issue by fragadass** [bludit/bludit#1562]
### Describe your problem
The 'about' section title in the sidebar is not translated.

### Steps to reproduce the problem
Use another language and a theme with sidebar.

### Bludit version
3.15

### PHP version
8.2

### Proposition

File : bl-plugins/about/plugin.php
Line : 40
Todo : replace $this->getValue('label') by $L->get('About') ; add global $L; at the beginning of the function.

Sorry if I don't do the change by myself in a request, but I'm not so familiar with Github.

**Comment by dignajar** [comment]
I changed the language to Spanish and is translated, can you tell me what language are you using ?

**Comment by fragadass** [comment]
French

**Comment by dignajar** [comment]
You can edit it from the plugin. Go to admin > plugins > about > label.

<img width="801" alt="Screenshot 2024-06-30 at 22 46 31" src="https://github.com/bludit/bludit/assets/507352/592f3101-f854-4ddb-9d9f-6ed7e64a7536">

**Comment by fragadass** [comment]
Oh, thanks, it works !
