### ISSUE TITLE
EasyMDE and TinyMCE aren't playing nicely together

### ISSUE THREAD

**Issue by joho1968** [bludit/bludit#1568]
### Describe your problem
Having both EasyMDE and TinyMCE activated seems to cause issues when saving content. The title of the post is saved, but the actual text content is not.

### Steps to reproduce the problem
Activate both editors, go to generate some content (or edit existing), when you save the content, the actual content text disappears.

### Bludit version
3.15.0

### PHP version
8.1.x

**Comment by dignajar** [comment]
You can not have enable two WYSIWGT at the same time..

**Comment by joho1968** [comment]
Yes, I noticed 😉 So perhaps they could both check if the other is active and simply return an error message stating exactly that 🤔
