### ISSUE TITLE
[minor]  Change of "Language and timezone" has  no effect on displaying the date

### ISSUE THREAD

**Issue by CryssDOTnet** [bludit/bludit#172]
December in German should be Dezember (with a 'z'). As this is the case with all themes I guess it is not a theme issue but something in bludit.
1. Screenshot (Business Casual theme)
   ![bildschirmfoto vom 2016-01-01 19-10-36](https://cloud.githubusercontent.com/assets/11821273/12071740/0c9a817e-b0bc-11e5-8296-5feb10c6308c.png)
2. Screenshot
   ![bildschirmfoto vom 2016-01-01 19-10-14](https://cloud.githubusercontent.com/assets/11821273/12071741/0ed60bd4-b0bc-11e5-8d16-867d9dcfb424.png)

**Comment by dignajar** [comment]
Yes I know, the posts and pages are saved with the current timezone. Maybe the best will be when the user change the timezone update the dates.

**Comment by clickwork-git** [comment]
The names of the months in English are given by PHP. This could be extended by the function setlocale.

**Comment by dignajar** [comment]
Fixed, take a look here https://github.com/bludit/bludit/issues/532
