### ISSUE TITLE
Feature request: Real categories

### ISSUE THREAD

**Issue by nickbe** [bludit/bludit#223]
No matter how hard I try, tags do not replace real categories. 
I think posts should belong to a category (even if it's a default 'uncategorized' one).

Tags are just too chaotic, since everyone uses different words for the same things. On the other hand, selecting a category for my post is simple and I don't have to invent something.

It would be an easy way to enter a certain area when visiting the site, just the "Gadget" posts, or just the "Economy" posts.

Also it would eventually be an oportunity to let an author write posts in certain categories, but not in all.
Please consider the possibilities for sites with several authors.

**Comment by veccora** [comment]
I agree. Categories should be part of every standard log CMS. Please highly consider this addition.

**Comment by nickbe** [comment]
I know Diego wants to keep things simple, but I think being able to use predefined categories make it much simpler to post since I'm much too lazy to think of tags when creating a post. 

So What I'd really like is enter a good post title (which can be already hard at times ;), select a fitting category or add a new one, and start writing. The list of main categories would be an easy way to navigate blog sites with multiple authors and interests.

**Comment by CryssDOTnet** [comment]
What is the difference between categories and tags?

**Comment by nickbe** [comment]
Tags are mostly freely defined for each post and you can have as many tags as you like with each post. While this sounds attractive the problem is that you cannot have a real sub menu list made out of tags, because you probably get thousands of tags after some time. So you will be restricted to the most interesting tags or tags from posts most viewed.

Categories on the other hand are prefereably selected from a predefined list. And if you select one category for each post you can show a reliable filter list of categories somewhere on your site.

Imagine a blog site with multiple authors. Each author is responsible for different category like 'Gadgets', 'Politics', 'Tech News' and so on. With categories you can distinctly select a certain section of posts. While with tags you can only set a predefined filter.

**Comment by CryssDOTnet** [comment]
With multiple authors this would make sense. Yes.

**Comment by nickbe** [comment]
Not only with multiple authors. I'm maintining a company internal news/blog here. For now I made a small portal site and installed bludit 5 times. That way you can choose between 'Client News', 'Micorosoft', 'Developer', 'Ideas & Tricks' and 'Projects' when entering the site. It works, but is defintely not a final solution to the category problem.

**Comment by nickbe** [comment]
Anything new regarding categories?
As simple as this feature sounds, it would help greatly.

**Comment by edos4** [comment]
Followup on this pls.

**Comment by Sirjoseph94** [comment]
i totally agree with @nickbe that Categories feature should be implemented at least  for easy navigation. it will really help a great deal.

**Comment by Torsten-K** [comment]
I would also prefer categories.

**Comment by nickbe** [comment]
Ok I'm working on it.....

**Comment by ColonelBlimp** [comment]
I would also like to see a Categories feature. I reader of a post should be able to click the category under which the post is filed and get a list (teaser) of all the other posts filed under that category.

**Comment by dignajar** [comment]
Working on this feature for the next version, you can download the code from Github branch master for test it.

**Comment by nickbe** [comment]
Did you get the categories implementation I've sent you?

**Comment by dignajar** [comment]
@nickbe Yes I received the implementation, but I going to add the categories on the version 2.0, not in the next version 1.6. I want to remove the posts from Bludit and have only pages.

**Comment by klermor** [comment]
I think it's a pity to abandon the posts...

**Comment by dignajar** [comment]
@klermor the idea to remove the post is replace for pages. The pages has the same structure, so you can configure your site order by date or order by postion, the page has both properties. So if you order your site by date, the pages are posts.

**Comment by dignajar** [comment]
When I going to make this kind of changes, I post alway in the Gitter channel, https://gitter.im/dignajar/bludit

**Comment by klermor** [comment]
ok, good !

**Comment by nickbe** [comment]
I think seperating posts from pages is in fact a good thing. Having only pages there's the problem of lettings one user manage pages and others only posts. I wouldn't want the same people who write posts also change the content of the main pages. So how do you plan do this?

**Comment by dignajar** [comment]
mm is not possible with this implementation, or you can have 2 installations, one for a website (pages) and one for a blog (posts), and share the database of users, or each page has a variable "type" and this variable can be page or post.

**Comment by nickbe** [comment]
Well it's fairly easy with the current version where posts and sites are different things anyway.

**Comment by nickbe** [comment]
Although I respect your decision I'm really sorry about it. I've decided to fork out after 1.6 and finish implementing categories and several other team oriented features myself before you remove posts from the release. This will allow us to take the fork in a different direction. Thanks for you effort so far.

**Comment by dignajar** [comment]
The idea of Bludit is to allow the user to create a quick website from scratch in seconds, and the administration of this website need to be super friendly user like click on a button and you are writing content for your site, you don't need to care about configuring things, this idea was to destroy when I add more and more things to the core, more code to debug, more databases, more point of fails, so I want to repair this.

I don't have a problem with your implementations, and modifications, but is no the stuff I want to add to Bludit, sorry for this.

Anyway, you need to wait for the new version, then you can get you conclusion if Bludit v2.0 is going to work for your team or not.

**Comment by nickbe** [comment]
Well I think you're on the right track, but I don't think that all users should be able to change pages, but only posts. Or to put it differently - there should be pages that only an admin can change and others that a user can change.

**Comment by Turqueso** [comment]
I haven't thought about that. Maybe restrict some categories? there would be different type of users?

**Comment by acrox999** [comment]
Or each pages can have permission settings. Categories too would be good as
well.

**Comment by nickbe** [comment]
Maybe my old proposal for user edit rights per category would really help here. 

For those who want it simple: one default category, one user being adnin in this category.
Quite simple.
But in a more complex work environment you can have more categories and restrict the users edit rights per category. 
I still think this would be a really powerful feature, which doesn't get in your way if you don't use it.

**Comment by nickbe** [comment]
And don't get mad at me for suggesting this again Diego ;) But I still don't want to let go of bludit.

**Comment by nickbe** [comment]
Right now I can extend the menu by creating a new page.
With only pages left and no posts, how might we be able to target a new menu item as opposed to new blog entries?

**Comment by Torsten-K** [comment]
@dignajar: I understand that you want to keep your CMS simple, because this is what makes it different, compared to so many other systems – no need to explain to an end user how to handle the backend. But  people are used to destinguish between pages for static content and posts for a blog or a news area. And this is what they might have seen in another system, be it WordPress, Pagekit or Serendipity, to name only a few. So, why confuse the users?

**Comment by Turqueso** [comment]
I think you should wait to check out a pre-release. So far I like the idea of making post and pages the same.

**Comment by nickbe** [comment]
We're currently playing around with the new 2.0 version and I'd like to make seceral comments and suggestions:

I think right now the new 'position' and 'parent' fields are confusing. Basically what we have now is an open treelike structure which would enable authors to divide posts into subposts. This is might be a good thing for extending the "static" pages, - because now you can easily creates sites and their subs, thus extending the menu. But, it's also quite confusing for normal posts.

Because the first question one asks is "Under which other post should I place my new blog post?" which might especially confusing if the menu grows.  So I suggest that users should be specifically allowed to be able to set posts below other posts, placing standard posts nowhere in particular like now.

So, I'm thinking of a simple  'create sub level posts' option which gives us the possibility to prevent some authors from extending the site itself. Think about secondary authors who might otherwise change the impressum of you site - a possible legal threat for some of us

Then there's the position. I assume you mean to give us the option to sort the sublevel posts somehow. To be honest I would prefer a simple drag/drop widget to sort posts here. And a way to select post sorting for subfolders by either 'date', 'manually (drag drop)' or 'alphabetical (by title)

While the old 1.6.2 was absolutely simple to use, you need much more thinking with the 2.0 version right now which should be prevented in my opinion.

**Comment by dignajar** [comment]
Implemented on Bludit v2.0
