### ISSUE TITLE
Problem UTF-8

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#257]
It is not (yet) possible to save posts and pages with some languages as Hebrew, Arabic etc.

mkdir has to be extended with encoding when using UTF-8:

http://stackoverflow.com/questions/1525830/how-do-i-use-filesystem-functions-in-php-using-utf-8-strings

**Comment by dignajar** [comment]
I will check this issues, thanks!

**Comment by abdtif** [comment]
+1

**Comment by dignajar** [comment]
I made some changes, and I added the variable EXTREME_FRIENDLY_URL in bl-kernel/boot/init.php

If you set this variable to TRUE, dismiss the Internet Standard https://tools.ietf.org/html/rfc3986

This changes are only in Github for the moment.

**Comment by dignajar** [comment]
Bludit v3.x use unicode to avoid this. I close the issue.
