### ISSUE TITLE
Editor-Sidebar is vanishing for smaller screens

### ISSUE THREAD

**Issue by MaxMalRichtig** [bludit/bludit#304]
Hey there!

When trying to write/edit a post or a page on a smaller screen (like smartphone or tablet), the sidebar just disappears! Using pictures or setting tags is therefore nearly impossible.

I'm talking about THIS sidebar ;)

![bildschirmfoto von 2016-07-13 19-19-06](https://cloud.githubusercontent.com/assets/16749508/16812881/68fe188e-492f-11e6-80e0-1f2d5068f404.png)

There is a CSS directive for the default-admin-theme, which just hides it for screen-sizes between (min-width: 333px) and (max-width: 959px):

> ./bl-kernel/admin/themes/default/css/default.css -- Line: 115

 `.uk-width-large-2-10 {
        width: 0% !important;
        display: none !important;
    }`

My question is: **Why is this even in there?** Deleting the whole directive brings back the sidebar (below the editor).

Max

**Comment by acrox999** [comment]
Diego probably had some plans to make it more mobile friendly and put that there. I noticed this too but God bless the "Request desktop site" button on mobile browsers.

**Comment by alexandreteles** [comment]
> @acrox999 said:
> Diego probably had some plans to make it more mobile friendly and put that there.

It works pretty well if you change the css in /bl-kernel/admin/themes/default/css/default.css as stated above. I think a PR could be submitted to make this small change or we could make a little adjustment.

**Comment by Max-malRichtig** [comment]
***Woops*** o.O

Sorry for the reference-mess in here. I tried to use the web-frontend for this little PR, since I'm at an other persons PC right now ... never again.

I'll provide a clean PR later.
