### ISSUE TITLE
Titles for tags

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#341]
May I ask about to change text in HTML **title** and **meta name="description"** for auto generated Bludit post tags URLs? It will be better for search engines to index page with defined names.

**Comment by dignajar** [comment]
Hi,
this tags depends of the theme and the developers who made the theme, anyway, I made some functions for make dynamic this fields.. could you showme some example ? thanks

**Comment by xm74** [comment]
For example I using default log theme on my site https://kostikov.co
If you click to any tag from sidebar you will get same data in **title** and **meta name="description"** as for main page:
`<title>Max Kostikov</title>
<meta name="description" content="Персональный блог">`
I think it will be better to chage to something like that:
`<title>FOO tag</title>
<meta name="description" content="Pages for FOO tag">`
Or may be sophisticated SEOs will tell something different and more usefull for search engines.

**Comment by dignajar** [comment]
Ok, I added the tag on the title, on the latest files on github.. the description I don't know what can I add, anyway the SEO of a website is not more for tags, it's more for the content of it.

**Comment by turbopixel** [comment]
I like the meta-tags in today's time still, if there no content like image galleries or status pages.
(Google uses these also on many product pages.)
