### ISSUE TITLE
Small improvement request: Easy insertion of "pagebreak" into posts

### ISSUE THREAD

**Issue by ThePrudentNinja** [bludit/bludit#371]
Maybe I'm just getting rusty with things but this is something I can't seem to figure out and I'm sure there is probably an easy way to do it.

I've done a lot of blogging over the years and usually editors allow easy insertion of a "read more" tag or link to keep the front page from becoming too big. The information [here](https://docs.bludit.com/en/content/readmore) works, but an easier way would be an improvement (such as a button in the editor bar to insert that tag).

Would be a small improvement but would probably help polish the interface some.

**Comment by niemes** [comment]
I agree with @ThePrudentNinja ! It will a great simple enhancement Where are the code of the built-in markdown editor ?

**Comment by niemes** [comment]
If you dont see the Page Break icon : put autoDownloadFontAwesome to true under plugin.php of the simplemde plugin.

**Comment by ADTC** [comment]
Hey this is a nice find and addition. SimpleMDE actually has the ability to add custom buttons (without touching the code, that is). But I don't know how to do that in the plugin settings in Bludit. Perhaps that would be another major enhancement.

**Comment by dignajar** [comment]
This button was added on Bludit v2.0 for SimpleMDE. thanks
