### ISSUE TITLE
Page set as default home page produces double content

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#394]
If a page is set as default home page, the mainpage / and the page /page are shown. This produces double content. In this case only / should be shown.

**Comment by Torsten-K** [comment]
My solution is the following line in .htaccess (in the case that I have a homepage by the name of start):

`RedirectPermanent /start http://www.domain.de/`

But now the home/start page is not marked as active in the menu.
 
A little more background: I use the sidebar navigation plugin for the main navigation, leave the text field for the title empty and switch off _show main page_. This way the (empty) blog home page is not shown. But no matter if switch on or off and no matter if in the .htaccess file I do a redirect or not – the home page (actually the first of my pages) is never marked as active. It seems like using the blog functionality is a must in Bludit.

So, a navigation would be fine that is usable as a main navigation but without the need of using the blog functionality.

I hope I could describe clearly enough what my issue is – English is not my natural language.

**Comment by Torsten-K** [comment]
If I don’t want a blog feature, I could simple change the template _bl-themes/[theme-name]/php/home.php_ to a page template, right?

**Comment by acrox999** [comment]
Yes, the homepage will reflect to however you make the template be.

**Comment by clickwork-git** [comment]
There is the following fix for the navigation:

https://forum.bludit.com/viewtopic.php?f=6&t=914&p=3685#p3685

**Comment by Torsten-K** [comment]
In the meantime, I had constructed my own workaround. At first, a check is run whether the visitor is on the home page or not. In the first case, the menu item is marked as active.

After that, the foreach-loop is combined with an if-query to exclude the pages that shall not appear in the main navigation (they are hard-coded links in a separate navigation menu):

`<?php 
	if($requri=="/") {
		echo '<li class="active"><a href="https://www.example.com/">Startseite</a></li>';					
	} else {
		echo '<li><a href="https://www.example.com/">Startseite</a></li>';	
	}

	foreach($parents as $page) {		
		if($page->title()!="Kontakt" and $page->title()!="Datenschutz" and $page->title()!="Impressum" and $page->title()!="Startseite"){
			echo '<li'.( ($page->key()==$Url->slug())?' class="active"':'').'><a href="'.$page->permalink().'">'.$page->title().'</a></li>';
		}	
	}					
?>`

I don’t know if that’s a good coding style, but at least it works fine.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
