### ISSUE TITLE
Remember me checkbox in Login

### ISSUE THREAD

**Issue by ADTC** [bludit/bludit#399]
How can I add a remember me checkbox in the login page? As in, how exactly can I remember the user for 30 days (for example)? Right now the session expires quite quickly when left idle, and it's become rather inconvenient to keep having to login.

Also it would be nice if the username field is pre-filled with the username that was typed in, when the login page reloads with the "Incorrect login" message.

**Comment by acrox999** [comment]
I agree. The cookie right now expires rather quickly, right after closing
the browser.

**Comment by ADTC** [comment]
I think it's only a session, not based on cookie. I guess I'll try to look for this. Any hints, @dignajar ?

**Comment by acrox999** [comment]
I think cookies are involved. Without cookies, the site won't even let you
login. Also, it seems to me that the cookies expiration time is somewhat
inconsistent at some times. Sometimes time it expires when I left the tab
for a while, sometimes it last even after I closed the browser.

**Comment by ADTC** [comment]
@acrox999 indeed, there is a single cookie called Bludit-KEY (it expires with the session). When I deleted it, I was kicked back into the login page.

But logins can function without cookies based on session alone (though they would not be able to remember the login). I have programmed a website that does it. I also read that the session cookie (used by Bludit, just to store the session id) is not a standard cookie but a special cookie that expires with the session, and so you can consider it as "no cookies".

**Comment by dignajar** [comment]
Implemented on v2.1-beta
https://github.com/bludit/bludit/tree/v2.1-beta
