### ISSUE TITLE
How to set up "Email access code" functionality?

### ISSUE THREAD

**Issue by ADTC** [bludit/bludit#402]
Would be nice to have a guide in the project readme on how to setup the "email access code" functionality, so that this function can actually work.

And can it use PHPMailer? Because I'm using PHPMailer for the rest of the website, and would like to just plug into it, coz it already works.

**Comment by clickwork-git** [comment]
What do you mean with email access?

Bludit does not use PHPMailer. It's an own library (with a high security risk as shown by other CMS not so long ago).

**Comment by dignajar** [comment]
Hi,
this is a little tricky because Bludit uses just the PHP function mail() with some "hacks" for Bludit, but this function of PHP use the internal configuration of PHP / Server, so you need to have configured your server to send emails.

http://php.net/manual/pl/function.mail.php

**Comment by taktojest** [comment]
@ADTC you can use phpmailer, but first you need to "connect" it as some plugin.
I'm using phpmailer here http://www.taktojest.com/kontakt

For the standard mail() functionality in Bludit yiu need to configure at least senmail on your server.

**Comment by ADTC** [comment]
@dignajar please let me know if it's possible to use PHPMailer via a plugin as @taktojest suggested. I can probably code a custom plugin for myself so that I can make the "email access code" functionality work using PHPMailer or any custom mailer library (instead of the stardard mail() function).

@clickwork-git sorry about the wording in my question, I meant to say "email access code" (getting an access code in email inbox), not "email access" (accessing something through email). There is a link in the login page called "email access code" which is what I was talking about.

**Comment by dignajar** [comment]
The class for send emails is this, https://github.com/dignajar/bludit/blob/master/bl-kernel/helpers/email.class.php you can change it and add the PHPMailer. For my side, I don't like PHPMailer is too big/complex to include on Bludit.

**Comment by acrox999** [comment]
I've been wanting to say this but mine worked just fine without configuring anything.

**Comment by dignajar** [comment]
This function was deprecated on Bludit v2.
To recover the password here is an alternative: https://github.com/bludit/password-recovery-tool
