### ISSUE TITLE
Show recent posts to another script

### ISSUE THREAD

**Issue by guleyc** [bludit/bludit#488]
Hello,

I want to show my last posts to another script. I think, it can be possible with API. But, I cant found any method. How I can show? Any idea?

Thanks.

**Comment by anaggh** [comment]
Bludit v1:
* https://docs.bludit.com/en/api/introduction
* https://docs.bludit.com/en/misc/embed-bludit-in-my-website

Bludit v2:
* https://docs-v2.bludit.com/en/api/introduction

**Comment by guleyc** [comment]
I write as https://my-domain.com/api/show/all/posts/5d23c7d2a97e08e977a671df3f4f4c59

I understand that 5d23c7d2a97e08e977a671df3f4f4c59 is api token. But something is wrong, error like {"status":"1","message":"Invalid token."}

When I use code in "https://docs.bludit.com/en/misc/embed-bludit-in-my-website", error shows like "Warning: Illegal string offset 'permalink' in..."

**Comment by anaggh** [comment]
This seems to be working in Bludit v1.6.2

* Posts:
```
curl -X GET -H "Content-Type: application/json" -d '{"token":"your_token", "limit":1}' http://localhost/bluditv1/api/posts
```

* Pages:
```
curl -X GET -H "Content-Type: application/json" -d '{"token":"your_token", "limit":1}' http://localhost/bluditv1/api/pages
```

More info: https://docs.bludit.com/en/api/posts

**Comment by anaggh** [comment]
Bludit v2 is easier:

* List of Pages:
```
GET
http://localhost/bludit/api/pages?token=your_token
```
* Specific Page:
```
GET
http://localhost/bludit/api/pages/welcome?token=your_token
```
