### ISSUE TITLE
Loading CSS failure when webserver listen on different port than 80 or 443

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#507]
How to reproduce it:
- Webserver listen on port 8080
- Make a fresh installation

**Comment by sirahngelu** [comment]
Thanks @dignajar 

Here is the modified code:
```
		// Parse the domain from the field URL.
		$parse = parse_url($this->url());
		$domain = trim($parse['host'], '/');
		$port = $parse['port'] ? ':'.$parse['port'] : '';

		return $parse['scheme'].'://'.$domain.$port;

```

https://github.com/bludit/bludit/blob/master/bl-kernel/dbsite.class.php#L209

**Comment by dignajar** [comment]
Fixed, take a look.
I need to add the empty function because if the port is not defined is null.

**Comment by sirahngelu** [comment]
Haha, nice!
I think C is your first computer language.
