### ISSUE TITLE
v2.0: Warnings on language change with 3rd-party plugins

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#508]
Got few warining when I changed language in admin panel depending 3rd party plugins
>Warning: file_get_contents(/usr/local/www/kostikov.co/bl-plugins/addtoany/languages/en.json): failed to open stream: No such file or directory in /usr/local/www/kostikov.co/bl-kernel/boot/rules/60.plugins.php on line 80
>
>Warning: file_get_contents(/usr/local/www/kostikov.co/bl-plugins/ads4u/languages/en.json): failed to open stream: No such file or directory in /usr/local/www/kostikov.co/bl-kernel/boot/rules/60.plugins.php on line 80
>
>Warning: file_get_contents(/usr/local/www/kostikov.co/bl-plugins/textarea/languages/en.json): failed to open stream: No such file or directory in /usr/local/www/kostikov.co/bl-kernel/boot/rules/60.plugins.php on line 80
>
>Warning: file_get_contents(/usr/local/www/kostikov.co/bl-plugins/yandextools/languages/en.json): failed to open stream: No such file or directory in /usr/local/www/kostikov.co/bl-kernel/boot/rules/60.plugins.php on line 80
>
>Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/kostikov.co/bl-kernel/boot/rules/60.plugins.php:80) in /usr/local/www/kostikov.co/bl-kernel/boot/rules/99.header.php on line 3

**Comment by clickwork-git** [comment]
Bludit 2 uses for the English language file en.json and for the Spanish language file es.json. These are a sort of standard language files. Besides these are still files as en_GB.json, en_US.json etc. possible.

But there has to be a file en.json.

**Comment by xm74** [comment]
I see. So simple copying old en_EN.json to en.json to save old and gain new versions compatibility must help.
