### ISSUE TITLE
v2.0: plugin checkbox alignment

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#509]
I found that for plugins checkbox options admin theme aligns text by right side of page instead left
![clipboard02](https://user-images.githubusercontent.com/18723664/31689872-2ee2b6be-b391-11e7-80a9-62c0e307a398.jpg)

**Comment by dignajar** [comment]
you need to check the form() method of the plugin, I made some changes on the structure on the CSS for the new version.

**Comment by xm74** [comment]
Got it. Fixed. Thanks, @dignajar!
