### ISSUE TITLE
v.2.0: "Undefined index" when saving existing category

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#526]
![clipboard04](https://user-images.githubusercontent.com/18723664/31769744-2b496652-b4d5-11e7-81ec-a6a9d75fbc97.jpg)

**Comment by anaggh** [comment]
Sorry it was the migration script again. Did not know that category key was compulsory. Pushed a fix.
`"category": ""` on the migration script.

**Comment by xm74** [comment]
Just tested new migration script and error gone. Thanks!
