### ISSUE TITLE
v2.0: Draft loaded instead page content when trying to edit

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#527]
1. Create any draft with text
2. Save it
3. Try to open any already existing page and you will get draft content.

Same happens when you trying to create one more draft.

**Comment by anaggh** [comment]
`Plugins -> Simple MDE -> Settings -> Autosave` Is it enabled? There is a bug with autosave currently.

**Comment by xm74** [comment]
@anaggh Yes it is.

**Comment by anaggh** [comment]
Autosave is very buggy. Better disable it.

**Comment by xm74** [comment]
@anaggh Got it. All works well after autosave was disabled. But anyway need to be fixed.

**Comment by anaggh** [comment]
Yup and this happens with all content not just drafts. @dignajar

**Comment by dignajar** [comment]
Is a bug on SimpleMDE?
I'm looking for an alternative to SimpleMDE, looks like is not more developed.

I have in my todoList a feature to create autosave for Bludit.

**Comment by dignajar** [comment]
I removed the function autosave of SimpleMDE.. Next version of Bludit I going to remove this SimpleMDE because is depracted and no longer supported.
