### ISSUE TITLE
Respect locale in date format

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#532]
I found that new Bludit v.2 contains the same problem with wrong locale date format which we saw in v.1 before. After little investigation I found that used PHP function date() doesn't respect current locale and pages always have english date output. But if there is special function strftime() works as it must.
Here is a little demonstration.

```
root@beta:/home/xm # echo "<?php setlocale(LC_ALL, 'ru_RU.UTF-8'); echo date('j F Y').PHP_EOL; ?>" | php
20 October 2017
root@beta:/home/xm # echo "<?php setlocale(LC_ALL, 'ru_RU.UTF-8'); echo strftime('%d %B %G').PHP_EOL; ?>" | php
20 октября 2017
```

So I believe that will be better to replace all usage of date() on strftime().

**Comment by clickwork-git** [comment]
Nice. I thought this has to to with the server settings.

**Comment by dignajar** [comment]
I don't use date() in any place, I created a Helper for dates, https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/date.class.php

I going to check again this class.

**Comment by dignajar** [comment]
Holy sh$#it http://php.net/manual/en/class.datetime.php doesn't support locales too... this is bad

**Comment by blog2read** [comment]
Please fix this problem ASAP - most themes are supporting languages but date is always in English - still in version 2.0.2. Thanks !

**Comment by clickwork-git** [comment]
By the way, there is a hack for this:

https://planet-bludit.ch/deutsche-monate-und-wochentage

**Comment by dignajar** [comment]
Working on it

**Comment by dignajar** [comment]
I'm looking the way to do this function with `strftime` format. The function `format()` can change the format date from `currentFormat` to the `outputFormat`

```
$date = '2017-12-15-22-00-00'
$currentFormat = '%Y-%m-%d-%H-%M-%S'
$outputFormat = '%a, %e %b %Y';
print format($date, $currentFormat, $outputFormat);
```

**Comment by anaggh** [comment]
Maybe this lib is useful ? https://github.com/fightbulc/moment.php

**Comment by dignajar** [comment]
I going to check, but is a pity use libraries to manipulate the dates on php.

**Comment by blog2read** [comment]
That is really good news - thanks a lot !

**Comment by dignajar** [comment]
Yesterday I create a workarround to this problem, I still using the DateTime class provide for PHP.

I added the months and day here, https://github.com/bludit/bludit/blob/master/bl-languages/en.json
and update the date.class.php, https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/date.class.php

**Comment by blog2read** [comment]
Thanks for looking into it.

Over here workaround seems not to work yet:

Fatal error: Uncaught Error: Call to undefined method dbLanguage::getDates() in /home/domain/public_html/enroute.tk/bl-kernel/helpers/date.class.php:61 Stack trace: #0

**Comment by dignajar** [comment]
You need to update this file, https://github.com/bludit/bludit/blob/master/bl-kernel/dblanguage.class.php

**Comment by blog2read** [comment]
Oh yes - seems to work now. **Great !**  BTW I updated /bl-languages/de_DE.json and /bl-languages/de_CH.json

**Comment by blog2read** [comment]
An other date/time question: In the dashboard the date/time format seems not to follow the language/timezone settings.

**Comment by dignajar** [comment]
maybe you can update with the latest files from github, I made some changes on the dashboard too about dates, but I'm not sure about your problem.

**Comment by blog2read** [comment]
Ok I downloaded the files. I meant the list of entries - there the date/time format isn't changed to the system format. 
https://i.imgur.com/2NhwxEv.png

**Comment by dignajar** [comment]
The format on the admin panel is not configurable, the format is for the website.

**Comment by blog2read** [comment]
Hi
I added the German day and month expressions in de_DE.json and de_CH.json. Where to upload them?

**Comment by dignajar** [comment]
I separated the variables on a different file and added the date format for Manage Content.

https://github.com/bludit/bludit/blob/master/bl-kernel/boot/variables.php#L72

**Comment by xm74** [comment]
Funny bug in latest v2.1 release. 
![screenshot-2017-12-29 bludit -](https://user-images.githubusercontent.com/18723664/34434769-10d4f838-ec91-11e7-9474-1a78273086d5.png)

**Comment by clickwork-git** [comment]
I do not understand, what is funny about it. Can you please explain it.

**Comment by xm74** [comment]
@clickwork-git 
It takes 3-letters month translation from language file and adds last part from English. 
In Russian it must look like "Декабрь"

**Comment by xm74** [comment]
I found the stupid solution to fix this behavior with substring replacement it month / day of the week  - just change order of dictionary pairs when full names listed before short ones (see as sample #592).

**Comment by dignajar** [comment]
I going to fix it :D

**Comment by dignajar** [comment]
Fixed, but I would like to check some performance for this script.

Here the solution
https://stackoverflow.com/questions/3426265/php-string-replace-match-whole-word

Here the changes
https://github.com/bludit/bludit/commit/8217d8b873cbebba95472d932dd7e19f3d921fa3

**Comment by xm74** [comment]
@dignajar 
I thought about preg_replace() but don't sure about performance impact with too.

**Comment by marekrost** [comment]
Couldn't all this be avoided simply by using [strftime](http://php.net/manual/en/function.strftime.php) instead of [date](http://php.net/manual/en/function.date.php) directly ?
