### ISSUE TITLE
Insert image to current cursor position

### ISSUE THREAD

**Issue by JonathanHolvey** [bludit/bludit#540]
When choosing to insert an image as markdown using the built in page editor, the code is appended to the end of the page. It would be much more user friendly if the current cursor position could be used instead.

**Comment by dignajar** [comment]
Good one.
You mean with SimpleMDE editor ? I need to check the docs from SimpleMDE, but this is the function called when an image is uploaded.
https://github.com/bludit/bludit/blob/master/bl-plugins/simplemde/plugin.php#L108-L110

**Comment by JonathanHolvey** [comment]
Yes, after checking, I mean SimpleMDE.

**Comment by dignajar** [comment]
Implemented in Bludit v3.1.0. Thanks!
