### ISSUE TITLE
[PLUGIN] Random Articles for sidebar

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#544]
Plugin to get randoms pages and show it on the sidebar.

**Comment by anaggh** [comment]
Created plugin - https://github.com/anaggh/random-pages

**Comment by clickwork-git** [comment]
Added to the repository.

**Comment by dignajar** [comment]
Thank @anaggh and @clickwork-git 

Here is the plugin
- https://plugins.bludit.com/plugin/random-pages

You can update the information about the plugin and your username @anaggh  here:
- https://github.com/bludit/plugins-repository/blob/master/authors/anaggh.json
- https://github.com/bludit/plugins-repository/blob/master/items/random-pages/metadata.json

**Comment by anaggh** [comment]
Okay! Will do for future plugins!

**Comment by naplaya** [comment]
@dignajar i think this issue can be closed
