### ISSUE TITLE
[THEME] Future imperfect for Bludit v2

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#545]
Port the below theme to Bludit v2.

https://html5up.net/future-imperfect

**Comment by Turqueso** [comment]
Made a version: https://github.com/Turqueso/Future-Imperfect

**Comment by dignajar** [comment]
@Turqueso nice one, I going to add to the repository.

**Comment by dignajar** [comment]
Done, now is on the repo and on the main page https://themes.bludit.com
I close the topic, thanks!
