### ISSUE TITLE
How can I embed Youtube Videos in Bludit v2.0.1?

### ISSUE THREAD

**Issue by AlexL777** [bludit/bludit#553]
Hi Developers,

is there a way to work with Bludit v2.0.1 with the Youtube videos or does the plugin shortcode have to be made compatible?

I wanted to embed in the content Youtube video and do not know how to realize that. The video should be displayed immediately.

Thanks in Advance.

**Comment by kaaleth** [comment]
You can use embed code, e.g.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/REyxoxScrbU?rel=0" frameborder="0" allowfullscreen></iframe>`

**Comment by dignajar** [comment]
Agree with @kaaleth.

You can go to the video on youtube, click on the button SHARE and you can copy the embed code.

<img width="1122" alt="screen shot 2017-11-01 at 16 07 16" src="https://user-images.githubusercontent.com/507352/32281381-f54609c6-bf1e-11e7-8359-e3b661d3f72f.png">

**Comment by AlexL777** [comment]
Yes, thank you both. It has already worked great with the inclusion of <iframe> code. The Youtube video is already displayed to me. Thus one can close the issue now.
