### ISSUE TITLE
How to update to 2.x keeping old posts

### ISSUE THREAD

**Issue by Turqueso** [bludit/bludit#573]
What would be the proper way to keeps all my post and upgrade to version 2?

---

So far this seems to work, in case someone as the same problem I had.
* Keep you bl-content folder.
* Rename posts folder to pages
* Rename posts.php to pages.php inside databases folder
* ~~profit~~ Done

**Comment by dignajar** [comment]
Have you tried with the migration tool from @anaggh ?
https://github.com/anaggh/bludit-scripts/tree/master/migration

**Comment by dignajar** [comment]
What you can do is copy all the files to a new folder for example `/bludit-test/` then try to update this one and is ok then do the same with the original.
