### ISSUE TITLE
White screen after update

### ISSUE THREAD

**Issue by blog2read** [bludit/bludit#587]
After last git upgrade to 2.1.0 / 20171226 I have simple white screen.

Seems something changed with themes use - only with "Kernel Panic" I have something on the screen. In error_log I can't see something.

So what would be necessary to change in the used theme?

As I see now - only "Kernel Panic" is the theme folder - all other removed? Why?

**Comment by dignajar** [comment]
I just update some fixes to github. I going to create the release from there.

**Comment by blog2read** [comment]
Thanks for your input. I am using theme Lingonberry - so there are something to change/add, too ?

**Comment by dignajar** [comment]
I think is not a problem of the theme, there was some problems with the dictionaries, can you test this release ? https://github.com/bludit/bludit/releases/tag/2.1

**Comment by blog2read** [comment]
No sorry, Lingonberry doesn't work any more.

**Comment by blog2read** [comment]
And with theme micro I get error message:

Fatal error: Uncaught Error: Call to a member function permalink() on boolean in /home/domain/public_html/site.tld/bl-themes/micro/php/sidebar.php:14 Stack trace: #0 /home/domain/public_html/site.tld/bl-themes/micro/index.php(18): include() #1 /home/domain/public_html/site.tld/bl-kernel/boot/site.php(25): include('/home/domain/...') #2 /home/domain/public_html/site.tld/index.php(38): require('/home/domain/...') #3 {main} thrown in /home/domain/public_html/site.tld/bl-themes/micro/php/sidebar.php on line 14

**Comment by dignajar** [comment]
yeap, a problem on the themes.. sorry.
I fixed Lingoberry, download from here the version 1.1. https://themes.bludit.com/

**Comment by blog2read** [comment]
Ok, thanks, it works again. And what did you change exactly?
