### ISSUE TITLE
Plugin "Static Pages" - Notice: Undefined variable: keys in /static-pages/plugin.php on line 63

### ISSUE THREAD

**Issue by AlexL777** [bludit/bludit#588]
Hello Developers,

Today I made an update to the very last Bludit CMS version, but there are error issues from the static pages in the frontend.

The errors are as follows:

`Notice: Undefined variable: keys in /xxxxxxxxxx/bludit.liebrechts-portfolio.de/bl-plugins/static-pages/plugin.php on line 63`

`Warning: Invalid argument supplied for foreach() in /xxxxxxxxxx/bludit.liebrechts-portfolio.de/bl-plugins/static-pages/plugin.php on line 63`

I use Centos 7.4, PHP 7.1 and MariaDB 10.2. Should actually be fine with this hosting.

Then maybe you can help me.

Thanks in Advance.

**Comment by dignajar** [comment]
FIxed! thanks

**Comment by dignajar** [comment]
Change this file, https://github.com/bludit/bludit/commit/2097847b7ab8586289ed5c5908fd546e735786d3

**Comment by AlexL777** [comment]
Thanks for this!
