### ISSUE TITLE
Dashboard error message

### ISSUE THREAD

**Issue by blog2read** [bludit/bludit#589]
In dashboard on the right side under "Drafts" I get an error message:

`Notice: Undefined variable: keys in /home/domain/public_html/site.tld/bl-kernel/admin/views/dashboard.php on line 161`

`Warning: Invalid argument supplied for foreach() in /home/domain/public_html/site.tld/bl-kernel/admin/views/dashboard.php on line 161`

**Comment by dignajar** [comment]
Fixed, thanks for reporting it.
Here the fix: https://github.com/bludit/bludit/commit/c42f1e76834dc5272107f775c225c12a7b5f33a8
