### ISSUE TITLE
Bludit 2.1 - Drafts are not displayed in the Backend

### ISSUE THREAD

**Issue by AlexL777** [bludit/bludit#590]
Hi Developers,

Today I noticed in the backend that drafts are not displayed.

I only see these mistakes.

    ENTWÜRFE

    Notice: Undefined variable: keys in /xxxxxxx/iebrechts-portfolio.de/bludit.liebrechts-portfolio.de/bl-kernel/admin/views/dashboard.php on line 161

    Warning: Invalid argument supplied for foreach() in /xxxxxxxx/liebrechts-portfolio.de/bludit.liebrechts-portfolio.de/bl-kernel/admin/views/dashboard.php on line 161`

Maybe you look at it at times.

Thanks in Advance.

**Comment by blog2read** [comment]
I reported this and it was fixed - you should upgrade your installation.

https://github.com/bludit/bludit/issues/589

**Comment by AlexL777** [comment]
Thanks for this 👍
