### ISSUE TITLE
[DEMO] Create a site for Scalability test

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#593]
A Demo with 10.000 pages.

**Comment by anaggh** [comment]
https://github.com/anaggh/bludit-scripts/tree/master/scalability-test

Tested it with v2.3.3 Bludit with 10,000 pages

### Observations:

#### Slow/Inaccessible:

Probable cause: Parent page select box

* New Content
* Edit Content

Probable cause: Predefined pages select box

* Settings -> Advanced

**Comment by dignajar** [comment]
Nice one.
You are talking about the admin panel, yeap for sure is the parent selector. I'm working on the new interface for the admin panel and I have this bug in mind.

**Comment by koreos** [comment]
Amazing! Really HUGE website without MySql :-)

**Comment by koreos** [comment]
I tried to test with 9000 pages and server stop and gave message:
504 Gateway Time-out
The server didn't respond in time.

**Comment by koreos** [comment]
But during this test, another my big websites on the same server worked very good and very fast. And this is normal basic server - shared host.
