### ISSUE TITLE
SimpleMDE: Problem posting code

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#594]
There is a problem posting code with SimpleMDE (I don't know if the problem is related to SimpleMDE or Bludit).

When posting the following I get the error 403:

https://www.dropbox.com/s/tg46gm0ziol4nsv/code-example.txt?dl=0

Parts of the content can be posted without any problem, but not the whole.

It works creating the file index.txt in the directory of the content.

**Comment by dignajar** [comment]
Hi Edi,
I create the page via SimpleMDE and creating the index.txt with the code-example.txt but I don't find the bug.

Also, I tried on the demo, and works fine, can you test ?

https://demo.bludit.com/blog/admin

**Comment by clickwork-git** [comment]
I will have a look at it. Perhaps the problem was caused using an updated installation.

**Comment by clickwork-git** [comment]
It seems that the problem is caused by security rules of the hoster. I happens, when there is a snippet with PHP for example like this:

`<?php echo $Language->get('Address'); ?>`

**Comment by clickwork-git** [comment]
The problem was related to the firewall, and could be solved by adding an exception to the file .htaccess.

**Comment by dignajar** [comment]
Interesting, can you share the exception added to the .htaccess ?, could be useful for other users. thanks

**Comment by clickwork-git** [comment]
The addition is related to a security rule of the Web Application Firewal of the hoster.

In this case the hoster has to be contacted.
