### ISSUE TITLE
Subpages problem

### ISSUE THREAD

**Issue by ruiborgespaninho** [bludit/bludit#603]
Hello,

I'm trying to execute this little snippet found on documentation:

```
$staticPages = buildStaticPages();

foreach ($staticPages as $page) {
    if ($page->title() == 'page2') {
        $subpages = $page->subpages();
        if (empty($subpages)) {
                echo 'The page has not subpages';
        } else {
            foreach ($subpages as $pageKey) {
                // buildPage function returns a Page-Object
                $subpage = buildPage($pageKey);

                echo 'Subpage title: ' . $subpage->title();
            }
        }
    }
}
```

result:

`Fatal error: Uncaught Error: Call to a member function title() on boolean`

I only have static pages:

pages
├── page1
├── page2
├───└── feature1
├───└── feature2

Can you help me pls ?

**Comment by clickwork-git** [comment]
This snippet was posted in the forum and works for me:

```
<?php

foreach ($pagesByParent[PARENT] as $Parent) {

	// $Parent is a Page Object
	echo 'Parent title' . $Parent->title();

	// Check if the parent has sub-pages/children
	if (!empty($pagesByParent[$Parent->key()])) {

		// Foreach sub-page/children
		foreach ($pagesByParent[$Parent->key()] as $Child) {

			// $Child is a Page Object
			echo 'Child title' . $Child->title();
		}
	}
}
```

[https://forum.bludit.org/viewtopic.php?p=4355#p4355](https://forum.bludit.org/viewtopic.php?p=4355#p4355)

**Comment by dignajar** [comment]
Hi @ruiborgespaninho, there is a bug, because Bludit does not support Subpages on Subpages, reported by @clickwork-git here https://github.com/bludit/bludit/issues/604.

Anyway, I going to check the first snippet code.
