### ISSUE TITLE
Parent/child issues

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#604]
The following is possible at the moment (but should not be):

1. Adding a child page to a child page.
2. Adding a child page to a static page.

**Comment by Joduai** [comment]
Just wanted to pop up an issue with setting a parent.

@dignajar  @clickwork-git 
Why it is not possible to set a parent to a default page type, when parent page is  static?
What's the sense of having a possibility to set a parent for a default page type only for the same default page type?

There's not even a way to set a static parent for a static page?
The option to set a parent is completely broken.

Could you point me where should I search in bludit's code to get rid of any conditionals and unblock this function? Parent added manually is cut during save.
