### ISSUE TITLE
[BRAIN STORM] Content, Pages, Posts, Static...

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#614]
I'm looking for the best way and simple way to order the content on Bludit, such as names, how to select this kind of pages, etc..

# Content
In this moment Bludit provides this kind of content:
- Pages
- Static Pages

## Pages
- Appear on the main page.
- Ordered by **position** or by **date**, you can define this in **settings**.
- Allow subpages

## Static Pages
- Doesn't appear on the main page, are hidden, only access by permalink.
- Ordered by **position**
- Allow subpages (I would like to remove this feature)

# How to create a Blog
- Bludit out of the box the content is ordered by Date. 
- You don't need to do anything, just create new pages.

# How to create a Website
- Change the order by position (this is not obligatory).
- Create the pages you would like to show on the main page.
- Create Static pages, such as `About` or `Contact`, this kind of page do not need to appear on the main page, just a link to them.

**Comment by clickwork-git** [comment]
What about **posts** and **pages**?

### Posts
- _Pages_ will become _posts_.
- Ordered by date.
- Posts cannot have subpages.

### Pages
- _Static pages_ will become _pages_.
- Ordered by position.
- Pages can have subpages.

By the way: This would it make easier coding themes and assign plugins.

**Comment by Torsten-K** [comment]
In Bludit Version 2.2.1, sub pages for static pages are no longer possible from the backend. This makes Bludit unusable as a CMS (not a blog system) for me. Very disappointing.

**Comment by clickwork-git** [comment]
> This makes Bludit unusable as a CMS (not a blog system) for me.

We often explained that Bludit can be used as blog (with additional static content, that can be used for pages as "About", "Contact" etc.) or as CMS (with pages and subpages).

If you want a CMS and a blog you can do this with two installations linked together.

**Comment by Torsten-K** [comment]
But in the right sidebar in the admin panel under Parent, there is no parent choosable, it is grayed out, and it wasn’t in 2.1.x.

**Comment by clickwork-git** [comment]
Yes, because static content is a sort of additional or special content. It can be used with a blog for static pages. But depending from the theme it can also be used for example as sector in a one page site, or in the header or the footer.

Perhaps it should be renamed, because static content is not only another page.

**Comment by Torsten-K** [comment]
Understood. I should have defined my pages as _Published_, not _Static_. So, everything’s fine, thanks for the clarification.

Renaming: Maybe _Additional content_ or something.

**Comment by Torsten-K** [comment]
I’m sorry for annoying you, but I can’t understand why you are building a system that can be a CMS **or** a blog instead of the ability to be a CMS **and** a blog.

And, yes, many business websites do have a corporate blog within their (conventional) website (and no, not only my own websites).

I wonder if it could be possible to program Bludit in a way that normal pages can be sorted by position, but a special area (the blog or news section) can be sorted by date. Other content management systems do this by different page templates, as far as I understand it. So, could this be done in Bludit via themes, if not in the core? Just an idea, which might be discussed.

**Comment by clickwork-git** [comment]
Bludit can be used for a **blog**, a **CMS** or a **blog with additional pages (static content)**.

But my experience is: Most of the people want a website or a blog. And in addition to this, it has to be easy to understand.

**Comment by Torsten-K** [comment]
Yes, but the pages (static content) can have no sub pages any longer. 

I agree that a CMS should be easy to understand. And that’s the reason why I hate monsters like Typo3 or Contao.

The fact is: I have tried much more than 100 content management systems, and they all have their strengths and limitations, of course. Bludit is one of the best, in my opinion. But it would only be perfect for my needs, if the blog pages and the static content pages both could be cascaded (have sub pages), and additionally could be sorted in different ways. That would be THE killer CMS/Blog system.

**Comment by clickwork-git** [comment]
Then use two installations and link them.

**Comment by hubbyist** [comment]
Two installations will make content management harder.

**Comment by dignajar** [comment]
I agree with both approaches, but if we allow the static pages can have subpages, is going to be harder to do themes or plugins, more conditionals, etc.

For me is easier to have 2 installations (is only 2MB extra), in each installation you can have different theme and plugins running, and the developers do not need to think too much in conditionals (such as, where is the user now, in the blog or in the website).

**Comment by Torsten-K** [comment]
But would it be possible for you to program Bludit in the way that the published pages could be sorted by position, and the blog articles (published pages under /blog/ or whatever) could be sorted by date?

**Comment by clickwork-git** [comment]
> But would it be possible for you to program Bludit in the way that the published pages could be sorted by position, and the blog articles (published pages under /blog/ or whatever) could be sorted by date?

This is explained here:

https://forum.bludit.org/viewtopic.php?f=6&t=1092

An other solution is, to add a template with a condition for `/blog`. But in this case also the paginator has to be modified.
