### ISSUE TITLE
[PLUGIN] update API plugin  with categories, cover image and tags

### ISSUE THREAD

**Issue by Sirjoseph94** [bludit/bludit#617]
Since the platform has evolved over time, i think it should also reflect on the API. this would be a very useful addition to make integration much better.

**Comment by dignajar** [comment]
- Cover image, https://github.com/bludit/bludit/blob/master/bl-kernel/page.class.php#L301-L302

**Comment by Sirjoseph94** [comment]
Thanks for listening, let me check it out

**Comment by Sirjoseph94** [comment]
There seems to be no endpoint for the cover image in the API

**Comment by dignajar** [comment]
I don't follow you, what you mean?

`coverImage` returns the absolute URL and `coverImageFilename` returns the filename.

**Comment by dignajar** [comment]
I do not have so many experiences on API, any recommendation is welcome.

**Comment by Sirjoseph94** [comment]
Oh, i downloaded the wrong release. Its working as expected. I also included Categories to it. Here is my adjusted  code.

```
   $tmp['category'] = $this->category();
   $tmp['cover'] = $this->thumbCoverImage();

```

**Comment by Sirjoseph94** [comment]
Thanks

**Comment by dignajar** [comment]
@Sirjoseph94 leave it open so I can remember and improve the API.

**Comment by Sirjoseph94** [comment]
Oh okay.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
