### ISSUE TITLE
Problem with categories (non ASCII)

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#636]
Seems that there is a problem with categories when using non ASCII characters:
 
https://forum.bludit.org/viewtopic.php?f=6&t=1082

**Comment by dignajar** [comment]
The problem is the Unicode characters, when the function cleanURL returns empty and the category is not created.

Solution: Enable EXTREME_FRIENDLY_URL=true

Related ticket: https://github.com/bludit/bludit/issues/655

**Comment by dignajar** [comment]
Implemented for Bludit v3.0.0, allow Unicode characters in the system.
