### ISSUE TITLE
Add Upload shortcut on theme.class.php

### ISSUE THREAD

**Issue by ViriisXP** [bludit/bludit#640]
Hello, i do it for my theme, but maybe you can put by yourself into the next update 👍 

`	public static function upload($titre)
	{
		return '<img src="bl-content/uploads/'.$titre.'.png" alt="'.$titre.'"/>';
	}
`

and on my theme `echo Theme::upload($titre);`

**Comment by dignajar** [comment]
Hi,
why you need this method ?

**Comment by ViriisXP** [comment]
i do this : 

`						<?php
								// On affiche les pages de gestion
	       $categoryKey = 'gestion';
        $category = getCategory($categoryKey);
        foreach ($category->pages() as $pageKey) {
                $page = buildPage($pageKey);
																
																if (($page->title()) === '#newgame'){
																		echo '<article id="newgame">';
																		echo '<h2 class="major">Nouvelle partie</h2>';
																	 echo '<div id="grid" class="affichage">';
																				$categoryKey = 'jeux';
																			$category = getCategory($categoryKey);
																						foreach ($category->pages() as $pageKey) {
																						$page = buildPage($pageKey);
																							$titre = $page->title();
																							if ($page->permalink() === "http://".$_SERVER['SERVER_NAME'].'/newgame/'.$titre){
																											echo '<div class="view">';
																														echo '<div class="view-back">';
																															echo '<span><i class="fas fa-user"></i>  3 &agrave; 9</span>';
																															echo '<span><i class="fas fa-child"></i>  12 et +</span>';
																															echo '<span><i class="fas fa-clock"></i>  30"</span>';
																															echo '<a href="#play" onclick="play(\''.$titre.'\')" >&rarr;</a>';
																														echo '</div>';
																													echo Theme::upload($titre);
																												echo '</div>';
																							} // endif permalink
																						} // end foreach
																	echo Theme::js('assets/js/grid.js');
																	echo '</div>';
																	echo '</article>';
																} // Endif newgame
																else
																{
																	$titre = substr($page->title(),1);
																		echo '<article id="'.$titre.'">';
															    echo $page->content();
																	 echo '</article>';
																}
        							} // endif newgame
						?>`

**Comment by dignajar** [comment]
You can use cover images for each page.

```
echo '<img src="' . $page->coverImage() . '" />';
```

**Comment by dignajar** [comment]
You can set a cover image when you are creating the page, on the right sidebar, images.

**Comment by ViriisXP** [comment]
haha ! OK ! perfect ! did you have a contenttable of each available request on bludit ?
to don't have to search.

**Comment by dignajar** [comment]
I try to upload this information in the documentation (https://docs.bludit.com) and on the forum (https://forum.bludit.org)
