### ISSUE TITLE
Additional field for tag <title>

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#641]
Additional field for custom entries for the tag `<titel>` (in addition to the field "Description").

See for example the following explantion:

https://support.google.com/webmasters/answer/35624?visit_id=0-636548378973071192-1254707671&rd=1

See also the forum at

https://forum.bludit.org/viewtopic.php?f=14&t=1100

**Comment by koreos** [comment]
Yes it's very important for SEO!

**Comment by koreos** [comment]
Also additional field for H1 will be very good!

**Comment by dignajar** [comment]
Implemented for Bludit v3.0.0.
Settings->General->Title formats
