### ISSUE TITLE
[PLUGINS] RSS feed add option to name feed [request]

### ISSUE THREAD

**Issue by podbiker** [bludit/bludit#645]
Feedly names the feed "RSS-Feed" when it is added as a new feed. Site url or site title are ignored.

Please add an option to "RSS Feed" plugin settings to set site title as feed name or to customize it.

**Comment by dignajar** [comment]
Hi,
the title is getting from the site title, here https://github.com/bludit/bludit/blob/master/bl-plugins/rss/plugin.php#L53

**Comment by podbiker** [comment]
Then Feedly seems to ignore that.

**Comment by dignajar** [comment]
Hi, I just want to know if what you are requestion? if not I would like to know.
