### ISSUE TITLE
Install.php expects email address, but the user is never asked for one. 

### ISSUE THREAD

**Issue by chumstick** [bludit/bludit#650]
Every time the install.php page is run this error is logged:

`[Thu Mar 01 00:51:12.126826 2018] [:error] [pid 5741] [client 10.0.1.41:49067] PHP Notice:  Undefined index: email in /var/www/bludit/install.php on line 509, referer: http://[TLD]/install.php?language=en`

It tries to pass an email parameter, but it's invalid because the user is never asked to input their email. Very minor, and doesn't seem to have any adverse affect on the installation process.

**Comment by dignajar** [comment]
Fixed, https://github.com/bludit/bludit/blob/master/install.php
