### ISSUE TITLE
[PLUGIN / CORE] Integration with Mailgun

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#651]
- Send an email through Mailgun.
- Contact plugin via Mailgun or defualt email system.
- Login mail via mailgun.
- Newsletter plugin.

**Comment by anaggh** [comment]
Duplicate https://github.com/bludit/bludit/issues/858

**Comment by dignajar** [comment]
Is not complete duplicated, the ticket #858 is for Newsletter and this tickets has 3 points more.
