### ISSUE TITLE
[CORE / PLUGINS / THEMES] EU General Data Protection Regulation (GDPR)

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#665]
Core, plugings and themes have to be reviewed and adapted to meet the requirements of the new law.

The EU GDPR will become enforceable on 25 May 2018.

**Comment by dignajar** [comment]
I need to apply this law for distribute the software in EU ? Also, Bludit is an open source project non profit is necessary too ? Thanks

**Comment by clickwork-git** [comment]
Yes. At the moment I still collect more information. I will add it to a sort of repository in the next few days, and try to point out the requirements,

There is for example a discussion about using Google webfonts as CDN, because they transfer data to the US. German lawyers say, that this is no longer allowed. But there is also the Data Protection Shield that would allow it in my opinion. It's very confusing.

**Comment by clickwork-git** [comment]
I started a wiki at

https://github.com/clickwork-git/EU-GDPR/wiki

**Comment by dignajar** [comment]
To Do:
- Include Cookies Concent on Bludit package.
- Split Google plugin in different tools (Google Analytics, Google Tag, etc).

**Comment by clickwork-git** [comment]
A Cookie consent is only mandatory, if a Cookie script like Google Analytics is used. Therefore it should be combined and work as follows:

* Opt-in (Yes): enable script.
* Opt-out (No): disbale script.

In addition to this there should be a log of the IPs with consent.

And there must be a page where the user can revoke his decision.

**Comment by dignajar** [comment]
I created a new plugin called `Google Analytics` (https://github.com/bludit/bludit/tree/master/bl-plugins/google-analytics) with a few changes for GDPR, if this is a good approach we can use it for other plugins.

**Comment by dignajar** [comment]
@clickwork-git as we talk via chat.

- Cookie `BLUDIT_EU_GDPR_CONCENT` = `true` or `false`, for plugins to know if the user can be tracked. I mean tracked to enable Google Analytics for example or similar.

- On Admin Panel > Settings > Advanced > EU General Data Protection concent > `Enable` / `Disable`

- if the administrator `Enable` this config, is going to show a dialog to the users to `allow` or `deny` be tracked by the site. if the user select `allow` the cookie `BLUDIT_EU_GDPR_CONCENT` = `true`, if the user select `deny` the cookie `BLUDIT_EU_GDPR_CONCENT` = `false`

- if the administrator `Disable` this config, is not going to show any kind of dialog. The cookie takes the value `BLUDIT_EU_GDPR_CONCENT` = `true` all the time.

**Comment by dignajar** [comment]
I close this topic for the moment if we need to do some changes more just open a new issue.
