### ISSUE TITLE
[Core] enctype="multipart/form-data" option form

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#666]
See request in the support forum:

[enctype="multipart/form-data" Option form](https://forum.bludit.org/viewtopic.php?f=13&t=1125)

**Comment by dignajar** [comment]
Added: https://github.com/bludit/bludit/blob/master/bl-kernel/admin/themes/default/init.php#L47

You need to send the type.

```
HTML::formOpen(array('id'=>'example', 'enctype'=>'multipart/form-data'));
```
