### ISSUE TITLE
[Core] More hooks in admin

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#667]
Request in the support forum:

[More hooks in admin](https://forum.bludit.org/viewtopic.php?f=13&t=1119)

**Comment by dignajar** [comment]
I add a few more.
https://github.com/bludit/bludit/commit/9b30b9aff6d5e747b8d5c27f49938332ef5d839f

**Comment by dignajar** [comment]
If you need more @Fred89 please create an issue and where you need this hooks. thanks

**Comment by devprodest** [comment]
Make a hook "AfterPublishing", please. =)

For use at autoposting plugins.

**Comment by dignajar** [comment]
@devprodest 
there is a hook called `afterPageCreate` make sense for your request ?
