### ISSUE TITLE
[PLUGIN] Sitemap XML problem

### ISSUE THREAD

**Issue by koreos** [bludit/bludit#675]
I installed 2.3.3 Bludit and in sitemap plugin I have only Sitemap URL, button Save and Cancel and nothing more. When I click Save button I can see message "Complete all fields". But I can't see any fields..

**Comment by dignajar** [comment]
the buttons are not necessary, I going to remove it from this plugin.
The settings only shows the URL of the sitemap.

**Comment by dignajar** [comment]
Done, here https://github.com/bludit/bludit/commit/e3536a9e2e8556aa8aba000190d9255a566b7fbd

**Comment by koreos** [comment]
1. But what when I will have for example 5000 subpages? It can't be only one sitemap.xml file because its too big.
2. What about priority settings?

**Comment by koreos** [comment]
Sorry, 50 000 subpages. https://www.sitemaps.org/en_GB/faq.html
How big can my Sitemap be?
Sitemaps should be no larger than 50MB (52,428,800 bytes) and can contain a maximum of 50,000 URLs. These limits help to ensure that your web server does not get bogged down serving very large files. This means that if your site contains more than 50,000 URLs or your Sitemap is bigger than 50MB, you must create multiple Sitemap files and use a Sitemap index file. You should use a Sitemap index file even if you have a small site but plan on growing beyond 50,000 URLs or a file size of 50MB. A Sitemap index file can include up to 50,000 Sitemaps and must not exceed 50MB (52,428,800 bytes). You can also use gzip to compress your Sitemaps.

**Comment by dignajar** [comment]
I don't have experience with splitting sitemap, anyway in the issues you created you don't mention this kind of request, you just say there was a problem.

The plugin is basic, maybe you can create a new issue with the requests or features to implement, also information about them, or maybe you can do it?
