### ISSUE TITLE
[CORE] Pages, Blog, News separated

### ISSUE THREAD

**Issue by koreos** [bludit/bludit#679]
It will be very useful to see in admin panel separated system of Pages, Blog and News. 
Sometimes is need only Pages or only Blog on the website and sometimes everything.

**Comment by dignajar** [comment]
Hi, long disscucion about this topic, for the moment to keep simple Bludit only support pages and there is a feature with support some kind of hidden pagan called static pages (to create some kind of contact page or about page).

You can work with pages as posts and static pages as pages.

Or if you have a big project like website and big blog, just make 2 installations of Bludit, is only 2MB each one, and you can configure both with different themes or plugins.

Regards

**Comment by koreos** [comment]
Hi, Bludit is really fantastic but I can see that only for Blogs because every pages are in one place in admin. And this is difficult to manage, and static pages have not subpages. Really, more people will be interested Bludit if it will have separated Pages, Blog and News - it can be also for small websites. 

It will give You more sponsors and donates!

ps. It is very very good that You interested GDPR!

Regards

**Comment by clickwork-git** [comment]
As @dignajar mentioned, you can use content as posts and static content as pages for a blog with pages.

Also you can configure a blog (by default) or as website with pages and subpages.

And yes, you can have two installations, one configured as blog and one as website.
