### ISSUE TITLE
[CORE] Autosave via Ajax

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#681]
Implement via Ajax autosave the progress.
- Save meanwhile as a draft?

**Comment by marekrost** [comment]
I could really appreciate this feature when writing posts. Especially when travelling or when at-risk of losing internet connectivity.

Please consider extending this further by showing status information on the edit page:
- timestamp of the last draft autosave
- warning if connection was lost or user was de-authenticated 

This would help a lot in those situations when clicking "Save" button erases all your work on an article.

**Comment by dignajar** [comment]
Hi,
I’m working on it, I developed the part of the auto save, but the ideas in your comment are very good, I going to implement them.
Thanks

**Comment by dignajar** [comment]
Implemented in v3.0.0 Alpha 4.
