### ISSUE TITLE
[Plugin] Comments

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#685]
Name: Comments or some fancy name

Idea:
Create a file for each page to store the comments.
- filename: the same as the key page
- the content of the file could be an array serialized to JSON.
- the new comments are inserted at the end or at the beginner? We need to think about if going be displayed from newer to old or from old to newer and try to focus en the best to keep performance.

Hooks
- `afterPageCreate` create the file with empty structure
-`afterPageModify` check if not was edited the key
- `afterPageDelete` delete the file with the comment for the page deleted
- `pageEnd` load the file for the comments

Settings
- Template for comments
- Order by older to newer / newer to older
- Date format

**Comment by clickwork-git** [comment]
To be GDPR compliant is has to be possible to delete on request the comments of a user (name and e-mail are personal data).

**Comment by dignajar** [comment]
That is going to be a problem, I mean is going to be hard to develop, but for the moment maybe is possible to request a nickname and the comment, or use some authentication via GMail or Facebook, so the data is not stored in Bludit.

**Comment by maurorappa** [comment]
This would be very useful!!

**Comment by Joduai** [comment]
Howdy guys

Just popped up to ask how are things going with implementing discussed commenting plugin?

Found bludit couple days ago and after testing several dozen flat file CMS-es, this one suits perfectly for a personal blog I'd want to launch. And it lacks only an internal commenting system.

**Comment by ltGuillaume** [comment]
@Joduai Currently there are three alternatives I've found:
- Using Disquz with the Disquz plug-in (already included with the base package)
- Using Vanilla Forums as comment system via https://github.com/clickwork-git/vanilla
- Using ISSO via https://git.mal-richtig.de/maxmalrichtig/bludit-isso-client (hasn't been updated in a year, though)

**Comment by Joduai** [comment]
@ltGuillaume 
>  Currently there are three alternatives I've found:

Thanks for mentioning, but I'm aware of all three of them, as I was searching if something else than disqus plugin exist. 
Unfortunately all available commenting solutions don't come as working out of box with bludit.
Kludge raised this issue on bludit's forum: https://forum.bludit.org/viewtopic.php?t=774 long time ago so I won't duplicate the reasons why a blogging platform needs an internal comment system.

Maintaining additional software which vanilla only for a comment purpose doesn't make sense for a simple blog. Not to mention it's a database driven piece of software, thus a flat file blog platform loose its sense.
As it goes to isso, bludit has only a connector_like plugin to isso server. This solution won't work on a shared hosting environment, and even with a shell access I'm afraid the restrictions would be too high.

**Comment by ltGuillaume** [comment]
> Maintaining additional software which vanilla only for a comment purpose doesn't make sense for a simple blog. Not to mention it's a database driven piece of software, thus a flat file blog platform loose its sense.

@Joduai I completely agree

> As it goes to isso, bludit has only a connector_like plugin to isso server. This solution won't work on a shared hosting environment, and even with a shell access I'm afraid the restrictions would be too high.

Yeah I suspected this when I had a quick peek at it earlier today. Pretty useless then, indeed.

**Comment by abdulhalim** [comment]
Oh, the built-in commenting system is my dream.
Disqus has some problem, it banned in some country just like in my country, it's LTR, a lot of people use RTL language, and the main problem is it slows down the Bludit.

As @Joduai said using vanilla forum just for the commenting system doesn't make sense.

Bludit is very easy to install and to work with, but installing Isso for regular users are the pain in the ass
