### ISSUE TITLE
[PLUGIN] Parsedown Extra

### ISSUE THREAD

**Issue by qwertygc** [bludit/bludit#688]
Hi!

I want use bludit. But, we don't have the parsedown extra option, only parsedown. It's possible to add Parsedown extra, for example, with a plugin ?

Regards,

qwerty

**Comment by dignajar** [comment]
Hi, yes is possible, let me work on it and I going to upload.

**Comment by qwertygc** [comment]
Oh think ! It's fantastic !

**Comment by dignajar** [comment]
Done, download from here, https://github.com/bludit-plugins/parsedown-extra/releases/tag/parsedown-extra-1.0

**Comment by qwertygc** [comment]
Think, it's great !

**Comment by qwertygc** [comment]
We have a little bug with the footnote : 
![capture d ecran_2018-04-24_10-59-02](https://user-images.githubusercontent.com/4261986/39177023-85fbbf8e-47ae-11e8-890c-1b1886b4f7f0.png)

**Comment by dignajar** [comment]
Hi @qwertygc was open again this ticket there is some problem with the plugin? I don't see the relation the footnote with the plugin
