### ISSUE TITLE
Gender specifc texts in the admin panel

### ISSUE THREAD

**Issue by SanBen** [bludit/bludit#690]
In the admin panel certain texts are gender specific.

> - _Delete the user and associate **his** pages to admin user_
> - _Delete the user and all **his** pages_

Replace with _they_/_their_

I noticed while editing a user that is a woman, confused me slighty for a second because I thought it was the wrong user.

**Comment by dignajar** [comment]
I modified for:

- `Delete user and keep content`
- `Delete user and delete content`

Make sense?
