### ISSUE TITLE
New editor role or edit current one

### ISSUE THREAD

**Issue by davede-git** [bludit/bludit#692]
Hello,

Bludit offers two in-built roles: admin and editor. The second one has limited functions that is good but I think there should be something to block its articles before publish. Something like verify system, but I think the way can be much easier. 

So there is my wish. I would like to see third role or edit second one and remove "publish" button for it. A person who is Editor would be possible to save post as draft only. Then, Administrator can log into ACP and check post, then change the status from draft to published. 
 
The ideas:
1. Create a third role like Junior Editor that can send drafts only and only admin and editor can publish its posts.

OR

2. Disable publish button for Editor.

Why? I would like to have a control, what is coming to my website.

**Comment by naplaya** [comment]
maybe its better if roles were generaly maintainable. means admins could create own roles and give them the permissions they need.

**Comment by BlakesHeaven** [comment]
I agree,
> maybe it's better if roles were generally more maintainable. means admins could create own roles and give them the permissions they need.

It would, of course, be a major undertaking, needing careful scoping/planning, and would impact the whole product right to its core, **but** I'd say this is necessary for Bludit to move into larger multi-person team operations. 

May ways to skin a cat, but how about Bitwise; i.e a field against each role with a value of eg, 11000110011001, where each position (with 1 or 0) represents an objects permission being on or off.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
