### ISSUE TITLE
Missing (some) translation strings

### ISSUE THREAD

**Issue by davede-git** [bludit/bludit#693]
Since some versions I see the same issue. Some of translation strings are missing. This is what I've found:

1. Inside of markdown editor I can see some tips written in... spanish(?) language.
![jeden](https://user-images.githubusercontent.com/3610174/40280916-7cd022a4-5c5a-11e8-85de-64f1aea685d8.png)

2. While user editting at the end of the page.
![dwa](https://user-images.githubusercontent.com/3610174/40280938-d7db3364-5c5a-11e8-94a3-57b61eb66fa4.png)

3. "About" page.
![trzy](https://user-images.githubusercontent.com/3610174/40280949-06047160-5c5b-11e8-968e-21b2ec55eb2c.png)

Of course, that's not a problem, but if the Bludit is going to be perfect then... it would be cool to complete it. 👍

**Comment by clickwork-git** [comment]
The first issue will be fixed in the next version.

Meanwhile you can exchange the following file:

https://github.com/bludit/bludit/blob/master/bl-plugins/simplemde/languages/en.json

Please see the forum:

[SimpleMDE is stuck on Italian?](https://forum.bludit.org/viewtopic.php?f=6&t=1149)

**Comment by dignajar** [comment]
Bugs fixes on Bludit v3.0.0
