### ISSUE TITLE
admin page - file not found

### ISSUE THREAD

**Issue by nicedreams** [bludit/bludit#694]
Recently found Bludit CMS and want to try it out.  I have a home Nginx server running some other local testing sites and created a directory for bludit and unzipped the files in there.  Changed the permissions to www-data and install depends via apt.

I can go to the site just fine and it says it installs, but when I try to go to the admin page I get "file not found" @ bludit/admin.   I don't even see an admin directory in the file structure.

Don't know what to try next.  Found this issue from 2015, but don't know if it's related since long time ago.
https://github.com/bludit/bludit/issues/85

Maybe something with the .htaccess file since I'm using Nginx?  I'm not a Nginx expert, but guessing its something to do with that.

**Comment by clickwork-git** [comment]
There are some explanations relating Nginx in the documentation:

https://docs.bludit.com/en/webservers/nginx

**Comment by clickwork-git** [comment]
Does it work now?

**Comment by pconrad-fb** [comment]
Same issue for me, Apache.

**Comment by clickwork-git** [comment]
> Same issue for me, Apache.

This issue from 2018 is closed. If you have any problems with your installation please use our forum at

https://forum.bludit.org
