### ISSUE TITLE
Category Sidebar not working

### ISSUE THREAD

**Issue by ITforHome** [bludit/bludit#699]
Hi,

I created a sidebar based on the theme DOC-X, but the sidebar is not working. When i click on a Link in a Sidebar, i don't get the page Content. The URL is correct but i don't see anything. 

This is the code of the sidebar:

``` php
<nav class="sidebar">
<?php
	// Get only Categories that have pages
	$categories = getCategories();
	foreach ($categories as $category) {
		if (count($category->pages())>0){
		echo '<h6 class="text-uppercase">'. $category->name() .'</h6>';
	}

			// Get the list of pages
			$page = $category->pages();

			echo '<ul class="nav flex-column">';
			foreach ($category->pages() as $pageKey) {
				//if ($pageKey==$url->slug()) {
					//echo '<li class="nav-item-active">';
				//} else {
					//echo '<li class="nav-item">';
				//}
				$page = buildPage($pageKey);
				echo '<a class="nav-link" href="'.$page->permalink().'">'.$page->title().'</a>';
				echo '</li>';
			}
			echo '</ul>';
	}
?>
</nav>
```

Where is my issue? I hope you can help me

**Comment by dignajar** [comment]
Hi, what is the error log ?

**Comment by ITforHome** [comment]
@dignajar 
Thank you for your quick reply and for your help. 
The Chrome WebConsole say:

![bludit_chrome_web_console](https://user-images.githubusercontent.com/27279514/40925123-3bbc358a-6819-11e8-80bc-0e41d90d15d7.png)

**Comment by clickwork-git** [comment]
Where have you inserted the code?

**Comment by ITforHome** [comment]
@clickwork-git In the sidebar.php file, which is stored in the theme directory. I use the Bludit docx theme. So far I have only customized the sidebar.php file to my needs.

**Comment by clickwork-git** [comment]
Strange... It worked in my installation.

Is the installation on a local server?

**Comment by dignajar** [comment]
Check the logs of PHP (backend) in the server side

**Comment by ITforHome** [comment]
@clickwork-git Crazy... yes i use bludit on a local Server with Apache2 Webserver and PHP7. The Bludit directories are stored directly in the DocumentRoot Directory. So i haven‘t a subdirectory e.g. /bludit

**Comment by clickwork-git** [comment]
@ITforHome And it works without the modification or is there also a problem?

**Comment by ITforHome** [comment]
@clickwork-git yes the sidebar.php file works without my modifications.

**Comment by clickwork-git** [comment]
Have you tried with another browser? This is a weird error message...

**Comment by ITforHome** [comment]
yes i tried in Firefox, Chrome and Safari - The same issue 
I have no idea what the cause of the error might be...

**Comment by clickwork-git** [comment]
You can PM me a copy the installation.

**Comment by clickwork-git** [comment]
It works on my side. But the version you sent me has no .htaccess.

**Comment by clickwork-git** [comment]
The problem was not the template sidebar.php, it was the template page.php.

Please always use the following:

`$Page->`

instead of

`$page->`

**Comment by ITforHome** [comment]
Thank you so much, Edi, that was the solution. I am very happy for your help.
Thank you again und have a nice day

Niklas

On 6. Juni 2018, 01:31 +0200, Edi <notifications@github.com>, wrote:

The problem was not the template sidebar.php, it was the template page.php.

Please always use the following:

$Page->

instead of

$page->
