### ISSUE TITLE
Can't attach a child page to a Parent if the desired Parent is Scheduled

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#700]
I'd like to ask for a fix to a bug or a change to the design... I'm guessing it is one or the other ;)
... but first I'll set the scene.

> On my site, the Parent Page is a summary of a programme of planned events; each Child page contains the detail of each event. They all need to be pre-scheduled to automatically appear on the same date on a date in the future; 01/07/2018 as it happens to be next.

**The main issue (ver 2.2.1 - 2.3.4):**
When a page is has a publish date set in the future, i.e. "Scheduled" that page does not show in the list of possible Parent pages. This makes it impossible to point another page at it to create a Child/Parent relationship. I wish to create both a Parent and several Child pages up, all with the same future publish date.

Resolution:
Allow any non-child page, whether **scheduled** or published to be selected as a parent page.

**Secondary issue (ver 2.2.1 - 2.3.4):**
Publish date gets changed when the status is changed. First set the published date in the future with the intention of scheduling it and save it as Draft. Then, change the status from Draft to Published and save; The published date/time changes to now. This means that it goes live immediately and is not scheduled any more. You have to then immediately re-set the desired scheduled date/time.

Resolution:
When changing the status field, the code should not change the published date field unless the user has changed it.

Hopefully, that makes sense, but many thanks in advance,
David

**Comment by dignajar** [comment]
Hi,
I understand both issues.

1- Is going to be complicated because a parent page needs to be published before you can select it.
2- If you save as draft I think don't make sense to have a date, even more, when you are going to schedule the content, but I can "fix" the issues keeping the date in the draft, but I need to check it.. I feel is not correct, but can I be wrong.

**Comment by BlakesHeaven** [comment]
Hi Dignajar,
Thanks for your response:

1) Parent/Child issue is, in my books, the most important. Could, for editing purposes in Admin, have it such that only the Status value is considered for selecting a Parent and not count the Published DateTime? And, of course, keep it as it is for display purposes.

2) I agree with you, when saved as Draft, have no date. Trouble is, right now it allows a date to be entered. Maybe remove the date field altogether when Status = "Draft"; or grey it out so we're aware it is there, but not to allowed to use it while in Draft. Could the DateTime be blank when in status, and when status changed to Published get prompted to enter the publish DateTime.

If you'd like to say what code/function controls this drop-down or fling something at me to try, I'd have a go myself, but I'd prefer to keep the core product in line with your releases. Besides - I'm no programmer.

What do you think?
Cheers,
David

**Comment by BlakesHeaven** [comment]
Hi @dignajar , It's been a while and you have been very busy, but is there any chance (please) of allowing Parent/Child relationships for scheduled pages when you get back to adding new functionality? 
Published is one thing, and scheduled is quite separate.
Thanks.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
