### ISSUE TITLE
Backend view broken on mobile?

### ISSUE THREAD

**Issue by Loweis** [bludit/bludit#701]
On screens smaller 380px Bludit backend does use only a third of full width.
The following did fix it for me:

**in bl-kernel/admin/themes/default/css/default.css:**
Line 318 (.uk-grid)
add: width:100%;

**and in bl-kernel/admin/themes/default/css/uikit/uikit.almost-flat.min.css:**
.uk-width-1-3, .uk-width-2-6 -> width: 100%; (instead of 33.333%)

Perhaps someone more skilled could investigate this further?

![bildschirmfoto 2018-06-04 um 10 29 32](https://user-images.githubusercontent.com/39954455/40976173-842484b2-68cd-11e8-8f29-f0f9bc7fdf4f.png)

**Comment by clickwork-git** [comment]
We aware of this. There will be a new backend with the next version of Bludit.

**Comment by dignajar** [comment]
Please check the new Alpha version of Bludit.
