### ISSUE TITLE
[CORE] specific template for static page

### ISSUE THREAD

**Issue by n0byk** [bludit/bludit#709]
Hi 4 all!
How can I create unique templates for different pages?

**Comment by dignajar** [comment]
Hi, the next version of Bludit v3.0 (I only release an Alpha version) has the field templates for the pages, then from the theme, you can choose.

**Comment by n0byk** [comment]
Ok, tnx ! Then 3.0 will be  available?

**Comment by dignajar** [comment]
yes, you can try now the v3.0 Alpha 1, but is not finished..

**Comment by n0byk** [comment]
Link? How download it?

**Comment by Mu9tafa-Online** [comment]
@n0byk - [Download Bludit v3.0](https://github.com/bludit/bludit/releases)

**Comment by n0byk** [comment]
Tnx !

**Comment by dignajar** [comment]
I just add a field for templates, is enough?
I mean when you create the new page you can write some value in the field `template`

```
<?php
if ($page->template() == 'some_template_name') {

}
```

**Comment by dignajar** [comment]
Implemented for v3.0.0
