### ISSUE TITLE
[CORE] Private type for new content

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#710]
Page type `Private`: Show on homepage only for members and access only for members.
Page type `Unlink`: Not listed on homepage and access only to who has the link.

**Comment by BlakesHeaven** [comment]
I think this would be welcome in the core product. If I understand correctly, it sounds like something I build into my Auto-Archive-Menu-Plus-More plugin where the hidden page is controlled by Category and therefore only available if you know the URL. go for it.

**Comment by dignajar** [comment]
Some user request in the chat and I remember there was some implementation but I don't find it.
I going to tell to the guy to check your plugin.
Thanks

**Comment by DigitalAssasin** [comment]
Hi! I'm also interested in the private mode feature. I want to allow a part of my visitors to see new contents earlier than the rest of the world. So i thought about sharing the static links by Patreon or something.

Blake's plugin could do the job but it seems to be a little outdated (the package content mentions 3.0.x as latest version) and I'm worried about future compatibility. There is also a lot of other stuff in this plugin I don't need for my purpose.

So for me it would be a great feature to have a third state beneath the current available "Draft" and "Published" which i could choose in the content editor to get the final URL but don't let the new content show up in the website.

**Comment by BlakesHeaven** [comment]
Thanks for the mention; I have Auto-Archive-Menu-Plus-More plugin running just fine against bludit v3.10.0a ;-)
In fact, I've just added something that means I'll be updating the Bludit plugin list.

**Comment by dignajar** [comment]
I updated the topic, is something I mentioned for Bludit v4. https://github.com/bludit/bludit/issues/1057

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
