### ISSUE TITLE
Add manual content

### ISSUE THREAD

**Issue by Jtreix** [bludit/bludit#712]
What can be done to manually add content (cron job)?
I could not understand which page your content was sent to(POST).

**Comment by clickwork-git** [comment]
Manually or with a cron job? I do not understand your question... Can you please give an example.

**Comment by dignajar** [comment]
You can use the API and do it via `curl` an set some cronjob.

https://docs.bludit.com/en/api/introduction

**Comment by dignajar** [comment]
or you can do this via command line.
```
$ mkdir /bl-content/new-page
$ vi /bl-content/new-page/index.txt # Add the proper structure of pages
```

```
<?php
# Call this method to rescan the content.
$dbPages->rescanClimode();
?>
```

**Comment by Jtreix** [comment]
how can i add content with api,
I do not understand much from api documentation.
Thanks.

**Comment by clickwork-git** [comment]
It's aexplained in the documentation:

https://docs.bludit.com/en/api/create-a-new-page

**Comment by Jtreix** [comment]
how can i add content title and content i cant see any think

**Comment by clickwork-git** [comment]
Also this is explained in the documentation.

**Comment by dignajar** [comment]
The link mention by Edi, and search for the title `CURL command example`

**Comment by Jtreix** [comment]
im sorry,
how can i add image?

**Comment by Jtreix** [comment]
where am i making mistakes?

**Comment by dignajar** [comment]
Create a file `data.json` put the next text inside:

```
{
    "token": "24a8857ed78a8c89a91c99afd503afa7",
    "authentication": "193569a9d341624e967486efb3d36d75",
    "title": "My dog",
    "content": "Content of the page here, support Markdown code and HTML code."
}
```

Change the token and authentication for yours.

Use `curl` command

```
curl -vvv \
    -X POST \
    -H "Content-Type: application/json" \
    -d @data.json \
    "https://example.com/api/pages"
```

**Comment by dignajar** [comment]
Feel free to open the issue or create a question in the forum. https://forum.bludit.org
