### ISSUE TITLE
[CORE] [Media Manager] Create different size of images after upload an image

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#713]
If the image is too big would be a good idea create new a resize the original.
- Original
- Thumbnail
- Resized

**Comment by dimobelov** [comment]
And may be embed in editor with srcset. Will be good for mobile users. [Responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
