### ISSUE TITLE
[CORE] Disable session cookie

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#715]
Some user want to disable the session cookie for the admin.

There is some confusion about cookies and the use of cookies in conection with personal data. Therefore a lot of users and visitors are afraid of any cookie.

**Comment by wpPerformance** [comment]
Personal i don't want any Cookie. And i want no cookie notice on my minimal website. A option without Cookie will be awesome.

**Comment by dignajar** [comment]
The cookie in the admin area is only for keeping the `SESSION ID`, is need it for know if the user is logged or not to the admin area.

**Comment by wpPerformance** [comment]
But why all users became this cookie? Is there no way to set the cookie only in admin, for users who login? Only for this cookie, i need to setup a cookie notice in EU or choose a other flat-file-cms.

**Comment by dignajar** [comment]
@wpPerformance choose other CMS.. good luck!

**Comment by turbopixel** [comment]
session cookie is a normal thing in the world wide web..

**Comment by clickwork-git** [comment]
It's not true that the GDPR or the EU says that there has to be a notice for a system cookie. This cookie does not track or store any personal information.

Sorry for opening the thread! Rethinking it it's nonsensense.

**Comment by clickwork-git** [comment]
@wpPerformance Any other idea or an example of a CMS without session cookies?

**Comment by dignajar** [comment]
I disable session cookie for the front page, is enabled only when you go to the admin area.

**Comment by dimobelov** [comment]
And now we cant check on front is user logged-in, right? I added "Edit" button in Pages - easy navigation to edit content. Now this is gone? What personal information contain user session? How this relate to GDPR?

**Comment by dignajar** [comment]
For the people is trying to check if the user is logged in the homepage, you can do this.

```
<?php
$login = new Login();
if ( $login->isLogged() ) {
    echo "User logged";
} else {
    echo "User not logged";
}
```

**Comment by anaggh** [comment]
Thanks! Working fine.
