### ISSUE TITLE
[CORE] Title from database

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#719]
Can we have title in database, and not build Page every time when we need only basic information - title, link, description, cover image? Something like inFile -> true, inDb -> true only for this field.

**Comment by anaggh** [comment]
+1. It might be repetitive to include title in database and the content file but I feel it is necessary. We could use it to build an archive plugin where only titles are pulled from the database. Currently if we try to build an archive page, we need to buildPage on each page just to get titles. Think about 10,000 pages.

**Comment by dimobelov** [comment]
This will optimize a lot of things - sitemap generation, index, category, tags. Now we have to build pages just to have title.

**Comment by anaggh** [comment]
Yup, it will also make it easier to implement this in Bludit Core. https://github.com/bludit/bludit/issues/600 A basic search on titles via ajax in admin panel.

**Comment by dignajar** [comment]
Yes is a feature I have in mind a long time, but I need to think how to be backward compatible and also I would like to keep the feature and store the title in the file...

**Comment by dignajar** [comment]
Implemented for v3.0.0
