### ISSUE TITLE
Dependencies Update

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#720]
Please note that before the **v3.0** release, some dependencies need updating:
- [TinyMCE](https://www.tiny.cloud/docs/changelog/)
- [Bootstrap](https://getbootstrap.com/)
- [Bootstrap Bundle](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/js/bootstrap.bundle.min.js)

Thanks!

**Comment by dignajar** [comment]
Updated!
