### ISSUE TITLE
Text Correction

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#721]
At https://github.com/bludit/bludit/blob/master/bl-kernel/js/bludit-ajax.php#L66 the correct text should be:

`You are not logged in anymore, so Bludit can't save your settings and content.`

Tested on https://github.com/bludit/bludit/commit/8cfd7df062f373dcbc2a272cd60270d9b4b76bd6

**Comment by dignajar** [comment]
Fixed, thanks!
