### ISSUE TITLE
Fatal Error when sorting the Plugins

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#722]
I got this error when I clicked on **Change the position of the plugins**:

`Fatal error: Uncaught Error: Class 'HTML' not found in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\bludit\bl-kernel\admin\views\plugins-position.php:3 Stack trace: #0 C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\bludit\bl-kernel\admin\themes\booty\index.php(69): include() #1 C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\bludit\bl-kernel\boot\admin.php(98): include('C:\\Bitnami\\wamp...') #2 C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\bludit\index.php(37): require('C:\\Bitnami\\wamp...') #3 {main} thrown in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\bludit\bl-kernel\admin\views\plugins-position.php on line 3`

Tested on https://github.com/bludit/bludit/commit/8cfd7df062f373dcbc2a272cd60270d9b4b76bd6

**Comment by dignajar** [comment]
Nee to be implemented. Please do not report bugs from the Alpha version, when I release the Beta version would be good to have a feedback for bugs.
