### ISSUE TITLE
Text Correction

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#724]
https://github.com/bludit/bludit/search?p=3&q=complete+all+fields&unscoped_q=complete+all+fields
https://github.com/bludit/bludit/blob/master/bl-kernel/admin/controllers/configure-plugin.php#L47
... etc.

In English there's no such thing as _Complete all fields_
It should be replaced with: **Please fill in all fields.**

Tested on https://github.com/bludit/bludit/commit/47e5994c94eae158249f0d7e19324c66c1caadcd

**Comment by BlakesHeaven** [comment]
Mmm, "To complete" or not "To complete" - that's the question...
Whilst saying "Please" is polite, "Complete all fields" is most certainly commonly used, understood and very much acceptable.
Both are ok, however, I'd prefer to complete the fields and for my 2 penneth's worth, I think "Complete" is more commonly used then "Fill".

**Comment by Tangol** [comment]
> "Complete all fields" is most certainly commonly used, understood and very much acceptable.

Sure, it's a perfectly valid verb, however I've never seen this statement being used for an online form before...
And for me, it just doesn't sound right.
