### ISSUE TITLE
Admin Icons

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#725]
Please note that some Admin items have incorrect icons:

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/content.php#L3
The `cog` icon at **Content** should be replaced with `document`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/users.php#L3
The `person` icon at **Users** should be replaced with `people`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/about.php#L3
The `person` icon at **About** should be replaced with `info`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/themes.php#L3
The `puzzle-piece` icon at **Themes** should be replaced with `eye`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/configure-plugin.php#L3
The `person` icon at **Configure Plugin** should be replaced with `wrench`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/new-content.php#L67
The `tags` icon at **Category** should be replaced with `tag`.

- https://github.com/bludit/bludit/blob/master/bl-kernel/admin/views/new-content.php#L68
The `tags` icon at **Description** should be replaced with `tag`.

Tested on https://github.com/bludit/bludit/commit/47e5994c94eae158249f0d7e19324c66c1caadcd

**Comment by dignajar** [comment]
Hi, I made the changes, the only I'm not sure is for Content, I put the icon `layers`
