### ISSUE TITLE
Wrong variable in dbList

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#727]
[https://github.com/bludit/bludit/blob/master/bl-kernel/abstract/dblist.class.php#L49](https://github.com/bludit/bludit/blob/master/bl-kernel/abstract/dblist.class.php#L49)

`$chunks = array_chunk($list, $realPageNumber);` must be `	$chunks = array_chunk($list, $amountOfItems);`

**Comment by dignajar** [comment]
Fixed thanks!

**Comment by dignajar** [comment]
Implemented for v3.0.0
