### ISSUE TITLE
[DOCUMENTATION] Fix Nginx configuration

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#728]
https://docs.bludit.com/en/webservers/nginx

Improve the rule for `location ^~ /bl-kernel/ { deny all; } `.
- Allow all files requeste by the browser, such as CSS and JS files.

**Comment by kavin-90** [comment]
that will deny ADMIN css, js files also

**Comment by dignajar** [comment]
Hi, yes I know, that why need to improve and allow `files requested via browser` (css, js).

**Comment by clickwork-git** [comment]
See also:

https://forum.bludit.org/viewtopic.php?p=5504#p5504

And the mentioned post:

https://support.plesk.com/hc/en-us/articles/213912945-A-WordPress-website-on-a-Plesk-server-shows-404-Not-Found-on-all-pages-except-index-php-when-running-on-FPM-by-nginx

**Comment by kavin-90** [comment]
`location ^~ /bl-kernel/*.php { deny all; }.` will do the work that i found on Forum.
