### ISSUE TITLE
Dependencies Update Part2

### ISSUE THREAD

**Issue by Tangol** [bludit/bludit#731]
Please note that the dependencies need updating again:
- [TinyMCE](https://www.tiny.cloud/docs/changelog/)
- [Bootstrap](https://getbootstrap.com/)
- [Bootstrap Bundle](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/js/bootstrap.bundle.min.js)

Thanks!

**Comment by dignajar** [comment]
Hi, I noticed the dependencies are needed to update again, but I can't do all the time, feel free to create a pull request with the changes, this kind of issues are not relevant.
