### ISSUE TITLE
[CORE] Category description

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#732]
I would like to know if necessary this feature ?
Add the field description to the categories.

**Comment by JonathanHolvey** [comment]
I would definitely use this feature.

It allows me to create a rich category listing page with a snippet of text about each category. An image for a category can be extracted from the content it contains, but this doesn't make sense for a description.

Disclaimer: I created the original PR referenced above.

**Comment by dignajar** [comment]
Implemented, I just push the code to github.
