### ISSUE TITLE
Bludit V3.0 has XSS vulnerability

### ISSUE THREAD

**Issue by liao10086** [bludit/bludit#738]
Bludit V3.0 has XSS vulnerability on parameter new_username.
 when I add a new user,
username input <script>alert(1)</script>
![xss](https://user-images.githubusercontent.com/37523122/43886179-8d79b1a6-9bed-11e8-9232-b832d217abb6.png)

the result
![xss2](https://user-images.githubusercontent.com/37523122/43886271-c9e6c0f2-9bed-11e8-9e7b-8c66c3608783.png)

the XSS also in other places 
I hope you can fix it.
best wish

author by:xijun.liao@dbappsecurity.com.cn

**Comment by dignajar** [comment]
Hi,
to insert something in Bludit you need to have administrator permissions, so at the end, the administrator for sure doesn't want to insert malicious code in his website.

Regards

**Comment by dignajar** [comment]
@liao10086, can you clarify your issues?

if you have administrator access to your OS, you are going to install Malware on it?

**Comment by xdisplayx** [comment]
> to insert something in Bludit you need to have administrator permissions, so at the end, the administrator for sure doesn't want to insert malicious code in his website.

In any system you have to be logged in and have a role to modify things (WordPress, joomla, ect). but that does not mean that they do not control all these vulnerabilities. It would be the same as saying: Since my bank has a large entrance door, I do not need the vault.

---

En cualquier sistema hay que estar logueado y tener un rol para modificar cosas(WordPress, joomla, ect). pero eso no quiere decir que no controlen todas esas vulneravilidades.  Seria lo mismo que decir: Como mi banco tiene una gran puerta de entrada no me hace falta la boveda acorazada.

**Comment by dignajar** [comment]
@xdisplayx pense que ibas a buscar otro CMS, pero veo que seguis dando vueltas por aca.

**Comment by xdisplayx** [comment]
> pense que ibas a buscar otro CMS, pero veo que seguis dando vueltas por aca.

Una cosa no quita la otra, de hecho aun sigo probando algunos proyectos con desarrolladores algo mas avispados, Pero al ver tu razonamiento no pude evitar el responder.  Y al parecer @liao10086 al ver tu gran razonamiento le quedo todo claro como a mi.

**Comment by dignajar** [comment]
Fijate en tu sistema operativo si te logueas como administrador e intentas instalar un malware/virus como quieras llamarle si hace alguna chequeo, este es el mismo caso.

Lo que mas me molesta es la gente como vos que viene a quejarse y no aporta nada util al projecto; Solo quejas.

**Comment by xdisplayx** [comment]
> Lo que mas me molesta es la gente como vos que viene a quejarse y no aporta nada util al projecto; Solo quejas.

No aportamos nada util? Pues probamos tu sistema y te dimos unas nociones de lo que le sucede. Pero parece ser que sino venimos a lamerte el culo no te interesa.
