### ISSUE TITLE
Request Editor plug-in that does not alter code

### ISSUE THREAD

**Issue by Andyfrizzle** [bludit/bludit#739]
I am currently using  Bludit v2.3.4.

I have three available plug-ins to edit/create html code.

TinyMCE, SimpleMDE and CkEditor

Unfortunately each of the editors either adds or removes code breaking my pages.

Can we have a simple html/code editor plugin that doesn't mess around with your code.

**Comment by dignajar** [comment]
SimpleMDE doesn't add any code, I would like to see some example of this add or remove code, can you show me?

If you have in mind some editor, feel free to create a request to create a plugin for it.

**Comment by Andyfrizzle** [comment]
You are quite correct. SimpleMDE does not change the code. Please excuse my confusion. I hope SimpleMDE will still be available in the forthcoming v3.

**Comment by dignajar** [comment]
Yes is going to be included in v3.
