### ISSUE TITLE
IIS Javascript error on media.php

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#740]
On IIS this line always throw error and break execution:
Back-slash need escape:
  ```path: "<?php echo PATH_UPLOADS_THUMBNAILS ?>"```
  to
  ```path: "<?php echo str_replace("\\","\\\\", PATH_UPLOADS_THUMBNAILS) ?>"```

https://github.com/bludit/bludit/blob/39d409ccc77c42c3004b33d130c439473164f732/bl-kernel/admin/themes/booty/html/media.php#L114

**Comment by dignajar** [comment]
Strange because I use `DIRECTORY_SEPARATOR` and this constant change between OS.. I would like to know what is happening. 

Can you check these variables in `www.example.com/admin/developers` and show me the values for all the predefined variables `Bludit Constants`

thanks

**Comment by dimobelov** [comment]
Bludit Constants
----------------

| BLUDIT | true |
| DS | \ |
| PATH_ROOT | D:\programming\php\Bludit\bludit-3-b1\ |
| PATH_BOOT | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\boot\ |
| BLUDIT_VERSION | 3.0.0-beta-1 |
| BLUDIT_CODENAME |  |
| BLUDIT_RELEASE_DATE | 2018-08-01 |
| BLUDIT_BUILD | 20180801 |
| DEBUG_MODE | true |
| PATH_LANGUAGES | D:\programming\php\Bludit\bludit-3-b1\bl-languages\ |
| PATH_THEMES | D:\programming\php\Bludit\bludit-3-b1\bl-themes\ |
| PATH_PLUGINS | D:\programming\php\Bludit\bludit-3-b1\bl-plugins\ |
| PATH_KERNEL | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\ |
| PATH_CONTENT | D:\programming\php\Bludit\bludit-3-b1\bl-content\ |
| PATH_ABSTRACT | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\abstract\ |
| PATH_RULES | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\boot\rules\ |
| PATH_HELPERS | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\helpers\ |
| PATH_AJAX | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\ajax\ |
| PATH_CORE_JS | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\js\ |
| PATH_PAGES | D:\programming\php\Bludit\bludit-3-b1\bl-content\pages\ |
| PATH_DATABASES | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\ |
| PATH_PLUGINS_DATABASES | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\plugins\ |
| PATH_TMP | D:\programming\php\Bludit\bludit-3-b1\bl-content\tmp\ |
| PATH_UPLOADS | D:\programming\php\Bludit\bludit-3-b1\bl-content\uploads\ |
| PATH_UPLOADS_PROFILES | D:\programming\php\Bludit\bludit-3-b1\bl-content\uploads\profiles\ |
| PATH_UPLOADS_THUMBNAILS | D:\programming\php\Bludit\bludit-3-b1\bl-content\uploads\thumbnails\ |
| PATH_ADMIN | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\admin\ |
| PATH_ADMIN_THEMES | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\admin\themes\ |
| PATH_ADMIN_CONTROLLERS | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\admin\controllers\ |
| PATH_ADMIN_VIEWS | D:\programming\php\Bludit\bludit-3-b1\bl-kernel\admin\views\ |
| DEBUG_FILE | D:\programming\php\Bludit\bludit-3-b1\bl-content\debug.txt |
| DB_PAGES | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\pages.php |
| DB_SITE | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\site.php |
| DB_CATEGORIES | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\categories.php |
| DB_TAGS | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\tags.php |
| DB_SYSLOG | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\syslog.php |
| DB_USERS | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\users.php |
| DB_SECURITY | D:\programming\php\Bludit\bludit-3-b1\bl-content\databases\security.php |
| LOG_SEP | | |
| LOG_TYPE_INFO | [INFO] |
| LOG_TYPE_WARN | [WARN] |
| LOG_TYPE_ERROR | [ERROR] |
| CHECK_SYMBOLIC_LINKS | true |
| ALERT_STATUS_OK | 0 |
| ALERT_STATUS_FAIL | 1 |
| THUMBNAILS_AMOUNT | 6 |
| THUMBNAILS_WIDTH | 400 |
| THUMBNAILS_HEIGHT | 400 |
| THUMBNAILS_QUALITY | 100 |
| PROFILE_IMG_WIDTH | 400 |
| PROFILE_IMG_HEIGHT | 400 |
| PROFILE_IMG_QUALITY | 100 |
| PASSWORD_LENGTH | 6 |
| SALT_LENGTH | 8 |
| PAGE_BREAK |  |
| PARENT | BLUDIT3849abb4cb7abd24c2d8dac17b216f17 |
| ITEMS_PER_PAGE_ADMIN | 20 |
| CLI_STATUS | published |
| CLI_USERNAME | admin |
| REMEMBER_COOKIE_USERNAME | BLUDITREMEMBERUSERNAME |
| REMEMBER_COOKIE_TOKEN | BLUDITREMEMBERTOKEN |
| REMEMBER_COOKIE_EXPIRE_IN_DAYS | 30 |
| FILENAME | index.txt |
| DB_DATE_FORMAT | Y-m-d H:i:s |
| BACKUP_DATE_FORMAT | Y-m-d-H-i-s |
| SITEMAP_DATE_FORMAT | Y-m-d |
| ADMIN_PANEL_DATE_FORMAT | D, j M Y, H:i |
| SCHEDULED_DATE_FORMAT | D, j M Y, H:i |
| NOTIFICATIONS_DATE_FORMAT | D, j M Y, H:i |
| NOTIFICATIONS_AMOUNT | 10 |
| TOKEN_EMAIL_TTL | +15 minutes |
| CHARSET | UTF-8 |
| DIR_PERMISSIONS | 493 |
| ADMIN_URI_FILTER | admin |
| DEFAULT_LANGUAGE_FILE | en.json |
| SESSION_GC_MAXLIFETIME | 3600 |
| SESSION_COOKIE_LIFE_TIME | 0 |
| HTML_PATH_ROOT | / |
| HTML_PATH_THEMES | /bl-themes/ |
| HTML_PATH_THEME | /bl-themes/alternative/ |
| HTML_PATH_THEME_CSS | /bl-themes/alternative/css/ |
| HTML_PATH_THEME_JS | /bl-themes/alternative/js/ |
| HTML_PATH_THEME_IMG | /bl-themes/alternative/img/ |
| HTML_PATH_ADMIN_ROOT | /admin/ |
| HTML_PATH_ADMIN_THEME | /bl-kernel/admin/themes/booty/ |
| HTML_PATH_ADMIN_THEME_JS | /bl-kernel/admin/themes/booty/js/ |
| HTML_PATH_ADMIN_THEME_CSS | /bl-kernel/admin/themes/booty/css/ |
| HTML_PATH_ADMIN_THEME_IMG | /bl-kernel/admin/themes/booty/img/ |
| HTML_PATH_CORE_JS | /bl-kernel/js/ |
| HTML_PATH_CORE_CSS | /bl-kernel/css/ |
| HTML_PATH_CONTENT | /bl-content/ |
| HTML_PATH_UPLOADS | /bl-content/uploads/ |
| HTML_PATH_UPLOADS_PROFILES | /bl-content/uploads/profiles/ |
| HTML_PATH_UPLOADS_THUMBNAILS | /bl-content/uploads/thumbnails/ |
| HTML_PATH_PLUGINS | /bl-plugins/ |
| TAG_URI_FILTER | tag |
| CATEGORY_URI_FILTER | category |
| PAGE_URI_FILTER |  |
| ORDER_BY | date |
| EXTREME_FRIENDLY_URL | false |
| AUTOSAVE_INTERVAL | 2 |
| THEME_DIR | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\ |
| THEME_DIR_PHP | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\php\ |
| THEME_DIR_CSS | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\css\ |
| THEME_DIR_JS | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\js\ |
| THEME_DIR_IMG | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\img\ |
| THEME_DIR_LANG | D:\programming\php\Bludit\bludit-3-b1\bl-themes\alternative\languages\ |
| DOMAIN | http://localhost:55041 |
| DOMAIN_BASE | http://localhost:55041/ |
| DOMAIN_CORE_JS | http://localhost:55041/bl-kernel/js/ |
| DOMAIN_CORE_CSS | http://localhost:55041/bl-kernel/css/ |
| DOMAIN_THEME | http://localhost:55041/bl-themes/alternative/ |
| DOMAIN_THEME_CSS | http://localhost:55041/bl-themes/alternative/css/ |
| DOMAIN_THEME_JS | http://localhost:55041/bl-themes/alternative/js/ |
| DOMAIN_THEME_IMG | http://localhost:55041/bl-themes/alternative/img/ |
| DOMAIN_ADMIN_THEME | http://localhost:55041/bl-kernel/admin/themes/booty/ |
| DOMAIN_ADMIN_THEME_CSS | http://localhost:55041/bl-kernel/admin/themes/booty/css/ |
| DOMAIN_ADMIN_THEME_JS | http://localhost:55041/bl-kernel/admin/themes/booty/js/ |
| DOMAIN_UPLOADS | http://localhost:55041/bl-content/uploads/ |
| DOMAIN_UPLOADS_PROFILES | http://localhost:55041/bl-content/uploads/profiles/ |
| DOMAIN_UPLOADS_THUMBNAILS | http://localhost:55041/bl-content/uploads/thumbnails/ |
| DOMAIN_PLUGINS | http://localhost:55041/bl-plugins/ |
| DOMAIN_CONTENT | http://localhost:55041/bl-content/ |
| DOMAIN_ADMIN | http://localhost:55041/admin |
| DOMAIN_TAGS | http://localhost:55041/tag/ |
| DOMAIN_CATEGORIES | http://localhost:55041/category/ |
| DOMAIN_PAGES | http://localhost:55041/

 |

**Comment by dignajar** [comment]
the variable is ok, `D:\programming\php\Bludit\bludit-3-b1\bl-content\uploads\thumbnails\`

I don't understand is need it escape the slash.

**Comment by dimobelov** [comment]
when you use it in javascript \t is reserved symbol for horizontal tab '\t'humbnails 
\u is reserved for unicode symbols from '\u'ploads
This is why back-slash need to be escaped.

**Comment by dimobelov** [comment]
This is what happen in browser  https://i.imgur.com/rALpVAX.jpg

**Comment by dignajar** [comment]
now I understand, and I don't like the idea to send the path via javascript (user control), I going to change this.

**Comment by dignajar** [comment]
I upload a fix for it, check it please: https://github.com/bludit/bludit/commit/6d067b036c0d6f3f733f03c4d8ee3c0391d4b65f

**Comment by dimobelov** [comment]
All is ok now. Issue can be closed.
