### ISSUE TITLE
Bug in view layer-bludit version-2.3.4

### ISSUE THREAD

**Issue by riteshgupta1993** [bludit/bludit#742]
•	Bludit version: 2.3.4
•	PHP Version: 5.6.35
•	Apache Version: 2.4.33
•	Operating system: Microsoft Windows v1

Issue: misconfigured admin level rights to USER.

Privilege escalation occurs when a user gets access to more resources or functionality than they are normally allowed, and such elevation or changes should have been prevented by the application. This is usually caused by a flaw in the application. The result is that the application performs actions with more privileges than those intended by the developer or system administrator.

STEPS TO REPRODUCE:

1: login as user
2: go to profile section and change the password.
3: user is not permitted to change the password (but because of misconfiguration it is allowed) because it can done by only admin.
4: after changing the password and clicking on save a pop-up will be displayed "you dont have sufficient permission", but ignore this pop-up.
5: just logout and login with ur new changed password u will be get access to your account and your old password will be not allowed for login.
6: so this is the misconfiguration that user has also admin level privilege and that pop-up is of no use.
 Submitted by: ritesh kumar

**Comment by riteshgupta1993** [comment]
Hello team
hope u r doing well
please cross check this vulnerabilty.
regards
ritesh kumar

**Comment by anaggh** [comment]
Hi Ritesh,

This seems like a bug in the view layer (invalid error message) instead of Privilege escalation. Users are allowed to change their own password. Are you able to change the password of an admin as a regular user?

**Comment by anaggh** [comment]
I have looked into it. It's not a privilege escalation bug but just a small redirect bug (which shows the insufficient permissions alert).

https://github.com/bludit/bludit/blob/v2.0/bl-kernel/admin/controllers/user-password.php#L60
has to be changed to `Redirect::page('edit-user');`

After a user successfully changes their own password, the `user-password` controller redirects to `Redirect::page('users');` (which shows the insufficient permissions alert since it's not allowed for regular users) instead of `Redirect::page('edit-user');`

**Comment by riteshgupta1993** [comment]
But it is some kind of error bug and should not exist in your product.

**Comment by riteshgupta1993** [comment]
Can you please mark label as bug so that i can apply for cve

**Comment by riteshgupta1993** [comment]
I should change this name to bug in a view layer and apply for cve.just
wanted acknowledgement from by marking the label as bug..

**Comment by riteshgupta1993** [comment]
Hello,
In my point of view the people who are still using this version,  a patch
should be released for those.
Like i am intrested in this version only for a particular amount of days,
so i, as a normal user should demand for the patch.
And this existing version is available for download, and some people are
downloading also,  like me, so in my perspective,  as a fresh user i should
call it bug only.
So its better recommended to think in all corners of perspective.
Thanks and regard
Ritesh

**Comment by dignajar** [comment]
Fixed in Bludit v3.0.0 rc3.

**Comment by riteshgupta1993** [comment]
Yea great...
