### ISSUE TITLE
Member plugin

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#743]
Plugin that shows content only to logged in users.

**Comment by dimobelov** [comment]
@clickwork-git, hidden content will have its own category or tag?

**Comment by clickwork-git** [comment]
@dimobelov, it's related to this:

https://forum.bludit.org/viewtopic.php?f=20&t=1206

Only logged in users can see navigation entries for members.

In addition to this the content should only be shown for logged in users.

**Comment by dignajar** [comment]
That why I want to add the role ‘reader’ to do this kind of things. The issues is need it a proper user register in the system.

**Comment by RubyTheRose** [comment]
![image](https://user-images.githubusercontent.com/10256477/51058316-a1367a80-15a5-11e9-8a20-92e50fa5974d.png)
Like this?
