### ISSUE TITLE
Bludit API Create New Content Err.

### ISSUE THREAD

**Issue by Jtreix** [bludit/bludit#744]
ERROR:
`Fatal error: Uncaught Error: Call to undefined method Text::htmlDecode() in C:\xampp\htdocs\blog\bl-plugins\api\plugin.php:281 Stack trace: #0 C:\xampp\htdocs\blog\bl-plugins\api\plugin.php(135): pluginAPI->createPage(Array) #1 C:\xampp\htdocs\blog\bl-kernel\helpers\theme.class.php(152): pluginAPI->beforeAll() #2 C:\xampp\htdocs\blog\bl-kernel\boot\site.php(7): Theme::plugins('beforeAll') #3 C:\xampp\htdocs\blog\index.php(40): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\blog\bl-plugins\api\plugin.php on line 281`
PHP File:
```
$data = array(
  "token" => "23bd4c1ee97eac62f2b0bd7cb3636086",
  "authentication" => "f00606a31b2da9b5d84834d5bb2b79a2",
  "title" => "test",
  "content" => "test content"
);
$data_string = json_encode($data);

$ch = curl_init('http://localhost/blog/api/pages');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json'
  )
);

$result = curl_exec($ch);

echo $result;
```
I do not know where I'm making mistakes, i need help.
Thanks.

**Comment by dignajar** [comment]
There is a bug in the API,
Change this Text::htmlDecode for this Sanitize::htmlDecode

**Comment by Jtreix** [comment]
I tried a different method and this is the result;
bot.php;
`$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://localhost/blog/api/pages");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$post = array(
    "file" => "@" .realpath("data.json")
);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo $result;`
data.json;
`{
    "token": "23bd4c1ee97eac62f2b0bd7cb3636086",
    "authentication": "f00606a31b2da9b5d84834d5bb2b79a2",
    "title": "My dog",
    "content": "Content of the page here, support Markdown code and HTML code."
}
`
localhost/blog/bot.php;
`{"message":"Missing method inputs."}`

**Comment by dignajar** [comment]
The first problem have you solved ? Replacing the object ?

Regarding to the second “error” have you tried first with command curl like the examples ? To be sure the API works ? I feel is missing the method POST in the call.

**Comment by Jtreix** [comment]
I could not solve the first problem, I wrote it again in a different way.
In the second method i post a json file and i tried postman but not works.
I have not found a solution to this problem for 1 month...

**Comment by dignajar** [comment]
You need to solve the first problem,  change in the plugin.php file, the object name, `Text::` for `Sanitize::`

**Comment by Jtreix** [comment]
![screenshot_1](https://user-images.githubusercontent.com/39380337/44168783-065f7000-a0db-11e8-86c1-a7550ffdac0d.png)
My problem is solved thanks
