### ISSUE TITLE
ReadingTime Function returns incorrect value (v3 beta 2) due to wrong if statement

### ISSUE THREAD

**Issue by cblte** [bludit/bludit#746]
The public function readingTime() should return 'minutes' for everything greater than 1 and 'minute' for a value of 1 or below.

Line 499 (v3 beta 2): Instead of `if ($minutes>0)` -> `if ($minutes>1)`

Thanks.

**Comment by dignajar** [comment]
Fixed by @anaggh here https://github.com/bludit/bludit/pull/735
