### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by AndiLeni** [bludit/bludit#752]
Hello,

I want to know, wether Bludit can be installed with composer or not. 
If not, it might be a good idea to make it possible.

Regards 
Andi

**Comment by dignajar** [comment]
Hi, is not possible, but I going to check how this `composer` works.

You can test quickly via Docker, https://hub.docker.com/r/bludit/docker/

Or just use PHP Build In-Server.
```
$ git clone https://github.com/bludit/bludit.git
$ cd bludit
$ php -S localhost:8000
```

Diego

**Comment by AndiLeni** [comment]
Thank you for considering this.

**Comment by dignajar** [comment]
Hello, I was checking to compose, and as far I understand is for install dependencies. Bludit has his own libraries in PHP so is not necessary use compose for it. I'm missing something ?

**Comment by AndiLeni** [comment]
You are right. Composer makes it easy to manage dependencies. 
If you are interested in following this concept and it's advandates you might have a look at  Pico CMS (picocms.org). 
They use composer which makes updating and installing very easy. 
The intention of this issue was to discuss in which direction Bludit might head in the future. Other opinions and ideas are welcome.

**Comment by dignajar** [comment]
I going to check the Pico CMS how they work;
If possible to do updates of Bludit could be good.
Thanks

**Comment by t2hv33** [comment]
This line helped me to fix composer.json when deploying on Heroku

  "require" : {
    "ext-mbstring": "*",
    "ext-gd": "*"
  },

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
