### ISSUE TITLE
Bar at the end of the url

### ISSUE THREAD

**Issue by xdisplayx** [bludit/bludit#754]
Because some url have, by noses, the bar at the end and others not?
It would not be better all with bar or otherwise none with final bar.

thanks and best regards!

**Comment by dignajar** [comment]
Hi,
just because some URL have ?

Are you talking about the final slash `/` ?

**Comment by xdisplayx** [comment]
Hi, if I talk about the final bar /. For example in the url of blog, categories, etc if it appears and in the others url no.

**Comment by xdisplayx** [comment]
Hola de nuevo! Voy a ser algo mas especifico:

Estas url tiene la barra final
misyte.com/category/
misyte.com/tag/
misyte.com/blog/

Y todas las demás como el ejemplo de continuación no la lleva.
misyte.com/acerca-de
misyte.com/crea-tu-propio-contenido

Y ahora otro problema derivado. Las url que si llevan barra si se la quitas crea un error 404. De lo contrario si la url no la lleva y se la pones crea otro error 404.
misyte.com/blog/  Funciona
misyte.com/blog   No funciona, error 404

misyte.com/acerca-de   Funciona
misyte.com/acerca-de/  No funciona, error 404

Ests dos url no funcionan de ningún modo
misyte.com/category/   No funciona, error 404
misyte.com/tag/    No funciona, error 404

A mi parecer este comportamiento muy normal no es. 
Muchas gracias por vuestro trabajo.

**Traduccion de Google**

Hello again! I'm going to be something more specific:

These url has the final bar
misyte.com/category/
misyte.com/tag/
misyte.com/blog/

And all the others as the example of acontinuacioón does not carry it.
misyte.com/about-de
misyte.com/crea-your-own-content

And now another problem derived. The url that if they take a bar if you remove it creates a 404 error. Otherwise if the url does not take it and put it on, it creates another 404 error.
misyte.com/blog/  It works
misyte.com/blog  It does not work, error 404

misyte.com/about-of/   It works
misyte.com/about-of    It does not work, error 404

These two urls do not work in any way
misyte.com/category/  It does not work, error 404
misyte.com/tag/   It does not work, 404 error


In my opinion, this very normal behavior is not.

Many thanks for your work.

**Comment by dignajar** [comment]
Hola,
lo que identifica la barra al final es como un que es un directorio y no un archivo en si.

mysite.com/category/ -> indica un directorio e indica un indice adentro
mysite.com/about -> indica un elemento, en este caso una pagina llamada about.

Es normal este comportamiento en Bludit.

Como filtrarias vos una categoria respecto a una pagina en la URL ?

**Comment by xdisplayx** [comment]
> Es normal este comportamiento en Bludit.

Si ya veo que es normal en Bludit, pero muy normal no es. Gracias por tu información, seguiré buscando un Flat-File CMS.

**Comment by dignajar** [comment]
No me respondiste la ultima pregunta.

> Como filtrarias vos una categoria respecto a una pagina en la URL ?

**Comment by xdisplayx** [comment]
> No me respondiste la ultima pregunta.

La filtraría de alguna forma que no tenga que influir en las rutas, ya que eso muy normal no es, solo fijate en cualquier sitio o aplicación web. 

No te puedo decir exactamente como lo enfocaría, yo no soy el desarrollador y no he revisado el código. La verdad desde que voy revisando este proyecto (seguir instrucciones e instalar), siempre encontré el mismo problema, ademas de algún otro. Por lo tanto prefiero invertir mi tiempo en revisar otros proyectos que me den una mejor primera impresión. 

Después de haber probado varios y aun siendo algo defectuosos las rutas la mayoría las respetan(como ha de ser). Por eso fue el colocar mi comentario, para que tomaran nota.

Pero si consideras que no es importante lo de las rutas, haz caso omiso a esta reseña. 

Un saludo y gracias!

**Comment by dignajar** [comment]
No intento que me revises el codigo, solo quiero una explicacion de lo que seria "normal", algunos ejemplo que sean de utilidad y ver si es posible seguir ese enfoque.

Saludos

**Comment by xdisplayx** [comment]
Lo normal es que tanto si lleva la barra invertida final como sino la URL funcione  y no de un error 404. Otra cosa es que ya se quiera forzar que aparezca de un forma u otra. Pero si yo te lo tengo que explicar y tu ni siquiera tomaste en cuenta eso (siendo lo importante que es) que mas no habrá por hay que este mal. 

Date una vuelta por cualquier pagina web (que este bien hecha claro) y juega un poco con las rutas, a ver cuantas marcan error 404 por quitarle la barra o ponérsela. Y sobre todo fijate cuantas hay así como las tienes en Bludit, mixtas. Ninguna!!

Un saludo!
