### ISSUE TITLE
output is not encoded with "htmlspecialchars" or "htmlentities"

### ISSUE THREAD

**Issue by cblte** [bludit/bludit#755]
> If you are concerned about XSS then use htmlspecialchars (there's no reason to use the full-blown htmlentities for that) and you are golden:
echo htmlspecialchars($user_input);
HTMLPurifier is only meaningful if you want to allow some HTML capability while still preventing XSS. But as any other piece of code, there's the possibility that it might not work as advertised at some point. Personally, I wouldn't go there.

https://stackoverflow.com/questions/8368714/do-i-still-need-to-use-htmlentities-if-im-using-htmlpurifier#8368731

Example:
```
<?php
$str = "Ein 'Anführungszeichen' ist <b>fett</b>";

// Gibt aus: Ein 'Anf&uuml;hrungszeichen' ist &lt;b&gt;fett&lt;/b&gt;
echo htmlentities($str);

// Gibt aus: Ein &#039;Anf&uuml;hrungszeichen&#039; ist &lt;b&gt;fett&lt;/b&gt;
echo htmlentities($str, ENT_QUOTES);
?>

```
Thanks

**Comment by dignajar** [comment]
Hi, sorry for my late answered.
Maybe I can add a field in the settings to encode the output of the content, I mean to enable or disable.
There are some users who put javascript code in his posts, for example for show some tweet or similar, so if we apply this is going to encode the javascript.

**Comment by cblte** [comment]
Sorry for "my" late reply. Have you check how wordpress is doing that?
