### ISSUE TITLE
Slash at the end of the URL

### ISSUE THREAD

**Issue by battlethem** [bludit/bludit#762]
I know there was an issue a week ago but I didn't quite get it.
My problem is that for a link:
mysite.com/page2 - works,
mysite.com/page2/- doesn't work, returns 404.
As far as I understand, slash at the end indicates that the URL links to either a page or a directory. 
But is there a way to make both links work so that the slash is simply left when the page is loaded as in the case with mysite.com/ redirects to mysite.com?
Thank you.

**Comment by dignajar** [comment]
Included in the version 3.0.0 rc-3

**Comment by stefan-scholl** [comment]
> I going to create a redirect 301 for the pages `mysite.com/page2/` -> `mysite.com/page2`, in the next version 3.0.

This means the user can never change his mind about the links of his site. If he changes the CMS to one with a / at the end of URLs it won't be found by search engines. Users with Google Chrome who visited "page2/" some time will never be able to visit it again.

Don't ever use a simple **301 Moved Permanently**! Use a 302, or a 301 together with expire information in the header.
