### ISSUE TITLE
API 2.3.4 Create new page empty error

### ISSUE THREAD

**Issue by Jtreix** [bludit/bludit#764]
Hello, sometimes it seems empty even though it's the title.
So the title looks fine but the url looks empty.
Json Response Screenshot: http://prntscr.com/kpevs0
Bludit Manage Content Screenshot: http://prntscr.com/kpex97
Ajax Page: 
```
$id = strip_tags($_POST['data']);
$row = $db::table('websites')->find($id);

$WData = array(
  "token" => $row->token,
  "authentication" => $row->authentication,
  "url" => $row->url.'api/pages'
);
$getAllCont = $db::table('contents')->findAll();
echo "<pre style='color: white;'>";
foreach ($getAllCont as $d) {
  $titleD = spinner($d->title);
  $contentD = spinner($d->content);

$data = array(
  "token" => $WData['token'],
  "authentication" => $WData['authentication'],
  "title" => $titleD['article'],
  "content" => $contentD['article'],
  "coverImage" => $d->image
  //"coverImageFilename" => "testimage.jpg"
);
$data_string = json_encode($data);

$ch = curl_init($WData['url']);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_REFERER, "https://www.google.com.tr");
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json'
  )
);

$result = curl_exec($ch);
echo $result."<br>";
}
echo "</pre>";
```
Thanks.

**Comment by Jtreix** [comment]
Again empty returns..
Resp. : http://prntscr.com/kpnwth
Bludit: http://prntscr.com/kpnxek
What's problem ?

**Comment by Jtreix** [comment]
Aynyone can help me?

**Comment by dignajar** [comment]
Looks like the function cleanURL() is removing the characters because you have already another page with the same key... have you tried the new version of Bludit ? there are many bug fix releated to the generation of the url.

**Comment by Jtreix** [comment]
@dignajar what version are you talking about?

**Comment by Jtreix** [comment]
@dignajar Here cleanURL() works; http://prntscr.com/kq4tia and other all functions works but key still empty. This is really bug i only get this error in certain contents and when i do it again only certain content is empty.
Thanks.

**Comment by dignajar** [comment]
looks like a bug.. how can I reproduce it ? do you have some example test ?
as far I understand, you do not set the title, the key is getting from the content ?

**Comment by Jtreix** [comment]
I send to api just title,content but there is no problem with other content but I get blank error in the same content I give you the title you try?
"Firefox to block Cryptojacking Malware in New Browser Releases" <= Title

**Comment by Jtreix** [comment]
Here the biggest proof: http://prntscr.com/kq50r2
Thanks.

**Comment by dignajar** [comment]
I found the bug.. I think..
Update this file, https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/text.class.php

**Comment by Jtreix** [comment]
@dignajar The best savior, thanks so much.

**Comment by dignajar** [comment]
thanks to you for reports this!
