### ISSUE TITLE
Report: Google Sitemap Error

### ISSUE THREAD

**Issue by Jtreix** [bludit/bludit#768]
### Describe your problem
Google cant verify new site map.

	

Find: bl-plugins/sitemap/plugin.php: 
`
$xml .= '<lastmod>'.$page->dateRaw(SITEMAP_DATE_FORMAT).'</lastmod>';
`
Change;
`
$xml .= '<lastmod>'.$page->date('Y-m-d').'</lastmod>';
`

### Bludit version
3.0.0 RC-2

**Comment by dignajar** [comment]
Done! thanks

**Comment by dignajar** [comment]
Fixed in Bludit v3.0.0 rc3
