### ISSUE TITLE
Navigation menu plugin repeats Children as Parents

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#772]
### Describe your problem
I noticed that children in my archive menu plugin were being repeated again as though they were parents so I switched to the Bludit Navigation menu plugin and it seems to be the same there. This was not the case it v2.3.4.
### Expected behaviour
If a page has a parent it should not appear in the Parents list from $parents = buildParentPages();
### Actual behaviour
Notice in the example below the children are repeated:
> ![image](https://user-images.githubusercontent.com/37149377/45258476-fe2fe300-b3af-11e8-95cb-e52a10c7a9ed.png)
### Steps to reproduce the problem
Set pages as Children to a parent and use Navigation menu plugin.
### Bludit version
v3-beta-2

**Comment by dignajar** [comment]
Fixed, thanks for reporting it.
I going to release today the version RC-3 with this bug fix and other.

**Comment by BlakesHeaven** [comment]
Fantastic - thanks.
