### ISSUE TITLE
[CORE] Bug: Select parent as himself

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#777]
### Describe your problem
When the user is editing the page, the user can select the same page that is editing as a parent.

### Expected behavior
The page does not need to appear on the list as a parent.

### Steps to reproduce the problem
Manage > Content > Edit a page and select it as a parent in Option tab.

### Bludit version
v3.0.0 rc-3

**Comment by SamBrishes** [comment]
Hellow,

I used the [HTTP_REFERER](https://github.com/SamBrishes/paw.MoreLevels/blob/master/paw-more-levels/plugin.php#L38) global to solve this issue (within a plugin), but this global may didn't get send by the browser or just lies. So I guess the best solution would be to just pass the current slug within the AJAX request [like on this possible way](https://github.com/pytesNET/bludit/commit/01be08c0e00ba04f5e22f17913771aec19d96664) (It also pass the current slug to the `buildParentPages` function itself to prevent unnecessary loops).

Happy new Year. :tada: 

Sincerely,
Sam.
