### ISSUE TITLE
Sitemap Plugin - Ping search engines with new sitemap when changed

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#796]
https://github.com/bludit/bludit/blob/5e1c72949c07384c84c801ddcd8b007780739ca2/bl-plugins/sitemap/plugin.php#L66

## Ping Urls

- Google -> https://www.google.com/webmasters/sitemaps/ping?sitemap=http://www.example.com/sitemap-file.xml //sitemap file url

-  Bing -> https://www.bing.com/webmaster/ping.aspx?sitemap=http://www.example.com/sitemap-file.xml //sitemap file url

**Comment by dignajar** [comment]
I like the idea, would be good to add some settings for disabling and enabling the feature.

**Comment by dimobelov** [comment]
Yes, it is important to be able to turn on and off. Also search engines need to be optional.

**Comment by dignajar** [comment]
Let see if this works.. https://github.com/bludit/bludit/blob/master/bl-plugins/sitemap/plugin.php

**Comment by dignajar** [comment]
Implemented in Bludit v3.0.0.
