### ISSUE TITLE
[CORE] Allow set homepage static pages

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#800]
### Describe your problem
Is not possible to set a static page as homepage.

### Steps to reproduce the problem
Settings > General > Advanced > Homepage > Try to search a static page.

### Bludit version
3.0.0

**Comment by BlakesHeaven** [comment]
Yes - please allow static pages to be set as home page.
Thanks.

**Comment by dignajar** [comment]
Implemented in Bludit v3.1.0. Thanks!
