### ISSUE TITLE
[CORE] [Media Manager] Missing wrap of pager with large amount of images

### ISSUE THREAD

**Issue by DigitalAssasin** [bludit/bludit#801]
Hi Diego,

I recently upgraded to the latest version 3.0.0 of Bludit. I use many images in my blog. In my case the pager is not wrapped.

See the attached screenshot for details:

![screen_mediamanager_pager](https://user-images.githubusercontent.com/40295910/45963937-b56d6080-c024-11e8-8ba5-88b8bb1fa11f.png)

Is it possible to create a more beautiful solution for a large amount of pages?

Regards

Chris

**Comment by dignajar** [comment]
Hi,
I going to fix it. Also, I was thinking to create a prefix with the page name so is possible to filter images by page..
