### ISSUE TITLE
[CORE] [Media Manager] Creation and upload to subfolders

### ISSUE THREAD

**Issue by DigitalAssasin** [bludit/bludit#803]
Hi Diego,

since I work with many image files in my blog, it would be a huge enhancement for me, to be able to manage the images in sub-folders.

Is anything like this planned in further versions of the Media Manager?

Regards

Chris

**Comment by dignajar** [comment]
Hi,
I don't have in mind to implement subfolders, but what about to create a folder for each post? and in the Media Manager only shows the images for that post?
I know this approach do not allow you to select images from other posts, but maybe this never happens.

Regards

**Comment by DigitalAssasin** [comment]
Hi Diego,

I didn't even know that there is a possibility to organize the post in folders. How can this be done? Currently I'm only using the "New content" button to create a new blog post. I can't find a folder option or something else in the editor or in the content of the options tab. Also I wasn't able to find a topic about this in the documentation.

Is this maybe a Pro feature?

Regards

Chris

**Comment by dignajar** [comment]
Hi,
the new changes allow to the user upload images per page, but this is only for fresh installations.
Take a look to Bludit v3.1.0.
Regards

**Comment by DigitalAssasin** [comment]
Hi Diego,

I tested today with the new Bludit version. As announced there is no effect for updated bludit installations. Is there a method of migration planned? Or how can I migrate an existing and updated Bludit installation manually to use this new feature?

Regards,

Chris

**Comment by dignajar** [comment]
Hi,
no there is not migration tool for that, because the image changed the place, so you need to update the links from the content of the page and move the images.

Old structure:
All images are upload to `/bl-content/uploads/`
All thumbnails are upload to `/bl-content/uploads/thumbnails/`

New structure:
The images are upload for each page to `/bl-content/uploads/pages/<PAGE UUID>/`
The thumbnails are upload to `/bl-content/uploads/pages/<PAGE UUID>/thumbnails/`

Questions to you:
How much images and pages do you have?
When you set an image in the content of the page has the absolute URL or just the name of the image, I mean this `<img src="https://example.com/bl-content/uploads/image.jpg>` or `<img src="image.jpg>`

If you have absolute URL maybe is possible to migrate to the new structure.

**Comment by BlakesHeaven** [comment]
If I may chip in with a comment or two...
I migrated from 2.3.4 to 3.0 to 3.2 and did not realise the image structure had changed - **this is good** as everything still looks the same and images show as before and without fixing links. 

**Old structure** (as described above) means that **same single image** can be shared across multiple pages from the same unique location. **This is good.**
**New structure**, images per page (as described above), means possibly having to load the same image multiple times or have more complex and different URLs to use the same image from multiple places. **Not so good**

Question back: where are Profile images going to go?

Actually.. in v3.2, I see the location `/bl-content/uploads/pages/`, but a new uploaded image went into `/bl-content/uploads/` and `/bl-content/uploads/thumbnails/`, i.e. old structure... so for my needs, this is good.

**Comment by dignajar** [comment]
You are right about to re-use the image in different pages with the new structure is not possible (is possible if you use absolute URLs), but I never saw a page with the same images. I did this change to keep simple and clean the images system.

Profile images go to `/bl-content/uploads/profiles`.

To keep compatiblity with the old strcuture, I add two field in the database `/bl-contnet/databases/site.php`.
- Field `imageRestrict` if you set `true` use the new structure, images per page.
- Field `imageRelativeToAbsolute` if you set `true` the image like `<img src="image.png>` are convert on the fly to `<img src="https://example.com/bl-content/uploads/image.png>`

**Comment by DigitalAssasin** [comment]
Hi Diego,

sorry for my late answer but I had no timeframe to check this before today.

> Questions to you:
> How much images and pages do you have?

from today I have 23 pages online. On these pages I'm using ca. 180 images in sum. Since I use bludit mostly as a blog there will be definitely much more in the future.

> When you set an image in the content of the page has the absolute URL or just the name of the image, I mean this `<img src="https://example.com/bl-content/uploads/image.jpg>` or `<img src="image.jpg>`
> 
> If you have absolute URL maybe is possible to migrate to the new structure.

The images are referenced by the absolute URL in the content.

If I understand you right, I have to move the images to the new file system structure and edit the absolute image URL step-by-step by hand. No prob, this is just a little mindless repetition in my spare time.

But where can I find the page UUID?

And why is the new structure not automatically used if I create new content? Is there a switch somewhere?

Regards,

Christian

**Comment by berteh** [comment]
> You are right about to re-use the image in different pages with the new structure is not possible (is possible if you use absolute URLs), but I never saw a page with the same images. I did this change to keep simple and clean the images system.
> (...) 
> 
>     * Field `imageRestrict` if you set `true` use the new structure, images per page.

My site has 1 post a week about food, and I like to be able to reuse pictures over the seasons/years, to save both on time to look for copyrights free pictures and webhost space.

Simply changing that setting to "false" worked like a charm, thanks a lot, please keep up the good work !

(now I would love to have an additional inline search function in the image pick dialog that would filter the available files based on a simple text "substring" e.g. typing "radis" would keep showing "soupe-carottes-radis.jpg" and "radis-botte.png" but hide the rest.)
