### ISSUE TITLE
Notice: Undefined index: type in /bl-kernel/pages.class.php on line 356

### ISSUE THREAD

**Issue by AlexL777** [bludit/bludit#805]
### Describe your problem

Hello Developers,
i have this Error under `/admin`. I have now uploaded the new Bludit-Version to my Shared Hosting and see this Error. 

    Notice: Undefined index: type in /xxxxxxxxxxxxxxxx/bl-kernel/pages.class.php on line 356

    Notice: Undefined index: type in /xxxxxxxxxxxxxxx/bl-kernel/pages.class.php on line 356

Why is this or what do I have to delete from the files in the hosting to old files?

Thank you in advance.

### Bludit version

Last Version of Bludit CMS.

**Comment by dignajar** [comment]
Hi,
have you follow the steps for migrate from Bludit v2.3.4 to v3.0 ? or you made a clean installation of Bludit v3.0 ?

**Comment by AlexL777** [comment]
Is there a documentary on how to migrate this? I just uploaded the new files to the server without worrying about it.

Thanks for the hint, but I do not know yet how to migrate that.

**Comment by dignajar** [comment]
Yes, in the documentation, https://docs.bludit.com/en/getting-started/upgrade-guide

What you can do now.
- Download to your PC the folder `/bl-content`, only for backup.
- Download the old version of Bludit, the previous you were using, maybe version 2.3.4 ?
- Upload all files of Bludit v2.3.4 and replace the files.
- Then do the process of migration.

Regards

**Comment by AlexL777** [comment]
Big Thanks for this Solution for my Problem. My Problem is now solved with this 😅
