### ISSUE TITLE
Bludit v3 - Disqus Plugin on Pages have the Errors

### ISSUE THREAD

**Issue by AlexL777** [bludit/bludit#806]
### Describe your problem

Hello Developers,
i have a big Problem with the new Disqus-Plugins on Pages. This not worked on Pages. I have this error under Page-Content.

    Fatal error
    : Uncaught Error: Call to undefined method Page::static() in /xxxxxxx/bludit.cms-blogger.eu/bl- plugins/disqus/plugin.php:58

     /xxxxxxxxxxxxxxxxxxxxx/bludit.cms-blogger.eu/bl-plugins/disqus/plugin.php
    on line
    58   

How can I fix this or what am I missing?

Thanks in advance.

**Comment by dignajar** [comment]
Try to reload the plugin (deactivate then activate) you need to reconfigure after that, so remember the current options you set.

**Comment by AlexL777** [comment]
Unfortunately, it does not fix the problem. I've disabled Disqus on Pages. I can live with that, because among the blog posts, I really like that.

**Comment by dignajar** [comment]
Which version of Bludit are you using ?

**Comment by AlexL777** [comment]
v3.0.0

**Comment by dignajar** [comment]
Can you update the plugin again? I feel is not updated, because the method `Call to undefined method Page::static()` is not longer exists in Bludit v3.0

**Comment by AlexL777** [comment]
I took the plugin from the Bludit release and uploaded it again. Unfortunately, no success.

Or do you have a special plugin source for me where the new v3 plugins are included?

Thank you.

**Comment by dignajar** [comment]
From the release is ok.
If you check the source code from here, https://github.com/bludit/bludit/blob/master/bl-plugins/disqus/plugin.php#L58 you can see doesn't exist the `Page::static()`, the object is called `$page->static()`

That why I think is not updated.

**Comment by AlexL777** [comment]
Genial. You are the Best Supporter today 👍 My Problem is now solved!

**Comment by dignajar** [comment]
Implemented in Bludit v3.1.0. Thanks!
