### ISSUE TITLE
BUG - Bludit 3 - Creating a new user does not handle spaces in UserName

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#808]
### Describe your problem
1. Creating a new user does not handle spaces - the space is removed
2. If username, "FredBlogs" (no space) already exists; creating "Fred Blogs" (with space) overwrites the existing "FredBlogs" username without space.

### Expected behaviour
1. The space in the UserName should be retained as it did in v3.2.4
2. Assuming No 1 is fixed, spaces should be counted in the comparison, checking for existing same name; it should not overwrite the existing username.

### Bludit version
version 3.0.0

**Comment by dignajar** [comment]
Hi, sorry for my late answered, the username with spaces are not allowed, but I going to check this overwrite. thanks
