### ISSUE TITLE
Latest update in media manager

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#814]
https://github.com/bludit/bludit/blob/0657c55191c40f4dc9b2f519058915522405a131/bl-kernel/admin/themes/booty/html/media.php#L4
**DS** cause error on IIS, because it is used in javascript.
Fix:
```
if (IMAGE_RESTRICT) {
	$imagesDirectory = (IMAGE_RELATIVE_TO_ABSOLUTE? '' : HTML_PATH_UPLOADS_PAGES.$uuid.'/');
	$thumbnailDirectory = PATH_UPLOADS_PAGES.$uuid.DS.'thumbnails'.DS;
	$thumbnailHTML = HTML_PATH_UPLOADS_PAGES.$uuid.'/thumbnails/';
} ...
```

**Comment by dignajar** [comment]
Implemented in Bludit v3.1.0. Thanks!
