### ISSUE TITLE
TinyMCE: Problem with page break

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#822]
Inserting a page break with TinyMCE shows an empty field in the editor.

![2018-10-15 12_36_20-window](https://user-images.githubusercontent.com/14312561/46946280-82444d00-d077-11e8-956d-4afe4292b98b.png)

**Comment by dignajar** [comment]
Yes, is fixed here.

https://github.com/bludit/bludit/commit/303ba212405c119bd005bc09c28c829acfb1e11e#diff-5b0ab6ab2e2e401d8988c8e33c1b93ce

For next release

**Comment by clickwork-git** [comment]
Thank you!

**Comment by dignajar** [comment]
Fixed in Bludit v3.2.0.
