### ISSUE TITLE
TinyMCE Code Block seems broken

### ISSUE THREAD

**Issue by cb109** [bludit/bludit#833]
### Describe your problem
I was using your demo, with plugin SimpleMDE deactivated and plugin TinyMCE activated. Addding a new Content post and then trying to add a code block results in entirely unformatted text without any code highlighting. See screenshots below.

![2018-10-27 18_07_27-bludit - edit content - test1](https://user-images.githubusercontent.com/6052590/47606417-af97e000-da13-11e8-8f2d-5fb09d940fd7.png)

![2018-10-27 18_07_43-bludit - edit content - test1](https://user-images.githubusercontent.com/6052590/47606418-b0c90d00-da13-11e8-9d1a-b4802b964edf.png)

### Expected behavior
It should add a formated code block with keywords highlighted (at least in the final page).

### Actual behavior
Code format is broken (all in one line), no highlighting, no sign of it being a block.

### Steps to reproduce the problem
Go to your demo page, add a code snippet, check the result after clickink Ok.

Possible example snippet:

```javascript
function fooBar(arg1) {
    return arg + 1;
}
```

### Bludit version
3.2

**Comment by dignajar** [comment]
I think this was solved.
Take a look here, https://github.com/bludit/bludit/issues/813
