### ISSUE TITLE
User logo.

### ISSUE THREAD

**Issue by uwejan** [bludit/bludit#835]
Hello there,
### Describe your problem
When you change an editor logo, the logo will change for all users and that editor will be without logo.
### Expected behavior
Changing an editor logo, will that user logo only and other users remain there state.
### Actual behavior
The logo changes for all users, and the meant user without logo.
### Steps to reproduce the problem
Can any body help out with that please?
### Bludit version
3.2.0

**Comment by dignajar** [comment]
Fixed in this commit. https://github.com/bludit/bludit/commit/ccdcba869916cc67689fb26584b88ae0f2f71c66
