### ISSUE TITLE
allow user to edit they own account

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#836]
### Describe your problem
Yet, only admin can edit all account, but editor can't edit they own
### Expected behavior

you can do something like this into bl-kernel/admin/controllers/users.php line 7 : 
checkRole(array('admin','editor'));

and into bl-kernel/admin/views/users : something like this : 
if ($login->role()==='admin'){ echo all user }
elseif ($login->username() == $username){ 	echo only the current user}

### Bludit version
3.2

**Comment by uwejan** [comment]
I think a better way would be elseif ($login->role()==='editor'), then an if if ($login->username() == $username).

**Comment by dignajar** [comment]
Implemented, please check the new version 3.4.0.
