### ISSUE TITLE
SEO Friendly url and Text class

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#843]
https://github.com/bludit/bludit/blob/3510fa6e30416e79e0dfd85f76f6553c606c99c7/bl-kernel/helpers/text.class.php#L144

We still need cleanup defined bellow before return. Fix:
```
               if (EXTREME_FRIENDLY_URL) {
			$string = self::lowercase($string);
			$string = trim($string, $separator);
			$string = self::removeSpecialCharacters($string, $separator);
			$string = self::removeLineBreaks($string);
			$string = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $string);
			$string = preg_replace("/[\/_|+ -]+/", $separator, $string);
			$string = trim($string, $separator);
			return $string;
		}
```

**Comment by dignajar** [comment]
The idea of `EXTREME_FRIENDLY_URL` is allow unicode characters, you can disable it in the `Settings > SEO > Allow Unicode > false`, the is going to remove all characters except the letters `a-z` and `-`.

https://github.com/bludit/bludit/blob/3510fa6e30416e79e0dfd85f76f6553c606c99c7/bl-kernel/helpers/text.class.php#L160-L163

**Comment by dimobelov** [comment]
Its reversed, @dignajar . If(EXTREME_FRIENDLY_URL == true) its nonunicode. if false unicode is allowed. i need this for nonunicode but it's not working like expected without these two lines.
