### ISSUE TITLE
Select cover image is not working.

### ISSUE THREAD

**Issue by uwejan** [bludit/bludit#847]
### Describe your problem
User profile, Select cover image is not working.

### Bludit version
3.3

**Comment by dignajar** [comment]
Hi, there is not section User profile and Select cover image in Bludit v3.3 ?

**Comment by uwejan** [comment]
Hi, its on Users -> Edit User -> Profile picture -> Select cover image is not working.
in developer console, i see the following error: Uncaught ReferenceError: openMediaManager is not defined
