### ISSUE TITLE
Docker latest tag is out of date

### ISSUE THREAD

**Issue by breadcat** [bludit/bludit#850]
### Describe your problem
Pulling bludit/docker:latest pulls version 2.3.3 instead of 3.3.0

### Expected behavior
3.3.0 should be pulled

### Actual behavior
2.3.3 is pulled

### Steps to reproduce the problem
`docker pull bludit/docker:latest`

### Bludit version
2.3.3

Additionally, the latest docker image available is version 3.2 instead of 3.3.

**Comment by dignajar** [comment]
I created the tag `3.4.0`. thanks for report it.
