### ISSUE TITLE
Limit each user to their content.

### ISSUE THREAD

**Issue by uwejan** [bludit/bludit#852]
### Describe your problem
Say i have a blog of multiple authors, now all authors are able to edit, remove, other authors posts, it would really helpful, if we could limit each author to their own content only.

### Bludit version
3.4.0

**Comment by BlakesHeaven** [comment]
Just expanding on this idea, it would also be good to have an approver role to approve the author's pages before they can be published.

**Comment by ikutaa46** [comment]
i have tested @uwejan idea.
Need to edit directly to `bl-kernel\admin\views\content.php`

add some line, like

```
...
global $login;
...
if ($page->username() == $login->username()){
...
}
```

**Comment by uwejan** [comment]
@ikutaa46 i just tried that , it just dose not work, can you provide a full example?

**Comment by ikutaa46** [comment]
@uwejan 

```
function table($type) {
  ...
  global $static;
  global $sticky;
  global $login;
   //add here
  global $login;
```
```
...
foreach ($list as $pageKey) {
  try {
    $page = new Page($pageKey);
    //put here
   if ($page->username() == $login->username()) {
   ...
```

```
//add  }  before exception 
...
     }
  } catch (Exception $e) {
...
```

**Comment by uwejan** [comment]
@ikutaa46 did you add new authors and new content for each author, Just did you code modification, and nothing changes. still any author can see others contents.

**Comment by ikutaa46** [comment]
@uwejan yes, i added new author, new editor, new contents,,,,
_my mistake, sorry, if the code not work_. 
oh, u can try for demo, tell me if they still see other content on they admin panel
[mysite](https://www.ikuta46.ga/admin)
id: **demo11** - pass: **demo11**
id: **demo22** - pass: **demo22**

**Comment by uwejan** [comment]
@ikutaa46  in your site, it seems to work, can you upload source code please, i can not get it to work with your proposition.

**Comment by ikutaa46** [comment]
sorry, late to answer, only this i can help,
[content.zip](https://github.com/bludit/bludit/files/2609427/content.zip)

**Comment by uwejan** [comment]
@ikutaa46 you will have to modify the edit-content.php in views as well, otherwise authors can edit the contents by just putting its name on the URL, i think this is a temporally fix, moreover drafts can be seen across for all.

**Comment by ikutaa46** [comment]
@uwejan yes this is temporary fix, and need someone advance to solve this issue, not me..
u should backup original file, im not responsible if a new bug come from my code.

 try this line, it will make author can only edit their content,, even he put url directly.
```
if ($page->username()!==$login->username()) {
Alert::set($L->g('You do not have sufficient permissions'));
		Redirect::page('dashboard');
}
```
put in on top `bl-kernel/admin/views/edit-content.php`
put after` //FORM START` line,then will look like this after edited...

```
<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
<?php
// FORM START

if ($page->username()!==$login->username()) {
Alert::set($L->g('You do not have sufficient permissions'));
		Redirect::page('dashboard');
}

echo Bootstrap::formOpen(array(
	'id'=>'jsform',
...
```

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
