### ISSUE TITLE
Multiple install of Bludit and access

### ISSUE THREAD

**Issue by Larsene** [bludit/bludit#853]
### Describe your problem
Hello, I've installed two instance of Bludit on my server, to be integrated in two differents websites (different contents, users, etc). But when a user, created on one Bludit instance (v3.3), this user has also access to the other instance (v2.2), to the admin page, can edit content !

### Expected behavior
complete isolation of every Bludit install.

### Actual behavior
One user created on one bludit install can access other bludit instances

### Steps to reproduce the problem
Install two bludit instances on one same server. Then create one user on the more recent version, connect his user to the backoffice. change the adress to access the other instance back-office : you could access it without connection.

### Bludit version
v2.2 & v3.3

**Comment by gitleif** [comment]
As far as I can se a possible quickfix can be to add this line

`ini_set('session.save_path',realpath(dirname(__FILE__)));`

to the session.class.php file in each bludit instance.

**Comment by Larsene** [comment]
> As far as I can se a possible quickfix can be to add this line
> `ini_set('session.save_path',realpath(dirname(__FILE__)));`
> to the session.class.php file in each bludit instance, (line 12)

Right, this solution works for my usage. Many thanks ! Hope this can be added to future releases !

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
