### ISSUE TITLE
[CORE] [THEMES] Select templates defined in the theme

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#855]
Currently the user can write any text in the field `template` in the options of the new page. Would be good to create a folder inside the theme with templates and show to the user these templates.

## Example
- Active theme`blogx`
- Folder for templates, `/bl-themes/blogx/templates/`
- Template `games`, `/bl-themes/blogx/templates/games.php`
- Template `animals`, `/bl-themes/blogx/templates/animals.php`
- Show to the user in the field `template` = `games` and `animals`

**Comment by naplaya** [comment]
i like to do this. i already have an idea. i could use `$WHERE_AM_I`, currently possible vaues were `home` ans `page` a possible solution were to use $WHERE_AM_I to determine wich template to use. maybe i move home.php and page.php to template folder to
