### ISSUE TITLE
Page Editor - Add a Save and Return Button

### ISSUE THREAD

**Issue by rbnsnlvslms** [bludit/bludit#859]
### Describe your problem
When I hit the save button, it send us to the editor, still editing that page. That is ok.

What I am missing is a save and return button. One that saves the page and return to the content manager.

### Expected behavior
Page editor with a save and return button

### Actual behavior
Page editor with only save button

### Steps to reproduce the problem
1. Enter the content manager
2. Edit one page
3. There you go. Just a save button
4. Hit save
5. You will be in the editor, still editing the same page

### Bludit version
3.3 and it looks the same in 3.4

**Comment by gmbhurgri** [comment]
I have just setup today and I don't think it is necessary. Because of simplicity, less is more. in UI interfaces.

**Comment by dignajar** [comment]
You can click on `cancel` button to return, maybe change the label of the button ?
