### ISSUE TITLE
[PLUGIN] Create plugin to integrate PayPal Button into content page.

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#860]
> PayPal Button Plugin idea, in short, is primarily to allow a `PayPal` button to be placed on selected pages so it would need to hold an array of pages to include the button on.

Further thoughts:
- It would be important to allow the author to decide where they want the button placed, `Top-Left`, `Top-Right`, `Middle-Right`, `Bottom-Right`, etc.
- It would also be important to have an option, Wrap-around button => Enabled/Disabled; so that the page content can flow around the button if desired.
- Looking on the PayPal site, the HTML code for the button (plus detail) is created within the PayPal account and then copy/pasted into the web page, so the plugin would only need to store this HTML code in the array, not create the HTML code.
- Stored the JSON data file in: `$this->workspace().'PayPal-PageButtons.json'` or similar.
- More than one button per page is probably too difficult, so only one button per page.
- Having an option to allow the author to set the padding around the button for each page with a suitable default value.
- Admin setup page would have a dropdown menu to select each item (an Item is a button to go on a page), which when selected would fill in the fields below. It would also have a `New Item` button and a `Delete Item` button.

> This could also be useful for placing any bit of extra HTML in a specific place on a Bludit content page.

**Comment by clickwork-git** [comment]
You can use the code of PayPal.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
