### ISSUE TITLE
Is there anyway to create a new content type?

### ISSUE THREAD

**Issue by gmbhurgri** [bludit/bludit#862]
There are some types of content already like pages, sticky and static etc. 

Custom project specific content type in which custom JSON fields can be added ?

**Comment by dimobelov** [comment]
@glossyweb , each page have in Advanced settings field **Template**. You can set custom template and handle it in your theme: `if ($page->template()== ....):`

**Comment by gmbhurgri** [comment]
@dimobelov Great that is helpful.

Also along with that, can we add more fields in content page ? Say like some other related information of specific content type.

Currently there is only Title and big content box for adding text (rich text editor)

Can we add more fields here, like some more input text fields along with content and title ?
Or is there any other way for adding that data on edit/create page.

I can customize in background if there is workaround available.

**Comment by clickwork-git** [comment]
No, not "out of the box". Bludit is a Content Management System and not a database.

But you can code a plugin for example similar to the contact form.

**Comment by gmbhurgri** [comment]
Okay, I will look at the source code of contact form. Thanks

The issue should be open, may be in future someone make PR to solve it.

**Comment by dignajar** [comment]
Maybe what you are looking for is custom fields (is not implemented).
You can also use the field `template` as Dimo said for this extra field.
Regards

**Comment by dignajar** [comment]
I created a topic related to custom fields for pages.
https://github.com/bludit/bludit/issues/895
