### ISSUE TITLE
Add version parameter to scripts and styles only in Debug mode

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#864]
Now Bludit adds its version to all resources, which is problem to cache them. If possible let it be active only in Debug mode.

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L200

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L214

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L248

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L253

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L258

https://github.com/bludit/bludit/blob/f8b6a0f6d9c60883381432d3592b02bb1ec0e3f0/bl-kernel/helpers/theme.class.php#L264

**Comment by dignajar** [comment]
I added the version for cache only the current version, I saw a lot of user complain about the styles are not updated after update Bludit.
