### ISSUE TITLE
Same image thumbs with Mediumish theme

### ISSUE THREAD

**Issue by davede-git** [bludit/bludit#866]
Hi, is there any fix to have all of thumbs the same size? And why all of thumbs are full images? There should be fix for it. 

Sample:

![zrzut ekranu 2018-11-18 o 15 48 22](https://user-images.githubusercontent.com/3610174/48674151-76055100-eb49-11e8-9a54-c002172ec683.png)

**Comment by ikutaa46** [comment]
i think it depends on theme, some theme using auto same width-height.
Here are a few suggestions to handle it, (for a while)

- Change all thumbnail with same width-height, and reupload it; or

- You can manually edit the home.php; (mediumish theme) find 
`<img class="img-fluid" src="<?php echo ($page->coverImage()?$page->coverImage():Theme::src('img/noimage.png')) ?>" alt="">`

change it to

`<div style="background-image:url(<?php echo ($page->coverImage()?$page->coverImage():Theme::src('img/noimage.png')) ?>); background-size: cover; background-position:center; width:100%; height:250px;">`
`</div>`

**Comment by dignajar** [comment]
Thanks @ikutaa46

**Comment by dignajar** [comment]
I create a new release with this changes.
https://themes.bludit.com/theme/mediumish

**Comment by ilovefreesw** [comment]
Hi. What would you suggest for uneven cards? @ikutaa46  @dignajar 

![image](https://user-images.githubusercontent.com/77317006/173243590-090dd3b8-4636-4334-9d89-6bc32469254d.png)
