### ISSUE TITLE
[ENHANCEMENT] Add settings variable for thumbnail 

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#867]
### Describe your problem
I want a 40x40 pixel for all my thumbnails - default is too big.

### Expected behavior
Too easily set the desired thumbnail size in settings.
Suggest the same for the main photo as well.

### Actual behavior
I have to manually backend edit the variables php file every time an upgrade is done as it gets overwritten.

### Bludit version
All.

Thanks...

**Comment by dignajar** [comment]
Implemented.
https://github.com/bludit/bludit/commit/41f4658bce207fca862acf19af5ff4f5707358ab

**Comment by BlakesHeaven** [comment]
Many thanks.
