### ISSUE TITLE
Image upload fails when extension is in upper case letters

### ISSUE THREAD

**Issue by geromueller** [bludit/bludit#868]
### Describe your problem
Image upload fails when extension is in upper case letters

### Expected behavior
ignore case of extension

### Actual behavior
case of fileextension matters

### Steps to reproduce the problem
upload image from digital cameras, they are often all upper case

### Bludit version
3.1.0

**Comment by clickwork-git** [comment]
There is a fix for this at

![Upload von PDF-, Audio- und Video-Dateien](https://planet-bludit.ch/anpassungen/upload-von-pdf-audio-und-video-dateien)

P. S. This is also the case with Bludit v3.4.0.

**Comment by dignajar** [comment]
Fixed, thank you for report it.

https://github.com/bludit/bludit/commit/45d725c909e50d86b8d91380ef02f09b867abbe8

**Comment by dignajar** [comment]
Implemented in Bludit v3.5, thanks for report it!.
