### ISSUE TITLE
Name and Nickname of users

### ISSUE THREAD

**Issue by bluditbeginner** [bludit/bludit#878]
In configuration of users in admin panel is written as a help-comment that the Nickname is displayed as the name of the author of content.
But the Name, not Nickname is displayed as author.

Bludit 3.4.0

**Comment by clickwork-git** [comment]
Which theme do you use? I think, it depends of the theme.

**Comment by bluditbeginner** [comment]
I'm using Theme Clean Blog.

**Comment by dimobelov** [comment]
Bludit is smart enough to show what you want @bluditbeginner . Look at method -> https://github.com/bludit/bludit/blob/1c2d2a6d99b247d71eb0224463b9df43ea424eae/bl-kernel/pagex.class.php#L214

There you can see how i print First name and Last Name -> https://github.com/blthemes/DevTheme/blob/dc2194a01ab37327f0953f0737695dccf1a49513/php/page.php#L59

**Comment by dignajar** [comment]
Hi,
I do not understand what is the problem.. the theme Clean Blog shows the nickname of the username.

For a page:
- https://github.com/bludit-themes/clean-blog/blob/master/php/page.php#L9

For the home:
- https://github.com/bludit-themes/clean-blog/blob/master/php/home.php#L28

**Comment by bluditbeginner** [comment]
Hi, @dignajar : You are right. I used Version 2.0 of Clean Blog. There is "username" used. In Version 2.1 "nickname" is used.
The issue is handled anymore. Sorry for that I not used the latest Version and wasted your time.
I thought the only change from 2.0 to 2.1 was the delete of Google+. Sorry.
