### ISSUE TITLE
Editor should edit its posts only

### ISSUE THREAD

**Issue by davede-git** [bludit/bludit#885]
Hi

This is an idea that I am looking for. I would like to to see that editor can edit posts written only by itself. At this time, editors in bludit are able to edit/delete posts sent by admin. 

It would be great to have something like simple permission system. For example, we have got 3 users.

- Admin (Administrator)
- yyy (Editor)
- xxx (Editor) 

Admin should be able to delete and edit posts come from yyy and xxx. ✅

User yyy should be able to edit/delete post written only by itself.❎

User xxx should be able to edit/delete post written only by itself.❎

Or another idea is:

Users xxx and yyy aren’t Editors but (let me call the new role) Junior Editors. This role would let them to create and edit their drafts only. The drafts would be able to be accepted by someone whose status is admin. 

Why? They would be able to prepare the post and when they will know that their post done is, they can inform admin to review and accept it.

The idea, I think, would bring us a simple control system if somebody decides to use bludit as a portal. Not everyone want to see new posts on his website without review and users are able to post/edit/delete everything.

**Comment by dignajar** [comment]
Here is the same topic. I would like to have one topic to discuss about it.
https://github.com/bludit/bludit/issues/852
