### ISSUE TITLE
[Plugin] Warning if already an editor is enabled

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#887]
Warning if already an editor is enabled, when a user tries to enable another editor.

**Comment by dignajar** [comment]
I don't get how is related to a Plugin ?
An user with the role `Editor` can not enable another user.

**Comment by clickwork-git** [comment]
This is a misunderstanding... :-D

The suggestion is, that when for example SimpleMDE is enabled, there will be a warning, when somebody also enables TinyMCE.

**Comment by dignajar** [comment]
I got it..
Looks hard to know if a plugin with an editor is already enabled.

Maybe we need to add a new field in the plugins `metadata.json` like plugin `type` where the `type` can be `editor` and check if some plugin with this type is already activated.

**Comment by panosnethood** [comment]
Yes, it took me some time to realize that I had to disactivate first the HTML editor and then activate the TinyMCE one. Otherwise, I was saving the content and it was disappearing without explanation.
