### ISSUE TITLE
Dashboard ideas

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#896]
I would like to discuss what is need it in a Dashboard.
For the moment we have:
- Quick links
- Notifications
- Simple stats

Maybe would be good keep what it's now but improve that items.

**Comment by felixplesoianu** [comment]
One thing I'd like Bludit to tell me is how much storage my database and uploads take up. The size of attached images can be saved to the database at upload time, and the database files themselves can have their size taken every time they are read from disk, which has to happen anyway.

Sure, I can use cPanel (or `du` as the case may be) to see for myself how much space is being used, but by the same logic I don't need visitor stats in Bludit either. A quick overview is good to have.

**Comment by SamBrishes** [comment]
Hellow,

this is not an idea for an widget, but for the dashboard page in general. It would be really nice, if you could "adapt" / "move" the single widgets to personalize this page. Somehow like this:

![dashboard](https://user-images.githubusercontent.com/31392477/51425532-6ce24000-1bdd-11e9-9f06-c2d585290bee.gif)

-------

I had to change the CSS / HTML structure (at least for the "Hello Message" and "Quick Links" Panel) and included the [html5sortable](https://github.com/lukasoppermann/html5sortable) library as well as the following snippet:

```javascript
sortable(".sortable-left", {
    acceptFrom: ".sortable-right,.sortable-left",
    handle: "h4",
    forcePlaceholderSize: true,
    placeholder: '<div style="border:1px dashed blue;"></div>'
});
sortable(".sortable-right", {
    acceptFrom: ".sortable-left,.sortable-right",
    handle: "h4",
    forcePlaceholderSize: true,
    placeholder: '<div style="border:1px dashed blue;"></div>'
});
```

Sincerely,
Sam.

**Comment by Joduai** [comment]
I'd definitely go with a small todo list window in dashboard for quick notes.
There are always lots of small things todo after loggin in (for example things to do when writing an article; or ideas for next one) , and storing them in a visible place would be great. Along with a way to edit them.

As it goes to simple stats, showing hits per page would be great.
Btw, the plugin counts every refresh for a logged in user. Imo it shouldn't.

**Comment by BlakesHeaven** [comment]
Hi @Joduai, re
`As it goes to simple stats, showing hits per page would be great.
Btw, the plugin counts every refresh for a logged in user. Imo it shouldn't.`
FYI, I am so close to putting in a pull request with a big ENHANCEMENT to Simple Stats, which also fixes the refresh issue.

**Comment by BlakesHeaven** [comment]
Hi @Joduai, the plug-in "Simple Stats Plus" became available a little while back as an alternative.
https://plugins.bludit.com/plugin/simple-stats-plus#download
