### ISSUE TITLE
Undefined variable: tmp in .../ajax/get-published.php on line 34

### ISSUE THREAD

**Issue by SamBrishes** [bludit/bludit#897]
Hellow,

### Describe your problem
The AJAX call to the `ajax/get-published.php` file ends up with the following error, if no page could be found. This error is only recognizable in the Browser console, of course.

`Undefined variable: tmp in .../ajax/get-published.php on line 34`

### Expected behavior
Just return an empty ARRAY, NULL or false, or something like this. I'm not sure, but the `$list` variable within the file looks like it should hold the requested pages instead of `$tmp` (otherwise `$list` would be unused).

### Actual behavior
It returns the error.

![error-1](https://user-images.githubusercontent.com/31392477/50536108-45a1d100-0b51-11e9-9a91-935b9500b9cd.JPG)
![error-2](https://user-images.githubusercontent.com/31392477/50536109-45a1d100-0b51-11e9-8a86-4501b88e2232.JPG)

### Steps to reproduce the problem
Visit the bludit configuration page, go to "Advanced" and type in something weird in the field `Homepage` (below `Predefined pages`).

### Bludit version
Version 3.5.0

**Comment by dignajar** [comment]
Hi, I just release a new version of Bludit take a look, and provide a fix for the issue. Thanks.
