### ISSUE TITLE
[PLUGIN] TinyMCE & blockquote error.

### ISSUE THREAD

**Issue by RolandTi** [bludit/bludit#903]
Hello, 
using the blockquote html element with TinyMCE is making an error with the implantation of
`blockquote::before {content: open-quote;} blockquote::after {content: close-quote;}`.
Because instead of inserting `<blockquote>blablablabla…` TinyMCE add a `<p>` element.
There is no need.
Thanks !

### Bludit version 3.5

Actual
<img width="505" alt="capture d ecran 2019-01-01 a 00 40 26" src="https://user-images.githubusercontent.com/28786873/50575407-465f8f00-0dff-11e9-8cfb-2ad90dac6a5d.png">

Corrected
<img width="486" alt="capture d ecran 2019-01-01 a 00 42 54" src="https://user-images.githubusercontent.com/28786873/50575408-46f82580-0dff-11e9-9998-ce7ad5bb747c.png">

**Comment by dignajar** [comment]
Hi, maybe is some configuration of TinyMCE ?

**Comment by dignajar** [comment]
Have you found some solution ?

**Comment by dignajar** [comment]
Hi, I just release a new version of Bludit take a look, and provide a fix for the issue. Thanks.

**Comment by RolandTi** [comment]
Hello ! Thanks you very much for your reply and the fix :-)
I wrote an email to the TinyMCE Staff and they said I had to buy a licence for an answer.
