### ISSUE TITLE
share plugin or theme

### ISSUE THREAD

**Issue by ejamshidiasl** [bludit/bludit#905]
Hello
i made some plugins and themes.how i can send these plugins and themes to you?

**Comment by SamBrishes** [comment]
Hellow,

you can create a new pull request on the official [plugin repository](https://github.com/bludit/plugins-repository) or [themes repository](https://github.com/bludit/themes-repository) or you share your projects on bludits [Forum](https://forum.bludit.org/).

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi,
I recommend uploading the source code of the plugins and themes in Github or similar to keep track of versions and changes.
Regards
