### ISSUE TITLE
Content Type and custom Fields | Tipos de Contenidos y Campos personalizados [improvement]

### ISSUE THREAD

**Issue by G3N-es** [bludit/bludit#906]
---
---EN---
---
- Introduction
-- Categories as a type container
-- Advantages of custom fields in content types
- Implementation
- Data model

### # Introduction

This proposal tries to simplify the conception of types of content taking advantage of the existing structure in Bludit as much as possible.

#### Categories as the type container:

A category by definition tends to group types of content.

---
** Examples: **

"Cooking Recipes" is a category. The associated content will tend to have special defined fields, a logical template linked to the content category:

- Ingredients: (contains a list of ingredients)
- Preparation phases: (contains a list of the steps necessary to make the meal)

---
The same applies to any other type of category "Products: price, reference ...", "Photography: Author, place, exif ...".
We usually create unconscious logical templates. These develop directly in the body of the text. They are present in an abstract, non-physical way, since implicitly a category "Recipe" necessarily includes "Ingredients", and "Phases of preparation" in their logic.

However, we can structure with predefined custom fields, instead of improvising templates by hand in the body of the text.

#### Advantages of custom fields in content types
The advantages of using custom fields are obvious.

- Simplicity for the author: you already have the physical template to complete.
- Potential for the developer: You can represent these contents in the subject in an accurate way. Develop special modules for unlimited purposes.

### # Implementation:

We start from saying that type of content and category is equivalent.

It would be as simple as adding a field "Special Fields" after description in the categories. This field would contain a list separated by commas.

---
** Example from category editor: **

Category
[Kitchen Recipes]

Description
[Cooking to taste of you and yours]

Special fields
[Ingredients, Preparation phases]

---
** Example from the content editor: **

When selecting the Cooking Recipes category, the fields to be filled out automatically appear:

[Title ]

Ingredients [+ Add value value](#)
Preparation phases [+ Add value value](#)

[Content text]

---
** Example completed: **

[Roscón de Reyes]

Ingredients [+ Add value value](#)
- [Ingredient one 250 g] [- Deleted value](#)
- [Ingredient two 350g] [- Deleted value](#)

Preparation phases [+ Add value value](#)
- [Phase one to simmer such and such] [- Deleted value] (#)
- [Phase two cut into thin slices such and which] [- Deleted value] (#)

[Content text]

###  # Data model

To simplify the database you could save the data like this:

```
        "Special Fields": {
            "Ingredients": ["ingredient1", "ingredient2", "ingredient3"],
            "Preparation phases": ["Phase1", "Phase2", "Phase3"]
         }
```

---
---ES---
---

- Introducción
-- Categorías como contendedor del tipo
-- Ventajas de campos personalizados en tipos de contenido
- Implementación
- Modelo de datos

### # Introducción

Esta propuesta intenta simplificar la concepción de tipos de contenidos aprovechando en la medida de lo posible la estructura existente en Bludit.

#### Categorías como contendedor del tipo:

Una categoría por definición tiende agrupar tipos de contenidos.

---
**Ejemplos:**

"Recetas de Cocina" es una categoría. El contenido asociado va a tender a tener unos campos definidos especiales, una plantilla lógica ligada a la categoría de contenido:

- Ingredientes: (contiene un listado de ingredientes)
- Fases de preparación: (contiene un listado de los pasos necesarios para realizar la comida)

---
Lo mismo ocurre con cualquier otro tipo de categoría "Productos: precio, referencia...", "Fotografía: Autor, lugar, exif...".
Solemos crear de forma inconsciente plantillas lógicas. Estas se desarrollan directamente en el cuerpo del texto. Están presentes de una forma abstracta, no física, ya que implícitamente una categoría "Receta" incluye forzosamente "Ingredientes", y "Fases de preparación" en su lógica.

Sin embargo, podemos estructurar con campos personalizados predefinidos, en vez de improvisar plantillas a mano en el cuerpo del texto.

#### Ventajas de campos personalizados en tipos de contenido
Las ventajas de usar campos personalizados son evidentes.

- Sencillez para el autor: ya tiene la plantilla física a cumplimentar.
- Potencial para el desarrollador: Puede representar estos contenidos en el tema de forma precisa. Desarrollar módulos especiales con finalidades ilimitadas.

### # Implementación:

Partimos de que decir tipo de contenido y categoría es equivalente.

Sería tan sencillo como añadir un campo "Campos Especiales" tras descripción en las categorías. Este campo contendría un listado separado por comas.

---
**Ejemplo desde editor de categorías:**

Categoría
[Recetas de Cocina]

Descripción
[Cocinar para deguste de ti y los tuyos]

Campos especiales
[Ingredientes, Fases de preparación]

---
**Ejemplo desde el editor de contenido:**

Al seleccionar la categoría Recetas de Cocina, automáticamente aparecerían los campos a cumplimentar:

[Titulo ]

Ingredientes [+ Añadir valor valor](#)
Fases de preparación [+ Añadir valor valor](#)

[ Texto de contenido ]

---
**Ejemplo cumplimentado:**

[Roscón de Reyes ]

Ingredientes [+ Añadir valor valor](#)
- [Ingrediente uno 250 g]   [- Eleminar valor](#)
- [Ingrediente dos 350g]   [- Eleminar valor](#)

Fases de preparación [+ Añadir valor valor](#)
- [Fase uno calentar a fuego lento tal y cual ]  [- Eleminar valor](#)
- [Fase dos cortar en rebanadas finas el tal y el cual]  [- Eleminar valor](#)

[ Texto de contenido]

###  # Modelo de datos

Para simplificar la base de datos podría guardar así los datos:

```
        "CamposEspeciales": {
            "Ingredientes": ["ingrediente1","ingrediente2","ingrediente3"]  ,
            "Fases de preparación": ["Fase1","Fase2","Fase3"]
         }
```

**Comment by DivineDominion** [comment]
I wonder: wouldn't it be possible to not add more metadata to the core, but to a plugin, and instead make the core ignore in-text data blocks?

I'm thinking about YAML metadata. You can have a YAML frontmatter block in e.g. a Markdown document like this:

```markdown
---
title: "Redundant title because Bludit stores it in its DB"
"Ingredients": ["ingredient1", "ingredient2", "ingredient3"],
"Preparation phases": 
  - "Phase 1 is very long and complicated"
  - "Phase 2"
  - "Phase 3"
---

The actual text that is not metadata. **Supports markdown**. Wow.
```

Static site generators use YAML frontmatter for all metadata; Bludit has its own "database" file for this (sadly), so `title` would not be useful, but all other customizations would.

This way, the YAML can be extracted with any PHP YAML library _by the Bludit core_, and ignored during rendering of the page's content. The YAML metadata would be stored in a dictionary/has map as `Page::getYAML()`, similar to `Page::getDB()`. This is then processed for display by e.g. a `Recipes` plugin, or by a theme template.

A plugin could even add itself to the page creation/edit hooks to parse YAML and add the frontmatter fields to the DB -- that should improve performance over ad-hoc YAML parsing.

I think this content-based approach is superior to expanding the database because you don't need any editor UI. You can use the plain text editor. And you can process (or _not_ process) the result any way you want.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
