### ISSUE TITLE
Usage Issue with Images with single quote in name

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#907]
### Describe your problem
It seems that if an image has a single quote in its name, e.g. "RobinHood<b>'</b>sBay2015.jpg", it can be uploaded but it can **not** be used or deleted.

### Expected behaviour
Preference: Allow image to be used with its correct name.
Secondary option: Automatically strip the offending character(s) from the file name.
Third option: prevent upload of the invalid file name with a suitable message.

### Actual behaviour
Can't set the image as cover or delete the image.

### Bludit version
v3.5

**Comment by dignajar** [comment]
Hi,
yes is a bug, because in the JavaScript function doesn't escape the quote.

I'm thinking to remove special characters from uploaded files, what do you think ?

**Comment by BlakesHeaven** [comment]
Hi, that would be a suitable resolution and probably the easiest. 
Many thanks.

**Comment by dignajar** [comment]
I Don’t want to bother the user like why Bludit is changing the file names, but is just remove quotes.

**Comment by BlakesHeaven** [comment]
> I Don’t want to bother the user like why Bludit is changing the file names, but is just remove quotes.

Sounds sensible; especially as it would only be for info at runtime. If necessary it could be mentioned in the documentation.

**Comment by dignajar** [comment]
Hi, I just release a new version of Bludit take a look, and provide a fix for the issue. Thanks.

**Comment by BlakesHeaven** [comment]
Thanks, Diago
