### ISSUE TITLE
Flat Databases and preformance problems.

### ISSUE THREAD

**Issue by RubyTheRose** [bludit/bludit#908]
I've recently installed **Bludit** onto my server, and looked into the source for the data storage. However, I'm a little concerned for heavier loads multiple instances accessing the file at the same time. For example, say the users file was attempted to be updated within the same second, how would it handle that?

Would it just ignore the newer modification due to the file lock, or would it fail completely?
Thanks for reading this, I'd love to hear your input.

**Comment by RubyTheRose** [comment]
Okay, I plan on extending the capability of the site to introduce guest users (via registration), so I'm a little worried for that, If the file is locked while another attempt tried to modify it, what happens?

**Comment by dignajar** [comment]
I don't know how you are going to implement it, but read about lock files in PHP.
http://php.net/manual/en/function.flock.php

**Comment by RubyTheRose** [comment]
So it just returns false on fail, It is possible to have a queue like thing? Like if it's already being updating wait or add to queue then preform action.

**Comment by dignajar** [comment]
Depends on of the function you are using to write files if you are using `file_put_contents` is going to return false.

http://php.net/manual/en/function.file-put-contents.php

```
if (file_put_contents( xxxx, LOCK_EX ) )
{ echo 'ok';}
else { echo 'locked' }
```

**Comment by RubyTheRose** [comment]
So a queue would be possible, but is it optimal?

**Comment by dignajar** [comment]
yes is possible but escape from what is Bludit this conversation, I recommend read about lock files and how PHP deal with them, for sure exists some library.

**Comment by RubyTheRose** [comment]
I want to extend Bludit with minimal to no modifications to the core, so updates aren't effected,

**Comment by dignajar** [comment]
Hi, I just release a new version of Bludit take a look, if you still have an issue feel free to create a new issue. Thanks.
