### ISSUE TITLE
[CORE] Directory name same as page key for images

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#909]
The media manager save the images per page, the directory created is the UUID of the page, would be good the directory name is the same as the page key or create a symlink.

**Comment by BlakesHeaven** [comment]
Sounds like a better idea than UUID though I do use "imageRestrict": false as I prefer a central image location so I can reuse images.

**Comment by dignajar** [comment]
Now I remember why I did this, because at the begging whe the user is creating a page doesn’t exist the page key, but exists the uuid. Is possible to do the same and rename the folder after the page is created, another problem is rename the folder each time the user changed the page key.
