### ISSUE TITLE
Sidebar in admin not accessible if window is too small horizzontally

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#914]
If i split my screen in two sides on an a standard desktop resolution the admin sidebar is hidden and apparently there is no way to interact with it.

**Comment by signalguest** [comment]
Nevermind i noticed there is a top bar. I was tunnel visioned by the fact that i excepted something on the left side.

**Comment by signalguest** [comment]
It depends on the size!
Between some size there is no sidebar and no topbar.
Maybe we should be sure to get the topbar at the time the sidebar disappear?

**Comment by dignajar** [comment]
Hi, I uploaded a bug fix related, can you update this line, https://github.com/bludit/bludit/commit/fd29f1ce1167498e3e78e5406efc2230204ac818

**Comment by signalguest** [comment]
Working great 👍
