### ISSUE TITLE
Table in TinyMCE

### ISSUE THREAD

**Issue by LuNiKoFf** [bludit/bludit#923]
### Describe your problem
When I add « table » to the tinyMCE plugin paramater, plugin works but plugin toolbar never hides when finish.
### Expected behavior
plugin toolbar hides himself when we click
### Actual behavior
plugin toolbar stay on top

### Steps to reproduce the problem
add « table » to tinyMCE plugin and simply add a table in a page
### Bludit version
3.6.1

![screenshot-2019-1-25 bludit - modifier le contenu -](https://user-images.githubusercontent.com/6583018/51754712-4f214900-20bd-11e9-9daf-8ddd49b052e9.png)

**Comment by dignajar** [comment]
Hi,
I found the bug, I uploaded the plugin again, can you download the plugin from here https://github.com/bludit/bludit/tree/master/bl-plugins/tinymce

Regards

**Comment by LuNiKoFf** [comment]
Hi,
I updated the plugin. Perfect !
Thx, regards !
