### ISSUE TITLE
[PLUGIN] Search Plugin - Improve interaction

### ISSUE THREAD

**Issue by laz00r-cat** [bludit/bludit#927]
### Describe your problem

When using the search plugin that comes with Bludit, a value can only be submitted by using the 'Search' button and not by pressing the Return key.
Additionally, the code doesn't use the _form_ tag but only relies on _input_ tags. This should be improved for better accessibility. 

### Expected behavior

When performing a search with the standard plugin, one should be able to type the search term and press Return to perform search.

### Actual behavior

Sending the search query by pressing Return is not possible. One has to click the 'Search' button.

### Steps to reproduce the problem

Enable search plugin and perform a search.

### Bludit version

3.61 (20190116) with search plugin enabled

**Comment by dignajar** [comment]
Implemented, also I add the feature to show or not the button `Search`.
