### ISSUE TITLE
Pull changes for remote content

### ISSUE THREAD

**Issue by kimamil** [bludit/bludit#928]
### Describe your problem
Several scenarios ask for a pull functionality when using remote content. For example when I am trying to connect an existing repository. I will have to make an unnecesary push in order to trigger the webhook.

### Expected behavior
I would like to have a button on the contents page if the remote plugin is used to manually trigger the pull.

### Actual behavior
No pull possibility at all.

### Steps to reproduce the problem
Try to connect an existing repository without an unnecessary push.

### Bludit version
3.6.1

**Comment by kimamil** [comment]
I mean, when I press the button, it should kick off same procedure as if it received a webhook ... (grabbing .zip file, unzip it, clean pages ... etc.)

**Comment by dignajar** [comment]
The button for trigger was implemented in 3.7.1
