### ISSUE TITLE
[ENHANCEMENT] Advance Setting to control sort order of both parents & children separately

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#935]
### Describe your problem
I need to sort Parent posts descending and child post ascending.

### Expected behaviour

1. Please add a setting option to control the **sort order** of both parent posts and child posts separately.
2. The same should apply to both order content whether sorted by Date or Position
3. The same should apply to posts on the website and in the admin/content
4. If Date/Position are the same, the configured asc/desc setting should also apply to order the same by Title

Example order by date:
```
2019-01-01 - Parent
    - 2019-01-05: Child A
    - 2019-01-10: Child B
    - 2019-01-15: Child C
2018-12-01 - Parent
    - 2018-12-05: Child A
    - 2018-12-10: Child B
    - 2018-12-15: Child C
```

Example order by position:
```
2 - Parent
    - 1: Child A
    - 2: Child B
    - 3: Child C

1 - Parent
    - 1: Child A
    - 2: Child B
    - 3: Child C
```

### Actual behaviour
Everything is ascending which means posts are ordered incorrectly and in the admin/content page the latest post entered is on the last pagination page at the bottom. 

### Bludit version
3.6.1

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
