### ISSUE TITLE
PHP7.2 Session initialization failure.

### ISSUE THREAD

**Issue by handfest** [bludit/bludit#938]
After changing from PHP7.0 to PHP7.2 on my Synology an error "Bludit CMS. Session initialization failure." occurs when I request the start page https://xxxx.xx/admin/

Changing back to PHP7.0 Bludit works fine

### Bludit version
3.7.0 downloaded today from Github als well as latest stable version 3.6.1 from webpage

**Comment by dignajar** [comment]
Do you use some webserver or just php buil-in server ? I would like to test it, I have a Synology with PHP 7.2

**Comment by handfest** [comment]
I am using the current Web Station (Sync Package, actualized today) together with the PHP 7.2 package which could be loaded directly via Packet Center. I took the same PHP Profile as for 7.0 without any changes.

**Comment by handfest** [comment]
Sorry, Reason was obviously missing path /tmp in open_basedir
Was also marked inside the server log of Apache 2.4...

Mea culpa

**Comment by dignajar** [comment]
When you do an installation from scratch, Bludit try to create `/bl-content` and write on it, if not possible an alert is popup, but if you already has a Bludit installed and you do some changes, Bludit do not check this permissions again.

What I'm thinking is create some kind of plugin checker and do some test in the system.
