### ISSUE TITLE
[idea] Category Order by: property and decimal position

### ISSUE THREAD

**Issue by G3N-es** [bludit/bludit#939]
Add the property "sort by: Date or position" to the categories.

This would allow to have a category for the blog and corporate or other categories and that each one work properly.

In addition, it would also be nice to add a customizable property, so that the plugins could have a place to work.

---

On the other hand I have detected an inconvenience in the ordering by bludit position.

If you want to reorder a page, you need to go one by one ordering all the pages.

Example:

1- About Us
2- Our work
3- Company philosophy
4- Legal notice

Now I want to put a new page after "About Us":
2- Important changes

OPS! ... I have to enter our work, change position to 3, save, company philosophy, change to 4 etc.
One possible solution is to admit decimals to order.

1,1- Important changes

Or that the ordering was alphabetic:

a-
aa-
b-
c

**Comment by BlakesHeaven** [comment]
Thumbs up.
For any work on Order By, please consider option to sort ascending or descending.
Link to #935 regarding sorting parent/child separately.

BTW, I use position sorting on one site and have played with position numbers like
201901010100 (yyyyMMddHHmm).
Bit long maybe, but offers lots of scope for moving things around.

**Comment by dignajar** [comment]
Here is the function to sort by position, if someone want to improve it for support floats.

https://github.com/bludit/bludit/blob/master/bl-kernel/pages.class.php#L535-L543

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
