### ISSUE TITLE
[Bug] Javascript error at image uploading

### ISSUE THREAD

**Issue by MoritzBrueckner** [bludit/bludit#940]
### Describe your problem
Images can't get uploaded anymore (I think it is the case since Bludit 3.7)

### Expected behavior
The image gets uploaded successfully and is displayed below the progress bar.

### Actual behavior
The progress bar of the image upload remains at 100% and nothing more happens. If you take a look at the console, it says:
![bludit_upload_bug](https://user-images.githubusercontent.com/17685000/51901224-6e6aef80-23b7-11e9-9481-e3707ef1c174.jpg)
```
TypeError: cannot use 'in' operator to search for 'length' in 'Out of index.' jquery.min.js:2:3515
C                /bl-kernel/js/jquery.min.js:2:3515
each             /bl-kernel/js/jquery.min.js:2:2534
displayFiles     /admin/new-content:564:3
getFiles/<       /admin/new-content:597:4
u                /bl-kernel/js/jquery.min.js:2:27452
fireWith         /bl-kernel/js/jquery.min.js:2:28202
k                /bl-kernel/js/jquery.min.js:2:77649
n/<              /bl-kernel/js/jquery.min.js:2:79907

```
### Steps to reproduce the problem
Create a new page and try to upload an image.

### Bludit version
3.7.1 - seems that it got introduced after 3.7

**Comment by dignajar** [comment]
Hi,
this is a clean installation ? can you check the php_error.log ?
I'm testing and I cannot reproduce it.
Thanks

**Comment by dignajar** [comment]
Can you show me the network tab this two requests.
<img width="1158" alt="screenshot 2019-01-29 at 20 37 48" src="https://user-images.githubusercontent.com/507352/51935262-ce888280-2405-11e9-8743-f7324bec045a.png">

**Comment by Momel15** [comment]
Hi,

no, it is not a clean installation if that means that it is the only version that was installed for this blog. I recently updated from 3.6.something to 3.7.1. I will check if copying the 3.7 version again will resolve the issue.

I'm running the server on xampp for development purposes and I'm not sure whether my log file config isn't correct or I didn't have any php errors yet, but there is no php error log. I will also investigate that, but I have not much time until saturday evening, so it might take a few days.

Do you use chrome? I'm using Firefox and it has a network analysis tab too but it looks a little bit different (but has the same filter settings like in your screenshot, xhr, css, img etc.):
![bludit_upload_bug2](https://user-images.githubusercontent.com/17685000/52015296-f3eabe80-24e1-11e9-8add-41a649b48dbc.jpg)
What should I look for, or should I just install chrome to get this debug view?

**Comment by dignajar** [comment]
I feel is some problem in PHP, like image size or some restriction, I forgot to mention you need to enable debug mode, this line https://github.com/bludit/bludit/blob/master/bl-kernel/boot/init.php#L11

After enable the logs, you can try to upload an image and then check the php logs.
Here are a few places where XAMPP save the logs, https://stackoverflow.com/questions/3719549/where-does-phps-error-log-reside-in-xampp

I did some changes to improve the Media manager, if you have time try to update these files:
https://github.com/bludit/bludit/blob/master/bl-kernel/admin/themes/booty/html/media.php
https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/delete-image.php
https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/list-images.php
https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/upload-images.php
https://github.com/bludit/bludit/blob/master/bl-kernel/functions.php

**Comment by MoritzBrueckner** [comment]
Thank you very much! Yes, it was the file size indeed.

Is there a way to check this value (php_value upload_max_filesize?) in the code and display an error/warning message in the UI? That would be great :)

You can close this issue (I leave it open so you don't miss this answer) and thank you again :)

**Comment by dignajar** [comment]
Yes I need to do something with that, at least some alert.

**Comment by dignajar** [comment]
I include the alerts for Maximum load file size and file type supported.

https://github.com/bludit/bludit/commit/088179f1fb6acf613086d31dce4555d84ba0ac8d

Thanks for the feedback.

**Comment by MoritzBrueckner** [comment]
Thank you very much :)

**Comment by sokay** [comment]
Thanks for this patch! Helped me figure out I had the upload limit set too low for my dev server.
