### ISSUE TITLE
[ENHANCEMENT] Images relative to parent

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#949]
### Describe your problem
There are two settings to control images and two options to define where images are loaded to... 
- Old way --> `/bl-content/uploads/`
- New way-->  `bl-content/uploads/pages/<PAGE>/`

With more images being uploaded I begin to see why storage against pages makes for easier management of images, however, I feel that it would be a nice middle ground to store images used in child pages against the parent. Also, I would like the usage of images to be relative to the parent.

In my site, extensive use of Parent/Child pages are used and images shown in the children pages have the thumbnail displayed in the parent as part of a table of contents.

### Expected behaviour
Previously in #803, it was stated:
> To keep compatibility with the old structure, I add two fields to the database /bl-contnet/databases/site.php.
> - Field **_imageRestrict_** if you set true then use the new structure, images per page.
> - Field **_imageRelativeToAbsolute_** if you set true the image like <img src="image.png> are convert on the fly to `<img src="https://example.com/bl-content/uploads/image.png>`

Add  site.php option to upload images to parent location, eg **_UploadImageToParent_** = true
If a page is a **child** set images to be uploaded to the **parent** in the new way, i.e. `bl-content/uploads/pages/<PARENT PAGE>/`

Please add option like **_imageRelativeToParent_** and if you set it true then image like <img src="image.png> are converted on the fly to:

- `<img src="https://example.com/bl-content/uploads/pages/<PARENT PAGE>/image.png>`
- `<img src="https://example.com/bl-content/uploads/pages/<PARENT PAGE>/thumbnails/image.png>`

### Bludit version
3.2 to 3.7.1

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
