### ISSUE TITLE
[Plugin] Search Plugin doesn't search through static pages and tags

### ISSUE THREAD

**Issue by laz00r-cat** [bludit/bludit#952]
### Describe your problem

When using the search plugin that comes with bludit, results from static pages and tags are not shown.

### Expected behavior

The search plugin should take into account different sorts of information from pages and posts when performing a search.

### Actual behavior

Only entries showing results from posts are shown.

### Steps to reproduce the problem

A) Create static page with unique search word. Search for that word. Static page will not be displayed.
or
B) Apply tag to post. Tag must not appear in the text field of the post. Search for the tag name. Post will not be displayed.

### Bludit version

3.7.1 (20190128) with search plugin enabled

**Comment by Joduai** [comment]
@laz00r-cat got a question about search.
Aside of static pages and tags, does the search actually show the pages containing only the phrase?
I see that also posts without the phrase are shown in search results.

**Comment by dignajar** [comment]
Fixed!
