### ISSUE TITLE
Cover images 

### ISSUE THREAD

**Issue by orasis1** [bludit/bludit#957]
Cover images get deleted/corrupted when activating and deactivating certain plugins (search, static pages, categories).  

Cover images should not be effected.  

Add a few post with a cover image - > activate and deactivate plugins -> change theme -> eventually cover images disappear or become corrupted. 

Version 3.7.1

**Comment by dignajar** [comment]
I can not reproduce the bug.
It's really strange that happen, plugins or themes doesn't have any relation with cover images.
Can you check you php_error.log ? and give me an example of which plugin are you activate and deactivate ?

**Comment by orasis1** [comment]
Sorry about the delay. Yes, I will check the log. I will try to reproduce
the error again and take step by step notes. All I have at present is my
memory and it fails me as to what plugins and in what order were
activated/deactivated.
