### ISSUE TITLE
Problem with automatic disconnections

### ISSUE THREAD

**Issue by MyNameIsTroll** [bludit/bludit#958]
### Describe your problem
When I am in the administration part I have disconnections somemtimes when I apply a modification by pressing the save button sometimes when I simply click on a link in the administration menu (example: content). I can't reproduce the bug, but it happens to me all the time, every time I use it. The disconnection sends me back to the login page and my changes have not been saved.
I use firefox 65 on Debian.
I don't know if other people have encountered this problem.

### Bludit version
Bludit Version | 3.7.1

**Comment by MyNameIsTroll** [comment]
It seems that the problem is related to the configuration of my browser (Firefox). I tried to reproduce it on another computer with Firefox but I didn't encounter any problems. I guess it must be an additional module that causes this. I have to test it.

**Comment by dignajar** [comment]
do you have access to the php_error.log ?

**Comment by MyNameIsTroll** [comment]
Unfortunately no, I unzipped it in a simple web hosting, I don't have access to the console.

**Comment by clickwork-git** [comment]
How do you login? With the option "Remember me" checked or not?
