### ISSUE TITLE
Impossible to save my mastodon nickname

### ISSUE THREAD

**Issue by MyNameIsTroll** [bludit/bludit#959]
In the social networks section, it is impossible to save my mastodon nickname. All the others apparently work but not mastodon. 

Bludit Version | 3.7.1

![test](https://user-images.githubusercontent.com/31790025/52851976-51e8ea00-310f-11e9-9a77-16d21e941fc1.gif)

**Comment by dignajar** [comment]
Fixed, thanks for report it!
