### ISSUE TITLE
Vanishing article after saving the content

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#960]
### Describe your problem
Sometimes I forgot to add labels to my article, such as Joomla, WP, etc...
So I save my article, then I want to add them to the article after I want to save the article, this problem happens.

### Expected behavior
Save the content

### Actual behavior
It deletes the article 

### Steps to reproduce the problem
Add title and content, save the content, click on the option to add the labels, save the article again. 
Sometimes articles removed from the editor.
### Bludit version
3.7.1 (Persian language)

**Comment by dignajar** [comment]
Hi,
I'm trying to reproduce the problem but I can't.
We you are talking about labels are tags ? can you check the php_error.log from your installation ?

**Comment by abdulhalim** [comment]
Hello Diego,
Actually, there is no problem with tags ( yes I mean tags ), there is a problem with editing only, maybe with my server. 
I create a video cast you can check it. also, you can check my blog if you need.
https://screencast-o-matic.com/watch/cqn3Fg0iea

**Comment by dignajar** [comment]
Hi,
thanks for the video, so at the end is when you edit the content of the post and click on save.
Maybe is a javascript problem, I'm not sure what is you browser (chrome, firefox, edge), can you open the inspector, for example in chrome (right click in the page, in the menu select inspect), and go the tab `console`, then click on save button.

<img width="1411" alt="screenshot 2019-02-23 at 11 34 59" src="https://user-images.githubusercontent.com/507352/53285277-137eab00-375f-11e9-8eaf-d20d7bd8f97a.png">

**Comment by abdulhalim** [comment]
Hello,
I tested it on GC and FF, the latest version, the only message in the console is [INFO] Function showAlert() called.
there is no error, I check it on the localhost, I can't reproduce the issue.
I sent you the details of my website on the forum. please check it.
thanks

**Comment by Joduai** [comment]
> I'm trying to reproduce the problem but I can't.

I've just fallen into similar - if not exact same - problem when saving post and it seems to be complex and serious as it leads to content loss.

It happens using both tinymce and simplemde editors with a slight difference.

When page's description field is empty and I use <pre> or <code> tags, whole content is being saved in page's description field. Of course it's trimmed to fixed amount of chars so I can't just copy->paste everything I wrote.
After the description field is filled, and I use again above html tags, the content is saved and then loaded into editors field. But sometimes using tinymce the content isn't loaded. It happens rarely thus I cannot reproduce it.
I suppose that not only pre and code tags are the cause such behaviour because abdulhalim didn't use them in his screencast. He should show how does source code looks before he saves the page.

I've just recently updated to v3.8.0 but I suppose v3.7.1 is also affected.

**Comment by abdulhalim** [comment]
Hello Joduai,
My problem is about all tags, no matter if I use code or pre tags, I know my content will disappear first I create a copy from the code section, I save the content, after the content in the editor removed, I put my copy in the code editor and save them again. 
It is the only solution for me

**Comment by anaggh** [comment]
Seems like content is lost on Save when SimpleMDE and TinyMCE are both active at the same time. @abdulhalim Are there any other editor plugins active apart from the one you are using?

**Comment by abdulhalim** [comment]
Content lost only in the edit, for the first time there is no problem.
I never activated the Simple MDE.

**Comment by Joduai** [comment]
> Seems like content is lost on Save when SimpleMDE and TinyMCE are both active at the same time.

Tested it one more time.
When it goes to active editors I had only one of them active, so I haven't step on the problem when two of them are enabled.

Looks like used tags doesn't matter, as @abdulhalim described.

New content  is being saved correctly for the first time.
First edit and resave - when description field is empty - leads to content lost (index.txt file is emptied)
Pasting some content and saving 2nd time makes it work again, when the descirption field is filled automatically [I'd say automagically].

But when I fill description field before first save it seems to prevent data loss.

Same happens using tinymce and simplemde.

**Comment by Joduai** [comment]
@abdulhalim  tell me, do you have 'blthemes' plugin installed?

**Comment by dignajar** [comment]
I'm digging in the code but I don't found a real bug.
Someone can download this file and upload to your current installation and make the test ?

https://github.com/bludit/bludit/blob/master/bl-kernel/pages.class.php

**Comment by dignajar** [comment]
Wait, I have some problem with the push..

**Comment by Joduai** [comment]
@dignajar I'm testing a fresh temp installation, wait a second as it might be the problem of a 3rd party plugin. I suppose it doesn't be to be active.

**Comment by dignajar** [comment]
Ok I push the changes, as I said is not a bug, but I improved a little the code when the page is edited.

Try with this new file:
https://github.com/bludit/bludit/blob/master/bl-kernel/pages.class.php

**Comment by Joduai** [comment]
@dignajar 5kb less doesn't sound like "a little improvement" ;)
With simplemde everything works fine with new pages.class.php
Problem with saving was caused by 'blthemes' plugin.
I will have to make changes in theme's code and use default search functions provided in default theme.

**Comment by dignajar** [comment]
@abdulhalim can you do the same and update the file ?

**Comment by Joduai** [comment]
@dignajar btw funny part, as I was digging the search functions provided in devtheme I see that search results show pages that doesn't contain search phrase. Checked on default blogx  and alternative themes.

**Comment by abdulhalim** [comment]
I update the file but the Bludit doesn't work anymore, it opens Github similar page with some dummy data.
And as @Joduai said, the problem is about the bltheme plugin, I disable it and it works for now.

**Comment by Joduai** [comment]
@abdulhalim you need to download raw php code, or just copy the php code and paste into the file.
As for now I'm 100% sure you copied whole github page html which also contains the php code, but it won't work.

**Comment by abdulhalim** [comment]
Yes you right, my bad.
I upload the file everything is OK right now. 
but I disable the bltheme plugin.
I will check the system several time again and inform you

**Comment by dimobelov** [comment]
@abdulhalim, BlThemes plugin is for early version of Bludit 3. It will not be required from the next version of Blekathlon. Do not use it for now. Next week there will be an update to the two themes of BlThemes.

**Comment by abdulhalim** [comment]
@dimobelov OK, Thank you for the themes, they are great, well-done .

**Comment by BlakesHeaven** [comment]
Fantastic, will look forward to Blekathlon update as I use on my mum's art site. Keep up good work 👏

**Comment by rahak** [comment]
I actually got this same problem right now. When I activated the remote content plugin and deactivated it. All my content in the pages got deleted. When I tried to put in the content and save the content vanishes. But when tried to make new content page the saving feature works. It all happened so suddenly.
