### ISSUE TITLE
function bootstrap_html() in paginator.class throws error

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#961]
I wanted to make a pagination in a classic style, not a typical blog one, but I found it's already there (great!).
Right after using it, and trying to move through pages, the bootstrap_html() function throws an error
`
 Uncaught Error: Call to undefined method Paginator::prevPageUrl() in /bl-kernel/helpers/paginator.class.php:168`

as for now I got rid of: self::prevPageUrl() as I don't currently need prev/next buttons (only first/last ones).

btw. would be good if getting back to first page using first/previous/1  buttons got rid of  "/?page=1" in url for seo purposes

**Comment by ltGuillaume** [comment]
That's a bug: `prevPageUrl` should be `previousPageUrl`.

**Comment by dignajar** [comment]
I changed the function name, but I was thinking to deprecated the function `bootstrap_html()`, almost the themes are using they own paginator code.
thanks!
