### ISSUE TITLE
Bug? reindextags() function call lowercase in functions.php - createPage() and deletePage()

### ISSUE THREAD

**Issue by inet-cologne** [bludit/bludit#965]
### Describe your problem
I did some code review with the latest bludit 3.7.1 installation to learn what happens. I found some issues I think you should have a look at.
I'm no php developer so may be I'm false.
BTW: great work you did!!!

### Actual behavior
reindextags() function call lowercase instead of reindexTags()

### Steps to reproduce the problem
Review code at functions.php
createPage()
deletePage()

### Bludit version
3.7.1

**Comment by dignajar** [comment]
Yes is a bug! fixed.
Thanks

**Comment by inet-cologne** [comment]
Great! Thank YOU!
👍
