### ISSUE TITLE
Bug? in url.class.php - checkfilters() - filterFullwoSlash

### ISSUE THREAD

**Issue by inet-cologne** [bludit/bludit#966]
### Describe your problem
I did some code review to learn what happens and found an issue I think, what may cause errors.
I'm no pro php developer, so may be I'm false with that.
Please check the code.

### Actual behavior
url.class.php
in checkfilters()

			// $filterFullwoSlash = '/base_url/category'
			$filterFullwoSlash = ltrim($filterURIwoSlash, '/');
			$filterFullwoSlash = HTML_PATH_ROOT.$filterURIwoSlash;
The third line overwrites filterFullwoSlash from second without the reuse of the trimmed var.			
Shouldn't it be so: (last line)	
			// $filterFullwoSlash = '/base_url/category'
			$filterFullwoSlash = ltrim($filterURIwoSlash, '/');
			$filterFullwoSlash = HTML_PATH_ROOT.$filterFullwoSlash;

### Steps to reproduce the problem
Look at the code above.
### Bludit version
3.7.1

**Comment by dignajar** [comment]
Hi,
even worst, the variable is defined and is not used.
Sometime I check my code and I don't understand what I did, maybe I was drunk :P 

Regards

**Comment by ltGuillaume** [comment]
I know the feeling, although I'm hoping you'll steer clear of Bludit development when drunk ;-)

**Comment by dignajar** [comment]
I removed the lines.
Regards
