### ISSUE TITLE
changing friendly url leads to blank page

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#968]
I made a typo in page's title, but found it out after saving page.
So I changed the title, corrected friendly url field, but saving page led to a blank page.
It seems that furl is saved correctly, but I have to go back in browsing history, and then edit the page again.

**Comment by dignajar** [comment]
Hi,
I'm trying to reproduce the problem but I can not.

Steps:
- Create new page
- Complete the title and content
- Save
- Edit the page
- Change title
- Change friendly url
- Save

Please complete the template when you create an issue in Github.

**Comment by Joduai** [comment]
@dignajar thanx for pointing this out.
Tried on a fresh temporary install, and all seems to work fine.
This might be the problem of one of additional plugins, no matter if activated or not.
