### ISSUE TITLE
About a easy but high risk vulnerability

### ISSUE THREAD

**Issue by Yanyouke** [bludit/bludit#970]
Hi,excuse me.I want to tell you about a easy but high risk vulnerability,

I found that our account number, password and our token value are transmitted in clear text, which will be a dangerous behavior.
In particular, this vulnerability does not apply to all scenarios, but it can be implemented in the following scenarios:
1. To intercept and obtain the plaintext under the same LAN (account name and password).
2. To obtain the plaintext by remote control or phishing (account name and password).
![image](https://user-images.githubusercontent.com/41262396/53302193-9b1b0580-3896-11e9-9c01-502fd8979125.png)

**Comment by Yanyouke** [comment]
> Hi,excuse me.I want to tell you about a easy but high risk vulnerability,
> 
> I found that our account number, password and our token value are transmitted in clear text, which will be a dangerous behavior.
> In particular, this vulnerability does not apply to all scenarios, but it can be implemented in the following scenarios:
> 
> 1. To intercept and obtain the plaintext under the same LAN (account name and password).
> 2. To obtain the plaintext by remote control or phishing (account name and password).

![image](https://user-images.githubusercontent.com/41262396/53302151-33fd5100-3896-11e9-8e19-f887dbcb404a.png)

**Comment by dignajar** [comment]
Hi,
would be good to contact me before publish this kind of vulnerabilities.
Anyway, the only place where the user and password is sent is when the user login. If you want to prevent this in your LAN you need to have a webserver with SSL where the traffic goes encrypted.
This behavior happens in all CMS.
