### ISSUE TITLE
sitemap.xml lacks sticky pages +quickfix

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#972]
Just launched sitemap plugin and thought this one will work w/o a single problem.
Sitemap.xml lacks urls to sticky pages.
No wonder, as only published and static DB's are checked
a quickfix, but copypasting takes longer than writing dozen chars ;)

From line 60 /plugins/sitemap/plugin.php
```
		$published = $pages->getPublishedDB();
		$stickies = $pages->getStickyDB();
		$statics = $pages->getStaticDB();
		$list = array_merge($published, $stickies, $statics);
```

Btw, as there is possibility to enable/disable ping to search engines, additional option to choose changefreq would be great. In my taste there's no need to set freq on a dailybasis, and letting weekly or monthly from the plugin management page would come in handy.

**Comment by dignajar** [comment]
Fixed!
