### ISSUE TITLE
[ENHANCEMENT]  Group plugins by enabled or not, with enabled at top

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#973]
### Describe your problem

All the plugins are in alphabetical ascending order. Making it harder to see those activated.

### Expected behavior

Show activated plugins first, then after `<hr>` line 

-----------

show inactive list.

### Actual behavior

Active/inactive are all mixed up.

### Bludit version
All, including v3.8.0

**Comment by BlakesHeaven** [comment]
Thanks for including this in v9.3, looks good in beta :)

**Comment by dignajar** [comment]
Implemented in v3.9.0! thanks
