### ISSUE TITLE
Sticky article is not count into category

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#974]
### Describe your problem
If you put a article in sticky option, his category is not defined.

### Steps to reproduce the problem
Create a content, set a category to this article.
When you'r going into the category page you will see the article.
Come back into the content editor, set a sticky to this article.
I will be hidden from category.
(same with the plugins category for sidebar).

### Bludit version
3.8.0

**Comment by dignajar** [comment]
Fixed here https://github.com/bludit/bludit/commit/54868df65294e21033505aa99a95d438485f037e

regards

**Comment by liartfr** [comment]
Perfect !!!!! Thx
