### ISSUE TITLE
setting a parent not possible

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#975]
Howdy
Just wanted to pop up an issue with setting a parent.
I've found an old issue treating about this function here:
https://github.com/bludit/bludit/issues/604

Basically why it is not possible to set a parent to a default page type when parent page is static?
What's the sense of having a possibility to set a parent for a default page type only for the same default page type? There's not even a way to set a static parent for a static page, making the Navigation plugin completely unusable. 
Only combination between default page types seem to work, no matter what's the default order is set up.

In current state the option to set a parent is completely broken, and comparing to the issue from last year it's a regress.

Could you point me where should I search in bludit's core to get rid of any conditionals and unblock this function? Parent page typed manually in parent's field is being cut during save.

edit:
Okay, seems that only default pages (published) can be set as parents, as buildParentPages() takes only _getPublishedDB()_  results.
I got rid of this by merging all pages DB arrays , but after saving couple test pages, everything started to look more complex than I thought.

**Comment by BlakesHeaven** [comment]
My issue is that default pages with a status of published can not be set as a Parent if the scheduled date is set in the future.
I guess my issue also lies in getPublishedDB(), but I only dabble a bit with php, so can't see how to hack it and fix #700 . 
Good luck.

**Comment by Joduai** [comment]
@BlakesHeaven 
I've read your issue some time ago, but I haven't understood what exactly you would like to achieve.
When it goes to setting a parent it needs a relatively small change in core file, to have a way of choosing other types of pages, and let them become a parent.

you can try it by modifying  blkernel/functions.php file
around line: ~161 should be a buildParentPages() function 
just check it, and merge all page databases like below example I used

	$list = array();
	$pagesKey_1 = $pages->getPublishedDB();
	$pagesKey_2 = $pages->getStaticDB();
	$pagesKey_3 = $pages->getStickyDB();
	$pagesKey_4 = $pages->getScheduledDB();
	$pagesKey = array_merge($pagesKey_1,$pagesKey_2,$pagesKey_3,$pagesKey_4);

Then you should be able to choose a parent.
This is only a "fix" for this one feature. I don't know if scheduled page with a set up parent page will work without modifying other core function.

**Comment by BlakesHeaven** [comment]
@Joduai , thanks for all that detail.
I put together uwcc.uk, which is a small concert club website advertising a programme of planed events. The `parent` page holds a summary of all events, and the `children` hold the detail.
All these pages for a programme are a group and should appear on the website at the same time. My auto archive menu uses the published date to auto move the menu as time passes.
Currently with this issue, they cannot be scheduled ahead of time in the format they need to appear. Always the pages need to be reconfigured after the scheduled data, which makes the concept of scheduling pages pointless for parent/child groups.

**Comment by Joduai** [comment]
@BlakesHeaven this is just a dirty fix for setting a parent of other type, than default published page.
I don't have any other choice than to make changes in core code after every update. As long as I'm going to use bludit of course ;)

I've just checked couple mins ago with a scheduled page with parent set up as a static page, and everything works fine (I'd be surprised if it wasn't)
Rest is a matter of proper frontend templating.

ps. don't forget that children will be shown in admin panel under the apropriate parent page.

**Comment by dignajar** [comment]
This issue is implemented in the new version of Bludit v3.11.0, let me know if you still have the problem.
