### ISSUE TITLE
Search problem in Semitic languages

### ISSUE THREAD

**Issue by abdulhalim** [bludit/bludit#976]
### Describe your problem
The search problem doesn't work properly for Semitic languages such as Persian and Arabic
### Expected behavior
Search for exact words and articles
### Actual behavior
Search results are actually unclear
### Steps to reproduce the problem
Use Persian article to reproduce the problem
http://loremsaz.com/
### Bludit version
3.8

**Comment by dignajar** [comment]
Hi,
can you do the test in the demo site ?

https://demo.bludit.com

I created a page with the title `ایپسوم` then using the search plugin and I found the page.

**Comment by abdulhalim** [comment]
Hello Diego,
Yes, you are right, it is OK with just one article, but if there is more than one article, it lists all of them.
https://screencast-o-matic.com/watch/cqenFa0FSP

P.S: I created 3 articles, the last 2 articles created automatically, I dunno why.

**Comment by nguyencongvu** [comment]
I had same issue in Vietnamese. Search plugin cannot return results 
Test here 
[https://haykhoinghiep.com/search/marketing](https://haykhoinghiep.com/search/marketing)

**Comment by dignajar** [comment]
Hi guys, sorry for my late answer, I improve the Fuzz algorithm to support UTF8, if you have time please test it.

https://github.com/bludit/bludit/commit/7c8bad72c574b1d2a3cd1b499f7672e231973ea3

**Comment by dignajar** [comment]
You can download the plugin search from here, https://github.com/bludit/bludit/tree/master/bl-plugins/search

**Comment by abdulhalim** [comment]
Hello Diego,
This is a very improving update, Thank you, But it needs more improvement, I mean the plugin is not smart enough, e.g: it can find the word "hello" , but it can't find the word "hello!" (in Persian I mean) , you should put all character together  to find the second word, anyway it's a great job, and I need to test more

**Comment by dignajar** [comment]
Ok is a good point, can you give me a few examples to create two pages with some keywords and try to search ?

**Comment by abdulhalim** [comment]
Could you use these words please, 
`

جوملا

وردپرس

ساده

آسان

اسان

سوال؟

کلمه

قالب

پلاگین

سلام!

حال شما چطوره

چطوری؟
`
only the two first words are searchable, but in other words not! I don't know why.
`جوملا

وردپرس`
These two words are fine with the plugin

**Comment by theuser17** [comment]
@dignajar 
I have this problem too :frowning_face:

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
