### ISSUE TITLE
sitesidebar shows tags from draft pages

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#977]
Using Theme::plugins('siteSidebar') to show plugins content in sidebar shows tag list containing those from draft pages. Checked twice to be sure.

After searching through issues I found that this bug should be fixed in v2.0 https://github.com/bludit/bludit/issues/274 but it seems to be a regress.

Tags plugin grabs tags from tagsDB, which contains all pages urls and tags only.
Shouldn't tagsDB contain also page type to filter out unneeded tags?
Also tags from static pages are in, but imo they shouldn't.

**Comment by dignajar** [comment]
I fixed the bug and created an array with the type of pages allowed in the database, by default the types are `published, sticky and static`.

https://github.com/bludit/bludit/commit/185ae093932d9f5638b8ccde542d5a6835b6cb59

**Comment by Joduai** [comment]
Checked with latest updates and works as supposed.
