### ISSUE TITLE
Request: Skip the Parsedown Rendering

### ISSUE THREAD

**Issue by SamBrishes** [bludit/bludit#980]
Hellow,

Is it possible to add a filter (or something) to skip the Parsedown Rendering within the Page class and to pass the plain content to an own rendering library? 

I'm asking because my **tail.writer** script also supports Textile and BBCodes, which isn't supported by Bludit directly. My current solution returns the already rendered HTML Code, when the page gets saved. This solution doesn't allow to show the content back in the respective Markup code, of course. (I'm currently try another solution, which stores the Markup version of the content separately of the HTML Content and to "just" bypass it on the admin interface. But a core solution to just use another Rendering library would be way better.)

Thanks.

Sincerely,
Sam

**Comment by dignajar** [comment]
Hi,
Is good idea to enable or disable the parser, I will check how I can do it.
Meanwhile Bludit keep both content, and contentRaw variable has the content without parsed.

`$page->contentRaw()`

**Comment by dignajar** [comment]
@SamBrishes so at the end you can use the method I mention which has the content in raw format, without the markdown parse, it's what you need ?

**Comment by SamBrishes** [comment]
Hellow,

no, not really. The problem isn't to get the raw content, because I'm not able to store the raw content. I need to pre-render the BBCodes / the textile Markup and store it as HTML. Otherwise no frontend template would be able to show it as HTML, because the `content()` method, which is used by each Bludit template, uses Parsedown to render the raw content. If this would be skippable / changeable, I would be able to store the plain / raw BBCodes (or Textile Markup).

Sincerely,
Sam.

**Comment by dimobelov** [comment]
It is not bad to have option to skip markdown parsing or better enable markdown parsing by option. Most of users in new versions use html editor to input content.

**Comment by dignajar** [comment]
Done.
https://github.com/bludit/bludit/commit/3ab8c4c0a630b86eedd79020c34d1758f0d2726d
