### ISSUE TITLE
Can't update profile image

### ISSUE THREAD

**Issue by fisklask** [bludit/bludit#984]
### Describe your problem
I am trying to update user profile picture and it only set to black, tried other files and checked logs, no luck.
Could only catch this message in DevTools Console:
"Form contains a file input, but is missing method=POST and enctype=multipart/form-data on the form.  The file will not be sent."
The problem doesn't happen on local webserver, once pushed to remote the problem start to occur.
The rest works, content can be created, images can be uploaded to the posts.

### Expected behavior
User profile image is updated.
### Actual behavior
User profile image goes black.
### Steps to reproduce the problem
Go to user profile and attempt to update picture
### Bludit version
Bludit Version | 3.8.1
-- | --
Bludit Codename | APA
Bludit Build Number | 20190228

**Comment by Joduai** [comment]
Tested this on my own blog based on B3.8.1, and admin img changes without a single problem.
I would double check if it's not a deployment problem from localhost.

**Comment by fisklask** [comment]
Oh my, I did type a comment a while ago and apparently forgot to submit it.
I haven't seen this problem with directly accessed instance however once it was moved behind reverse proxy the problem occurred.

I need to double check that, will add some info later this week.

**Comment by dignajar** [comment]
Check in your browser the dev console when you are uploading the image, if you recevid some error. also the tab `network`.

**Comment by fisklask** [comment]
Finally, got my hands there.
Confirmed - our reverse proxy messes something up here.
Nothing unusual on Network tab, POST request went normal:
`{"status":0,"message":"Image uploaded.","filename":"test.png","absoluteURL":"https:\/\/counself.com\/site\/blog\/bl-content\/uploads\/profiles\/test.png","absolutePath":"\/app\/site\/blog\/bl-content\/uploads\/profiles\/test.png"}`

Stay tuned.

**Comment by fisklask** [comment]
In the end it turned out that php worker tried to use ./bl-content/tmp folder for processing uploaded files but the folder wasn't there and it couldn't create it due to lack of permissions and didn't report it anywhere.
That happened as we use docker volume for ./bl-content folder where only **root** user could create a missing folder.
