### ISSUE TITLE
get latest bludit version from web

### ISSUE THREAD

**Issue by philippd1** [bludit/bludit#986]
So, I'm trying to build a new version of my "bludit-auto-update" plugin.
But before actually updating, it would be nice to know if the installed version is actually old or not.

So, basically here's my question: is there any file which specifies the current version?
Then I wouldn't have to hack together something like getting the "https://www.bludit.com/releases/bludit-3-8-1.zip"/ latest github release

**Comment by Joduai** [comment]
a look at files in plugins/version
and also at https://version.bludit.com

**Comment by philippd1** [comment]
awesome, thanks!
