### ISSUE TITLE
[bug] rss lacks sticky pages

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#995]
Just realized that rss plugin has the same issue like sitemap plugin had in #972
Only published pages gets into rss.xml without sticky ones.

**Comment by dignajar** [comment]
Was fixed here ?

https://github.com/bludit/bludit/commit/c16741808f0a8dfa0710171dbb661d56a2f61e2f

**Comment by Joduai** [comment]
Yeah, sitemap was fixed, but rss plugin still contains obsolete:

> $list = $pages->getList($pageNumber, $numberOfItems, $onlyPublished);
